"""Attribution and evaluation: where the headline book's P&L comes from, and what it depends on. Week 10.

Generated by `scripts/build_tearsheet.py`, never hand-edited: every number comes
from the books run here, and every sentence is a template filled from them.
The book is week 9's headline (`report/portfolio.py`, `headline`), run once;
nothing here re-sizes it or picks a better one.

**By component** (`split`). Each sleeve's positions, as the book decided them,
go back through `expression.run` on its own calendar, so the P&L splits into
carry, roll and rate change (`strategy/carry.py`) exactly as week 7 marks it,
and is credited to the book calendar as week 9 credits it (`check`: the parts
add up to the book's gross to 1e-8). The component groups are the sleeves'
kinds: level (the outrights), slope (the 2s10s) and cross-country (the
differential).

**The level factor** (`factor_split`). The groups are not independent: a 2s10s
receive gains in a bull steepening, when the front end rallies too. So each
sleeve's unit P&L is regressed on the outright unit P&L of its currencies
(`metrics.factor`, full sample, ex post), and its P&L split into its
position times its betas times the outrights' unit P&L (what its level
exposure earned) and the rest (the relative value). For an outright it is all
level. The share of the book's daily gross P&L variance the level part
explains, cov(level, book) / var(book), decides the verdict: at half or more,
the report says the level dominates, and that the book is closer to a
duration timer than to relative value.

**Carry against rate** (`carry_book`). The same split into carry and roll
against the rate change, and a benchmark: the same sleeves, rule, ELB
treatment, sizing and costs, with the z replaced by the sign of each
sleeve's carry and roll ahead (`expression.ahead`, CR_h for a receive). Its
daily net P&L's correlation with the headline's says whether the book is a
carry trade in costume: `CARRY_WORDS` words it.

**By sleeve** (`carry_by_sleeve`). The book-level split can hide which
sleeves carry it, so each sleeve's carry and roll, rate change and cost are
reported with a reading of their signs (right or wrong on the rate, bleeding
or collecting carry), the share of held sessions whose carry and roll ahead
runs against the side, and the side's correlation with the sign of carry and
roll: the test of "the signal cannot be right without the trade being
expensive", sleeve by sleeve. What the rate calls would have had to earn is
the rate change needed for a net of zero, and as a correlation of position
and move (`information`, an exact identity, no model). The carry filter's
bite at entry (`filter_entries`) is counted beside it.

**Where the costs go** (`cost_sources`). The cost a year is turns x mean
gross DV01 x the one-way cost; the table gives each factor, per sleeve and
cause, so the cost can be checked by hand (`check_costs` holds the causes to
the charge). A reader's first check is today's DV01s against the cost, and
today's are well below the sample's mean: the words say so when they are.

**The level the z removes** (`level_gap`). The z trades the gap's deviation
from its trailing mean; the level it removes is reported by regime and year,
with the r* it rests on, as a measurement, not a signal.

**Regimes** (`regime_table`): `regimes.states` for each currency, real time. A
sleeve is keyed by its own currency's state, the cross sleeve and the book by
the book currency's, and the book also by whether the two currencies are in
the same collapsed regime (hiking, on hold, cutting, ELB). Every Sharpe carries
its counted and active sessions and the trades put on in the regime.

**The ELB** (`elb_books`). The book run under each treatment of
`strategy/positions.py` (flat, the configured one; exclude; hold), on the same
sizing and costs: the P&L of positions decided in the state, the rest, the
Sharpe with and without the state's sessions, and the boundary trades (the
positions a flat treatment closes on entering the state, and their cost).

**The IC** (`ics`): `metrics.ic_table` per sleeve, z against the next h
sessions of the rate-change component of unit P&L (and of the total), at
``evaluation.ic_horizons`` (a week, a month, a quarter), on the sessions
outside the ELB state and on all.

**Without 2022** (`metrics.ex_2022`, `metrics.ex_2022_23`): for the book, each
sleeve's contribution, each ELB treatment and the carry benchmark.
"""

from dataclasses import dataclass, replace
import json
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath import regimes
from policypath.backtest import metrics
from policypath.report import charts
from policypath.report import costs as sleeves
from policypath.report import portfolio as books
from policypath.report.coverage import table
from policypath.report.expression import _and, _plain
from policypath.report.figures import THEMES, _style
from policypath.report.onepager import ORDINAL
from policypath.strategy import costs, expression, portfolio, positions

GROUPS = {"outright": "level", "curve": "slope", "cross": "cross-country"}
COLLAPSED = {regimes.ELB: "ELB", "early_hiking": "hiking", "late_hiking": "hiking", "hold_after_hikes": "on hold",
             "hold_after_cuts": "on hold", "cutting": "cutting"}
COLLAPSED_ORDER = ["hiking", "on hold", "cutting", "ELB"]
# The book table's rows: each state, with the collapsed regime after the states it sums.
REGIME_ROWS = [("early_hiking",), ("late_hiking",), ("early_hiking", "late_hiking"), ("hold_after_hikes",),
               ("hold_after_cuts",), ("hold_after_hikes", "hold_after_cuts"), ("cutting",), (regimes.ELB,)]
STATE_WORDS = {"early_hiking": "early hiking", "late_hiking": "late hiking", "hold_after_hikes": "hold after hikes",
               "hold_after_cuts": "hold after cuts", "cutting": "cutting", regimes.ELB: "ELB"}
LEVEL_DOMINATES = 0.5    # the level part's share of the book's gross P&L variance at which the level dominates
# |corr| of the book's daily net P&L with the carry benchmark's, and the words for it.
CARRY_WORDS = [(0.6, "a carry trade in costume"), (0.3, "partly a carry trade"), (0.0, "not a carry trade")]
TOL = 1e-8
LEVEL_MIN_SESSIONS = 60    # a year's mean gap outside the ELB state is reported from this many sessions
MONTH = 21                 # sessions in the worst month's loss (`drawdown_shape`)


# ---- the headline, split -----------------------------------------------------------

def outrights(st):
    """{ccy: the outright sleeve's name} in `st` (a `report.portfolio.Setup`)."""
    return {i.sleeve.ccys[0]: n for n, i in st.inputs.items() if i.sleeve.kind == "outright"}


def unit_total(i, part="total"):
    """A sleeve's unit P&L component (`part`) by its own session, bp: its legs summed."""
    return i.u.groupby("session")[part].sum(min_count=1).reindex(i.sleeve.sessions)


def betas(st):
    """{sleeve: (betas {outright name: beta}, R^2, sessions)}: each sleeve's unit P&L on its currencies' outrights.

    An outright is its own level (beta 1, R^2 1); the others are
    `metrics.factor` from the sleeve's first counted session.
    """
    out, level = {}, outrights(st)
    for n, i in st.inputs.items():
        on = [level[c] for c in i.sleeve.ccys if c in level]
        if n in on:
            out[n] = ({n: 1.0}, 1.0, int(unit_total(i).loc[i.start:].notna().sum()))
            continue
        xs = pd.DataFrame({o: unit_total(st.inputs[o]).reindex(i.sleeve.sessions) for o in on})
        out[n] = metrics.factor(unit_total(i).loc[i.start:], xs.loc[i.start:])
    return out


def split(st, b, fits):
    """{sleeve: its flows in book `b` on the book calendar}: gross, cost, traded, carry, roll, rate, level, held
    (signed first-leg DV01 held), gross_dv01 and kept (the book's). `fits` is `betas`."""
    level = outrights(st)
    days, kept = st.days, b.run.daily["kept"]
    out = {}
    for n, i in st.inputs.items():
        s = i.sleeve
        q = portfolio.asof(b.decided[n], s.sessions).fillna(0.0)
        _, sessions = expression.run(s, q, i.u)
        _, pnl, _, _ = positions.samples(i.state, st.spec.treatment, s.lag)
        held = sessions["position"].fillna(0.0).where(pnl, 0.0)
        coef = fits[n][0]
        x = sum(unit_total(st.inputs[o]).reindex(s.sessions) * beta for o, beta in coef.items())
        own = sessions[["carry", "roll", "rate"]].where(pnl, 0.0, axis=0)
        own["level"] = (held * x).fillna(0.0) if n not in level.values() else sessions["pnl"].where(pnl, 0.0)
        f = portfolio.to_book(own, days)
        part = b.parts[n]
        f["gross"], f["cost"], f["traded"] = part["gross"], part["cost"], part["traded"]
        f["held"] = portfolio.asof(held, days).fillna(0.0)
        f["gross_dv01"] = f["held"].abs() * len(s.legs)
        f["kept"] = kept
        out[n] = f
    return out


def contribution(f, periods):
    """One part's `metrics.Result` in the book (its flows, the book's counted sessions)."""
    return metrics.Result(f, periods)


def group_of(st):
    """{sleeve: its component group}: level, slope, cross-country."""
    return {n: GROUPS[i.sleeve.kind] for n, i in st.inputs.items()}


def _sum(parts, names, cols):
    return sum(parts[n][cols] for n in names)


def components(st, b, parts, capital):
    """Per component group and the book: net, gross, cost, carry and roll, rate, % of capital a year; the share of
    the book's net P&L variance (cov(part, book) / var(book)); the Sharpe of the group's net contribution."""
    k = b.run.daily["kept"]
    per = b.run.periods
    years = k.sum() / per
    book_net = (b.run.daily["gross"] - b.run.daily["cost"])[k]
    groups = group_of(st)
    rows = []
    for g in [*dict.fromkeys(groups.values()), "book"]:
        names = [n for n, x in groups.items() if g in (x, "book")]
        f = _sum(parts, names, ["gross", "cost", "carry", "roll", "rate", "level"])[k]
        net = f["gross"] - f["cost"]
        sr = metrics.sharpe(net, per)
        rows.append({"group": g, "sleeves": names, "net": net.sum() / years / capital * 100,
                     "gross": f["gross"].sum() / years / capital * 100, "cost": f["cost"].sum() / years / capital * 100,
                     "carry_roll": (f["carry"] + f["roll"]).sum() / years / capital * 100,
                     "rate": f["rate"].sum() / years / capital * 100,
                     "variance_share": float(np.cov(net, book_net)[0, 1] / book_net.var()),
                     "net_sr": sr, "net_se": metrics.sharpe_se(sr, years)})
    return rows


def level_view(st, b, parts, fits, capital):
    """The level-factor view: per sleeve its betas, R^2, and gross P&L split into level and the rest (% of capital a
    year); for the book the same split and the level part's share of the gross P&L variance."""
    k = b.run.daily["kept"]
    years = k.sum() / b.run.periods
    rows = []
    for n, f in parts.items():
        coef, r2, obs = fits[n]
        g, lv = f.loc[k, "gross"], f.loc[k, "level"]
        rows.append({"sleeve": n, "betas": coef, "r2": r2, "sessions": obs,
                     "level": lv.sum() / years / capital * 100, "rest": (g - lv).sum() / years / capital * 100})
    g = b.run.daily.loc[k, "gross"]
    lv = sum(f.loc[k, "level"] for f in parts.values())
    share = float(np.cov(lv, g)[0, 1] / g.var())
    return rows, {"level": lv.sum() / years / capital * 100, "rest": (g - lv).sum() / years / capital * 100,
                  "gross": g.sum() / years / capital * 100, "variance_share": share,
                  "corr": float(np.corrcoef(lv, g)[0, 1]), "dominates": bool(share >= LEVEL_DOMINATES)}


def z_agreement(st):
    """Per currency with an outright and a curve sleeve: corr(level z, slope z) and the share of sessions their signs
    agree, for the traded (orthogonal) slope and the raw 8-minus-1; and the share of book sessions both sleeves hold a
    side on which the sides agree."""
    rows = []
    for c, o in outrights(st).items():
        for n, i in st.inputs.items():
            if i.sleeve.kind != "curve" or i.sleeve.ccys[0] != c:
                continue
            lz, comp = st.inputs[o].sleeve.component["z"], i.sleeve.component
            row = {"ccy": c, "level": o, "slope": n}
            for name, z in (("orthogonal", comp["z"]), ("raw", comp.get("raw_z"))):
                if z is None:
                    continue
                both = pd.concat([lz, z], axis=1).dropna()
                row[name] = {"corr": float(both.corr().iloc[0, 1]),
                             "same_sign": float((np.sign(both.iloc[:, 0]) == np.sign(both.iloc[:, 1])).mean()),
                             "sessions": len(both)}
            g = st.g[[o, n]]
            on = (g != 0).all(axis=1)
            row["sides"] = {"same": float((g[on].iloc[:, 0] == g[on].iloc[:, 1]).mean()) if on.any() else np.nan,
                            "sessions": int(on.sum())}
            rows.append(row)
    return rows


def check(b, parts, tol=TOL):
    """Raise unless the split adds up: carry + roll + rate is each part's gross, and the parts are the book's."""
    for n, f in parts.items():
        off = (f["carry"] + f["roll"] + f["rate"] - f["gross"]).abs().max()
        if off > tol:
            raise RuntimeError(f"{n}: carry + roll + rate is {off:g} off its gross P&L in the book")
    total = sum(f["gross"] for f in parts.values())
    if (total - b.run.daily["gross"]).abs().max() > tol:
        raise RuntimeError("the parts' gross P&L is not the book's")


# ---- where the costs go, and carry against rate by sleeve --------------------------

def one_way(i):
    """A sleeve's one-way cost, bp per unit of book DV01 traded: its legs' mean (they trade the same DV01 together)."""
    return float(np.mean(list(costs.configured(i.costs).values())))


def cost_sources(st, b, parts, capital):
    """Where the costs go: per sleeve and the book, the mean gross DV01 held on the sessions with a position (book
    currency per bp, every leg), the turns a year by cause (DV01 traded a year over it, as `metrics.turnover`), the
    mean one-way cost (bp) and the cost a year by cause, % of capital.

    A sleeve's legs hold the same book DV01 and trade at the same closes, so each cause's DV01 splits evenly over
    them and its cost is the DV01 at the legs' mean one-way rate (`check_costs` holds the causes to the charge).
    """
    k = b.run.daily["kept"]
    years = k.sum() / b.run.periods
    rows, book = [], {"traded": dict.fromkeys(books.CAUSES, 0.0), "cost": dict.fromkeys(books.CAUSES, 0.0)}
    for n, flows in b.parts.items():
        f, rate = flows[k], one_way(st.inputs[n])
        traded = {c: float(f[c].sum()) for c in books.CAUSES}
        cost = {c: v * rate for c, v in traded.items()}
        for c in books.CAUSES:
            book["traded"][c] += traded[c]
            book["cost"][c] += cost[c]
        rows.append(_cost_row(n, len(st.inputs[n].sleeve.legs), traded, cost, parts[n].loc[k, "gross_dv01"], years,
                              capital))
    legs = sum(len(i.sleeve.legs) for i in st.inputs.values())
    rows.append(_cost_row("book", legs, book["traded"], book["cost"], b.run.daily.loc[k, "gross_dv01"], years,
                          capital))
    return rows


def _cost_row(name, legs, traded, cost, dv01, years, capital):
    held = dv01[dv01 > 0].mean()
    total, spent = sum(traded.values()), sum(cost.values())
    return {"name": name, "legs": legs, "mean_dv01": float(held),
            "turns": {c: v / years / held for c, v in traded.items()}, "turns_year": total / years / held,
            "one_way_bp": spent / total if total else np.nan,
            "cost": {c: v / years / capital * 100 for c, v in cost.items()}, "cost_year": spent / years / capital * 100,
            "maintenance": sum(cost[c] for c in costs.MAINTENANCE) / spent if spent else np.nan}


def check_costs(st, b, tol=1e-6):
    """Raise unless each sleeve's DV01 traded by cause, at its mean one-way rate, is the cost the book charged it."""
    for n, f in b.parts.items():
        by_cause = f[list(books.CAUSES)].sum(axis=1) * one_way(st.inputs[n])
        off = (by_cause - f["cost"]).abs().max()
        if off > tol * max(1.0, f["cost"].abs().max()):
            raise RuntimeError(f"{n}: the cost by cause is {off:g} off the cost charged")


def carry_by_sleeve(st, b, parts, capital):
    """Carry against rate by sleeve, and what the rate change would have had to earn to break even.

    Per sleeve, % of capital a year inside the book: carry and roll, the rate
    change, the cost, and the rate change needed for a net of zero (the cost
    less carry and roll). On the counted sessions with a position: the share on
    which the carry and roll ahead of the side held is negative (``bleeding``,
    CR_h over ``carry.horizon_days`` as `expression.ahead` has it), and the
    correlation of the side with the sign of a receive's CR_h (below zero: the
    side is against the carry).

    The information needed (``rho``, ``rho_star``): on the sleeve's sessions
    credited to counted book sessions, the rate change is the position held q
    (book currency per bp) times the unit rate move x (bp), and exactly
    sum(q x) = N (rho sd(q) sd(x) + mean(q) mean(x)), rho their correlation
    (population moments). rho* solves it for the rate change needed, holding
    the positions' sizes and the rate's moves as they were: the correlation of
    position and move at which the sleeve breaks even.
    """
    c = st.book["carry"]
    k = b.run.daily["kept"]
    years = k.sum() / b.run.periods
    days = st.days
    rows = []
    for n, i in st.inputs.items():
        s, f = i.sleeve, parts[n][k]
        cr, rate, cost = float((f["carry"] + f["roll"]).sum()), float(f["rate"].sum()), float(f["cost"].sum())
        receive = expression.ahead(s, c["horizon_days"], c["closure_min_pairs"],
                                   side=pd.Series(1.0, index=s.component.index))["cr_h_bp"]
        side = np.sign(b.decided[n].fillna(0.0))
        cr_on = portfolio.asof(receive, days)
        on = k & (side != 0) & cr_on.notna()
        held = portfolio.asof(b.decided[n], s.sessions).fillna(0.0)
        _, sessions = expression.run(s, held, i.u)
        _, pnl, _, _ = positions.samples(i.state, st.spec.treatment, s.lag)
        at = portfolio.credited_to(s.sessions, days)
        counted = np.where(at >= 0, k.to_numpy()[np.maximum(at, 0)], False) & pnl.to_numpy()
        x = unit_total(i, "rate")
        m = counted & x.notna().to_numpy()
        rho, rho_star = information(sessions["position"].fillna(0.0).to_numpy()[m], x.to_numpy()[m], cost - cr)
        rows.append({"sleeve": n, "carry_roll": cr / years / capital * 100, "rate": rate / years / capital * 100,
                     "cost": cost / years / capital * 100, "need": (cost - cr) / years / capital * 100,
                     "bleeding": float((side[on] * cr_on[on] < 0).mean()) if on.any() else np.nan,
                     "against": _corr(side[on], np.sign(cr_on[on])),
                     "rho": rho, "rho_star": rho_star,
                     "sessions": int(m.sum())})
    book = {key: sum(r[key] for r in rows) for key in ("carry_roll", "rate", "cost", "need")}
    book["multiple"] = book["need"] / book["rate"] if book["rate"] > 0 else np.nan
    return {"sleeves": rows, "book": book}


def information(q, x, need):
    """(rho, rho*): the correlation of positions `q` with moves `x`, and the one at which sum(q x) would be `need`.

    Exactly sum(q x) = N (rho sd(q) sd(x) + mean(q) mean(x)) with population
    moments, so rho* = (need / N - mean(q) mean(x)) / (sd(q) sd(x)); NaN
    unless both vary.
    """
    q, x = np.asarray(q, dtype=float), np.asarray(x, dtype=float)
    spread = q.std() * x.std() if len(q) else 0.0
    if not spread > 0:
        return np.nan, np.nan
    return _corr(q, x), float((need / len(q) - q.mean() * x.mean()) / spread)


def _corr(a, b):
    """Pearson correlation of `a` and `b`; NaN unless both vary."""
    a, b = np.asarray(a, dtype=float), np.asarray(b, dtype=float)
    return float(np.corrcoef(a, b)[0, 1]) if len(a) > 1 and a.std() > 0 and b.std() > 0 else np.nan


def filter_entries(st):
    """The carry filter at entry: {sleeve: (entries the book's rule makes from its first counted session, those the
    filter would skip)}. An entry is a close whose side is new and not flat; the gate is `positions.pays`."""
    out = {}
    for n, i in st.inputs.items():
        side = st.side[n]
        side = side[side.index >= i.start]
        entry = (side != 0) & (side != side.shift(fill_value=0.0))
        out[n] = (int(entry.sum()), int((entry & ~i.allow.reindex(side.index, fill_value=True)).sum()))
    return out


def level_gap(world, st):
    """The level the z removes: per currency with an outright, the mean gap (market minus rule, bp) at the first,
    the traded and the last meeting by collapsed regime, and the traded meeting's by year outside the ELB state
    (years with at least `LEVEL_MIN_SESSIONS` of them)."""
    out = {}
    for ccy, n in outrights(st).items():
        gap = world.panel(ccy, "signal").pivot(index="session", columns="k", values="gap_bp")
        ks = [int(gap.columns.min()), int(world.cfg(ccy)["backtest"]["horizon"]), int(gap.columns.max())]
        state = regimes.states(world.panel(ccy, "model")).reindex(gap.index).map(COLLAPSED)
        regime = [{"regime": g, "sessions": int((state == g).sum()),
                   "mean": {kk: float(gap.loc[state == g, kk].mean()) for kk in ks}}
                  for g in COLLAPSED_ORDER if (state == g).any()]
        off = gap.loc[state != "ELB", ks[1]]
        by = off.groupby(off.index.year).agg(["mean", "size"])
        by = by[by["size"] >= LEVEL_MIN_SESSIONS]["mean"]
        r = world.cfg(ccy)["rule"]["rstar"]
        out[ccy] = {"k": ks, "regimes": regime, "years": {int(y): float(v) for y, v in by.items()},
                    "rstar": f"a constant {r['constant']:+.1f}%" if "constant" in r else f"the {r['label']} median"}
    return out


def drawdown_shape(b, capital):
    """The worst drawdown's shape on the counted sessions: its depth (% of capital), the peak and trough sessions, the
    years between them, and the worst loss over `MONTH` sessions anywhere (% of capital)."""
    d = b.run.daily[b.run.daily["kept"]]
    e = (d["gross"] - d["cost"]).cumsum() / capital * 100
    peak = np.maximum.accumulate(np.maximum(e, 0.0))
    trough = (peak - e).idxmax()
    top = e.loc[:trough].idxmax() if e.loc[:trough].max() > 0 else e.index[0]
    return {"depth": float((peak - e).max()), "peak": top, "trough": trough,
            "years": (trough - top).days / 365.25, "worst_month": float(-(e - e.shift(MONTH)).min())}


# ---- the other books: carry benchmark and ELB treatments ---------------------------

def carry_inputs(st, h, min_pairs):
    """The sleeves' `Inputs` with each z replaced by the sign of the receive's carry and roll ahead (CR_h)."""
    out = {}
    for n, i in st.inputs.items():
        a = expression.ahead(i.sleeve, h, min_pairs)
        cr = a["cr_h_bp"] * a["side"]            # the receive's CR_h: ahead signs it for sign(z)
        comp = i.sleeve.component.copy()
        comp["z"] = np.sign(cr).where(cr.notna() & (cr != 0))
        out[n] = replace(i, sleeve=replace(i.sleeve, component=comp))
    return out


def carry_book(pb):
    """The carry benchmark (module docstring): its `Setup` and headline book, on the headline's covariance."""
    st = pb.setup
    c = st.book["carry"]
    cs = books.from_inputs(st.book, st.days, carry_inputs(st, c["horizon_days"], c["closure_min_pairs"]))
    return cs, books.run_book(cs, pb.risks[None], books.headline(st.book))


def with_treatment(book, treatment):
    """A copy of the book config with ``evaluation.elb.chosen`` = `treatment`."""
    out = books.copy_book(book)
    out["evaluation"]["elb"]["chosen"] = treatment
    return out


def elb_books(pb):
    """{treatment: (Setup, Book)}: the headline under each ELB treatment, the configured one being the headline."""
    st = pb.setup
    h = books.headline(st.book)
    out = {}
    for tr in positions.TREATMENTS:
        if tr == st.spec.treatment:
            out[tr] = (st, pb.books[h])
            continue
        s = books.from_inputs(with_treatment(st.book, tr), st.days, st.inputs)
        out[tr] = (s, books.run_book(s, pb.risks[None], h))
    return out


def elb_split(st, b, capital):
    """One treatment's book against the ELB state, % of capital where P&L.

    On each sleeve session, the position held into it was decided in the state
    where the state shifted lag + 1 is (``line``), and the one put on at its
    close where the state shifted lag is (``put``). The P&L of positions decided
    in the state is the gross on ``line`` sessions less the cost of trades on
    sessions both are; the boundary trades are the trades on sessions exactly
    one is: the close on entering the state and the re-open on leaving it,
    which the flat treatment forces (under hold and exclude they are ordinary
    trades, so the count is the flat treatment's only). Also the net Sharpe on
    every counted session and on those no sleeve holds a position decided in
    the state.
    """
    days = st.days
    d = b.run.daily
    k = d["kept"]
    net = (d["gross"] - d["cost"])
    in_state = pd.Series(0.0, index=days)
    touched = pd.Series(False, index=days)
    closes, reopens, boundary_cost = 0, 0, 0.0
    for n, i in st.inputs.items():
        s = i.sleeve
        daily, _, _, _ = books._sleeve(st, n, b.decided, b.run.start)
        state = i.state.reindex(s.sessions, fill_value=False)
        line = state.shift(s.lag + 1, fill_value=False)
        put = state.shift(s.lag, fill_value=False)
        live = s.sessions >= b.run.start
        held = portfolio.asof(b.decided[n], s.sessions).fillna(0.0).shift(s.lag + 1, fill_value=0.0)
        mine = daily["gross"].where(line, 0.0) - daily["cost"].where(line & put, 0.0)
        in_state += portfolio.to_book(mine, days)
        touched |= portfolio.to_book((line & (held != 0)).astype(int), days) > 0
        if st.spec.treatment == "flat":
            traded = (daily["traded"] > 0) & live
            closes += int((traded & put & ~line).sum())
            reopens += int((traded & line & ~put).sum())
            boundary_cost += float(daily["cost"][traded & (put != line)].sum())
    per = b.run.periods
    out_sr = metrics.sharpe(net[k & ~touched], per)
    ev = metrics.evaluate(b, capital=capital)
    forced = st.spec.treatment == "flat"
    return {"treatment": st.spec.treatment, **ev,
            "state_sessions": int((k & touched).sum()),
            "in_state": float(in_state[k].sum() / capital * 100),
            "outside": float((net[k].sum() - in_state[k].sum()) / capital * 100),
            "outside_sr": out_sr, "outside_se": metrics.sharpe_se(out_sr, (k & ~touched).sum() / per),
            "closes": closes if forced else None, "reopens": reopens if forced else None,
            "boundary_cost": boundary_cost / capital * 100 if forced else None,
            "ex_2022": metrics.ex_2022(b, st.book, capital), "ex_2022_23": metrics.ex_2022_23(b, st.book, capital)}


def elb_episodes(world, book):
    """{ccy: [(first, last, sessions)]}: each currency's runs in the ELB state (`regimes.elb_state`)."""
    out = {}
    for c in dict.fromkeys(c for s in book["sleeves"] for c in ([s["ccy"]] if "ccy" in s else s["pair"])):
        e = regimes.episodes(regimes.elb_state(world.panel(c, "model")))
        e = e[e["state"]]
        out[c] = [(r["first"], r["last"], int(r["sessions"])) for _, r in e.iterrows()]
    return out


# ---- regimes -----------------------------------------------------------------------

def states_on(world, ccys, days):
    """{ccy: its regime (`regimes.states`) on each of `days`: the latest on or before it}."""
    out = {}
    for c in ccys:
        s = regimes.states(world.panel(c, "model")).sort_index()
        at = s.index.searchsorted(days, side="right") - 1
        out[c] = pd.Series(np.where(at >= 0, s.to_numpy()[np.maximum(at, 0)], None), index=days)
    return out


def regime_rows(net, kept, active, entries, state, groups, periods, capital):
    """One row per group of states in `groups` (tuples of `regimes.STATES`, or collapsed names): counted and active
    sessions, trades entered, net P&L (% of capital, and a year), net Sharpe (SE)."""
    rows = []
    for g in groups:
        on = kept & state.isin(g)
        x = net[on]
        n = len(x)
        sr = metrics.sharpe(x, periods) if n > 1 else np.nan
        rows.append({"regime": g, "sessions": n, "active": int((active & on).sum()),
                     "trades": int(entries[on].sum()),
                     "net": x.sum() / capital * 100, "net_year": x.sum() / (n / periods) / capital * 100 if n else np.nan,
                     "net_sr": sr, "net_se": metrics.sharpe_se(sr, n / periods) if pd.notna(sr) else np.nan})
    return rows


def entries_of(f):
    """The trades a part puts on, by book session: 1 at each entry close (`metrics.trades`)."""
    k = f["kept"]
    t = metrics.trades(f.loc[k, "gross"], f.loc[k, "cost"], f.loc[k, "held"])
    return pd.Series(1, index=t.index).reindex(f.index, fill_value=0)


def regime_tables(world, st, b, parts, capital):
    """The regime tables: the book by the book currency's state (every state and the collapsed regimes), each
    sleeve by its own currency's collapsed regime (the cross sleeve by the book currency's), and the book by
    whether the currencies are in the same collapsed regime."""
    home = st.book["book"]["currency"]
    ccys = list(dict.fromkeys([home, *(c for i in st.inputs.values() for c in i.sleeve.ccys)]))
    on = states_on(world, ccys, st.days)
    per = b.run.periods
    d = b.run.daily
    k, net, active = d["kept"], d["gross"] - d["cost"], d["gross_dv01"] > 0
    entries = {n: entries_of(f) for n, f in parts.items()}
    every = sum(entries.values())
    book_rows = regime_rows(net, k, active, every, on[home], REGIME_ROWS, per, capital)
    coll = {c: s.map(COLLAPSED) for c, s in on.items()}
    by_sleeve = {}
    for n, f in parts.items():
        i = st.inputs[n]
        c = i.sleeve.ccys[0] if len(i.sleeve.ccys) == 1 else home
        by_sleeve[n] = {"ccy": c, "rows": regime_rows(f["gross"] - f["cost"], k, f["gross_dv01"] > 0, entries[n],
                                                      coll[c], [(g,) for g in COLLAPSED_ORDER], per, capital)}
    others = [c for c in ccys if c != home]
    pair = None
    if others:
        same = pd.Series(np.where(coll[home] == coll[others[0]], "same", "different"), index=st.days)
        pair = {"pair": [home, others[0]], "rows": regime_rows(net, k, active, every, same, [("same",), ("different",)],
                                                               per, capital)}
    return {"book": book_rows, "book_ccy": home, "sleeves": by_sleeve, "pair": pair}


# ---- the IC ------------------------------------------------------------------------

def ics(st):
    """{sleeve: {part: {sample: `metrics.ic_table` rows}}}: rate and total unit P&L, outside the ELB state and all."""
    hs = st.book["evaluation"]["ic_horizons"]
    out = {}
    for n, i in st.inputs.items():
        z = i.sleeve.component["z"]
        samples = {"ex_elb": z.notna() & ~i.state.reindex(z.index, fill_value=False), "all": z.notna()}
        out[n] = {part: {name: metrics.ic_table(z, unit_total(i, part), hs, i.sleeve.lag, m)
                         for name, m in samples.items()} for part in ("rate", "total")}
    return out


# ---- the current signal ------------------------------------------------------------

def current(st, b):
    """Each sleeve on the book's last session: its session, z, the rule's side, the book DV01 decided (book
    currency per bp), the instruments selected, and for the side z points to the edge, CR_h and E_h (bp)."""
    c = st.book["carry"]
    day = st.days[-1]
    rows = []
    for n, i in st.inputs.items():
        a = expression.ahead(i.sleeve, c["horizon_days"], c["closure_min_pairs"])
        a = a[a.index <= day].dropna(subset=["z"])
        r = a.iloc[-1]
        rows.append({"sleeve": n, "session": a.index[-1], "z": r["z"], "side": float(st.side[n].loc[a.index[-1]]),
                     "dv01": float(b.decided.loc[day, n]), "instrument": r["selected"], "edge_bp": r["edge_bp"],
                     "cr_h_bp": r["cr_h_bp"], "expected_bp": r["expected_bp"]})
    return rows


# ---- the build ---------------------------------------------------------------------

@dataclass
class Build:
    """Everything the report and the tear sheet say (module docstring)."""
    world: object
    portfolio: books.Build
    headline: books.Book
    fits: dict
    parts: dict
    carry: tuple
    elb: dict
    numbers: dict


def build(world=None, log=None):
    """The headline split, the carry benchmark, the ELB books and every table, from `world` (the real one)."""
    world = expression.World() if world is None else world
    say = log or (lambda *_: None)
    pb = books.build(world)
    say("books built")
    st = pb.setup
    book, capital = st.book, st.book["book"]["capital"]
    hb = pb.books[books.headline(book)]
    fits = betas(st)
    parts = split(st, hb, fits)
    check(hb, parts)
    check_costs(st, hb)
    cb = carry_book(pb)
    say("carry benchmark built")
    elb = elb_books(pb)
    say("ELB books built")
    b = Build(world, pb, hb, fits, parts, cb, elb, {})
    b.numbers = numbers(b)
    return b


def performance(b):
    """The performance rows: the book (trades pooled over sleeves), then each sleeve's contribution; `metrics.evaluate`
    on the whole sample, without 2022 and without 2022-23, % of capital."""
    st = b.portfolio.setup
    book, capital = st.book, st.book["book"]["capital"]
    per = b.headline.run.periods
    rows = []
    for name, x in [("book", b.headline), *((n, contribution(f, per)) for n, f in b.parts.items())]:
        ev = metrics.evaluate(x, capital=capital)
        if name == "book":
            k = b.headline.run.daily["kept"]
            t = pd.concat([metrics.trades(f.loc[k, "gross"], f.loc[k, "cost"], f.loc[k, "held"])
                           for f in b.parts.values()])
            ev |= {"trades": len(t), "hit_trade": float((t > 0).mean()) if len(t) else np.nan}
            ev |= {"cstar_bp": sleeves.stats(b.headline.run)["cstar_bp"]}
        rows.append({"name": name, **ev, "ex_2022": metrics.ex_2022(x, book, capital),
                     "ex_2022_23": metrics.ex_2022_23(x, book, capital)})
    return rows


def cost_curve(b):
    """The headline's net Sharpe against a uniform round trip (and the assumed legs only), its c* and cost mix."""
    run = b.headline.run
    s = sleeves.stats(run)
    c = s["cstar_bp"]
    top = max(sleeves.MIN_X_BP, sleeves.PAST_BREAKEVEN * c) if c is not None and np.isfinite(c) else sleeves.MIN_X_BP
    xs = np.linspace(0.0, top, sleeves.STEPS)
    return {"round_trip_bp": xs, "net_sr": sleeves.curve(run, xs), "assumed_net_sr": sleeves.curve(run, xs, "assumed"),
            "cstar_bp": c, "mix_bp": s["mix_bp"], "net_sr_at_mix": float(sleeves.curve(run, [s["mix_bp"]])[0]),
            "net_se": s["net_se"]}


def equity_curves(b):
    """Cumulative net P&L, % of capital, on the counted sessions: the book, its gross, and each component group."""
    st = b.portfolio.setup
    capital = st.book["book"]["capital"]
    d = b.headline.run.daily
    k = d["kept"]
    out = {"book": ((d["gross"] - d["cost"])[k].cumsum() / capital * 100),
           "book gross": (d["gross"][k].cumsum() / capital * 100)}
    groups = group_of(st)
    for g in dict.fromkeys(groups.values()):
        f = _sum(b.parts, [n for n, x in groups.items() if x == g], ["gross", "cost"])[k]
        out[g] = (f["gross"] - f["cost"]).cumsum() / capital * 100
    return out


def numbers(b):
    """Every number the report, the tear sheet and reports/results/metrics.json print."""
    st, pb = b.portfolio.setup, b.portfolio
    book, capital = st.book, st.book["book"]["capital"]
    rows, level = level_view(st, b.headline, b.parts, b.fits, capital)
    cs, cb = b.carry
    k = b.headline.run.daily["kept"] & cb.run.daily["kept"]
    x = (b.headline.run.daily["gross"] - b.headline.run.daily["cost"])[k]
    y = (cb.run.daily["gross"] - cb.run.daily["cost"])[k]
    both = (st.g != 0) & (cs.g != 0)
    agree = (st.g == cs.g) & both
    carry = {"summary": metrics.evaluate(cb, capital=capital), "corr": float(np.corrcoef(x, y)[0, 1]),
             "same_side": float(agree.to_numpy().sum() / both.to_numpy().sum()) if both.to_numpy().any() else np.nan,
             "same_side_by_sleeve": {n: float(agree[n].sum() / both[n].sum()) if both[n].any() else np.nan
                                     for n in st.g.columns},
             "ex_2022": metrics.ex_2022(cb, book, capital), "difference": books.difference(b.headline, cb)}
    carry["words"] = next(w for lim, w in CARRY_WORDS if abs(carry["corr"]) >= lim)
    elb = {tr: elb_split(s, bk, capital) for tr, (s, bk) in b.elb.items()}
    for tr, (s, bk) in b.elb.items():
        if tr != st.spec.treatment:
            elb[tr]["difference"] = books.difference(bk, b.headline)
    return {"days": (st.days[0], st.days[-1]), "first_counted": b.headline.run.daily.index[
                b.headline.run.daily["kept"]].min(),
            "performance": performance(b), "components": components(st, b.headline, b.parts, capital),
            "level_sleeves": rows, "level": level, "z_agreement": z_agreement(st), "carry": carry,
            "regimes": regime_tables(b.world, st, b.headline, b.parts, capital), "elb": elb,
            "elb_episodes": elb_episodes(b.world, book), "ic": ics(st), "current": current(st, b.headline),
            "cost_curve": cost_curve(b), "costs": cost_sources(st, b.headline, b.parts, capital),
            "carry_sleeves": carry_by_sleeve(st, b.headline, b.parts, capital), "filter": filter_entries(st),
            "level_gap": level_gap(b.world, st), "drawdown": drawdown_shape(b.headline, capital),
            "spec": st.spec, "treatment": st.spec.treatment}


# ---- the words ---------------------------------------------------------------------

sr, pc, pct = books.sr, books.pc, books.pct


def level_words(n):
    """The level-or-relative-value verdict, in words from the level-factor split."""
    lv = n["level"]
    share, gross = lv["variance_share"], lv["gross"]
    comp = {r["group"]: r for r in n["components"]}
    head = ("The level dominates: this is closer to a duration timer than to relative value" if lv["dominates"] else
            "Relative value dominates: the level exposure is the smaller part")
    return (f"**{head}.** {pct(share)} of the variance of the book's daily gross P&L is its exposure to the front ends "
            f"(the outrights, and the curve and cross sleeves' betas on them); the rest, {pct(1 - share)}, is the "
            f"relative value. In P&L the level exposure made {pc(lv['level'])} of capital a year gross and the rest "
            f"{pc(lv['rest'])}, of a gross {pc(gross)}"
            + (": the risk is mostly the level's, the loss mostly the rest's" if lv["dominates"] and
               lv["rest"] < min(lv["level"], 0.0) else "")
            + f". By sleeve group the level sleeves net {pc(comp['level']['net'])} "
            "a year, " + _and(f"the {g} sleeves {pc(comp[g]['net'])}" for g in comp if g not in ("level", "book"))
            + f", the book {pc(comp['book']['net'])}.")


def carry_words(n):
    """Carry and roll against the rate change, and the carry benchmark."""
    c, comp = n["carry"], {r["group"]: r for r in n["components"]}
    b, cs = comp["book"], c["summary"]
    paid = b["carry_roll"] < 0 < b["rate"]
    return (f"**The book is {c['words']}.** Of its gross {pc(b['gross'])} of capital a year, carry and roll are "
            f"{pc(b['carry_roll'])} and the rate change {pc(b['rate'])}"
            + (": its calls on the rate earn, and it pays more than that to hold them" if paid and b["gross"] < 0 else
               ": its calls on the rate earn, and it pays carry to hold them" if paid else "")
            + ". A benchmark on the same sleeves, rule, sizing "
            f"and costs, trading only the sign of each sleeve's carry and roll ahead, nets {sr(cs['net_sr'], cs['net_se'])}; "
            f"the book's daily net P&L correlates {c['corr']:+.2f} with it, and {pct(c['same_side'])} of the sleeve-"
            "sessions both hold a side are on the same side.")


def elb_words(n):
    """The ELB decision in words: the chosen treatment and what the others would have given."""
    e, chosen = n["elb"], n["treatment"]
    c = e[chosen]
    others = [t for t in positions.TREATMENTS if t != chosen]
    forced = (f", {c['closes']} positions closed on entering the state and {c['reopens']} re-opened on leaving it, "
              f"at {c['boundary_cost']:.2f}% of capital" if c["closes"] is not None else "")
    return (f"**The ELB: {sleeves.TREATMENT_WORDS[chosen]} (proposed).** The book nets {sr(c['net_sr'], c['net_se'])}"
            + forced + ". " + "; ".join(
                f"{sleeves.TREATMENT_WORDS[t]} it would net {sr(e[t]['net_sr'], e[t]['net_se'])} "
                f"({books.gap(e[t]['difference'])} against {chosen}), {pc(e[t]['in_state'], 1)} of capital from "
                f"positions decided in the state" for t in others) + ".")


def ex_words(n):
    """The book without 2022 and without the 2022-23 cycle."""
    p = n["performance"][0]
    a, b = p["ex_2022"], p["ex_2022_23"]
    return (f"**Without 2022.** The book nets {sr(p['net_sr'], p['net_se'])} over the sample, {sr(a['net_sr'], a['net_se'])} "
            f"without 2022 and {sr(b['net_sr'], b['net_se'])} without Dec 2021 to Aug 2023 (the positions not re-run: "
            "the rest of the sample's P&L).")


def regime_words(n):
    """Where the book earns by regime of the book currency."""
    rows = {r["regime"]: r for r in n["regimes"]["book"]}
    coll = [rows[g] for g in REGIME_ROWS if len(g) == 2] + [rows[("cutting",)], rows[(regimes.ELB,)]]
    name = lambda g: "hiking" if g == ("early_hiking", "late_hiking") else \
        "on hold" if g == ("hold_after_hikes", "hold_after_cuts") else STATE_WORDS[g[0]]
    return (f"**By {n['regimes']['book_ccy']} regime** the book nets "
            + _and(f"{sr(r['net_sr'], r['net_se'])} {name(r['regime'])} ({r['sessions']:,} sessions)" for r in coll)
            + ".")


def ic_words(n):
    """The level sleeves' IC at each horizon, on the rate change outside the ELB state."""
    hs = [r["h"] for r in next(iter(n["ic"].values()))["rate"]["ex_elb"]]
    parts = []
    for s, v in n["ic"].items():
        parts.append(f"{s} " + ", ".join(f"{r['ic']:+.2f} (t {r['t']:+.1f})" for r in v["rate"]["ex_elb"]))
    return (f"**The IC** of z against the next {', '.join(map(str, hs))} sessions' rate change, outside the ELB state: "
            + "; ".join(parts) + ".")


def _k(x):
    return f"{x / 1e3:,.0f}k"


def cost_words(n):
    """What the costs are made of: the turnover identity, the maintenance share, and today's DV01 against the mean."""
    r = n["costs"][-1]
    legs = {x["name"]: x["legs"] for x in n["costs"][:-1]}
    now = sum(abs(c["dv01"]) * legs[c["sleeve"]] for c in n["current"])
    maint = {x["name"]: x["cost"]["roll"] + x["cost"]["restrike"] for x in n["costs"][:-1]}
    top = max(maint, key=maint.get)
    return (f"**The costs are what the turnover says.** On the sessions with a position the book holds a mean gross "
            f"DV01 of {_k(r['mean_dv01'])} a bp over its {r['legs']} legs and trades it {r['turns_year']:.1f} times a "
            f"year at a mean {r['one_way_bp']:.2f}bp one way: {r['turns_year']:.1f} x {_k(r['mean_dv01'])} x "
            f"{r['one_way_bp']:.2f}bp is {r['cost_year']:.2f}% of capital a year, the cost charged. "
            f"{pct(r['maintenance'])} of it is maintenance (the outrights moved to the new instrument as each meeting "
            f"passes, charged as two outright one-ways, and the par legs re-struck every quarter), the most "
            f"{top}'s, {maint[top]:.2f}% a year."
            + (f" The current signal's positions ({_k(now)} gross) are {now / r['mean_dv01']:.0%} of that mean."
               if now < r["mean_dv01"] / 2 else ""))


READINGS = {(True, False): "right and bleeding", (False, False): "wrong and bleeding",
            (False, True): "wrong and collecting carry", (True, True): "right and collecting carry"}


def reading(r):
    """A sleeve's carry against rate in words: the rate change's sign, then carry and roll's."""
    return READINGS[(r["rate"] > 0, r["carry_roll"] > 0)]


def carry_sleeve_words(n):
    """Carry against rate by sleeve: which sleeves are right and bleeding, and whether the side runs against carry."""
    cs = n["carry_sleeves"]
    rows, book = cs["sleeves"], cs["book"]
    top = max(rows, key=lambda r: r["rate"])
    by = {}
    for r in rows:
        by.setdefault(reading(r), []).append(r)
    against = [r for r in rows if r["against"] < 0]
    with_ = [r for r in rows if r["against"] >= 0]
    rb = by.get("right and bleeding", [])
    return (("**By sleeve, only " + _and(r["sleeve"] for r in rb) + f" {'is' if len(rb) == 1 else 'are'} right and "
             "bleeding.** " if rb else "**By sleeve, no sleeve is right and bleeding.** ")
            + f"The book's rate change earns {pc(book['rate'])} a year, {top['sleeve']} {pc(top['rate'])} and the "
              f"other sleeves together {pc(book['rate'] - top['rate'])}. "
            + "; ".join(f"{_and(r['sleeve'] + ' (rate ' + pc(r['rate']) + ', carry and roll ' + pc(r['carry_roll']) + ')' for r in v)}"
                        f" {'is' if len(v) == 1 else 'are'} {w}" for w, v in by.items())
            + ". The side held runs against its carry and roll ahead in "
            + _and(f"{r['sleeve']} ({r['against']:+.2f})" for r in against)
            + (" and with it in " + _and(f"{r['sleeve']} ({r['against']:+.2f})" for r in with_) if with_ else "")
            + " (the correlation of the side with the sign of a receive's carry and roll ahead).")


def breakeven_words(n):
    """What the rate calls would have had to earn, for the book and as each sleeve's correlation of position and move."""
    cs = n["carry_sleeves"]
    b = cs["book"]
    clears = [r["sleeve"] for r in cs["sleeves"] if r["rate"] >= r["need"]]
    return (f"**What the rate calls would have had to earn.** Net zero needs the rate change to pay the costs less "
            f"carry and roll: the book's earns {pc(b['rate'])} a year against {pc(b['need'])} needed"
            + (f", {b['multiple']:.1f} times as much" if pd.notna(b["multiple"]) else "")
            + ". As the correlation of the position held with each session's rate move, sizes and moves as they "
              "were: " + _and(f"{r['sleeve']} {r['rho']:+.3f} against {r['rho_star']:+.3f}" for r in cs["sleeves"])
            + ". " + (f"{_and(clears)} {'clears' if len(clears) == 1 else 'clear'} it."
                      if clears else "No sleeve clears it."))


def filter_words(n):
    """The carry filter at entry: how many of the rule's entries it would skip."""
    f = n["filter"]
    entries, skipped = sum(v[0] for v in f.values()), sum(v[1] for v in f.values())
    return (f"**The carry filter would skip {skipped} of the rule's {entries} entries** "
            f"({pct(skipped / entries) if entries else 'n/a'}; an entry whose expected quarter, the edge's past "
            "closure and carry and roll on the rest, is below zero): "
            + _and(f"{s} {v[1]} of {v[0]}" for s, v in f.items())
            + ". The book with it on is the carry filter row of `reports/robustness.md`.")


def level_gap_words(n):
    """The level the z removes, per currency: how often the market sat below the rule, the range, and r*."""
    parts = []
    for c, v in n["level_gap"].items():
        ys = v["years"]
        if not ys:
            continue
        below = sum(x < 0 for x in ys.values())
        k = ORDINAL.get(v["k"][1], v["k"][1])
        count = ("every one" if below == len(ys) else "none" if below == 0 else f"{below}") + f" of {len(ys)}"
        parts.append(f"{c}'s market sat below the rule at the {k} meeting in {count} years outside the ELB state "
                     f"(annual means {min(ys.values()):+.0f} to {max(ys.values()):+.0f}bp, r* {v['rstar']})")
    return ("**The level the z removes.** " + "; ".join(parts) + ". The z trades the deviation from a trailing mean "
            "of this level; the level itself turns on r*, and what it is (a term premium, a discount on the "
            "committee following the rule, or the rule's own error) this report cannot tell.")


def drawdown_words(n):
    """The worst drawdown's shape: depth against vol, how long it took, and the worst month."""
    p, d = n["performance"][0], n["drawdown"]
    return (f"**The worst drawdown is a grind, not a break.** {d['depth']:.1f}% of capital at {p['vol']:.1f}% vol, "
            f"from {d['peak']:%b %Y} to {d['trough']:%b %Y} ({d['years']:.1f} years), while the worst "
            f"{MONTH}-session loss anywhere is {d['worst_month']:.1f}%. Hit rates, net: "
            + _and(f"{r['name']} {pct(r['hit_daily'])} of days and {pct(r['hit_trade'])} of trades"
                   for r in n["performance"][1:]) + ".")


def _cost_table(n):
    rows = [[r["name"], r["legs"], _k(r["mean_dv01"]), f"{r['one_way_bp']:.2f}",
             *[f"{r['turns'][c]:.1f}" for c in books.CAUSES], f"{r['turns_year']:.1f}",
             f"{r['cost_year']:.2f}%", pct(r["maintenance"])] for r in n["costs"]]
    return table(pd.DataFrame(rows, columns=["", "legs", "mean gross DV01 per bp", "one way bp",
                                             *[books.CAUSE_WORDS[c] for c in books.CAUSES], "turns a year",
                                             "cost a year", "maintenance share"]))


def _carry_sleeve_table(n):
    cs = n["carry_sleeves"]
    rows = [[r["sleeve"], pc(r["carry_roll"]), pc(r["rate"]), pc(-r["cost"]), pc(r["rate"] + r["carry_roll"] - r["cost"]),
             pc(r["need"]), reading(r), pct(r["bleeding"]), _num(r["against"], "+.2f"), _num(r["rho"], "+.3f"),
             _num(r["rho_star"], "+.3f")] for r in cs["sleeves"]]
    b = cs["book"]
    rows.append(["book", pc(b["carry_roll"]), pc(b["rate"]), pc(-b["cost"]), pc(b["rate"] + b["carry_roll"] - b["cost"]),
                 pc(b["need"]), "", "", "", "", ""])
    return table(pd.DataFrame(rows, columns=["sleeve", "carry and roll", "rate change", "costs", "net", "rate needed",
                                             "reading", "held and bleeding", "side vs carry", "rho", "rho*"]))


def _level_gap_table(n):
    rows = []
    for c, v in n["level_gap"].items():
        for r in v["regimes"]:
            rows.append([c, r["regime"], f"{r['sessions']:,}", *[f"{r['mean'][k]:+.0f}" for k in v["k"]]])
    ks = next(iter(n["level_gap"].values()))["k"]
    return table(pd.DataFrame(rows, columns=["", "regime", "sessions", *[f"gap at meeting {k}" for k in ks]]))


def _level_year_table(n):
    lg = n["level_gap"]
    years = sorted({y for v in lg.values() for y in v["years"]})
    rows = [[y, *[_num(v["years"].get(y), "+.0f") for v in lg.values()]] for y in years]
    return table(pd.DataFrame(rows, columns=["year", *[f"{c}, meeting {v['k'][1]}" for c, v in lg.items()]]))


def _num(x, spec):
    """`x` formatted by `spec`, or n/a where there is no number."""
    return "n/a" if x is None or pd.isna(x) else format(x, spec)


def _ic_table(n):
    head = ["sleeve", "part", "sample", *[f"IC({r['h']}) t" for r in next(iter(n["ic"].values()))["rate"]["all"]],
            "non-overlapping mean [range]"]
    rows = []
    for s, v in n["ic"].items():
        for part, samples in v.items():
            for name, rs in samples.items():
                rows.append([s, part, "outside the ELB" if name == "ex_elb" else "all",
                             *[f"{_num(r['ic'], '+.3f')} ({_num(r['t'], '+.1f')})" for r in rs],
                             "; ".join(f"{_num(r['offsets_mean'], '+.3f')} [{_num(r['offsets_min'], '+.2f')}, "
                                       f"{_num(r['offsets_max'], '+.2f')}]" for r in rs)])
    return table(pd.DataFrame(rows, columns=head))


def _perf_table(n):
    rows = []
    for r in n["performance"]:
        rows.append([r["name"], sr(r["gross_sr"], r["gross_se"]), sr(r["net_sr"], r["net_se"]), pc(r["net_year"]),
                     f"{r['vol']:.1f}%", f"{r['max_dd']:.1f}%", pct(r["hit_daily"]), pct(r["hit_trade"]),
                     f"{r['trades']:,}", f"{r['turns_year']:.1f}", pct(r["time_in_market"]),
                     sr(r["ex_2022"]["net_sr"], r["ex_2022"]["net_se"]),
                     sr(r["ex_2022_23"]["net_sr"], r["ex_2022_23"]["net_se"])])
    return table(pd.DataFrame(rows, columns=["", "gross SR", "net SR", "net a year", "vol", "worst dd", "hit (days)",
                                             "hit (trades)", "trades", "turns a year", "in market", "ex-2022",
                                             "ex-2022-23"]))


def _components_table(n):
    rows = [[r["group"], _and(r["sleeves"]) if r["group"] != "book" else "every sleeve", pc(r["gross"]),
             pc(-r["cost"]), pc(r["net"]), pc(r["carry_roll"]), pc(r["rate"]), pct(r["variance_share"]),
             sr(r["net_sr"], r["net_se"])] for r in n["components"]]
    return table(pd.DataFrame(rows, columns=["group", "sleeves", "gross a year", "costs", "net a year",
                                             "carry and roll", "rate change", "share of net variance",
                                             "net SR of the contribution"]))


def _level_table(n):
    rows = [[r["sleeve"], "; ".join(f"{o} {v:+.2f}" for o, v in r["betas"].items()), f"{r['r2']:.2f}",
             f"{r['sessions']:,}", pc(r["level"]), pc(r["rest"])] for r in n["level_sleeves"]]
    lv = n["level"]
    rows.append(["book", "", "", "", pc(lv["level"]), pc(lv["rest"])])
    return table(pd.DataFrame(rows, columns=["sleeve", "beta on the outright(s)", "R^2", "sessions",
                                             "level part, gross a year", "the rest, gross a year"]))


def _z_table(n):
    rows = []
    for r in n["z_agreement"]:
        for name in ("orthogonal", "raw"):
            if name in r:
                v = r[name]
                rows.append([r["ccy"], f"{r['level']} vs {r['slope']} ({name} slope)", f"{v['corr']:+.2f}",
                             pct(v["same_sign"]), f"{v['sessions']:,}"])
        rows.append([r["ccy"], "the book's sides, both on", "", pct(r["sides"]["same"]), f"{r['sides']['sessions']:,}"])
    return table(pd.DataFrame(rows, columns=["", "what", "corr of z", "same sign", "sessions"]))


def _regime_name(g):
    if len(g) == 2:
        return "**hiking**" if g[0] == "early_hiking" else "**on hold**"
    return STATE_WORDS.get(g[0], g[0])


def _regime_table(rows, name=_regime_name):
    return table(pd.DataFrame([[name(r["regime"]), f"{r['sessions']:,}", f"{r['active']:,}", f"{r['trades']:,}",
                                pc(r["net"], 1), pc(r["net_year"]), sr(r["net_sr"], r["net_se"])] for r in rows],
                              columns=["regime", "sessions", "with a position", "trades", "net", "net a year",
                                       "net SR"]))


def _sleeve_regimes(n):
    rows = []
    for s, v in n["regimes"]["sleeves"].items():
        rows.append([s, v["ccy"], *[f"{sr(r['net_sr'])} ({r['sessions']:,}; {r['trades']})" for r in v["rows"]]])
    return table(pd.DataFrame(rows, columns=["sleeve", "regime of", *COLLAPSED_ORDER]))


def _elb_table(n):
    rows = []
    for tr, e in n["elb"].items():
        rows.append([sleeves.TREATMENT_WORDS[tr] + ("*" if tr == n["treatment"] else ""), f"{e['sessions']:,}",
                     f"{e['state_sessions']:,}", pc(e["in_state"], 1), pc(e["outside"], 1), sr(e["net_sr"], e["net_se"]),
                     sr(e["outside_sr"], e["outside_se"]),
                     "n/a" if e["closes"] is None else f"{e['closes']} / {e['reopens']}",
                     "n/a" if e["boundary_cost"] is None else f"{e['boundary_cost']:.2f}%",
                     sr(e["ex_2022"]["net_sr"]), f"{e['max_dd']:.1f}%"])
    return table(pd.DataFrame(rows, columns=["treatment", "sessions counted", "with a position decided in the state",
                                             "net from those positions", "net from the rest", "net SR",
                                             "net SR without those sessions", "forced closes / re-opens",
                                             "their cost", "ex-2022", "worst dd"]))


def _episodes(n):
    return "; ".join(f"{c}: " + (", ".join(f"{a:%b %Y} to {b:%b %Y} ({k:,})" for a, b, k in eps) if eps else "none")
                     for c, eps in n["elb_episodes"].items())


def _current_table(n):
    rows = [[r["sleeve"], f"{r['session']:%d %b}", f"{r['z']:+.1f}",
             {1.0: "receive", -1.0: "pay", 0.0: "flat"}[r["side"]], f"{r['dv01'] / 1e3:+,.0f}k",
             r["instrument"], f"{r['edge_bp']:+.0f}", f"{r['cr_h_bp']:+.0f}", f"{r['expected_bp']:+.0f}"]
            for r in n["current"]]
    return rows


def markdown(b):
    """reports/metrics.md."""
    n = b.numbers
    st = b.portfolio.setup
    book = st.book
    c = n["cost_curve"]
    lines = [
        "# Attribution and evaluation: where the book's P&L comes from",
        "",
        f"Generated by `scripts/build_tearsheet.py` from `data/panel/` and the cache, book sessions "
        f"{n['days'][0]:%Y-%m-%d} .. {n['days'][1]:%Y-%m-%d}, counted from {n['first_counted']:%Y-%m-%d}. Do not edit by "
        "hand. The book is week 9's headline (`reports/portfolio.md`): "
        f"{books._name(books.headline(book))}, {st.spec.words(sizing=False)}, shrunk covariance, "
        f"{book['book']['vol_target']:.0%} vol target, no drawdown control. Net of costs unless named gross; P&L in % of "
        "capital. Every choice is a row in notes/DECISIONS.md, section A (attribution and evaluation).",
        "",
        "## The answer",
        "",
        f"- {level_words(n)}",
        f"- {carry_words(n)}",
        f"- {carry_sleeve_words(n)}",
        f"- {breakeven_words(n)}",
        f"- {cost_words(n)}",
        f"- {drawdown_words(n)}",
        f"- {level_gap_words(n)}",
        f"- {regime_words(n)}",
        f"- {elb_words(n)}",
        f"- {ex_words(n)}",
        f"- {ic_words(n)}",
        "",
        "![Attribution](figures/attribution_light.png)",
        "",
        "## Performance",
        "",
        "The book, then each sleeve's contribution to it (its P&L inside the book, over the book's counted sessions, so "
        "a sleeve's Sharpe counts the sessions it is flat). Hit rates are net: of the sessions with a position, and of "
        "the trades (a run of one side, from the close that opens it to the close that shuts it, its costs in; the "
        "book's are every sleeve's trades pooled). Without 2022 and 2022-23: the window's sessions left out, the "
        "positions not re-run.",
        "",
        _perf_table(n),
        "",
        f"The breakeven cost: {sleeves.cstar(c['cstar_bp'])}; at the configured mix ({c['mix_bp']:.2f}bp a round trip) "
        f"the book nets {sr(c['net_sr_at_mix'])}.",
        "",
        drawdown_words(n),
        "",
        "## Where the costs go",
        "",
        "Each sleeve's costs inside the book, and the book's. Mean gross DV01: every leg, on the sessions with a "
        "position, book currency per bp. Turns: DV01 traded a year over it, by cause (a whole round trip is 2): "
        "entries and exits (the sleeve's own side moved), resizing (another sleeve's did), rescaling (neither: the "
        "covariance, the vol target, the cap), rolls (the instrument changed under a held position) and re-strikes "
        "(the par legs, every quarter); rolls and re-strikes are the maintenance. The cost a year is turns x mean "
        "gross DV01 x the one-way cost, a year of counted sessions (`check_costs` holds the causes to the cost "
        "charged).",
        "",
        _cost_table(n),
        "",
        cost_words(n),
        "",
        "## By component",
        "",
        "Each group's P&L inside the book. The share of net variance is cov(group, book) / var(book): the shares add to "
        "one.",
        "",
        _components_table(n),
        "",
        "### The level factor",
        "",
        "Each sleeve's unit P&L on the outright unit P&L of its currencies (OLS with an intercept, full sample from the "
        "sleeve's first counted session: ex post). Its gross P&L in the book splits into position x betas x the "
        f"outrights' unit P&L, the level part, and the rest. The level part is {pct(n['level']['variance_share'])} of "
        f"the variance of the book's daily gross P&L (correlation {n['level']['corr']:.2f}); the verdict turns at "
        f"{LEVEL_DOMINATES:.0%}.",
        "",
        _level_table(n),
        "",
        "How far the level and slope signals agree (the traded slope is orthogonalised against the level; the raw "
        "8-minus-1 is not):",
        "",
        _z_table(n),
        "",
        "## Carry against rate",
        "",
        f"{carry_words(n)} Without 2022 the benchmark nets {sr(n['carry']['ex_2022']['net_sr'])}. The book against it: "
        f"{books.gap(n['carry']['difference'])}. By sleeve, the share of the sessions both hold a side on which they "
        "agree: " + _and(f"{s} {pct(v)}" for s, v in n["carry"]["same_side_by_sleeve"].items()) + ".",
        "",
        "### By sleeve",
        "",
        f"Each sleeve inside the book, % of capital a year. Rate needed: the rate change at which the sleeve nets "
        f"zero, its costs less its carry and roll. Held and bleeding: the share of the counted sessions with a "
        f"position on which the carry and roll ahead of the side held ({book['carry']['horizon_days']} days, the "
        "curve frozen) is below zero. Side vs carry: the correlation of the side with the sign of a receive's carry "
        "and roll ahead, on the same sessions. rho: the correlation of the position held with each session's rate "
        "move (unit P&L's rate component), and rho* the one at which the rate change pays for the costs less carry "
        "and roll, the positions' sizes and the moves as they were (`carry_by_sleeve`). They are daily, so small: "
        "the rate change is N x (rho x sd(position) x sd(move) + mean(position) x mean(move)), and rho* is near or "
        "below zero where the second term, the average tilt times the average move, already pays most of what is "
        "needed.",
        "",
        _carry_sleeve_table(n),
        "",
        f"- {carry_sleeve_words(n)}",
        f"- {breakeven_words(n)}",
        f"- {filter_words(n)}",
        "",
        "## By regime",
        "",
        f"Real-time regimes (`regimes.py`: ELB, early and late hiking, the two holds, cutting). The book by "
        f"{n['regimes']['book_ccy']}'s regime; hiking and on hold sum their two states. Trades are every sleeve's, by "
        "the regime at the close that put them on.",
        "",
        _regime_table(n["regimes"]["book"]),
        "",
        "Each sleeve's contribution by the collapsed regime of its own currency (the cross sleeve by the book "
        "currency's): net Sharpe (sessions; trades).",
        "",
        _sleeve_regimes(n),
    ]
    if n["regimes"]["pair"]:
        p = n["regimes"]["pair"]
        lines += ["", f"The book by whether {p['pair'][0]} and {p['pair'][1]} are in the same collapsed regime:", "",
                  _regime_table(p["rows"], name=lambda g: g[0])]
    lines += [
        "",
        "## The ELB",
        "",
        f"The state (`regimes.elb_state`): the policy rate on its floor and the rule's notional below it, so the model "
        f"path is flat at the floor and has no view. Its runs: {_episodes(n)}. The book under each treatment, same "
        "sizing and costs (* the configured one):",
        "",
        _elb_table(n),
        "",
        f"- {elb_words(n)}",
        "- The post-lift-off z is standardised against a trailing window that is mostly ELB sessions for up to two "
        "years after lift-off, so the first signals out of the state are measured against a quiet yardstick.",
        "",
        "## The IC",
        "",
        "Rank IC of z against the next h sessions of the unit P&L's rate change (and total) after the execution lag, "
        "t from a Newey-West SE with Bartlett weights to h (the overlap; a persistent z keeps the products "
        "autocorrelated past it, so the t overstates the precision). The non-overlapping cross-check is the IC on "
        "every h-th session, over the h start offsets.",
        "",
        _ic_table(n),
        "",
        "## The level the z removes",
        "",
        "The gap is market minus rule, bp; the z is its deviation from its own trailing two-year mean, so the level "
        "below is what the traded signal leaves out. By each currency's own collapsed regime (the ELB state its own "
        "row), at the first, the traded and the last meeting; then the traded meeting's mean by year outside the "
        f"ELB state (years with {LEVEL_MIN_SESSIONS} such sessions or more).",
        "",
        _level_gap_table(n),
        "",
        _level_year_table(n),
        "",
        level_gap_words(n),
        "",
        "## The current signal",
        "",
        table(pd.DataFrame(_current_table(n), columns=["sleeve", "as of", "z", "side", "book DV01 per bp",
                                                        "instrument", "edge bp", f"CR {book['carry']['horizon_days']}d",
                                                        f"E {book['carry']['horizon_days']}d"])),
        "",
    ]
    return "\n".join(lines)


def results(b):
    """reports/results/metrics.json: the numbers the note quotes, to six significant figures."""
    n = dict(b.numbers)
    n["spec"] = {"rule": n["spec"].rule, "enter": n["spec"].enter, "exit": n["spec"].exit,
                 "treatment": n["spec"].treatment}
    n["cost_curve"] = {k: (list(v) if isinstance(v, np.ndarray) else v) for k, v in n["cost_curve"].items()}
    reg = dict(n["regimes"])
    reg["book"] = [r | {"regime": "+".join(r["regime"])} for r in reg["book"]]
    reg["sleeves"] = {s: v | {"rows": [r | {"regime": r["regime"][0]} for r in v["rows"]]}
                      for s, v in reg["sleeves"].items()}
    if reg["pair"]:
        reg["pair"] = reg["pair"] | {"rows": [r | {"regime": r["regime"][0]} for r in reg["pair"]["rows"]]}
    n["regimes"] = reg
    n["elb_episodes"] = {c: [list(e) for e in v] for c, v in n["elb_episodes"].items()}
    n["filter"] = {s: {"entries": v[0], "skipped": v[1]} for s, v in n["filter"].items()}
    return _plain(n)


def figure(b, path, theme="light"):
    """reports/figures/attribution_{theme}.png: equity by component, the cost curve, IC bars, regime bars."""
    t = _style(theme)
    n = b.numbers
    fig, axes = plt.subplots(2, 2, figsize=(12, 8.4), gridspec_kw={"hspace": 0.5, "wspace": 0.25})
    colors = books.CATEGORICAL[theme]
    charts.equity_by_component(axes[0, 0], equity_curves(b), t, colors, windows=_windows(b))
    charts.cost_curve(axes[0, 1], n["cost_curve"], t, colors)
    charts.ic_bars(axes[1, 0], {s: v["rate"]["ex_elb"] for s, v in n["ic"].items()}, t, theme)
    book_rows, sleeve_rows = regime_bars_data(n)
    charts.regime_bars(axes[1, 1], book_rows, sleeve_rows, t, marks(b.portfolio.setup, colors))
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


MARKERS = ["o", "s", "^", "v"]      # by a sleeve's currency, in the book's order; a cross sleeve is a diamond


def marks(st, colors):
    """{sleeve: (colour, marker)}: its component group's colour (as `equity_curves` draws it), its currency's marker."""
    groups = list(dict.fromkeys(group_of(st).values()))
    ccys = list(dict.fromkeys(i.sleeve.ccys[0] for i in st.inputs.values() if len(i.sleeve.ccys) == 1))
    return {n: (colors[groups.index(GROUPS[i.sleeve.kind])],
                "D" if len(i.sleeve.ccys) > 1 else MARKERS[ccys.index(i.sleeve.ccys[0]) % len(MARKERS)])
            for n, i in st.inputs.items()}


def regime_bars_data(n):
    """({collapsed regime: the book's row}, {sleeve: its rows}) in `COLLAPSED_ORDER`, for `charts.regime_bars`."""
    rows = {r["regime"]: r for r in n["regimes"]["book"]}
    whole = {"hiking": ("early_hiking", "late_hiking"), "on hold": ("hold_after_hikes", "hold_after_cuts"),
             "cutting": ("cutting",), "ELB": (regimes.ELB,)}
    return ({g: rows[whole[g]] for g in COLLAPSED_ORDER},
            {s: v["rows"] for s, v in n["regimes"]["sleeves"].items()})


def _windows(b):
    lo, hi = metrics.window("ex_2022", b.portfolio.setup.book)
    return [(lo, hi, "2022")]


def write(b, root):
    """reports/metrics.md, reports/results/metrics.json and the figures under repo `root`. Returns the paths."""
    root = Path(root)
    out = {"report": root / "reports" / "metrics.md", "json": root / "reports" / "results" / "metrics.json"}
    for p in out.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    out["report"].write_text(markdown(b), encoding="utf-8")
    out["json"].write_text(json.dumps(results(b), indent=1) + "\n", encoding="utf-8")
    figures = root / "reports" / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        p = figures / f"attribution_{theme}.png"
        figure(b, p, theme)
        out[f"figure_{theme}"] = p
    return out
