"""Attribution and evaluation: where the headline book's P&L comes from, and what it depends on. Week 10.

Generated by `scripts/build_tearsheet.py`, never hand-edited: every number comes
from the books run here, and every sentence is a template filled from them.
The book is week 9's headline (`report/portfolio.py`, `headline`), run once;
nothing here re-sizes it or picks a better one.

**By component** (`split`). Each sleeve's positions, as the book decided them,
go back through `expression.run` on its own calendar, so the P&L splits into
carry, roll and rate change (`strategy/carry.py`) exactly as week 7 marks it,
and is credited to the book calendar as week 9 credits it (`check`: the parts
add up to the book's gross to 1e-8). The component groups are the sleeves'
kinds: level (the outrights), slope (the 2s10s) and cross-country (the
differential).

**The level factor** (`factor_split`). The groups are not independent: a 2s10s
receive gains in a bull steepening, when the front end rallies too. So each
sleeve's unit P&L is regressed on the outright unit P&L of its currencies
(`metrics.factor`, full sample, ex post), and its P&L split into its
position times its betas times the outrights' unit P&L (what its level
exposure earned) and the rest (the relative value). For an outright it is all
level. The share of the book's daily gross P&L variance the level part
explains, cov(level, book) / var(book), decides the verdict: at half or more,
the report says the level dominates, and that the book is closer to a
duration timer than to relative value.

**Carry against rate** (`carry_book`). The same split into carry and roll
against the rate change, and a benchmark: the same sleeves, rule, ELB
treatment, sizing and costs, with the z replaced by the sign of each
sleeve's carry and roll ahead (`expression.ahead`, CR_h for a receive). Its
daily net P&L's correlation with the headline's says whether the book is a
carry trade in costume: `CARRY_WORDS` words it.

**Regimes** (`regime_table`): `regimes.states` for each currency, real time. A
sleeve is keyed by its own currency's state, the cross sleeve and the book by
the book currency's, and the book also by whether the two currencies are in
the same collapsed regime (hiking, on hold, cutting, ELB). Every Sharpe carries
its counted and active sessions and the trades put on in the regime.

**The ELB** (`elb_books`). The book run under each treatment of
`strategy/positions.py` (flat, the configured one; exclude; hold), on the same
sizing and costs: the P&L of positions decided in the state, the rest, the
Sharpe with and without the state's sessions, and the boundary trades (the
positions a flat treatment closes on entering the state, and their cost).

**The IC** (`ics`): `metrics.ic_table` per sleeve, z against the next h
sessions of the rate-change component of unit P&L (and of the total), at
``evaluation.ic_horizons`` (a week, a month, a quarter), on the sessions
outside the ELB state and on all.

**Without 2022** (`metrics.ex_2022`, `metrics.ex_2022_23`): for the book, each
sleeve's contribution, each ELB treatment and the carry benchmark.
"""

from dataclasses import dataclass, replace
import json
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath import regimes
from policypath.backtest import metrics
from policypath.report import charts
from policypath.report import costs as sleeves
from policypath.report import portfolio as books
from policypath.report.coverage import table
from policypath.report.expression import _and, _plain
from policypath.report.figures import THEMES, _style
from policypath.strategy import expression, portfolio, positions

GROUPS = {"outright": "level", "curve": "slope", "cross": "cross-country"}
COLLAPSED = {regimes.ELB: "ELB", "early_hiking": "hiking", "late_hiking": "hiking", "hold_after_hikes": "on hold",
             "hold_after_cuts": "on hold", "cutting": "cutting"}
COLLAPSED_ORDER = ["hiking", "on hold", "cutting", "ELB"]
# The book table's rows: each state, with the collapsed regime after the states it sums.
REGIME_ROWS = [("early_hiking",), ("late_hiking",), ("early_hiking", "late_hiking"), ("hold_after_hikes",),
               ("hold_after_cuts",), ("hold_after_hikes", "hold_after_cuts"), ("cutting",), (regimes.ELB,)]
STATE_WORDS = {"early_hiking": "early hiking", "late_hiking": "late hiking", "hold_after_hikes": "hold after hikes",
               "hold_after_cuts": "hold after cuts", "cutting": "cutting", regimes.ELB: "ELB"}
LEVEL_DOMINATES = 0.5    # the level part's share of the book's gross P&L variance at which the level dominates
# |corr| of the book's daily net P&L with the carry benchmark's, and the words for it.
CARRY_WORDS = [(0.6, "a carry trade in costume"), (0.3, "partly a carry trade"), (0.0, "not a carry trade")]
TOL = 1e-8


# ---- the headline, split -----------------------------------------------------------

def outrights(st):
    """{ccy: the outright sleeve's name} in `st` (a `report.portfolio.Setup`)."""
    return {i.sleeve.ccys[0]: n for n, i in st.inputs.items() if i.sleeve.kind == "outright"}


def unit_total(i, part="total"):
    """A sleeve's unit P&L component (`part`) by its own session, bp: its legs summed."""
    return i.u.groupby("session")[part].sum(min_count=1).reindex(i.sleeve.sessions)


def betas(st):
    """{sleeve: (betas {outright name: beta}, R^2, sessions)}: each sleeve's unit P&L on its currencies' outrights.

    An outright is its own level (beta 1, R^2 1); the others are
    `metrics.factor` from the sleeve's first counted session.
    """
    out, level = {}, outrights(st)
    for n, i in st.inputs.items():
        on = [level[c] for c in i.sleeve.ccys if c in level]
        if n in on:
            out[n] = ({n: 1.0}, 1.0, int(unit_total(i).loc[i.start:].notna().sum()))
            continue
        xs = pd.DataFrame({o: unit_total(st.inputs[o]).reindex(i.sleeve.sessions) for o in on})
        out[n] = metrics.factor(unit_total(i).loc[i.start:], xs.loc[i.start:])
    return out


def split(st, b, fits):
    """{sleeve: its flows in book `b` on the book calendar}: gross, cost, traded, carry, roll, rate, level, held
    (signed first-leg DV01 held), gross_dv01 and kept (the book's). `fits` is `betas`."""
    level = outrights(st)
    days, kept = st.days, b.run.daily["kept"]
    out = {}
    for n, i in st.inputs.items():
        s = i.sleeve
        q = portfolio.asof(b.decided[n], s.sessions).fillna(0.0)
        _, sessions = expression.run(s, q, i.u)
        _, pnl, _, _ = positions.samples(i.state, st.spec.treatment, s.lag)
        held = sessions["position"].fillna(0.0).where(pnl, 0.0)
        coef = fits[n][0]
        x = sum(unit_total(st.inputs[o]).reindex(s.sessions) * beta for o, beta in coef.items())
        own = sessions[["carry", "roll", "rate"]].where(pnl, 0.0, axis=0)
        own["level"] = (held * x).fillna(0.0) if n not in level.values() else sessions["pnl"].where(pnl, 0.0)
        f = portfolio.to_book(own, days)
        part = b.parts[n]
        f["gross"], f["cost"], f["traded"] = part["gross"], part["cost"], part["traded"]
        f["held"] = portfolio.asof(held, days).fillna(0.0)
        f["gross_dv01"] = f["held"].abs() * len(s.legs)
        f["kept"] = kept
        out[n] = f
    return out


def contribution(f, periods):
    """One part's `metrics.Result` in the book (its flows, the book's counted sessions)."""
    return metrics.Result(f, periods)


def group_of(st):
    """{sleeve: its component group}: level, slope, cross-country."""
    return {n: GROUPS[i.sleeve.kind] for n, i in st.inputs.items()}


def _sum(parts, names, cols):
    return sum(parts[n][cols] for n in names)


def components(st, b, parts, capital):
    """Per component group and the book: net, gross, cost, carry and roll, rate, % of capital a year; the share of
    the book's net P&L variance (cov(part, book) / var(book)); the Sharpe of the group's net contribution."""
    k = b.run.daily["kept"]
    per = b.run.periods
    years = k.sum() / per
    book_net = (b.run.daily["gross"] - b.run.daily["cost"])[k]
    groups = group_of(st)
    rows = []
    for g in [*dict.fromkeys(groups.values()), "book"]:
        names = [n for n, x in groups.items() if g in (x, "book")]
        f = _sum(parts, names, ["gross", "cost", "carry", "roll", "rate", "level"])[k]
        net = f["gross"] - f["cost"]
        sr = metrics.sharpe(net, per)
        rows.append({"group": g, "sleeves": names, "net": net.sum() / years / capital * 100,
                     "gross": f["gross"].sum() / years / capital * 100, "cost": f["cost"].sum() / years / capital * 100,
                     "carry_roll": (f["carry"] + f["roll"]).sum() / years / capital * 100,
                     "rate": f["rate"].sum() / years / capital * 100,
                     "variance_share": float(np.cov(net, book_net)[0, 1] / book_net.var()),
                     "net_sr": sr, "net_se": metrics.sharpe_se(sr, years)})
    return rows


def level_view(st, b, parts, fits, capital):
    """The level-factor view: per sleeve its betas, R^2, and gross P&L split into level and the rest (% of capital a
    year); for the book the same split and the level part's share of the gross P&L variance."""
    k = b.run.daily["kept"]
    years = k.sum() / b.run.periods
    rows = []
    for n, f in parts.items():
        coef, r2, obs = fits[n]
        g, lv = f.loc[k, "gross"], f.loc[k, "level"]
        rows.append({"sleeve": n, "betas": coef, "r2": r2, "sessions": obs,
                     "level": lv.sum() / years / capital * 100, "rest": (g - lv).sum() / years / capital * 100})
    g = b.run.daily.loc[k, "gross"]
    lv = sum(f.loc[k, "level"] for f in parts.values())
    share = float(np.cov(lv, g)[0, 1] / g.var())
    return rows, {"level": lv.sum() / years / capital * 100, "rest": (g - lv).sum() / years / capital * 100,
                  "gross": g.sum() / years / capital * 100, "variance_share": share,
                  "corr": float(np.corrcoef(lv, g)[0, 1]), "dominates": bool(share >= LEVEL_DOMINATES)}


def z_agreement(st):
    """Per currency with an outright and a curve sleeve: corr(level z, slope z) and the share of sessions their signs
    agree, for the traded (orthogonal) slope and the raw 8-minus-1; and the share of book sessions both sleeves hold a
    side on which the sides agree."""
    rows = []
    for c, o in outrights(st).items():
        for n, i in st.inputs.items():
            if i.sleeve.kind != "curve" or i.sleeve.ccys[0] != c:
                continue
            lz, comp = st.inputs[o].sleeve.component["z"], i.sleeve.component
            row = {"ccy": c, "level": o, "slope": n}
            for name, z in (("orthogonal", comp["z"]), ("raw", comp.get("raw_z"))):
                if z is None:
                    continue
                both = pd.concat([lz, z], axis=1).dropna()
                row[name] = {"corr": float(both.corr().iloc[0, 1]),
                             "same_sign": float((np.sign(both.iloc[:, 0]) == np.sign(both.iloc[:, 1])).mean()),
                             "sessions": len(both)}
            g = st.g[[o, n]]
            on = (g != 0).all(axis=1)
            row["sides"] = {"same": float((g[on].iloc[:, 0] == g[on].iloc[:, 1]).mean()) if on.any() else np.nan,
                            "sessions": int(on.sum())}
            rows.append(row)
    return rows


def check(b, parts, tol=TOL):
    """Raise unless the split adds up: carry + roll + rate is each part's gross, and the parts are the book's."""
    for n, f in parts.items():
        off = (f["carry"] + f["roll"] + f["rate"] - f["gross"]).abs().max()
        if off > tol:
            raise RuntimeError(f"{n}: carry + roll + rate is {off:g} off its gross P&L in the book")
    total = sum(f["gross"] for f in parts.values())
    if (total - b.run.daily["gross"]).abs().max() > tol:
        raise RuntimeError("the parts' gross P&L is not the book's")


# ---- the other books: carry benchmark and ELB treatments ---------------------------

def carry_inputs(st, h, min_pairs):
    """The sleeves' `Inputs` with each z replaced by the sign of the receive's carry and roll ahead (CR_h)."""
    out = {}
    for n, i in st.inputs.items():
        a = expression.ahead(i.sleeve, h, min_pairs)
        cr = a["cr_h_bp"] * a["side"]            # the receive's CR_h: ahead signs it for sign(z)
        comp = i.sleeve.component.copy()
        comp["z"] = np.sign(cr).where(cr.notna() & (cr != 0))
        out[n] = replace(i, sleeve=replace(i.sleeve, component=comp))
    return out


def carry_book(pb):
    """The carry benchmark (module docstring): its `Setup` and headline book, on the headline's covariance."""
    st = pb.setup
    c = st.book["carry"]
    cs = books.from_inputs(st.book, st.days, carry_inputs(st, c["horizon_days"], c["closure_min_pairs"]))
    return cs, books.run_book(cs, pb.risks[None], books.headline(st.book))


def with_treatment(book, treatment):
    """A copy of the book config with ``evaluation.elb.chosen`` = `treatment`."""
    out = books.copy_book(book)
    out["evaluation"]["elb"]["chosen"] = treatment
    return out


def elb_books(pb):
    """{treatment: (Setup, Book)}: the headline under each ELB treatment, the configured one being the headline."""
    st = pb.setup
    h = books.headline(st.book)
    out = {}
    for tr in positions.TREATMENTS:
        if tr == st.spec.treatment:
            out[tr] = (st, pb.books[h])
            continue
        s = books.from_inputs(with_treatment(st.book, tr), st.days, st.inputs)
        out[tr] = (s, books.run_book(s, pb.risks[None], h))
    return out


def elb_split(st, b, capital):
    """One treatment's book against the ELB state, % of capital where P&L.

    On each sleeve session, the position held into it was decided in the state
    where the state shifted lag + 1 is (``line``), and the one put on at its
    close where the state shifted lag is (``put``). The P&L of positions decided
    in the state is the gross on ``line`` sessions less the cost of trades on
    sessions both are; the boundary trades are the trades on sessions exactly
    one is: the close on entering the state and the re-open on leaving it,
    which the flat treatment forces (under hold and exclude they are ordinary
    trades, so the count is the flat treatment's only). Also the net Sharpe on
    every counted session and on those no sleeve holds a position decided in
    the state.
    """
    days = st.days
    d = b.run.daily
    k = d["kept"]
    net = (d["gross"] - d["cost"])
    in_state = pd.Series(0.0, index=days)
    touched = pd.Series(False, index=days)
    closes, reopens, boundary_cost = 0, 0, 0.0
    for n, i in st.inputs.items():
        s = i.sleeve
        daily, _, _, _ = books._sleeve(st, n, b.decided, b.run.start)
        state = i.state.reindex(s.sessions, fill_value=False)
        line = state.shift(s.lag + 1, fill_value=False)
        put = state.shift(s.lag, fill_value=False)
        live = s.sessions >= b.run.start
        held = portfolio.asof(b.decided[n], s.sessions).fillna(0.0).shift(s.lag + 1, fill_value=0.0)
        mine = daily["gross"].where(line, 0.0) - daily["cost"].where(line & put, 0.0)
        in_state += portfolio.to_book(mine, days)
        touched |= portfolio.to_book((line & (held != 0)).astype(int), days) > 0
        if st.spec.treatment == "flat":
            traded = (daily["traded"] > 0) & live
            closes += int((traded & put & ~line).sum())
            reopens += int((traded & line & ~put).sum())
            boundary_cost += float(daily["cost"][traded & (put != line)].sum())
    per = b.run.periods
    out_sr = metrics.sharpe(net[k & ~touched], per)
    ev = metrics.evaluate(b, capital=capital)
    forced = st.spec.treatment == "flat"
    return {"treatment": st.spec.treatment, **ev,
            "state_sessions": int((k & touched).sum()),
            "in_state": float(in_state[k].sum() / capital * 100),
            "outside": float((net[k].sum() - in_state[k].sum()) / capital * 100),
            "outside_sr": out_sr, "outside_se": metrics.sharpe_se(out_sr, (k & ~touched).sum() / per),
            "closes": closes if forced else None, "reopens": reopens if forced else None,
            "boundary_cost": boundary_cost / capital * 100 if forced else None,
            "ex_2022": metrics.ex_2022(b, st.book, capital), "ex_2022_23": metrics.ex_2022_23(b, st.book, capital)}


def elb_episodes(world, book):
    """{ccy: [(first, last, sessions)]}: each currency's runs in the ELB state (`regimes.elb_state`)."""
    out = {}
    for c in dict.fromkeys(c for s in book["sleeves"] for c in ([s["ccy"]] if "ccy" in s else s["pair"])):
        e = regimes.episodes(regimes.elb_state(world.panel(c, "model")))
        e = e[e["state"]]
        out[c] = [(r["first"], r["last"], int(r["sessions"])) for _, r in e.iterrows()]
    return out


# ---- regimes -----------------------------------------------------------------------

def states_on(world, ccys, days):
    """{ccy: its regime (`regimes.states`) on each of `days`: the latest on or before it}."""
    out = {}
    for c in ccys:
        s = regimes.states(world.panel(c, "model")).sort_index()
        at = s.index.searchsorted(days, side="right") - 1
        out[c] = pd.Series(np.where(at >= 0, s.to_numpy()[np.maximum(at, 0)], None), index=days)
    return out


def regime_rows(net, kept, active, entries, state, groups, periods, capital):
    """One row per group of states in `groups` (tuples of `regimes.STATES`, or collapsed names): counted and active
    sessions, trades entered, net P&L (% of capital, and a year), net Sharpe (SE)."""
    rows = []
    for g in groups:
        on = kept & state.isin(g)
        x = net[on]
        n = len(x)
        sr = metrics.sharpe(x, periods) if n > 1 else np.nan
        rows.append({"regime": g, "sessions": n, "active": int((active & on).sum()),
                     "trades": int(entries[on].sum()),
                     "net": x.sum() / capital * 100, "net_year": x.sum() / (n / periods) / capital * 100 if n else np.nan,
                     "net_sr": sr, "net_se": metrics.sharpe_se(sr, n / periods) if pd.notna(sr) else np.nan})
    return rows


def entries_of(f):
    """The trades a part puts on, by book session: 1 at each entry close (`metrics.trades`)."""
    k = f["kept"]
    t = metrics.trades(f.loc[k, "gross"], f.loc[k, "cost"], f.loc[k, "held"])
    return pd.Series(1, index=t.index).reindex(f.index, fill_value=0)


def regime_tables(world, st, b, parts, capital):
    """The regime tables: the book by the book currency's state (every state and the collapsed regimes), each
    sleeve by its own currency's collapsed regime (the cross sleeve by the book currency's), and the book by
    whether the currencies are in the same collapsed regime."""
    home = st.book["book"]["currency"]
    ccys = list(dict.fromkeys([home, *(c for i in st.inputs.values() for c in i.sleeve.ccys)]))
    on = states_on(world, ccys, st.days)
    per = b.run.periods
    d = b.run.daily
    k, net, active = d["kept"], d["gross"] - d["cost"], d["gross_dv01"] > 0
    entries = {n: entries_of(f) for n, f in parts.items()}
    every = sum(entries.values())
    book_rows = regime_rows(net, k, active, every, on[home], REGIME_ROWS, per, capital)
    coll = {c: s.map(COLLAPSED) for c, s in on.items()}
    by_sleeve = {}
    for n, f in parts.items():
        i = st.inputs[n]
        c = i.sleeve.ccys[0] if len(i.sleeve.ccys) == 1 else home
        by_sleeve[n] = {"ccy": c, "rows": regime_rows(f["gross"] - f["cost"], k, f["gross_dv01"] > 0, entries[n],
                                                      coll[c], [(g,) for g in COLLAPSED_ORDER], per, capital)}
    others = [c for c in ccys if c != home]
    pair = None
    if others:
        same = pd.Series(np.where(coll[home] == coll[others[0]], "same", "different"), index=st.days)
        pair = {"pair": [home, others[0]], "rows": regime_rows(net, k, active, every, same, [("same",), ("different",)],
                                                               per, capital)}
    return {"book": book_rows, "book_ccy": home, "sleeves": by_sleeve, "pair": pair}


# ---- the IC ------------------------------------------------------------------------

def ics(st):
    """{sleeve: {part: {sample: `metrics.ic_table` rows}}}: rate and total unit P&L, outside the ELB state and all."""
    hs = st.book["evaluation"]["ic_horizons"]
    out = {}
    for n, i in st.inputs.items():
        z = i.sleeve.component["z"]
        samples = {"ex_elb": z.notna() & ~i.state.reindex(z.index, fill_value=False), "all": z.notna()}
        out[n] = {part: {name: metrics.ic_table(z, unit_total(i, part), hs, i.sleeve.lag, m)
                         for name, m in samples.items()} for part in ("rate", "total")}
    return out


# ---- the current signal ------------------------------------------------------------

def current(st, b):
    """Each sleeve on the book's last session: its session, z, the rule's side, the book DV01 decided (book
    currency per bp), the instruments selected, and for the side z points to the edge, CR_h and E_h (bp)."""
    c = st.book["carry"]
    day = st.days[-1]
    rows = []
    for n, i in st.inputs.items():
        a = expression.ahead(i.sleeve, c["horizon_days"], c["closure_min_pairs"])
        a = a[a.index <= day].dropna(subset=["z"])
        r = a.iloc[-1]
        rows.append({"sleeve": n, "session": a.index[-1], "z": r["z"], "side": float(st.side[n].loc[a.index[-1]]),
                     "dv01": float(b.decided.loc[day, n]), "instrument": r["selected"], "edge_bp": r["edge_bp"],
                     "cr_h_bp": r["cr_h_bp"], "expected_bp": r["expected_bp"]})
    return rows


# ---- the build ---------------------------------------------------------------------

@dataclass
class Build:
    """Everything the report and the tear sheet say (module docstring)."""
    world: object
    portfolio: books.Build
    headline: books.Book
    fits: dict
    parts: dict
    carry: tuple
    elb: dict
    numbers: dict


def build(world=None, log=None):
    """The headline split, the carry benchmark, the ELB books and every table, from `world` (the real one)."""
    world = expression.World() if world is None else world
    say = log or (lambda *_: None)
    pb = books.build(world)
    say("books built")
    st = pb.setup
    book, capital = st.book, st.book["book"]["capital"]
    hb = pb.books[books.headline(book)]
    fits = betas(st)
    parts = split(st, hb, fits)
    check(hb, parts)
    cb = carry_book(pb)
    say("carry benchmark built")
    elb = elb_books(pb)
    say("ELB books built")
    b = Build(world, pb, hb, fits, parts, cb, elb, {})
    b.numbers = numbers(b)
    return b


def performance(b):
    """The performance rows: the book (trades pooled over sleeves), then each sleeve's contribution; `metrics.evaluate`
    on the whole sample, without 2022 and without 2022-23, % of capital."""
    st = b.portfolio.setup
    book, capital = st.book, st.book["book"]["capital"]
    per = b.headline.run.periods
    rows = []
    for name, x in [("book", b.headline), *((n, contribution(f, per)) for n, f in b.parts.items())]:
        ev = metrics.evaluate(x, capital=capital)
        if name == "book":
            k = b.headline.run.daily["kept"]
            t = pd.concat([metrics.trades(f.loc[k, "gross"], f.loc[k, "cost"], f.loc[k, "held"])
                           for f in b.parts.values()])
            ev |= {"trades": len(t), "hit_trade": float((t > 0).mean()) if len(t) else np.nan}
            ev |= {"cstar_bp": sleeves.stats(b.headline.run)["cstar_bp"]}
        rows.append({"name": name, **ev, "ex_2022": metrics.ex_2022(x, book, capital),
                     "ex_2022_23": metrics.ex_2022_23(x, book, capital)})
    return rows


def cost_curve(b):
    """The headline's net Sharpe against a uniform round trip (and the assumed legs only), its c* and cost mix."""
    run = b.headline.run
    s = sleeves.stats(run)
    c = s["cstar_bp"]
    top = max(sleeves.MIN_X_BP, sleeves.PAST_BREAKEVEN * c) if c is not None and np.isfinite(c) else sleeves.MIN_X_BP
    xs = np.linspace(0.0, top, sleeves.STEPS)
    return {"round_trip_bp": xs, "net_sr": sleeves.curve(run, xs), "assumed_net_sr": sleeves.curve(run, xs, "assumed"),
            "cstar_bp": c, "mix_bp": s["mix_bp"], "net_sr_at_mix": float(sleeves.curve(run, [s["mix_bp"]])[0]),
            "net_se": s["net_se"]}


def equity_curves(b):
    """Cumulative net P&L, % of capital, on the counted sessions: the book, its gross, and each component group."""
    st = b.portfolio.setup
    capital = st.book["book"]["capital"]
    d = b.headline.run.daily
    k = d["kept"]
    out = {"book": ((d["gross"] - d["cost"])[k].cumsum() / capital * 100),
           "book gross": (d["gross"][k].cumsum() / capital * 100)}
    groups = group_of(st)
    for g in dict.fromkeys(groups.values()):
        f = _sum(b.parts, [n for n, x in groups.items() if x == g], ["gross", "cost"])[k]
        out[g] = (f["gross"] - f["cost"]).cumsum() / capital * 100
    return out


def numbers(b):
    """Every number the report, the tear sheet and reports/results/metrics.json print."""
    st, pb = b.portfolio.setup, b.portfolio
    book, capital = st.book, st.book["book"]["capital"]
    rows, level = level_view(st, b.headline, b.parts, b.fits, capital)
    cs, cb = b.carry
    k = b.headline.run.daily["kept"] & cb.run.daily["kept"]
    x = (b.headline.run.daily["gross"] - b.headline.run.daily["cost"])[k]
    y = (cb.run.daily["gross"] - cb.run.daily["cost"])[k]
    both = (st.g != 0) & (cs.g != 0)
    agree = (st.g == cs.g) & both
    carry = {"summary": metrics.evaluate(cb, capital=capital), "corr": float(np.corrcoef(x, y)[0, 1]),
             "same_side": float(agree.to_numpy().sum() / both.to_numpy().sum()) if both.to_numpy().any() else np.nan,
             "same_side_by_sleeve": {n: float(agree[n].sum() / both[n].sum()) if both[n].any() else np.nan
                                     for n in st.g.columns},
             "ex_2022": metrics.ex_2022(cb, book, capital), "difference": books.difference(b.headline, cb)}
    carry["words"] = next(w for lim, w in CARRY_WORDS if abs(carry["corr"]) >= lim)
    elb = {tr: elb_split(s, bk, capital) for tr, (s, bk) in b.elb.items()}
    for tr, (s, bk) in b.elb.items():
        if tr != st.spec.treatment:
            elb[tr]["difference"] = books.difference(bk, b.headline)
    return {"days": (st.days[0], st.days[-1]), "first_counted": b.headline.run.daily.index[
                b.headline.run.daily["kept"]].min(),
            "performance": performance(b), "components": components(st, b.headline, b.parts, capital),
            "level_sleeves": rows, "level": level, "z_agreement": z_agreement(st), "carry": carry,
            "regimes": regime_tables(b.world, st, b.headline, b.parts, capital), "elb": elb,
            "elb_episodes": elb_episodes(b.world, book), "ic": ics(st), "current": current(st, b.headline),
            "cost_curve": cost_curve(b), "spec": st.spec, "treatment": st.spec.treatment}


# ---- the words ---------------------------------------------------------------------

sr, pc, pct = books.sr, books.pc, books.pct


def level_words(n):
    """The level-or-relative-value verdict, in words from the level-factor split."""
    lv = n["level"]
    share, gross = lv["variance_share"], lv["gross"]
    comp = {r["group"]: r for r in n["components"]}
    head = ("The level dominates: this is closer to a duration timer than to relative value" if lv["dominates"] else
            "Relative value dominates: the level exposure is the smaller part")
    return (f"**{head}.** {pct(share)} of the variance of the book's daily gross P&L is its exposure to the front ends "
            f"(the outrights, and the curve and cross sleeves' betas on them); the rest, {pct(1 - share)}, is the "
            f"relative value. In P&L the level exposure made {pc(lv['level'])} of capital a year gross and the rest "
            f"{pc(lv['rest'])}, of a gross {pc(gross)}"
            + (": the risk is mostly the level's, the loss mostly the rest's" if lv["dominates"] and
               lv["rest"] < min(lv["level"], 0.0) else "")
            + f". By sleeve group the level sleeves net {pc(comp['level']['net'])} "
            "a year, " + _and(f"the {g} sleeves {pc(comp[g]['net'])}" for g in comp if g not in ("level", "book"))
            + f", the book {pc(comp['book']['net'])}.")


def carry_words(n):
    """Carry and roll against the rate change, and the carry benchmark."""
    c, comp = n["carry"], {r["group"]: r for r in n["components"]}
    b, cs = comp["book"], c["summary"]
    paid = b["carry_roll"] < 0 < b["rate"]
    return (f"**The book is {c['words']}.** Of its gross {pc(b['gross'])} of capital a year, carry and roll are "
            f"{pc(b['carry_roll'])} and the rate change {pc(b['rate'])}"
            + (": its calls on the rate earn, and it pays more than that to hold them" if paid and b["gross"] < 0 else
               ": its calls on the rate earn, and it pays carry to hold them" if paid else "")
            + ". A benchmark on the same sleeves, rule, sizing "
            f"and costs, trading only the sign of each sleeve's carry and roll ahead, nets {sr(cs['net_sr'], cs['net_se'])}; "
            f"the book's daily net P&L correlates {c['corr']:+.2f} with it, and {pct(c['same_side'])} of the sleeve-"
            "sessions both hold a side are on the same side.")


def elb_words(n):
    """The ELB decision in words: the chosen treatment and what the others would have given."""
    e, chosen = n["elb"], n["treatment"]
    c = e[chosen]
    others = [t for t in positions.TREATMENTS if t != chosen]
    forced = (f", {c['closes']} positions closed on entering the state and {c['reopens']} re-opened on leaving it, "
              f"at {c['boundary_cost']:.2f}% of capital" if c["closes"] is not None else "")
    return (f"**The ELB: {sleeves.TREATMENT_WORDS[chosen]} (proposed).** The book nets {sr(c['net_sr'], c['net_se'])}"
            + forced + ". " + "; ".join(
                f"{sleeves.TREATMENT_WORDS[t]} it would net {sr(e[t]['net_sr'], e[t]['net_se'])} "
                f"({books.gap(e[t]['difference'])} against {chosen}), {pc(e[t]['in_state'], 1)} of capital from "
                f"positions decided in the state" for t in others) + ".")


def ex_words(n):
    """The book without 2022 and without the 2022-23 cycle."""
    p = n["performance"][0]
    a, b = p["ex_2022"], p["ex_2022_23"]
    return (f"**Without 2022.** The book nets {sr(p['net_sr'], p['net_se'])} over the sample, {sr(a['net_sr'], a['net_se'])} "
            f"without 2022 and {sr(b['net_sr'], b['net_se'])} without Dec 2021 to Aug 2023 (the positions not re-run: "
            "the rest of the sample's P&L).")


def regime_words(n):
    """Where the book earns by regime of the book currency."""
    rows = {r["regime"]: r for r in n["regimes"]["book"]}
    coll = [rows[g] for g in REGIME_ROWS if len(g) == 2] + [rows[("cutting",)], rows[(regimes.ELB,)]]
    name = lambda g: "hiking" if g == ("early_hiking", "late_hiking") else \
        "on hold" if g == ("hold_after_hikes", "hold_after_cuts") else STATE_WORDS[g[0]]
    return (f"**By {n['regimes']['book_ccy']} regime** the book nets "
            + _and(f"{sr(r['net_sr'], r['net_se'])} {name(r['regime'])} ({r['sessions']:,} sessions)" for r in coll)
            + ".")


def ic_words(n):
    """The level sleeves' IC at each horizon, on the rate change outside the ELB state."""
    hs = [r["h"] for r in next(iter(n["ic"].values()))["rate"]["ex_elb"]]
    parts = []
    for s, v in n["ic"].items():
        parts.append(f"{s} " + ", ".join(f"{r['ic']:+.2f} (t {r['t']:+.1f})" for r in v["rate"]["ex_elb"]))
    return (f"**The IC** of z against the next {', '.join(map(str, hs))} sessions' rate change, outside the ELB state: "
            + "; ".join(parts) + ".")


def _num(x, spec):
    """`x` formatted by `spec`, or n/a where there is no number."""
    return "n/a" if x is None or pd.isna(x) else format(x, spec)


def _ic_table(n):
    head = ["sleeve", "part", "sample", *[f"IC({r['h']}) t" for r in next(iter(n["ic"].values()))["rate"]["all"]],
            "non-overlapping mean [range]"]
    rows = []
    for s, v in n["ic"].items():
        for part, samples in v.items():
            for name, rs in samples.items():
                rows.append([s, part, "outside the ELB" if name == "ex_elb" else "all",
                             *[f"{_num(r['ic'], '+.3f')} ({_num(r['t'], '+.1f')})" for r in rs],
                             "; ".join(f"{_num(r['offsets_mean'], '+.3f')} [{_num(r['offsets_min'], '+.2f')}, "
                                       f"{_num(r['offsets_max'], '+.2f')}]" for r in rs)])
    return table(pd.DataFrame(rows, columns=head))


def _perf_table(n):
    rows = []
    for r in n["performance"]:
        rows.append([r["name"], sr(r["gross_sr"], r["gross_se"]), sr(r["net_sr"], r["net_se"]), pc(r["net_year"]),
                     f"{r['vol']:.1f}%", f"{r['max_dd']:.1f}%", pct(r["hit_daily"]), pct(r["hit_trade"]),
                     f"{r['trades']:,}", f"{r['turns_year']:.1f}", pct(r["time_in_market"]),
                     sr(r["ex_2022"]["net_sr"], r["ex_2022"]["net_se"]),
                     sr(r["ex_2022_23"]["net_sr"], r["ex_2022_23"]["net_se"])])
    return table(pd.DataFrame(rows, columns=["", "gross SR", "net SR", "net a year", "vol", "worst dd", "hit (days)",
                                             "hit (trades)", "trades", "turns a year", "in market", "ex-2022",
                                             "ex-2022-23"]))


def _components_table(n):
    rows = [[r["group"], _and(r["sleeves"]) if r["group"] != "book" else "every sleeve", pc(r["gross"]),
             pc(-r["cost"]), pc(r["net"]), pc(r["carry_roll"]), pc(r["rate"]), pct(r["variance_share"]),
             sr(r["net_sr"], r["net_se"])] for r in n["components"]]
    return table(pd.DataFrame(rows, columns=["group", "sleeves", "gross a year", "costs", "net a year",
                                             "carry and roll", "rate change", "share of net variance",
                                             "net SR of the contribution"]))


def _level_table(n):
    rows = [[r["sleeve"], "; ".join(f"{o} {v:+.2f}" for o, v in r["betas"].items()), f"{r['r2']:.2f}",
             f"{r['sessions']:,}", pc(r["level"]), pc(r["rest"])] for r in n["level_sleeves"]]
    lv = n["level"]
    rows.append(["book", "", "", "", pc(lv["level"]), pc(lv["rest"])])
    return table(pd.DataFrame(rows, columns=["sleeve", "beta on the outright(s)", "R^2", "sessions",
                                             "level part, gross a year", "the rest, gross a year"]))


def _z_table(n):
    rows = []
    for r in n["z_agreement"]:
        for name in ("orthogonal", "raw"):
            if name in r:
                v = r[name]
                rows.append([r["ccy"], f"{r['level']} vs {r['slope']} ({name} slope)", f"{v['corr']:+.2f}",
                             pct(v["same_sign"]), f"{v['sessions']:,}"])
        rows.append([r["ccy"], "the book's sides, both on", "", pct(r["sides"]["same"]), f"{r['sides']['sessions']:,}"])
    return table(pd.DataFrame(rows, columns=["", "what", "corr of z", "same sign", "sessions"]))


def _regime_name(g):
    if len(g) == 2:
        return "**hiking**" if g[0] == "early_hiking" else "**on hold**"
    return STATE_WORDS.get(g[0], g[0])


def _regime_table(rows, name=_regime_name):
    return table(pd.DataFrame([[name(r["regime"]), f"{r['sessions']:,}", f"{r['active']:,}", f"{r['trades']:,}",
                                pc(r["net"], 1), pc(r["net_year"]), sr(r["net_sr"], r["net_se"])] for r in rows],
                              columns=["regime", "sessions", "with a position", "trades", "net", "net a year",
                                       "net SR"]))


def _sleeve_regimes(n):
    rows = []
    for s, v in n["regimes"]["sleeves"].items():
        rows.append([s, v["ccy"], *[f"{sr(r['net_sr'])} ({r['sessions']:,}; {r['trades']})" for r in v["rows"]]])
    return table(pd.DataFrame(rows, columns=["sleeve", "regime of", *COLLAPSED_ORDER]))


def _elb_table(n):
    rows = []
    for tr, e in n["elb"].items():
        rows.append([sleeves.TREATMENT_WORDS[tr] + ("*" if tr == n["treatment"] else ""), f"{e['sessions']:,}",
                     f"{e['state_sessions']:,}", pc(e["in_state"], 1), pc(e["outside"], 1), sr(e["net_sr"], e["net_se"]),
                     sr(e["outside_sr"], e["outside_se"]),
                     "n/a" if e["closes"] is None else f"{e['closes']} / {e['reopens']}",
                     "n/a" if e["boundary_cost"] is None else f"{e['boundary_cost']:.2f}%",
                     sr(e["ex_2022"]["net_sr"]), f"{e['max_dd']:.1f}%"])
    return table(pd.DataFrame(rows, columns=["treatment", "sessions counted", "with a position decided in the state",
                                             "net from those positions", "net from the rest", "net SR",
                                             "net SR without those sessions", "forced closes / re-opens",
                                             "their cost", "ex-2022", "worst dd"]))


def _episodes(n):
    return "; ".join(f"{c}: " + (", ".join(f"{a:%b %Y} to {b:%b %Y} ({k:,})" for a, b, k in eps) if eps else "none")
                     for c, eps in n["elb_episodes"].items())


def _current_table(n):
    rows = [[r["sleeve"], f"{r['session']:%d %b}", f"{r['z']:+.1f}",
             {1.0: "receive", -1.0: "pay", 0.0: "flat"}[r["side"]], f"{r['dv01'] / 1e3:+,.0f}k",
             r["instrument"], f"{r['edge_bp']:+.0f}", f"{r['cr_h_bp']:+.0f}", f"{r['expected_bp']:+.0f}"]
            for r in n["current"]]
    return rows


def markdown(b):
    """reports/metrics.md."""
    n = b.numbers
    st = b.portfolio.setup
    book = st.book
    c = n["cost_curve"]
    lines = [
        "# Attribution and evaluation: where the book's P&L comes from",
        "",
        f"Generated by `scripts/build_tearsheet.py` from `data/panel/` and the cache, book sessions "
        f"{n['days'][0]:%Y-%m-%d} .. {n['days'][1]:%Y-%m-%d}, counted from {n['first_counted']:%Y-%m-%d}. Do not edit by "
        "hand. The book is week 9's headline (`reports/portfolio.md`): "
        f"{books._name(books.headline(book))}, {st.spec.words(sizing=False)}, shrunk covariance, "
        f"{book['book']['vol_target']:.0%} vol target, no drawdown control. Net of costs unless named gross; P&L in % of "
        "capital. Every choice is a row in notes/DECISIONS.md, section A (attribution and evaluation).",
        "",
        "## The answer",
        "",
        f"- {level_words(n)}",
        f"- {carry_words(n)}",
        f"- {regime_words(n)}",
        f"- {elb_words(n)}",
        f"- {ex_words(n)}",
        f"- {ic_words(n)}",
        "",
        "![Attribution](figures/attribution_light.png)",
        "",
        "## Performance",
        "",
        "The book, then each sleeve's contribution to it (its P&L inside the book, over the book's counted sessions, so "
        "a sleeve's Sharpe counts the sessions it is flat). Hit rates are net: of the sessions with a position, and of "
        "the trades (a run of one side, from the close that opens it to the close that shuts it, its costs in; the "
        "book's are every sleeve's trades pooled). Without 2022 and 2022-23: the window's sessions left out, the "
        "positions not re-run.",
        "",
        _perf_table(n),
        "",
        f"The breakeven cost: {sleeves.cstar(c['cstar_bp'])}; at the configured mix ({c['mix_bp']:.2f}bp a round trip) "
        f"the book nets {sr(c['net_sr_at_mix'])}.",
        "",
        "## By component",
        "",
        "Each group's P&L inside the book. The share of net variance is cov(group, book) / var(book): the shares add to "
        "one.",
        "",
        _components_table(n),
        "",
        "### The level factor",
        "",
        "Each sleeve's unit P&L on the outright unit P&L of its currencies (OLS with an intercept, full sample from the "
        "sleeve's first counted session: ex post). Its gross P&L in the book splits into position x betas x the "
        f"outrights' unit P&L, the level part, and the rest. The level part is {pct(n['level']['variance_share'])} of "
        f"the variance of the book's daily gross P&L (correlation {n['level']['corr']:.2f}); the verdict turns at "
        f"{LEVEL_DOMINATES:.0%}.",
        "",
        _level_table(n),
        "",
        "How far the level and slope signals agree (the traded slope is orthogonalised against the level; the raw "
        "8-minus-1 is not):",
        "",
        _z_table(n),
        "",
        "## Carry against rate",
        "",
        f"{carry_words(n)} Without 2022 the benchmark nets {sr(n['carry']['ex_2022']['net_sr'])}. The book against it: "
        f"{books.gap(n['carry']['difference'])}. By sleeve, the share of the sessions both hold a side on which they "
        "agree: " + _and(f"{s} {pct(v)}" for s, v in n["carry"]["same_side_by_sleeve"].items()) + ".",
        "",
        "## By regime",
        "",
        f"Real-time regimes (`regimes.py`: ELB, early and late hiking, the two holds, cutting). The book by "
        f"{n['regimes']['book_ccy']}'s regime; hiking and on hold sum their two states. Trades are every sleeve's, by "
        "the regime at the close that put them on.",
        "",
        _regime_table(n["regimes"]["book"]),
        "",
        "Each sleeve's contribution by the collapsed regime of its own currency (the cross sleeve by the book "
        "currency's): net Sharpe (sessions; trades).",
        "",
        _sleeve_regimes(n),
    ]
    if n["regimes"]["pair"]:
        p = n["regimes"]["pair"]
        lines += ["", f"The book by whether {p['pair'][0]} and {p['pair'][1]} are in the same collapsed regime:", "",
                  _regime_table(p["rows"], name=lambda g: g[0])]
    lines += [
        "",
        "## The ELB",
        "",
        f"The state (`regimes.elb_state`): the policy rate on its floor and the rule's notional below it, so the model "
        f"path is flat at the floor and has no view. Its runs: {_episodes(n)}. The book under each treatment, same "
        "sizing and costs (* the configured one):",
        "",
        _elb_table(n),
        "",
        f"- {elb_words(n)}",
        "- The post-lift-off z is standardised against a trailing window that is mostly ELB sessions for up to two "
        "years after lift-off, so the first signals out of the state are measured against a quiet yardstick.",
        "",
        "## The IC",
        "",
        "Rank IC of z against the next h sessions of the unit P&L's rate change (and total) after the execution lag, "
        "t from a Newey-West SE with Bartlett weights to h (the overlap; a persistent z keeps the products "
        "autocorrelated past it, so the t overstates the precision). The non-overlapping cross-check is the IC on "
        "every h-th session, over the h start offsets.",
        "",
        _ic_table(n),
        "",
        "## The current signal",
        "",
        table(pd.DataFrame(_current_table(n), columns=["sleeve", "as of", "z", "side", "book DV01 per bp",
                                                        "instrument", "edge bp", f"CR {book['carry']['horizon_days']}d",
                                                        f"E {book['carry']['horizon_days']}d"])),
        "",
    ]
    return "\n".join(lines)


def results(b):
    """reports/results/metrics.json: the numbers the note quotes, to six significant figures."""
    n = dict(b.numbers)
    n["spec"] = {"rule": n["spec"].rule, "enter": n["spec"].enter, "exit": n["spec"].exit,
                 "treatment": n["spec"].treatment}
    n["cost_curve"] = {k: (list(v) if isinstance(v, np.ndarray) else v) for k, v in n["cost_curve"].items()}
    reg = dict(n["regimes"])
    reg["book"] = [r | {"regime": "+".join(r["regime"])} for r in reg["book"]]
    reg["sleeves"] = {s: v | {"rows": [r | {"regime": r["regime"][0]} for r in v["rows"]]}
                      for s, v in reg["sleeves"].items()}
    if reg["pair"]:
        reg["pair"] = reg["pair"] | {"rows": [r | {"regime": r["regime"][0]} for r in reg["pair"]["rows"]]}
    n["regimes"] = reg
    n["elb_episodes"] = {c: [list(e) for e in v] for c, v in n["elb_episodes"].items()}
    return _plain(n)


def figure(b, path, theme="light"):
    """reports/figures/attribution_{theme}.png: equity by component, the cost curve, IC bars, regime bars."""
    t = _style(theme)
    n = b.numbers
    fig, axes = plt.subplots(2, 2, figsize=(12, 8.4), gridspec_kw={"hspace": 0.5, "wspace": 0.25})
    colors = books.CATEGORICAL[theme]
    charts.equity_by_component(axes[0, 0], equity_curves(b), t, colors, windows=_windows(b))
    charts.cost_curve(axes[0, 1], n["cost_curve"], t, colors)
    charts.ic_bars(axes[1, 0], {s: v["rate"]["ex_elb"] for s, v in n["ic"].items()}, t, theme)
    book_rows, sleeve_rows = regime_bars_data(n)
    charts.regime_bars(axes[1, 1], book_rows, sleeve_rows, t, marks(b.portfolio.setup, colors))
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


MARKERS = ["o", "s", "^", "v"]      # by a sleeve's currency, in the book's order; a cross sleeve is a diamond


def marks(st, colors):
    """{sleeve: (colour, marker)}: its component group's colour (as `equity_curves` draws it), its currency's marker."""
    groups = list(dict.fromkeys(group_of(st).values()))
    ccys = list(dict.fromkeys(i.sleeve.ccys[0] for i in st.inputs.values() if len(i.sleeve.ccys) == 1))
    return {n: (colors[groups.index(GROUPS[i.sleeve.kind])],
                "D" if len(i.sleeve.ccys) > 1 else MARKERS[ccys.index(i.sleeve.ccys[0]) % len(MARKERS)])
            for n, i in st.inputs.items()}


def regime_bars_data(n):
    """({collapsed regime: the book's row}, {sleeve: its rows}) in `COLLAPSED_ORDER`, for `charts.regime_bars`."""
    rows = {r["regime"]: r for r in n["regimes"]["book"]}
    whole = {"hiking": ("early_hiking", "late_hiking"), "on hold": ("hold_after_hikes", "hold_after_cuts"),
             "cutting": ("cutting",), "ELB": (regimes.ELB,)}
    return ({g: rows[whole[g]] for g in COLLAPSED_ORDER},
            {s: v["rows"] for s, v in n["regimes"]["sleeves"].items()})


def _windows(b):
    lo, hi = metrics.window("ex_2022", b.portfolio.setup.book)
    return [(lo, hi, "2022")]


def write(b, root):
    """reports/metrics.md, reports/results/metrics.json and the figures under repo `root`. Returns the paths."""
    root = Path(root)
    out = {"report": root / "reports" / "metrics.md", "json": root / "reports" / "results" / "metrics.json"}
    for p in out.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    out["report"].write_text(markdown(b), encoding="utf-8")
    out["json"].write_text(json.dumps(results(b), indent=1) + "\n", encoding="utf-8")
    figures = root / "reports" / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        p = figures / f"attribution_{theme}.png"
        figure(b, p, theme)
        out[f"figure_{theme}"] = p
    return out
