"""The costs report: what each sleeve is worth net of costs, how fragile that is, and what it trades to get there.

Generated by `scripts/build_strategy.py`, never hand-edited: every number comes
from the sleeves run under the book's rules (`strategy/positions.py`), charged
by `strategy/costs.py`, and every sentence is a template filled from them.

The question is not "what is the Sharpe" but "how fragile
is it". So the report leads with the net Sharpe as a function of the cost
assumed, and the cost at which it stops working, in closed form.

**What is run.** A sleeve under one `Spec`: the rule (``positions.rule``,
hysteresis at (``positions.enter``, ``positions.exit``) = (1.0, 0.0), or
linear), the ELB treatment (``evaluation.elb.chosen``, flat, or exclude or
hold), and the sizing (vol-scaled, primary: each sleeve alone at the book's
vol target; or unit, one book DV01 a unit of s). Every number the report
prints says which. Each run is `expression.run` on the positions decided:
the expression seam, so the legs, marks and P&L are the expression layer's to the bit.

**The sample.** From the first session a position decided on the sleeve's
first z is held (first z + lag + 1) to its last session; the treatment says
which of those count (`positions.samples`). Sharpe is annualised by the
sleeve calendar's observed sessions a year (`backtest.metrics`), and every
one carries its standard error.

**The equal-risk sum** (`combine`): each sleeve's vol-scaled P&L (each alone at
the book's risk), summed into the next session of the book currency's
calendar, as the book's calendar has it; from the first session every
sleeve has started, and a session counts where any sleeve's treatment counts
it, with only what each sleeve's treatment keeps in it. It is a sum of sleeves, not the book: the covariance, the vol target on
the whole and the drawdown control are the book's. With unit sizing it is the
equal-DV01 sum.

**Turnover** is book DV01 traded, summed over legs. "Turns" divides it by the
mean gross DV01 held on the sessions with a position (every leg's |q|), so a
whole round trip is 2 turns however many legs a sleeve has, and a
vol-scaled sleeve's turnover is comparable with a unit one's.
"""

from dataclasses import dataclass, replace
import json
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.lines import Line2D
from matplotlib.patches import Patch, Rectangle
from policypath import config
from policypath.backtest import metrics
from policypath.report.coverage import table
from policypath.report.expression import _and, _ink_on, _label, _plain
from policypath.report.figures import THEMES, _style
from policypath.strategy import costs, expression, instruments, positions, risk

SUM = "Equal-risk sum"
SIZING_WORDS = {"vol_scaled": "vol-scaled", "unit": "unit"}
TREATMENT_WORDS = {"flat": "flat at the ELB", "exclude": "ELB sessions excluded", "hold": "held through the ELB"}
MIN_X_BP = 5.0          # the sensitivity curve is drawn to max(this, 1.2 c*)
PAST_BREAKEVEN = 1.2
STEPS = 241             # points on each drawn curve


# ---- running a sleeve --------------------------------------------------------------

@dataclass(frozen=True)
class Spec:
    """One way of running a sleeve: rule, ELB treatment, sizing, the hysteresis pair, and the options.

    `restrike_months` overrides every par leg's ``roll_every_months``; `band`
    the ``risk.no_trade_band`` (None: the book's).
    """
    rule: str
    treatment: str
    sizing: str
    enter: float
    exit: float
    carry_filter: bool = False
    restrike_months: int | None = None
    band: float | None = None

    def words(self, sizing=True):
        rule = f"hysteresis ({self.enter:g}, {self.exit:g})" if self.rule == "hysteresis" else "linear"
        return f"{rule}, {TREATMENT_WORDS[self.treatment]}" + (f", {SIZING_WORDS[self.sizing]}" if sizing else "")


def chosen(book, sizing="vol_scaled", **kw):
    """The book's own spec: its rule and pair, its ELB treatment, the carry filter as configured."""
    p = book["positions"]
    base = Spec(p["rule"], book["evaluation"]["elb"]["chosen"], sizing, p["enter"], p["exit"], p["carry_filter"])
    return replace(base, **kw)


@dataclass
class Inputs:
    """What every run of one sleeve shares, built once: unit P&L, sigma, the ELB state, the carry gate, the costs.

    `start` is the first session a position decided on the first z is held;
    `periods` the sleeve calendar's sessions a year from there; `raw_sigma` the
    unfloored EWMA sigma.
    """
    sleeve: object
    u: pd.DataFrame
    sigma: pd.Series
    raw_sigma: pd.Series
    state: pd.Series
    allow: pd.Series
    costs: list
    start: pd.Timestamp
    periods: float


def inputs(sleeve, world, book, like=None):
    """One sleeve's `Inputs`, from the world its sleeves were built from.

    `like` is the `Inputs` of the same sleeve on the same legs with another
    signal (the robustness rows): its unit P&L, sigma and costs are
    reused, and only what reads the signal or the model (the ELB state, the
    carry gate, the start) is built again.
    """
    if like is None:
        u = expression.unit(sleeve)
        total = u.groupby("session")["total"].sum(min_count=1).reindex(sleeve.sessions)
        r = book["risk"]
        raw = risk.ewma_sigma(total, r["ewma_lambda"])
        like = Inputs(None, u, risk.sigma_floor(raw, r["sigma_floor"]), raw, None, None, costs.leg_costs(sleeve), None,
                      None)
    state = positions.elb(sleeve, {c: world.panel(c, "model") for c in sleeve.ccys})
    ahead = expression.ahead(sleeve, book["carry"]["horizon_days"], book["carry"]["closure_min_pairs"])
    at = sleeve.sessions.get_loc(sleeve.component["z"].first_valid_index()) + sleeve.lag + 1
    return replace(like, sleeve=sleeve, state=state, allow=positions.pays(ahead), start=sleeve.sessions[at],
                   periods=metrics.per_year(sleeve.sessions[at:]))


@dataclass
class Run:
    """One sleeve (or the sum) under one spec: by session, what it earned, what it traded, which sessions count.

    `daily` columns: gross (P&L before costs), cost (at the configured costs),
    traded (book DV01, every leg), assumed (on the ``observed: false`` legs),
    observed_cost, traded by cause (`costs.CAUSES`), side (the rule's side held
    into the session), held (the first leg's DV01 held), gross_dv01 (every leg's
    |q| held), kept, elb_line. Book currency, bp x DV01. The P&L columns
    (`PNL`) are 0 where the treatment drops the held position's P&L, the cost
    columns (`COSTS`) where it drops the cost of the one put on
    (`positions.samples`).
    """
    name: str
    spec: Spec
    daily: pd.DataFrame
    start: pd.Timestamp
    periods: float


def simulate(inp, spec, book):
    """Run one sleeve under `spec`: decide, size, `expression.run`, charge. Returns a `Run`."""
    s = inp.sleeve
    allow = inp.allow if spec.carry_filter else None
    side = positions.decide(s.component["z"], spec.rule, spec.enter, spec.exit, inp.state, spec.treatment, allow)
    band = book["risk"]["no_trade_band"] if spec.band is None else spec.band
    q = positions.size(side, spec.sizing, inp.sigma, positions.target_sigma(book), band)
    legs, sessions = expression.run(s, q, inp.u)
    lc = inp.costs if spec.restrike_months is None else [
        replace(c, restrike_months=spec.restrike_months) if c.restrike_months else c for c in inp.costs]
    trades = costs.traded(s, legs, side, lc)
    per_leg = costs.by_leg(trades)
    rates = costs.configured(lc)
    observed = [c.leg for c in lc if c.observed]
    kept, pnl, paid, line = positions.samples(inp.state, spec.treatment, s.lag)
    held = sessions["position"].fillna(0.0)
    daily = pd.DataFrame({
        "gross": sessions["pnl"], "cost": costs.charge(trades, rates), "traded": per_leg.sum(axis=1),
        "assumed": per_leg.drop(columns=observed).sum(axis=1),
        "observed_cost": sum((per_leg[leg] * rates[leg] for leg in observed), pd.Series(0.0, index=s.sessions)),
        **{cause: trades[cause].sum(axis=1) for cause in costs.CAUSES},
        "side": side.shift(s.lag + 1).fillna(0.0), "held": held, "gross_dv01": held.abs() * len(s.legs),
        "kept": kept & (s.sessions >= inp.start), "elb_line": line & (s.sessions >= inp.start)}, index=s.sessions)
    daily[PNL] = daily[PNL].where(pnl, 0.0, axis=0)
    daily[COSTS] = daily[COSTS].where(paid, 0.0, axis=0)
    return Run(s.name, spec, daily, inp.start, inp.periods)


PNL = ["gross", "gross_dv01"]
COSTS = ["cost", "traded", "assumed", "observed_cost", *costs.CAUSES]
SUMMED = [*PNL, *COSTS]


def combine(runs, days, name=SUM):
    """The sum of `runs` on the book calendar `days`: each session's P&L and trades into the next book session.

    From the latest start among the runs; a book session is kept where any
    run keeps a session mapped into it, and sums only what the runs keep: a
    session a run's treatment leaves out adds nothing of that run's.
    """
    days = pd.DatetimeIndex(days)
    start = max(r.start for r in runs)
    parts = []
    for r in runs:
        d = r.daily.copy()
        d[SUMMED] = d[SUMMED].where(d["kept"], 0.0, axis=0)
        at = days.searchsorted(d.index)
        ok = at < len(days)
        parts.append(d.loc[ok, SUMMED + ["kept", "elb_line"]].set_axis(days[at[ok]]))
    both = pd.concat(parts)
    summed = both.groupby(level=0)[SUMMED].sum().reindex(days, fill_value=0.0)
    flags = both.groupby(level=0)[["kept", "elb_line"]].any().reindex(days, fill_value=False)
    daily = summed.join(flags)
    daily["kept"] &= days >= start
    daily["elb_line"] &= days >= start
    return Run(name, runs[0].spec, daily, start, metrics.per_year(days[days >= start]))


# ---- statistics --------------------------------------------------------------------

def spells(side):
    """Runs of one non-zero side, in session order: (first session, sessions held) each."""
    v = side.to_numpy(dtype=float)
    starts = np.flatnonzero(v != np.r_[0.0, v[:-1]])
    ends = np.r_[starts[1:], len(v)]
    keep = v[starts] != 0
    return pd.DataFrame({"first": side.index[starts[keep]], "sessions": (ends - starts)[keep]})


def _sharpe(x, periods):
    sr = metrics.sharpe(x, periods)
    return sr, metrics.sharpe_se(sr, len(x) / periods) if pd.notna(sr) else np.nan


def stats(run):
    """The numbers the report prints for one run (module docstring): Sharpe with SE, P&L, turnover, breakevens."""
    d = run.daily[run.daily["kept"]]
    n, per = len(d), run.periods
    years = n / per
    net = d["gross"] - d["cost"]
    gross_sr, gross_se = _sharpe(d["gross"], per)
    net_sr, net_se = _sharpe(net, per)
    active = d["gross_dv01"] > 0
    traded = d["traded"].sum()
    held = d.loc[active, "gross_dv01"].mean() if active.any() else np.nan
    half = n // 2
    first, second = (_sharpe(net.iloc[sl], per) for sl in (slice(0, half), slice(half, n)))
    out = {
        "sessions": n, "active": int(active.sum()), "years": years, "first": d.index.min(), "last": d.index.max(),
        "gross_sr": gross_sr, "gross_se": gross_se, "net_sr": net_sr, "net_se": net_se,
        "gross_year": d["gross"].sum() / years, "cost_year": d["cost"].sum() / years, "net_year": net.sum() / years,
        "traded_year": traded / years, **{f"{c}_year": d[c].sum() / years for c in costs.CAUSES},
        "maintenance_share": d[list(costs.MAINTENANCE)].sum().sum() / traded if traded > 0 else np.nan,
        "turns_year": traded / years / held if held > 0 else np.nan, "mean_gross_dv01": held,
        "cstar_bp": costs.breakeven(d["gross"].sum(), traded),
        "cstar_assumed_bp": costs.breakeven(d["gross"].sum() - d["observed_cost"].sum(), d["assumed"].sum()),
        "mix_bp": 2.0 * d["cost"].sum() / traded if traded > 0 else np.nan,
        "time_in_market": float(active.mean()) if n else np.nan,
        "halves": {"split": d.index[half] if n else pd.NaT, "first_sr": first[0], "first_se": first[1],
                   "second_sr": second[0], "second_se": second[1]},
    }
    if "side" in d:
        sp = spells(run.daily.loc[run.daily.index >= run.start, "side"])
        sp = sp[sp["first"].isin(d.index)]
        out |= {"entries_year": len(sp) / years, "holding_sessions": float(sp["sessions"].mean()) if len(sp) else np.nan}
    return out


def curve(run, cs, mode="uniform"):
    """Net Sharpe at each round trip in `cs` (bp): every leg at c (``uniform``), or only the assumed ones (``assumed``).

    Costs are linear in c, so from the kept sessions' gross P&L x and DV01
    traded t: mean = mean(x) - c/2 mean(t), var = var(x) - c cov(x, t) + c^2/4
    var(t); exactly `backtest.metrics.sharpe` of x - c/2 t.
    """
    d = run.daily[run.daily["kept"]]
    x, t = (d["gross"], d["traded"]) if mode == "uniform" else (d["gross"] - d["observed_cost"], d["assumed"])
    x, t = x.to_numpy(dtype=float), t.to_numpy(dtype=float)
    cs = np.asarray(cs, dtype=float)
    cov = np.cov(x, t)
    mean = x.mean() - cs / 2.0 * t.mean()
    var = cov[0, 0] - cs * cov[0, 1] + cs ** 2 / 4.0 * cov[1, 1]
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(var > 0, mean / np.sqrt(var) * np.sqrt(run.periods), np.nan)


def by_year(run, capital=None):
    """Net P&L by calendar year over the kept sessions: book currency, or percent of `capital` if given."""
    d = run.daily[run.daily["kept"]]
    net = (d["gross"] - d["cost"]).groupby(d.index.year).sum()
    return net / capital * 100.0 if capital else net


def cells(book):
    """The grid's cells with exit < enter, as (enter, exit), in grid order."""
    g = book["positions"]["grid"]
    return [(e, x) for e in g["enter"] for x in g["exit"] if x < e]


def neighbours(book, cell):
    """The up-to-8 cells adjacent to `cell` in grid-index space that have exit < enter."""
    g = book["positions"]["grid"]
    i, j = g["enter"].index(cell[0]), g["exit"].index(cell[1])
    out = []
    for a in (i - 1, i, i + 1):
        for b in (j - 1, j, j + 1):
            if (a, b) != (i, j) and 0 <= a < len(g["enter"]) and 0 <= b < len(g["exit"]) \
                    and g["exit"][b] < g["enter"][a]:
                out.append((g["enter"][a], g["exit"][b]))
    return out


def surface(grid, book, name):
    """What the grid says about one sleeve at the chosen cell: its neighbours', the grid's and the halves' Sharpes.

    `grid` is {cell: {name: stats}}. ``stable`` is True only if the range of
    net Sharpe over the chosen cell and its neighbours is under one SE at the
    chosen cell.
    """
    here = (book["positions"]["enter"], book["positions"]["exit"])
    at = grid[here][name]
    near = np.array([grid[c][name]["net_sr"] for c in [here, *neighbours(book, here)]])
    every = np.array([grid[c][name]["net_sr"] for c in grid])
    spread = float(np.nanmax(near) - np.nanmin(near))
    return {"cell": here, "net_sr": at["net_sr"], "net_se": at["net_se"], "gross_sr": at["gross_sr"],
            "neighbours": len(near) - 1,
            "near_min": float(np.nanmin(near[1:])), "near_median": float(np.nanmedian(near[1:])),
            "near_max": float(np.nanmax(near[1:])), "near_range": spread,
            "grid_min": float(np.nanmin(every)), "grid_median": float(np.nanmedian(every)),
            "grid_max": float(np.nanmax(every)), "share_positive": float(np.mean(every > 0)), "cells": len(every),
            "stable": bool(spread < at["net_se"]), "halves": at["halves"]}


# ---- the build ---------------------------------------------------------------------

@dataclass
class Build:
    """Everything the report says. Stats are `stats` dicts keyed by sleeve name (and `SUM`).

    `chosen` is {sizing: {name: Run}}; `rules` {sizing: {treatment: {rule:
    {name: stats}}}}; `grid` {sizing: {cell: {name: stats}}}; `restrike`
    {months: {sizing: {name: stats}}} for the sleeves with par legs; `band`
    {"off": {name: stats}} (vol-scaled, no band); `carry_filter` {name: stats}.
    """
    book: dict
    sleeves: dict
    inputs: dict
    chosen: dict
    rules: dict
    grid: dict
    restrike: dict
    band: dict
    carry_filter: dict
    elb: pd.DataFrame


def _book_days(world, book):
    home = book["book"]["currency"]
    return pd.DatetimeIndex(sorted(world.panel(home, "signal")["session"].unique()))


def run_all(inp, spec, book, days):
    """Every sleeve under `spec`, and their sum: {name: Run}."""
    runs = {name: simulate(i, spec, book) for name, i in inp.items()}
    return {**runs, SUM: combine(list(runs.values()), days)}


def elb_table(inp, runs, book):
    """Per sleeve, the ELB state: its entries and exits, the positions a flat treatment closes, and hold's split.

    `runs` is {treatment: {name: Run}} at the chosen rule and sizing.
    """
    rows = []
    for name, i in inp.items():
        st = i.state[i.state.index >= i.start].astype(int)
        moves = st.diff().fillna(0.0)
        flat, hold = runs["flat"][name].daily, runs["hold"][name].daily
        lag = i.sleeve.lag
        entries = st.index[moves > 0]
        at = [i.sleeve.sessions.get_loc(e) + lag for e in entries if i.sleeve.sessions.get_loc(e) + lag < len(flat)]
        closed = [k for k in at if flat["held"].iloc[k] != 0]
        live = hold[hold.index >= i.start]
        net = live["gross"] - live["cost"]
        rows.append({"sleeve": name, "elb_sessions": int(st.sum()), "entries": int((moves > 0).sum()),
                     "exits": int((moves < 0).sum()), "closed": len(closed),
                     "closing_cost": float(flat["cost"].iloc[closed].sum()) if closed else 0.0,
                     "hold_elb_net": float(net[live["elb_line"]].sum()),
                     "hold_other_net": float(net[~live["elb_line"]].sum())})
    return pd.DataFrame(rows)


def build(world=None):
    """Every run the report reads: the chosen spec both sizings, the rules x treatments, the grid, the sensitivities."""
    world = expression.World() if world is None else world
    book = world.book
    sleeves = expression.build(world)
    inp = {name: inputs(s, world, book) for name, s in sleeves.items()}
    days = _book_days(world, book)
    picked = {sz: run_all(inp, chosen(book, sz), book, days) for sz in positions.SIZING}
    rules, by_treatment = {}, {}
    for sz in positions.SIZING:
        rules[sz] = {}
        for tr in positions.TREATMENTS:
            rules[sz][tr] = {}
            for rule in positions.RULES:
                spec = chosen(book, sz, treatment=tr, rule=rule, carry_filter=False)
                runs = picked[sz] if spec == chosen(book, sz) else run_all(inp, spec, book, days)
                rules[sz][tr][rule] = {n: stats(r) for n, r in runs.items()}
                if rule == book["positions"]["rule"] and sz == "vol_scaled":
                    by_treatment[tr] = runs
    grid = {sz: {cell: {n: stats(r) for n, r in run_all(inp, chosen(book, sz, enter=cell[0], exit=cell[1]),
                                                           book, days).items()}
                 for cell in cells(book)} for sz in positions.SIZING}
    par = {n: i for n, i in inp.items() if any(c.restrike_months for c in i.costs)}
    months = sorted({1, *(c.restrike_months for i in par.values() for c in i.costs if c.restrike_months)})
    restrike = {m: {sz: {n: stats(simulate(i, chosen(book, sz, restrike_months=m), book)) for n, i in par.items()}
                    for sz in positions.SIZING} for m in months}
    band = {"off": {n: stats(r) for n, r in run_all(inp, chosen(book, band=0.0), book, days).items()}}
    carry_on = {n: stats(r) for n, r in run_all(inp, chosen(book, carry_filter=True), book, days).items()}
    check([*picked.values(), *by_treatment.values()], inp, days)
    return Build(book, sleeves, inp, picked, rules, grid, restrike, band, carry_on,
                 elb_table(inp, by_treatment, book))


def check(sets, inp, days, tol=1e-9):
    """Raise if a build's own invariants fail, on each {name: Run} in `sets` (each sleeve and its sum).

    Every trade has one cause; a treatment leaves nothing in the sessions it
    drops; the sum is its runs' kept P&L; each breakeven is the zero of its
    curve; and a sleeve whose legs share one cost nets, at the configured
    costs, what its uniform curve says at that cost.
    """
    for runs in sets:
        parts = [r for n, r in runs.items() if n != SUM]
        for r in runs.values():
            d, st, where = r.daily, stats(r), f"{r.name} ({r.spec.words() if r.spec else ''})"
            if not np.allclose(d[list(costs.CAUSES)].sum(axis=1), d["traded"], atol=tol):
                raise RuntimeError(f"{where}: DV01 traded by cause does not add up to DV01 traded")
            dropped = d.loc[~d["kept"] & (d.index >= r.start), SUMMED].abs().to_numpy().sum()
            if r.spec.treatment != "hold" and dropped > tol:
                raise RuntimeError(f"{where}: {dropped:g} of P&L or cost on sessions the treatment leaves out")
            for key, mode in (("cstar_bp", "uniform"), ("cstar_assumed_bp", "assumed")):
                x = st[key]
                if x is not None and np.isfinite(x) and abs(curve(r, [x], mode)[0]) > 1e-6:
                    raise RuntimeError(f"{where}: the net Sharpe at c* ({key}) is not 0")
            if r.name in inp and len({round(c.round_trip_bp, 12) for c in inp[r.name].costs}) == 1 \
                    and st["traded_year"] > 0 and abs(curve(r, [st["mix_bp"]])[0] - st["net_sr"]) > 1e-6:
                raise RuntimeError(f"{where}: the configured net is off its uniform curve at its one cost")
        kept = sum(float(r.daily.loc[r.daily["kept"] & (r.daily.index <= days[-1]), "gross"].sum()) for r in parts)
        total = float(runs[SUM].daily["gross"].sum())
        if abs(total - kept) > tol * max(1.0, abs(kept)):
            raise RuntimeError(f"the sum's gross {total:g} is not its runs' kept gross {kept:g}")


# ---- the words ---------------------------------------------------------------------

def sr(x, se=None):
    """"+0.42 (0.31)": a Sharpe and, if given, its SE."""
    if pd.isna(x):
        return "n/a"
    return f"{x:+.2f}" + ("" if se is None or pd.isna(se) else f" ({se:.2f})")


def cstar(x):
    """A breakeven cost in words."""
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "none (gross <= 0)"
    return "any (never trades)" if np.isinf(x) else f"{x:.2f}bp"


def pct(x):
    return "n/a" if pd.isna(x) else f"{x:.0%}"


def leg_words(b):
    """Every leg's cost, one row each: sleeve, leg, instrument, round trip, one way, observed, re-strike, basis."""
    rows = []
    for name, i in b.inputs.items():
        for c, (_, _, leg) in zip(i.costs, i.sleeve.legs):
            cfg = config.currency(leg.ccy)
            spec = cfg["costs"][c.expression]
            if "ticks_round_trip" in spec:
                ct = cfg["contracts"][cfg["expression"][c.expression]["contract"]]
                basis = (f"{spec['ticks_round_trip']:g} ticks of {ct['tick']['other']:g} + {ct['fee_per_side']:g} "
                         f"{leg.ccy} a side a contract")
            else:
                basis = f"{spec['round_trip_bp']:g}bp a round trip"
            rows.append({"sleeve": name, "leg": c.leg, "instrument": _label(i.sleeve, leg),
                         "round trip (bp)": f"{c.round_trip_bp:.3f}", "one way (bp)": f"{c.one_way_bp:.3f}",
                         "from": basis, "cost is": "tick-based (a listed contract)" if c.observed else "assumed",
                         "re-struck": f"every {c.restrike_months} months" if c.restrike_months else "no"})
    return pd.DataFrame(rows)


def futures_lines(b):
    """The tick-based cost of each futures leg, derived from its contract spec, in words."""
    out, seen = [], set()
    for i in b.inputs.values():
        for c, (_, _, leg) in zip(i.costs, i.sleeve.legs):
            if leg.contract is None or c.expression in seen:
                continue
            seen.add(c.expression)
            cfg = config.currency(leg.ccy)
            spec, ct = cfg["costs"][c.expression], leg.contract
            dv01 = instruments.contract_dv01(ct)
            spread = spec["ticks_round_trip"] * ct["tick"]["other"] / costs.BP_PRICE
            fee = 2.0 * ct["fee_per_side"] / dv01
            label = _label(i.sleeve, leg)
            out.append(
                f"{label}, from the contract spec in config: {spec['ticks_round_trip']:g} back-month ticks of "
                f"{ct['tick']['other']:g} (the fourth meeting's month is never the front one) = {spread:.3f}bp, plus "
                f"{ct['fee_per_side']:g} {leg.ccy} a side over {dv01:.4f} {leg.ccy} per bp a contract = {fee:.3f}bp: "
                f"{c.round_trip_bp:.3f}bp a round trip, {c.one_way_bp:.3f}bp one way per unit of DV01. "
                f"{spec['ticks_round_trip']:g} ticks a round trip is {spec['ticks_round_trip'] / 2:g} a side, the "
                f"cost of crossing a market {spec['ticks_round_trip']:g} ticks wide; the floor, crossing a one-tick "
                "market, is one tick a round trip. The tick is "
                f"{ct['exchange']}'s minimum price increment, not a measured bid-offer: the archive holds settles, not "
                "quotes, so there is no spread to measure, and a quote-based estimate would be a data purchase. The fee "
                "is assumed.")
    return out


def _range(per, key, fmt=sr):
    """', from x (a) to y (b)' over {name: stats}; empty with fewer than two known."""
    vals = {n: v[key] for n, v in per.items() if pd.notna(v[key])}
    if len(vals) < 2:
        return ""
    lo, hi = min(vals, key=vals.get), max(vals, key=vals.get)
    return f", from {fmt(vals[lo])} ({lo}) to {fmt(vals[hi])} ({hi})"


def _take(gross, net):
    """What costs did to a Sharpe, in words, from the numbers: halved, took a share, or deepened a loss."""
    if not gross > 0:
        return "the gross Sharpe is already at or below zero, and costs only deepen it"
    share = (gross - net) / gross
    if net <= 0:
        return f"costs take all of it and more ({share:.0%} of the gross Sharpe)"
    return "costs roughly halve it" if 0.4 <= share <= 0.6 else f"costs take {share:.0%} of it"


def _verdict(net, se):
    """The first bullet's head: the sign of a net Sharpe and whether it is two SEs from zero."""
    if not net > 0:
        return "loses money"
    return "earns, but within two SEs of zero" if net < 2 * se else "still earns"


def _row_means(grid, book, name):
    """Mean net Sharpe over each entry threshold's cells: {enter: mean}."""
    out = {}
    for (e, _), per in grid.items():
        out.setdefault(e, []).append(per[name]["net_sr"])
    return {e: float(np.nanmean(v)) for e, v in out.items()}


def _clear(vs, names):
    """The sleeves' breakevens against their configured costs, in words (vol-scaled)."""
    clear = [n for n in names if vs[n]["cstar_bp"] is not None and vs[n]["cstar_bp"] > vs[n]["mix_bp"]]
    short = [n for n in names if vs[n]["cstar_bp"] is not None and vs[n]["cstar_bp"] <= vs[n]["mix_bp"]]
    none = [n for n in names if vs[n]["cstar_bp"] is None]
    parts = [f"{n}: c* {cstar(vs[n]['cstar_bp'])}, {vs[n]['cstar_bp'] / vs[n]['mix_bp']:.1f} times its "
             f"configured {vs[n]['mix_bp']:.2f}bp" for n in clear]
    parts += [f"{n}: c* {cstar(vs[n]['cstar_bp'])}, below its configured {vs[n]['mix_bp']:.2f}bp" for n in short]
    if none:
        parts.append(f"{_and(none)}: no breakeven, {'its' if len(none) == 1 else 'their'} gross P&L at or below "
                     "zero before any cost")
    return clear, "; ".join(parts)


def answer(b):
    """The report's opening bullets, each worded by what the numbers say."""
    book = b.book
    cap = book["book"]["capital"]
    spec = chosen(book)
    names = list(b.sleeves)
    vs = {n: stats(r) for n, r in b.chosen["vol_scaled"].items()}
    un = {n: stats(r) for n, r in b.chosen["unit"].items()}
    s, su = vs[SUM], un[SUM]
    lines = [
        f"- **Net of costs, the sum of the sleeves {_verdict(s['net_sr'], s['net_se'])}.** The equal-risk sum "
        f"({spec.words()}) has a gross Sharpe of {sr(s['gross_sr'], s['gross_se'])} and a net one of "
        f"{sr(s['net_sr'], s['net_se'])} at the configured costs (SE in brackets; {s['active']:,} of the "
        f"{s['sessions']:,} sessions counted have a position): {_take(s['gross_sr'], s['net_sr'])}. The configured "
        f"costs are a mix, {s['mix_bp']:.2f}bp a round trip per leg traded on average. Unit-sized (the equal-DV01 "
        f"sum), {sr(su['gross_sr'], su['gross_se'])} gross and {sr(su['net_sr'], su['net_se'])} net: "
        f"{_take(su['gross_sr'], su['net_sr'])}. The sum's own breakeven is {cstar(s['cstar_bp'])} vol-scaled and "
        f"{cstar(su['cstar_bp'])} unit-sized.",
    ]
    clear, words = _clear(vs, names)
    verb = "clears its" if len(clear) == 1 else "clear their"
    held_up = []
    for n in clear:
        years = by_year(b.chosen["vol_scaled"][n], cap)
        top2 = years.nlargest(2)
        two = "within two SEs of" if vs[n]["net_sr"] < 2 * vs[n]["net_se"] else "more than two SEs from"
        held_up.append(f"{n} nets {sr(vs[n]['net_sr'], vs[n]['net_se'])}, {two} zero; "
                       f"{years.max() / years.sum():.0%} of its net P&L is {years.idxmax()}, and its best two years, "
                       f"{_and(str(y) for y in sorted(top2.index))}, make {top2.sum() / years.sum():.0%} of it: its "
                       f"other {len(years) - 2} years net {years.drop(top2.index).sum():+.2f}% of capital")
    lines.append(f"- **{len(clear)} of the {len(names)} sleeves {verb} costs** (vol-scaled breakeven c* = "
                 f"2 x gross P&L / DV01 traded, against each sleeve's configured round trip). {words}."
                 + (f" {'; '.join(held_up)}." if held_up else ""))
    vy, uy = by_year(b.chosen["vol_scaled"][SUM], cap), by_year(b.chosen["unit"][SUM])
    if len(uy) and uy.sum() > 0:
        top2 = uy.nlargest(2)
        lines.append(
            f"- **The sizing {'decides the sign' if np.sign(s['net_sr']) != np.sign(su['net_sr']) else 'moves the size'}"
            f".** Unit-sized, a sleeve's P&L is largest where its vol is: {_and(str(y) for y in sorted(top2.index))} "
            f"net {top2.sum():+,.0f}bp, against {uy.sum():+,.0f}bp for the unit sum's {len(uy)} years, so its other "
            f"{len(uy) - 2} years net {uy.drop(top2.index).sum():+,.0f}bp. Vol-scaled, every year carries the same "
            "risk: those two years make "
            f"{vy.reindex(top2.index).sum():+.2f}% of capital and the other years {vy.drop(top2.index).sum():+.2f}%. "
            "The unit result is those years'.")
    maint = {n: {"m": un[n]["maintenance_share"]} for n in names}
    most = su["maintenance_share"] > 0.5
    lines.append(
        f"- **{'Maintenance, not the signal, is most of what is traded' if most else 'Maintenance is a large part of what is traded'}"
        f".** Unit-sized, {pct(su['maintenance_share'])} of the DV01 the sleeves trade is maintenance: moving to the "
        "new fourth meeting's instrument each time a meeting passes, and re-striking the par legs every quarter"
        f"{_range(maint, 'm', pct)}. Maintenance is charged at each roll and each re-strike while a position is held, "
        "so a hysteresis pair saves it only by holding less.")
    listed = list(dict.fromkeys(f"{n}'s {_label(i.sleeve, leg)} leg" for n, i in b.inputs.items()
                                for c, (_, _, leg) in zip(i.costs, i.sleeve.legs) if c.observed))
    n_legs = sum(len(i.costs) for i in b.inputs.values())
    n_obs = sum(c.observed for i in b.inputs.values() for c in i.costs)
    free = float(curve(b.chosen["vol_scaled"][SUM], [0.0], "assumed")[0])
    assumed_clear = [n for n in clear if not any(c.observed for c in b.inputs[n].costs)]
    lines.append(
        f"- **{n_obs} of the {n_legs} legs {'has a' if n_obs == 1 else 'have'} tick-based cost, and the rest are "
        f"assumed.** {_and(listed)} trade{'s' if n_obs == 1 else ''} a listed contract, costed at its tick (not a "
        "measured spread: the archive has no quotes); the others are valued off fitted curves or Treasury CMT, so "
        f"their cost is an assumption. The assumed legs carry {1 - _observed_share(b.chosen['vol_scaled']):.0%} of "
        f"the DV01 traded. Holding the tick-based legs at their tick and making every assumed leg free, the sum nets "
        f"{sr(free)}; varying only the assumed legs, its breakeven is {cstar(s['cstar_assumed_bp'])}."
        + (f" The sleeve{'s' if len(assumed_clear) > 1 else ''} that clear{'' if len(assumed_clear) > 1 else 's'} "
           f"{'their' if len(assumed_clear) > 1 else 'its'} costs ({_and(assumed_clear)}) "
           f"{'have' if len(assumed_clear) > 1 else 'has'} only assumed costs, so the result that survives rests on "
           "an assumed cost, not a listed tick." if assumed_clear else ""))
    g = surface(b.grid["vol_scaled"], book, SUM)
    rows = _row_means(b.grid["vol_scaled"], book, SUM)
    lo, hi = min(rows), max(rows)
    halves = g["halves"]
    lines.append(
        f"- **The hysteresis grid is {'stable' if g['stable'] else 'not stable'} by the report's test, and it tilts.** "
        f"At the chosen {g['cell']} the sum nets {sr(g['net_sr'], g['net_se'])}; over it and its {g['neighbours']} "
        f"neighbours the range is {g['near_range']:.2f}, {'under' if g['stable'] else 'not under'} one SE. Over all "
        f"{g['cells']} cells it runs from {sr(g['grid_min'])} to {sr(g['grid_max'])} (median {sr(g['grid_median'])}), "
        f"{pct(g['share_positive'])} of cells above zero; averaged over exits it goes from {sr(rows[lo])} at enter "
        f"{lo:g} to {sr(rows[hi])} at {hi:g}. The pair stays where config fixed it. Every cell trades one signal, so "
        "a smooth surface is expected with or without an edge: stability is necessary, not evidence.")
    lines.append(
        f"- **The two halves disagree.** At the chosen cell the sum's first half (to {halves['split']:%b %Y}) nets "
        f"{sr(halves['first_sr'], halves['first_se'])} and its second {sr(halves['second_sr'], halves['second_se'])}."
        if abs(halves["first_sr"] - halves["second_sr"]) > max(halves["first_se"], halves["second_se"]) else
        f"- **The two halves agree within an SE.** At the chosen cell the sum's first half (to "
        f"{halves['split']:%b %Y}) nets {sr(halves['first_sr'], halves['first_se'])} and its second "
        f"{sr(halves['second_sr'], halves['second_se'])}.")
    tr = {t: b.rules["vol_scaled"][t][spec.rule][SUM] for t in positions.TREATMENTS}
    nets = [tr[t]["net_sr"] for t in positions.TREATMENTS]
    moves = max(nets) - min(nets) >= s["net_se"]
    spread = {n: [b.rules["vol_scaled"][t][spec.rule][n]["net_sr"] for t in positions.TREATMENTS] for n in names}
    most = max(spread, key=lambda n: max(spread[n]) - min(spread[n]))
    one = {t: b.rules["vol_scaled"][t][spec.rule][most] for t in positions.TREATMENTS}
    lines.append(
        f"- **The ELB treatment {'moves the answer' if moves else 'moves the sum by less than an SE'}.** The sum nets "
        + _and(f"{sr(tr[t]['net_sr'], tr[t]['net_se'])} {TREATMENT_WORDS[t]}" for t in positions.TREATMENTS)
        + f" ({spec.rule}, vol-scaled). It matters most for {most}: "
        + _and(f"{sr(one[t]['net_sr'], one[t]['net_se'])} {TREATMENT_WORDS[t]}" for t in positions.TREATMENTS)
        + ". The state is the model's: it moves with r*.")
    if len(vy) and vy.sum() > 0:
        top = vy.idxmax()
        lines.append(
            f"- **The result is concentrated.** The sum's best year, {top}, made {vy.max():+.2f}% of capital net, "
            f"{vy.max() / vy.sum():.0%} of its whole net P&L ({vy.sum():+.2f}% over {len(vy)} years); the other years "
            f"net {vy.drop(top).sum():+.2f}%.")
    elif len(vy):
        good = vy[vy > 0]
        lines.append(
            f"- **Net, the sum made money in {len(good)} of {len(vy)} years.** Over the {len(vy)} years it nets "
            f"{vy.sum():+.2f}% of capital (five sleeves each at the book's risk); its best year, {vy.idxmax()}, made "
            f"{vy.max():+.2f}%.")
    flags = []
    if not s["net_sr"] > 0:
        flags.append("the sum of the sleeves loses money net of costs")
    if np.sign(s["net_sr"]) != np.sign(su["net_sr"]):
        flags.append(f"its sign turns on the sizing ({sr(s['net_sr'])} vol-scaled, {sr(su['net_sr'])} unit)")
    if len(uy) > 2 and uy.sum() > 0 and uy.drop(uy.nlargest(2).index).sum() <= 0:
        flags.append(f"the unit-sized gain is {_and(str(y) for y in sorted(uy.nlargest(2).index))}'s")
    if abs(halves["first_sr"] - halves["second_sr"]) > max(halves["first_se"], halves["second_se"]):
        flags.append(f"the halves disagree ({sr(halves['first_sr'])} to {halves['split']:%b %Y}, "
                     f"{sr(halves['second_sr'])} after)")
    if clear and len(assumed_clear) == len(clear):
        flags.append(f"{'the one sleeve that clears its' if len(clear) == 1 else 'the sleeves that clear their'} "
                     f"costs ({_and(clear)}) {'does' if len(clear) == 1 else 'do'} so on an assumed cost")
    elif not clear:
        flags.append("no sleeve clears its costs")
    head = (f"**In one line: fragile.** {_and(flags)[:1].upper()}{_and(flags)[1:]}." if flags else
            "**In one line: not fragile by these tests.**")
    return [head, "", *lines]


def _observed_share(runs):
    """Share of the sleeves' DV01 traded (the runs' kept sessions, the sum left out) that is on observed legs."""
    total = sum(r.daily.loc[r.daily["kept"], "traded"].sum() for n, r in runs.items() if n != SUM)
    assumed = sum(r.daily.loc[r.daily["kept"], "assumed"].sum() for n, r in runs.items() if n != SUM)
    return 1.0 - assumed / total if total > 0 else np.nan


def _curve_table(b, sizing, mode="uniform"):
    grid = b.book["costs"]["sensitivity_bp"]
    rows = []
    for name, run in b.chosen[sizing].items():
        st = stats(run)
        vals = curve(run, grid, mode)
        key = "cstar_bp" if mode == "uniform" else "cstar_assumed_bp"
        rows.append({"sleeve": name, **{f"{c:g}bp": sr(v) for c, v in zip(grid, vals)},
                     "configured": sr(st["net_sr"], st["net_se"]), "c*": cstar(st[key])})
    return pd.DataFrame(rows)


def _turnover_table(b):
    rows = []
    for name, run in b.chosen["unit"].items():
        if name == SUM:
            continue
        st = stats(run)
        rows.append({"sleeve": name, "signal": f"{st['signal_year']:.1f}",
                     "maintenance": f"{st['roll_year'] + st['restrike_year']:.1f}",
                     "rolls": f"{st['roll_year']:.1f}", "re-strikes": f"{st['restrike_year']:.1f}",
                     "total": f"{st['traded_year']:.1f}", "maintenance share": pct(st["maintenance_share"]),
                     "entries a year": f"{st['entries_year']:.1f}",
                     "held (sessions)": f"{st['holding_sessions']:.0f}", "in market": pct(st["time_in_market"]),
                     "gross a year": f"{st['gross_year']:+.1f}bp", "cost a year": f"{st['cost_year']:.1f}bp",
                     "c*": cstar(st["cstar_bp"])})
    return pd.DataFrame(rows)


def _band_table(b):
    rows = []
    for name, run in b.chosen["vol_scaled"].items():
        on, off = stats(run), b.band["off"][name]
        share = {k: (v["rescale_year"] / v["traded_year"] if v["traded_year"] > 0 else np.nan) for k, v in
                 (("on", on), ("off", off))}
        rows.append({"sleeve": name, "band: turns a year": f"{on['turns_year']:.1f}",
                     "band: rescaling share": pct(share["on"]), "band: net": sr(on["net_sr"], on["net_se"]),
                     "no band: turns a year": f"{off['turns_year']:.1f}", "no band: rescaling share": pct(share["off"]),
                     "no band: net": sr(off["net_sr"], off["net_se"])})
    return pd.DataFrame(rows)


def _restrike_table(b):
    rows = []
    order = list(b.sleeves)
    for m, by in b.restrike.items():
        for name in by["vol_scaled"]:
            v, u = by["vol_scaled"][name], by["unit"][name]
            rows.append({"sleeve": name, "re-struck every": f"{m} month{'s' if m > 1 else ''}",
                         "re-strikes a year (unit DV01)": f"{u['restrike_year']:.1f}",
                         "cost a year (unit)": f"{u['cost_year']:.1f}bp",
                         "net Sharpe, vol-scaled": sr(v["net_sr"], v["net_se"]),
                         "net Sharpe, unit": sr(u["net_sr"], u["net_se"]), "c*, vol-scaled": cstar(v["cstar_bp"])})
    out = pd.DataFrame(rows)
    return out.iloc[np.lexsort((out["re-struck every"].map(lambda x: int(x.split()[0])),
                                out["sleeve"].map(order.index)))]


def _surface_table(b, sizing):
    rows = []
    for name in [SUM, *b.sleeves]:
        g = surface(b.grid[sizing], b.book, name)
        h = g["halves"]
        rows.append({"sleeve": name, "chosen": sr(g["net_sr"], g["net_se"]),
                     "neighbours min / median / max": f"{sr(g['near_min'])} / {sr(g['near_median'])} / "
                                                      f"{sr(g['near_max'])}",
                     "range incl. chosen": f"{g['near_range']:.2f}",
                     "grid min / median / max": f"{sr(g['grid_min'])} / {sr(g['grid_median'])} / {sr(g['grid_max'])}",
                     "cells > 0": pct(g["share_positive"]),
                     "halves split": f"{h['split']:%Y-%m-%d}" if pd.notna(h["split"]) else "n/a",
                     "first half": sr(h["first_sr"], h["first_se"]),
                     "second half": sr(h["second_sr"], h["second_se"]), "stable?": "yes" if g["stable"] else "no"})
    return pd.DataFrame(rows)


def _grid_tables(b, sizing):
    """One table per sleeve (and the sum): enter down, exit across, each cell "net / gross, turns"."""
    g = b.book["positions"]["grid"]
    here = (b.book["positions"]["enter"], b.book["positions"]["exit"])
    out = []
    for name in [SUM, *b.sleeves]:
        rows = []
        for e in g["enter"]:
            row = {"enter \\ exit": f"{e:g}"}
            for x in g["exit"]:
                st = b.grid[sizing].get((e, x), {}).get(name)
                cell = "" if st is None else f"{sr(st['net_sr'])} / {sr(st['gross_sr'])}, {st['turns_year']:.0f}"
                row[f"{x:g}"] = f"**{cell}**" if (e, x) == here else cell
            rows.append(row)
        out.append((name, pd.DataFrame(rows)))
    return out


def _rules_table(b, sizing):
    rows = []
    for name in [*b.sleeves, SUM]:
        for rule in positions.RULES:
            row = {"sleeve": name, "rule": rule}
            for t in positions.TREATMENTS:
                st = b.rules[sizing][t][rule][name]
                row[f"{t}: gross"] = sr(st["gross_sr"], st["gross_se"])
                row[f"{t}: net"] = sr(st["net_sr"], st["net_se"])
                row[f"{t}: active, from"] = (f"{st['active']:,} of {st['sessions']:,}, "
                                             f"{st['first']:%Y-%m}" if st["sessions"] else "none")
            rows.append(row)
    return pd.DataFrame(rows)


def _elb_rows(b):
    e = b.elb
    cap = b.book["book"]["capital"]
    return e.assign(closing_cost=(e["closing_cost"] / cap * 100).map(lambda x: f"{x:.3f}%"),
                    hold_elb_net=(e["hold_elb_net"] / cap * 100).map(lambda x: f"{x:+.2f}%"),
                    hold_other_net=(e["hold_other_net"] / cap * 100).map(lambda x: f"{x:+.2f}%")).rename(columns={
        "elb_sessions": "ELB sessions", "entries": "entries", "exits": "exits",
        "closed": "positions closed at entry (flat)", "closing_cost": "their cost",
        "hold_elb_net": "hold: net P&L of ELB-decided positions", "hold_other_net": "hold: the rest"})


def _year_table(b):
    cap = b.book["book"]["capital"]
    wide = pd.DataFrame({n: by_year(r, cap) for n, r in b.chosen["vol_scaled"].items()})
    wide = wide[[*b.sleeves, SUM]].sort_index()
    body = wide.map(lambda x: "" if pd.isna(x) else f"{x:+.2f}%").reset_index(names="year")
    total = {"year": "all", **{n: f"{wide[n].sum():+.2f}%" for n in wide}}
    best = {"year": "best year's share", **{n: (f"{wide[n].max() / wide[n].sum():.0%} ({int(wide[n].idxmax())})"
                                                 if wide[n].sum() > 0 else "n/a (net <= 0)") for n in wide}}
    two = {"year": "best two years' share", **{n: _two_years(wide[n].dropna()) for n in wide}}
    return pd.concat([body.assign(year=body["year"].astype(str)), pd.DataFrame([total, best, two])],
                     ignore_index=True)


def _two_years(years):
    """'101% (2022, 2023)': the best two years' share of a sleeve's net P&L; n/a where the net is at or below 0."""
    if not years.sum() > 0 or len(years) < 2:
        return "n/a (net <= 0)" if not years.sum() > 0 else "n/a"
    top = years.nlargest(2)
    return f"{top.sum() / years.sum():.0%} ({', '.join(str(int(y)) for y in sorted(top.index))})"


def _realized(run, capital):
    """Realized vol of a run's net P&L over its kept sessions, percent of `capital` a year."""
    d = run.daily[run.daily["kept"]]
    return float((d["gross"] - d["cost"]).std() * np.sqrt(run.periods) / capital * 100.0)


def _filter_table(b):
    rows = []
    for name, run in b.chosen["vol_scaled"].items():
        off, on = stats(run), b.carry_filter[name]
        rows.append({"sleeve": name, "off: net": sr(off["net_sr"], off["net_se"]),
                     "off: entries a year": f"{off.get('entries_year', np.nan):.1f}",
                     "on: net": sr(on["net_sr"], on["net_se"]),
                     "on: entries a year": f"{on.get('entries_year', np.nan):.1f}",
                     "difference": f"{on['net_sr'] - off['net_sr']:+.2f}"})
    return pd.DataFrame(rows).replace("nan", "n/a")


def markdown(b):
    """reports/costs.md."""
    book = b.book
    spec = chosen(book)
    cap, target = book["book"]["capital"], book["book"]["vol_target"]
    r = book["risk"]
    home = book["book"]["currency"]
    first = min(i.start for i in b.inputs.values())
    last = max(i.sleeve.sessions[-1] for i in b.inputs.values())
    h = book["positions"]
    lines = [
        "# Costs, turnover and hysteresis: what the signal is worth net, and how fragile that is",
        "",
        f"Generated by `scripts/build_strategy.py` from `data/panel/` and the cache, sessions {first:%Y-%m-%d} .. "
        f"{last:%Y-%m-%d}. Do not edit by hand. The rules are in `strategy/positions.py`, the costs in "
        "`strategy/costs.py`, sigma in `strategy/risk.py`, Sharpe and its SE in `backtest/metrics.py`; every choice "
        "is a row in notes/DECISIONS.md, section K (costs).",
        "",
        "## The answer",
        "",
        *answer(b),
        "",
        "![Cost sensitivity](figures/cost_sensitivity_light.png)",
        "",
        "## How it is run",
        "",
        f"Unless a number says otherwise it is the book's own spec: **{spec.words()}**. Hysteresis enters at "
        f"|z| >= {h['enter']:g} and leaves where z x side <= {h['exit']:g}, the pair fixed in config before the grid "
        f"below was run. Flat at the ELB: no position while the policy rate and the rule are both on the floor (the "
        "model has no view), the close and the re-open charged, those flat sessions left out. Vol-scaled: each "
        f"sleeve alone at the book's risk, {target:.0%} of {home} {cap / 1e6:,.0f}m a year, sigma the EWMA "
        f"(lambda {r['ewma_lambda']:g}) sd of its unit P&L strictly before the session, floored at "
        f"{r['sigma_floor']:g} x its trailing two-year median, re-scaled only outside a {r['no_trade_band']:.0%} band; "
        f"P&L in % of capital. Unit: one {home} of DV01 a unit, P&L in bp. Sharpe is mean over sd of daily net P&L, "
        "flat days in, annualised by the calendar's observed sessions a year; the SE in brackets is "
        "sqrt((1 + SR^2/2)/years), the least the uncertainty can be. Active: sessions with a position. Each run is "
        "evaluated over its own counted sessions, which the treatment and the sleeve's start set: the rules tables "
        "give each run's first counted month, and the grid's halves split each run's counted sessions at the date "
        "given.",
        "",
        "## What each leg costs",
        "",
        "One way is half the round trip, per unit of book DV01 traded. A cost is charged on the change in DV01 "
        "in the same instrument, on the whole position out and in when the instrument changes (a futures month, a "
        "forward's window), and on a par leg's re-strike every few months while it is held (the P&L marks a "
        "constant-maturity bond, which a desk replaces by rolling a bond it holds). Rolls are charged as two "
        "outright one-ways, not a calendar spread: the conservative end.",
        "",
        table(leg_words(b)),
        "",
        *[x + "\n" for x in futures_lines(b)],
        "## The cost sensitivity",
        "",
        f"Net Sharpe with every leg at a uniform round trip c (for a future, the fee inside c, not added), "
        f"{spec.words(sizing=False)}. The configured column charges each leg its own cost; c* is where "
        "the net Sharpe crosses 0, in closed form.",
        "",
        "### Vol-scaled (primary)",
        "",
        table(_curve_table(b, "vol_scaled")),
        "",
        "### Unit (secondary)",
        "",
        table(_curve_table(b, "unit")),
        "",
        "### Only the assumed legs varied, the tick-based at their tick cost (vol-scaled)",
        "",
        "A sleeve with no tick-based leg has the curve above; one with only tick-based legs is flat here.",
        "",
        table(_curve_table(b, "vol_scaled", "assumed")),
        "",
        "## Turnover",
        "",
        f"Unit-sized, {spec.words(sizing=False)}: DV01 traded a year, every leg summed (a unit "
        "round trip on one leg is 2). Signal: trades where the rule's side changed. Maintenance: rolls (the "
        "instrument changed under a held position) and par re-strikes, the part beyond a same-instrument trade. "
        "Entries: new sides a year; held: the mean sessions a side is held; in market: the share of counted "
        "sessions with a position.",
        "",
        table(_turnover_table(b)),
        "",
        "### The no-trade band (vol-scaled)",
        "",
        f"Turns: DV01 traded a year over the mean gross DV01 held (a whole round trip is 2). Rescaling: trades where "
        f"only the vol multiplier moved. With the {r['no_trade_band']:.0%} band, and without it.",
        "",
        table(_band_table(b)),
        "",
        "### Par legs re-struck monthly against quarterly (a stated sensitivity)",
        "",
        table(_restrike_table(b)),
        "",
        "## The hysteresis grid",
        "",
        f"The pair ({h['enter']:g}, {h['exit']:g}) was fixed in `config/strategy.yml` before this grid was first run "
        "and is not chosen from it. Each cell is the same signal under another pair, vol-scaled, "
        f"{TREATMENT_WORDS[spec.treatment]}; cells with exit >= enter are not rules. Neighbours are the up-to-8 "
        "adjacent cells. 'Stable' means the range of net Sharpe over the chosen cell and its neighbours is under one "
        "SE at the chosen cell, and nothing weaker earns the word. A smooth surface is expected either way: every "
        "cell trades one signal.",
        "",
        table(_surface_table(b, "vol_scaled")),
        "",
        "![Hysteresis grid](figures/hysteresis_grid_light.png)",
        "",
        "Each cell: net / gross Sharpe, turns a year (vol-scaled). The chosen cell in bold.",
        "",
    ]
    for name, t in _grid_tables(b, "vol_scaled"):
        lines += [f"### {name}", "", table(t), ""]
    unit = surface(b.grid["unit"], book, SUM)
    lines += [f"Unit-sized, the sum's chosen cell is {sr(unit['net_sr'], unit['net_se'])} net, the grid from "
              f"{sr(unit['grid_min'])} to {sr(unit['grid_max'])}, {pct(unit['share_positive'])} of cells above zero, "
              f"{'stable' if unit['stable'] else 'not stable'} by the same test (`reports/results/costs.json`).", ""]
    lines += [
        "## Rules and ELB treatments, before and after costs",
        "",
        "Gross and net Sharpe (SE), at the configured costs, and the sessions with a position of those counted, from "
        "the first counted month. Flat: no position in the ELB state, its flat sessions left out. Exclude: the hold "
        "run with the positions decided in the state left out, their P&L and the cost of putting them on. "
        "Hold: positions through the state, every session counted. Linear is s = z (the crude backtest's sizing).",
        "",
        "### Vol-scaled",
        "",
        table(_rules_table(b, "vol_scaled")),
        "",
        "### Unit",
        "",
        table(_rules_table(b, "unit")),
        "",
        f"### The ELB state, per sleeve ({spec.rule}, vol-scaled)",
        "",
        "The state is the model's (the policy rate and the rule both on the floor), so it moves with r*. A cross "
        "sleeve is in it when either currency is. It has no minimum duration: each entry is a close under flat, "
        "each exit a chance to re-open.",
        "",
        table(_elb_rows(b)),
        "",
        f"## By year: net P&L, {spec.words()}, % of capital",
        "",
        f"Each sleeve alone at the book's risk, so a year is comparable across sleeves; the sum is their total, and "
        f"runs at {_realized(b.chosen['vol_scaled'][SUM], cap):.1f}% a year realized (five sleeves at "
        f"{target:.0%} each, less what their correlations diversify). A blank is a year with no session counted"
        + ("" if spec.treatment == "hold" else
           f" ({TREATMENT_WORDS[spec.treatment]}, a sleeve in the ELB state all year counts none)") + ".",
        "",
        table(_year_table(b)),
        "",
        "## The carry filter (a diagnostic)",
        "",
        f"Skip an entry whose expected quarter does not pay for its bleed (`positions.carry_filter`, off in the book), "
        f"{spec.words()}. At entry its effect rests on a few episodes (reports/expression.md); this is its effect net of costs.",
        "",
        table(_filter_table(b)),
        "",
    ]
    return "\n".join(lines)


# ---- the figures -------------------------------------------------------------------

def _leg_marks(b, name, near):
    """(x, words) marks for a sleeve's configured leg costs (every sleeve's for the sum), one per cluster.

    Costs within `near` bp of the cluster's first share one mark at it, named
    together: "gilt 1, ZQ 1.05".
    """
    picks = b.inputs.values() if name == SUM else [b.inputs[name]]
    found = {}
    for i in picks:
        for c, (_, _, leg) in zip(i.costs, i.sleeve.legs):
            found.setdefault(round(c.round_trip_bp, 6), []).append(_label(i.sleeve, leg))
    marks = []
    for x, labels in sorted(found.items()):
        words = f"{'/'.join(dict.fromkeys(labels))} {x:.3g}"
        if marks and x - marks[-1][0] < near:
            marks[-1] = (marks[-1][0], f"{marks[-1][1]}, {words}")
        else:
            marks.append((x, words))
    return marks


def cost_figure(b, path, theme="light"):
    """Net Sharpe against a uniform round trip, per sleeve and for the sum: vol-scaled, unit, assumed legs only."""
    t = _style(theme)
    names = [SUM, *b.sleeves]
    fig, axes = plt.subplots(2, 3, figsize=(12, 7.4), gridspec_kw={"hspace": 0.55, "wspace": 0.22})
    for ax, name in zip(axes.ravel(), names):
        vs, un = b.chosen["vol_scaled"][name], b.chosen["unit"][name]
        st = stats(vs)
        star = st["cstar_bp"]
        top = max(MIN_X_BP, PAST_BREAKEVEN * star) if star is not None and np.isfinite(star) else MIN_X_BP
        cs = np.linspace(0.0, top, STEPS)
        y = curve(vs, cs)
        se = np.sqrt((1.0 + y ** 2 / 2.0) / st["years"])
        ax.fill_between(cs, y - se, y + se, color=t["series"][0], alpha=0.14, lw=0)
        ax.plot(cs, curve(un, cs), color=t["series"][1], lw=1.5)
        ax.plot(cs, y, color=t["series"][0], lw=2)
        if any(c.observed for i in (b.inputs.values() if name == SUM else [b.inputs[name]]) for c in i.costs):
            ax.plot(cs, curve(vs, cs, "assumed"), color=t["series"][0], lw=1.5, ls=(0, (4, 2)))
        ax.axhline(0, color=t["axis"], lw=1)
        for x, label in _leg_marks(b, name, 0.08 * top):
            ax.axvline(x, color=t["muted"], lw=0.8, ls=":")
            ax.text(x, 0.02, f"{label} ", transform=ax.get_xaxis_transform(), fontsize=7, rotation=90,
                    va="bottom", ha="right", color=t["secondary"])
        ax.plot([st["mix_bp"]], [st["net_sr"]], "o", ms=8, color=t["series"][0], mec=t["surface"], mew=2, zorder=4)
        unit_star = stats(un)["cstar_bp"]
        for x, color in ((star, t["ink"]), (unit_star, t["series"][1])):
            if x is not None and np.isfinite(x) and x <= top:
                ax.plot([x], [0], "D", ms=6, color=color, mec=t["surface"], mew=1.5, zorder=4)
                ax.annotate(f"c* {x:.1f}bp", (x, 0), xytext=(4, 6), textcoords="offset points", fontsize=8,
                            color=t["ink"])
        ax.set_xlim(0, top)
        ax.set_title(name, loc="left", fontsize=10, fontweight="bold", color=t["ink"], pad=18)
        short = {k: "none" if x is None else f"{x:.1f}bp" for k, x in (("vol", star), ("unit", unit_star))}
        ax.text(0, 1.02, f"c* {short['vol']} (vol-scaled), {short['unit']} (unit); configured "
                f"{sr(st['net_sr'], st['net_se'])}",
                transform=ax.transAxes, fontsize=8, color=t["secondary"], va="bottom")
        ax.tick_params(labelsize=8, length=0)
        ax.set_xlabel("round trip per leg, bp", fontsize=8)
    axes[0, 0].set_ylabel("net Sharpe", fontsize=8)
    axes[1, 0].set_ylabel("net Sharpe", fontsize=8)
    handles = [Line2D([], [], color=t["series"][0], lw=2, label="vol-scaled"),
               Patch(color=t["series"][0], alpha=0.14, label="vol-scaled ± 1 SE"),
               Line2D([], [], color=t["series"][1], lw=1.5, label="unit"),
               Line2D([], [], color=t["series"][0], lw=1.5, ls=(0, (4, 2)), label="only assumed legs varied"),
               Line2D([], [], ls="", marker="o", ms=7, color=t["series"][0], label="configured costs (a mix)"),
               Line2D([], [], ls="", marker="D", ms=6, color=t["ink"], label="c*, vol-scaled"),
               Line2D([], [], ls="", marker="D", ms=6, color=t["series"][1], label="c*, unit")]
    fig.legend(handles=handles, loc="lower center", ncols=7, bbox_to_anchor=(0.5, -0.01), fontsize=8.5,
               labelcolor=t["secondary"], handlelength=1.8)
    spec = chosen(b.book)
    s = stats(b.chosen["vol_scaled"][SUM])
    tail = (f"its breakeven is {s['cstar_bp']:.1f}bp a round trip" if s["cstar_bp"] is not None else
            "its gross P&L is below zero before any cost")
    fig.text(0.125, 0.985, f"How fragile: the sum of the sleeves nets {sr(s['net_sr'])} at the configured costs, "
             f"and {tail}", fontsize=12, fontweight="bold", color=t["ink"], va="top")
    fig.text(0.125, 0.952, f"Net Sharpe against a uniform round trip on every leg, {spec.words(sizing=False)}. "
             "Dotted: each leg's configured cost. c* none: gross P&L at or below zero. The sum is not the book "
             "(reports/portfolio.md).", fontsize=9, color=t["secondary"], va="top")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def grid_figure(b, path, theme="light"):
    """Net Sharpe over the hysteresis grid, per sleeve and for the sum (vol-scaled), the chosen cell outlined."""
    t = _style(theme)
    g = b.book["positions"]["grid"]
    here = (b.book["positions"]["enter"], b.book["positions"]["exit"])
    names = [SUM, *b.sleeves]
    cube = np.full((len(names), len(g["enter"]), len(g["exit"])), np.nan)
    for k, name in enumerate(names):
        for (e, x), per in b.grid["vol_scaled"].items():
            cube[k, g["enter"].index(e), g["exit"].index(x)] = per[name]["net_sr"]
    top = float(np.nanmax(np.abs(cube))) or 1.0
    cmap = LinearSegmentedColormap.from_list("sharpe", t["diverging"][::-1]).with_extremes(bad=t["surface"])   # red below 0, blue above
    fig, axes = plt.subplots(2, 3, figsize=(12, 7.6), gridspec_kw={"hspace": 0.45, "wspace": 0.18})
    for k, (ax, name) in enumerate(zip(axes.ravel(), names)):
        m = np.ma.masked_invalid(cube[k])
        image = ax.imshow(m, cmap=cmap, vmin=-top, vmax=top, origin="lower", aspect="auto")
        for i in range(len(g["enter"])):
            for j in range(len(g["exit"])):
                v = cube[k, i, j]
                if np.isnan(v):
                    continue
                fill = cmap((v + top) / (2 * top))
                ax.text(j, i, f"{v:+.2f}", ha="center", va="center", fontsize=7.5, color=_ink_on(fill[:3]))
        i, j = g["enter"].index(here[0]), g["exit"].index(here[1])
        ax.add_patch(Rectangle((j - 0.5, i - 0.5), 1, 1, fill=False, ec=t["ink"], lw=2))
        ax.set_xticks(range(len(g["exit"])), [f"{x:g}" for x in g["exit"]], fontsize=8)
        ax.set_yticks(range(len(g["enter"])), [f"{e:g}" for e in g["enter"]], fontsize=8)
        ax.set_xlabel("exit (z x side at or below)", fontsize=8)
        ax.set_ylabel("enter (|z| at or above)", fontsize=8)
        ax.grid(False)
        ax.tick_params(length=0)
        s = surface(b.grid["vol_scaled"], b.book, name)
        ax.set_title(name, loc="left", fontsize=10, fontweight="bold", color=t["ink"], pad=18)
        ax.text(0, 1.02, f"chosen {sr(s['net_sr'], s['net_se'])}; {pct(s['share_positive'])} of cells > 0",
                transform=ax.transAxes, fontsize=8, color=t["secondary"], va="bottom")
    bar = fig.colorbar(image, ax=axes.ravel().tolist(), fraction=0.02, pad=0.02)
    bar.set_label("net Sharpe", fontsize=8, color=t["secondary"])
    bar.ax.tick_params(labelsize=7, length=0)
    bar.outline.set_visible(False)
    s = surface(b.grid["vol_scaled"], b.book, SUM)
    spec = chosen(b.book)
    fig.text(0.125, 0.985, f"The hysteresis grid: the sum's net Sharpe runs from {sr(s['grid_min'])} to "
             f"{sr(s['grid_max'])}; the chosen pair {here} is outlined", fontsize=12, fontweight="bold",
             color=t["ink"], va="top")
    fig.text(0.125, 0.952, f"Net Sharpe per (enter, exit) pair, {TREATMENT_WORDS[spec.treatment]}, vol-scaled, "
             "configured costs. Blank: exit >= enter, not a rule. The pair was fixed before the grid was run.",
             fontsize=9, color=t["secondary"], va="top")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---- the outputs -------------------------------------------------------------------

def results(b):
    """reports/results/costs.json: the numbers the note quotes, to six significant figures."""
    book = b.book
    grid_bp = book["costs"]["sensitivity_bp"]
    chosen_stats = {sz: {n: stats(r) for n, r in runs.items()} for sz, runs in b.chosen.items()}
    return _plain({
        "spec": {"rule": chosen(book).rule, "enter": book["positions"]["enter"], "exit": book["positions"]["exit"],
                 "treatment": chosen(book).treatment, "primary_sizing": "vol_scaled",
                 "vol_target": book["book"]["vol_target"], "capital": book["book"]["capital"]},
        "legs": leg_words(b).to_dict("records"),
        "chosen": chosen_stats,
        "curves": {sz: {n: {"round_trip_bp": grid_bp, "net_sr": list(curve(r, grid_bp)),
                            "assumed_only_net_sr": list(curve(r, grid_bp, "assumed"))}
                        for n, r in runs.items()} for sz, runs in b.chosen.items()},
        "surface": {sz: {n: surface(b.grid[sz], book, n) for n in [SUM, *b.sleeves]} for sz in b.grid},
        "grid": {sz: {f"{e:g}/{x:g}": {n: {"net_sr": st["net_sr"], "net_se": st["net_se"], "gross_sr": st["gross_sr"],
                                           "turns_year": st["turns_year"], "traded_year": st["traded_year"]}
                                       for n, st in per.items()} for (e, x), per in cells_of.items()}
                 for sz, cells_of in b.grid.items()},
        "rules": b.rules,
        "restrike": {f"{m}_months": by for m, by in b.restrike.items()},
        "band_off": b.band["off"],
        "carry_filter_on": b.carry_filter,
        "elb": b.elb.set_index("sleeve").to_dict("index"),
        "by_year_pct_capital": {n: by_year(r, book["book"]["capital"]).to_dict()
                                for n, r in b.chosen["vol_scaled"].items()},
    })


def write(b, root):
    """Every output of the build under repo `root`. Returns the paths."""
    root = Path(root)
    out = {"report": root / "reports" / "costs.md", "json": root / "reports" / "results" / "costs.json"}
    for p in out.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    out["report"].write_text(markdown(b), encoding="utf-8")
    out["json"].write_text(json.dumps(results(b), indent=1) + "\n", encoding="utf-8")
    figures = root / "reports" / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        for stem, draw in (("cost_sensitivity", cost_figure), ("hysteresis_grid", grid_figure)):
            p = figures / f"{stem}_{theme}.png"
            draw(b, p, theme)
            out[f"{stem}_{theme}"] = p
    return out
