"""Coverage of the path panel: what solved, what did not, and what looks wrong.

Generated by `scripts/build_panel.py` into ``reports/``; never edit the output.
Each check is a table, so an entry can be traced back to its session.
"""

import pandas as pd
from pandas.tseries.holiday import GoodFriday, USFederalHolidayCalendar
from policypath.calendars import US_BDAY

BIG_STEP_BP = 75.0


def checks(sessions, meetings, start, end, n_meetings):
    """Every diagnostic as a named DataFrame, plus a dict of headline numbers."""
    start, end = pd.Timestamp(start), pd.Timestamp(end)
    bdays = pd.date_range(start, end, freq=US_BDAY)
    in_range = sessions[(sessions["session"] >= start) & (sessions["session"] <= end)]
    solved = in_range[in_range["error"].isna()]
    good_fridays = set(GoodFriday.dates(start, end))
    # pandas moves a Saturday holiday to the Friday, as CME does; the Fed does not.
    friday_observed = set(USFederalHolidayCalendar().holidays(start, end))

    missing = pd.DataFrame({"date": bdays.difference(pd.DatetimeIndex(in_range["session"]))})
    missing["reason"] = [
        "Good Friday: CME closed, Fed open" if d in good_fridays
        else "Saturday holiday: CME closed the Friday, Fed open" if d in friday_observed
        else "no ZQ settles in the archive"
        for d in missing["date"]]
    extra = in_range.loc[~in_range["session"].isin(bdays), ["session"]]
    extra["note"] = "CME open, Fed closed: solved on fixings through the prior Fed business day"

    failed = in_range.loc[in_range["error"].notna(), ["session", "error"]]
    m = meetings[meetings["session"].isin(solved["session"])]
    big = m.loc[m["step_bp"].abs() > BIG_STEP_BP,
                ["session", "k", "announcement_date", "step_bp"]]
    flat = m.groupby("session")["step_bp"].apply(lambda s: (s == 0).all())
    flat = pd.DataFrame({"session": flat[flat].index})
    spanned = m.groupby("session")["rate"].count()
    short = pd.DataFrame({"session": spanned[spanned < n_meetings].index,
                          "meetings": spanned[spanned < n_meetings].to_numpy()})
    no_front = solved.loc[~solved["front_is_current"].astype(bool), ["session", "front_month"]]
    worst = solved.nlargest(10, "residual_bp")[["session", "n_contracts", "residual_bp"]]

    covered = len(bdays.intersection(pd.DatetimeIndex(solved["session"])))
    headline = {
        "fed_business_days": len(bdays),
        "sessions": len(in_range),
        "solved": len(solved),
        "failed": len(failed),
        "coverage_pct": 100.0 * covered / len(bdays),
        "contracts_min": int(solved["n_contracts"].min()),
        "contracts_median": float(solved["n_contracts"].median()),
        "contracts_max": int(solved["n_contracts"].max()),
        "front_dropped": int(solved["front_dropped"].sum()),
        "pinned": int(solved["pinned"].sum()),
        "residual_bp_median": float(solved["residual_bp"].median()),
        "residual_bp_p95": float(solved["residual_bp"].quantile(0.95)),
    }
    tables = {
        "Fed business days missing from the panel": missing,
        "Sessions on Fed holidays": extra,
        "Solver failures": failed,
        f"Sessions spanning fewer than {n_meetings} meetings": short,
        f"Implied steps beyond {BIG_STEP_BP:.0f}bp": big,
        "Sessions where every implied step is exactly zero": flat,
        "Sessions without the current month's contract": no_front,
        "Worst repricing residuals": worst,
    }
    return headline, tables


def markdown(ccy, headline, tables, start, end):
    h = headline
    lines = [
        f"# Path panel coverage: {ccy}",
        "",
        f"Generated by `scripts/build_panel.py` for {pd.Timestamp(start).date()} .. "
        f"{pd.Timestamp(end).date()}. Do not edit by hand.",
        "",
        f"- Fed business days: {h['fed_business_days']}",
        f"- Sessions in the panel: {h['sessions']} (solved {h['solved']}, failed {h['failed']})",
        f"- **Coverage: {h['coverage_pct']:.2f}%** of Fed business days solved",
        f"- Contracts per session: min {h['contracts_min']}, median {h['contracts_median']:.0f}, "
        f"max {h['contracts_max']}",
        f"- Front contract dropped near expiry: {h['front_dropped']} sessions",
        f"- First regime pinned to the last fixing: {h['pinned']} sessions",
        f"- Repricing residual: median {h['residual_bp_median']:.2f}bp, "
        f"95th percentile {h['residual_bp_p95']:.2f}bp",
        "",
    ]
    for title, df in tables.items():
        lines += [f"## {title} ({len(df)})", ""]
        if df.empty:
            lines += ["None.", ""]
            continue
        lines += [table(df.head(40)), ""]
        if len(df) > 40:
            lines += [f"... and {len(df) - 40} more.", ""]
    return "\n".join(lines)


def _cell(v):
    if isinstance(v, pd.Timestamp):
        return f"{v:%Y-%m-%d}"
    if isinstance(v, float):
        return f"{v:.2f}"
    return str(v).replace("|", "\\|")


def table(df):
    rows = [list(df.columns), ["---"] * df.shape[1],
            *([_cell(v) for v in row] for row in df.itertuples(index=False))]
    return "\n".join("| " + " | ".join(map(str, r)) + " |" for r in rows)
