"""The ZQ path against SOFR futures: how well the implied SOFR - EFFR basis behaves.

Generated by `scripts/build_panel.py` into ``reports/``; never edit the output.
"""

import pandas as pd
from policypath.curves.basis import next_period, trailing_basis
from policypath.report.coverage import table

JUMP_BP = 3.0


def summary(basis, sofr, effr):
    """(yearly table, largest daily moves, per-session next-quarter frame)."""
    nq = next_period(basis)
    nq["trailing_bp"] = [trailing_basis(sofr, effr, day) for day in nq.index]
    nq["error_bp"] = nq["basis_bp"] - nq["realized_bp"]
    nq["change_bp"] = nq["basis_bp"].diff()
    nq["rolled"] = nq["contract"] != nq["contract"].shift()
    by_year = nq.groupby(nq.index.year).agg(
        sessions=("basis_bp", "size"),
        implied_bp=("basis_bp", "mean"),
        realized_bp=("realized_bp", "mean"),
        trailing_bp=("trailing_bp", "mean"),
        abs_error_bp=("error_bp", lambda x: x.abs().mean()),
        daily_change_sd_bp=("change_bp", "std"),
    ).rename_axis("year").reset_index()
    jumps = nq.loc[nq["change_bp"].abs() > JUMP_BP, ["contract", "rolled", "basis_bp", "change_bp"]]
    return by_year, jumps.rename_axis("session").reset_index(), nq


PERIOD = {"month": "month", "imm_quarter": "quarter"}
COMBINED = {"month": "averaged over each {root} contract month",
            "imm_quarter": "compounded over each {root} IMM quarter"}


def markdown(ccy, root, shape, by_year, jumps, nq):
    e = nq["error_bp"].dropna()
    period = PERIOD[shape]
    lines = [
        f"# ZQ path against {root}: {ccy}",
        "",
        "Generated by `scripts/build_panel.py`. Do not edit by hand.",
        "",
        f"For every session, the ZQ-implied EFFR path is {COMBINED[shape].format(root=root)}",
        f"(realized SOFR on days already fixed) and the constant spread that reprices the {root}",
        "settle is solved for: the SOFR - EFFR basis the two markets imply together. Below,",
        f"for the first {period} lying wholly ahead of each session.",
        "",
        f"- Sessions: {len(nq)} ({nq.index.min():%Y-%m-%d} .. {nq.index.max():%Y-%m-%d}); "
        f"{period}s since fully printed: {len(e)}",
        f"- Implied minus later-realized basis: mean {e.mean():+.2f}bp, "
        f"mean absolute {e.abs().mean():.2f}bp, within 3bp on {100 * (e.abs() <= 3).mean():.0f}%",
        f"- Day-to-day change in the implied basis: sd {nq['change_bp'].std():.2f}bp; "
        f"{len(jumps)} session{'' if len(jumps) == 1 else 's'} moved more than {JUMP_BP:.0f}bp",
        "",
        "## By year",
        "",
        table(by_year),
        "",
        f"## Days the implied basis moved more than {JUMP_BP:.0f}bp ({len(jumps)})",
        "",
        f"`rolled` marks days the next {period} became a different contract, so part of",
        "the move is the window changing rather than the market.",
        "",
        table(jumps) if len(jumps) else "None.",
        "",
    ]
    return "\n".join(lines)
