"""The ZQ path against SOFR futures: how well the implied SOFR - EFFR basis behaves.

Generated by `scripts/build_panel.py` into ``reports/``; never edit the output.
"""

from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd
from policypath.curves.basis import next_period, trailing_basis
from policypath.report.coverage import table
from policypath.report.figures import THEMES, _style, _title

JUMP_BP = 3.0


def summary(basis, sofr, effr):
    """(yearly table, largest daily moves, per-session next-quarter frame)."""
    nq = next_period(basis)
    nq["trailing_bp"] = [trailing_basis(sofr, effr, day) for day in nq.index]
    nq["error_bp"] = nq["basis_bp"] - nq["realized_bp"]
    nq["change_bp"] = nq["basis_bp"].diff()
    nq["rolled"] = nq["contract"] != nq["contract"].shift()
    by_year = nq.groupby(nq.index.year).agg(
        sessions=("basis_bp", "size"),
        implied_bp=("basis_bp", "mean"),
        realized_bp=("realized_bp", "mean"),
        trailing_bp=("trailing_bp", "mean"),
        abs_error_bp=("error_bp", lambda x: x.abs().mean()),
        daily_change_sd_bp=("change_bp", "std"),
    ).rename_axis("year").reset_index()
    jumps = nq.loc[nq["change_bp"].abs() > JUMP_BP, ["contract", "rolled", "basis_bp", "change_bp"]]
    return by_year, jumps.rename_axis("session").reset_index(), nq


PERIOD = {"month": "month", "imm_quarter": "quarter"}
COMBINED = {"month": "averaged over each {root} contract month",
            "imm_quarter": "compounded over each {root} IMM quarter"}


def markdown(ccy, root, shape, by_year, jumps, nq):
    e = nq["error_bp"].dropna()
    period = PERIOD[shape]
    lines = [
        f"# ZQ path against {root}: {ccy}",
        "",
        "Generated by `scripts/build_panel.py`. Do not edit by hand.",
        "",
        f"For every session, the ZQ-implied EFFR path is {COMBINED[shape].format(root=root)}",
        f"(realized SOFR on days already fixed) and the constant spread that reprices the {root}",
        "settle is solved for: the SOFR - EFFR basis the two markets imply together. Below,",
        f"for the first {period} lying wholly ahead of each session.",
        "",
        f"- Sessions: {len(nq)} ({nq.index.min():%Y-%m-%d} .. {nq.index.max():%Y-%m-%d}); "
        f"{period}s since fully printed: {len(e)}",
        f"- Implied minus later-realized basis: mean {e.mean():+.2f}bp, "
        f"mean absolute {e.abs().mean():.2f}bp, within 3bp on {100 * (e.abs() <= 3).mean():.0f}%",
        f"- Day-to-day change in the implied basis: sd {nq['change_bp'].std():.2f}bp; "
        f"{len(jumps)} session{'' if len(jumps) == 1 else 's'} moved more than {JUMP_BP:.0f}bp",
        "",
        "## By year",
        "",
        table(by_year),
        "",
        f"## Days the implied basis moved more than {JUMP_BP:.0f}bp ({len(jumps)})",
        "",
        f"`rolled` marks days the next {period} became a different contract, so part of",
        "the move is the window changing rather than the market.",
        "",
        table(jumps) if len(jumps) else "None.",
        "",
    ]
    return "\n".join(lines)


def sofr_basis(nq, root, path, theme="light"):
    """The SOFR - EFFR basis implied by `root` against the ZQ path, and what then printed."""
    t = _style(theme)
    fig, ax = plt.subplots(figsize=(11, 4.4))
    ax.axhline(0, color=t["axis"], lw=1)
    ax.plot(nq.index, nq["basis_bp"], color=t["series"][0], lw=1.5, label=f"Implied by {root} and ZQ")
    ax.plot(nq.index, nq["realized_bp"], color=t["series"][1], lw=2,
            label="Realized over the same days, ex post")
    ax.set_ylabel("bp")
    ax.legend(loc="upper left", fontsize=9, labelcolor=t["secondary"])
    last = nq["basis_bp"].dropna()
    ax.annotate(f"{last.iloc[-1]:+.1f}bp", xy=(last.index[-1], last.iloc[-1]), xytext=(6, 0),
                textcoords="offset points", va="center", fontsize=9, color=t["secondary"])
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    ax.tick_params(axis="both", length=0)
    _title(ax, f"SOFR minus EFFR: what {root} implies against the ZQ path",
           f"First {root} contract wholly ahead of each session. A wrong ZQ path would show up as noise here.", t)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def write_figures(nq, root, out_dir, ccy):
    """The basis figure, light and dark."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for theme in THEMES:
        p = out_dir / f"sofr_basis_{ccy}_{theme}.png"
        sofr_basis(nq, root, p, theme)
        written.append(p)
    return written
