"""The UK nowcast, and the labour market read three ways: LFS unemployment against the claimant count and PAYE.

The ONS recommends reading the LFS alongside Workforce Jobs, the claimant
count and PAYE Real Time Information rather than alone, after the 2023
response-rate collapse. The gap the rule uses is built from the LFS; this
report is where the other two say whether to believe it. Divergence is
reported as a finding, not reconciled away: the UK signal is noisier than
the US one, and this is how much.

Every comparison is in real time: each month's figures as the release that
first printed them had them, from the ONS revisions triangles.

Generated by `scripts/build_nowcast.py`, never hand-edited.
"""

from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath.report.coverage import table
from policypath.report.figures import THEMES, _style, _title

LFS, CLAIMANTS, PAYE = "MGSX", "CLAIMANTS", "PAYE"


def first_prints(panel, as_of, series):
    """Each reference month's first published value, and the change on a year earlier in that same release.

    ``change_12m`` is what a reader of that release saw: this month against
    the same release's figure twelve months before, so revisions to the base
    do not leak in from later vintages.
    """
    rows = []
    for day, vintage in releases(panel, as_of, series):
        v = vintage.dropna()
        if v.empty:
            continue
        month = v.index[-1]
        base = v.get(month - pd.DateOffset(months=12))
        rows.append({"release": day, "month": month, "value": v.iloc[-1],
                     "level_change_12m": np.nan if base is None else v.iloc[-1] - base,
                     "pct_change_12m": np.nan if base is None else (v.iloc[-1] / base - 1) * 100})
    return pd.DataFrame(rows).drop_duplicates("month", keep="first")


def releases(panel, as_of, series):
    """Every release of `series` up to `as_of`, each with the whole series as it then stood."""
    for day in panel.release_dates(as_of, series)["published"].drop_duplicates().sort_values():
        yield day, panel.series(series, day)


def crosscheck(panel, as_of):
    """Month by month, the three measures as first printed, and whether they point the same way."""
    lfs = first_prints(panel, as_of, LFS).set_index("month")
    cc = first_prints(panel, as_of, CLAIMANTS).set_index("month")
    paye = first_prints(panel, as_of, PAYE).set_index("month")
    df = pd.DataFrame({
        "lfs_rate": lfs["value"], "lfs_change_12m_pp": lfs["level_change_12m"],
        "claimants_change_12m_pct": cc["pct_change_12m"], "paye_change_12m_pct": paye["pct_change_12m"],
    }).dropna(subset=["lfs_change_12m_pp"])
    # Unemployment and claimants should rise together; unemployment and payrolls should not.
    u = np.sign(df["lfs_change_12m_pp"])
    df["lfs_vs_claimants_disagree"] = (u != np.sign(df["claimants_change_12m_pct"])).astype(float).where(
        df["claimants_change_12m_pct"].notna())
    df["lfs_vs_paye_disagree"] = (u == np.sign(df["paye_change_12m_pct"])).astype(float).where(
        df["paye_change_12m_pct"].notna())
    return df


def revisions(panel, as_of, series):
    """First print against the value in the `as_of` vintage, by reference year."""
    first = first_prints(panel, as_of, series).set_index("month")["value"]
    latest = panel.series(series, as_of).reindex(first.index)
    rev = (latest - first)
    return rev.groupby(rev.index.year).agg(months="count", mean="mean", mean_abs=lambda s: s.abs().mean())


def checks(frame, panel, spec, as_of):
    """Every section as a named DataFrame, and a dict of headline numbers."""
    cross = crosscheck(panel, as_of)
    by_year = cross.groupby(cross.index.year).agg(
        lfs_rate=("lfs_rate", "mean"), lfs_change_12m_pp=("lfs_change_12m_pp", "mean"),
        claimants_change_12m_pct=("claimants_change_12m_pct", "mean"),
        paye_change_12m_pct=("paye_change_12m_pct", "mean"),
        lfs_vs_claimants_disagree=("lfs_vs_claimants_disagree", "mean"),
        lfs_vs_paye_disagree=("lfs_vs_paye_disagree", "mean")).reset_index(names="year")
    recent = cross.tail(12).reset_index(names="month")
    lfs_rev = revisions(panel, as_of, LFS).reset_index(names="year")
    last = frame.iloc[-1]
    since = lambda s, d: s[s.index >= d].mean()
    headline = {
        "business_days": len(frame), "first": frame["as_of"].min(), "last": frame["as_of"].max(),
        "latest": last,
        "disagree_claimants_all": cross["lfs_vs_claimants_disagree"].mean(),
        "disagree_claimants_2023": since(cross["lfs_vs_claimants_disagree"], "2023-01-01"),
        "disagree_paye_2020": since(cross["lfs_vs_paye_disagree"], "2020-01-01"),
        "disagree_paye_2023": since(cross["lfs_vs_paye_disagree"], "2023-01-01"),
        "corr_claimants_pre": cross.loc[:"2022-12-31", ["lfs_change_12m_pp", "claimants_change_12m_pct"]].corr().iloc[0, 1],
        "corr_claimants_post": cross.loc["2023-01-01":, ["lfs_change_12m_pp", "claimants_change_12m_pct"]].corr().iloc[0, 1],
    }
    tables = {
        "The three measures by year, as first printed (12-month changes; disagree = share of months)": by_year,
        "The last twelve months, as first printed": recent,
        "LFS unemployment: latest estimate minus first print, pp, by reference year": lfs_rev,
    }
    return headline, tables, cross


def markdown(ccy, headline, tables, tags):
    h, last = headline, headline["latest"]
    lines = [
        f"# Macro nowcast: {ccy}",
        "",
        f"Generated by `scripts/build_nowcast.py` for {h['first']:%Y-%m-%d} .. {h['last']:%Y-%m-%d}. "
        "Do not edit by hand.",
        "",
        f"- Business days: {h['business_days']}, every one solved (a failure stops the build)",
        f"- Latest ({last['as_of']:%Y-%m-%d}): CPI 12m {last['infl_12m']:.1f}% ({last['infl_month']:%Y-%m}), "
        f"LFS unemployment {last['u']:.2f}% (three months to {last['gap_month']:%Y-%m}), "
        f"u - u* {last['u_gap']:+.2f}pp against a constant u* of {last['u_star']:.1f}%",
        "",
        "## The labour market three ways",
        "",
        "The rule's gap is built from LFS unemployment. The claimant count and PAYE payrolled employees are "
        "read beside it, as the ONS recommends, and never enter the rule. Each month is as first printed.",
        "",
        f"- The LFS and the claimant count point different ways over twelve months in "
        f"{h['disagree_claimants_all']:.0%} of months overall, {h['disagree_claimants_2023']:.0%} since 2023. "
        f"Correlation of the two 12-month changes: {h['corr_claimants_pre']:+.2f} to 2022, "
        f"{h['corr_claimants_post']:+.2f} since.",
        f"- The LFS says unemployment rose while payrolls rose too (or the reverse) in "
        f"{h['disagree_paye_2020']:.0%} of months since 2020 (PAYE vintages start in December 2019), "
        f"{h['disagree_paye_2023']:.0%} since 2023.",
        "",
        "Not all disagreement is LFS noise. In 2017-19 the claimant count rose while LFS unemployment fell: "
        "that is the Universal Credit rollout, which widened who counts as a claimant, so the claimant count "
        "has a break of its own there. The disagreement since 2023 has no such explanation on the claimant side.",
        "",
        "This is a finding, not a gap to reconcile: the UK labour market input is less reliable than the US "
        "one, so the UK signal is noisier, and that should be known before anything is sized on it.",
        "",
        "## Data quality, from the config's tags",
        "",
        *[f"- **{series}**: {text}" for series, t in tags.items() for text in t.values()],
        "",
    ]
    for title, df in tables.items():
        lines += [f"## {title}", "", table(df) if len(df) else "None.", ""]
    return "\n".join(lines)


def figure(cross, path, theme="light"):
    """LFS unemployment as first printed, and the three measures' 12-month changes."""
    t = _style(theme)
    fig, (top, bottom) = plt.subplots(2, 1, figsize=(11, 7), sharex=True, gridspec_kw={"hspace": 0.35})
    for ax in (top, bottom):
        ax.axvspan(pd.Timestamp("2023-10-01"), pd.Timestamp("2024-02-01"), color=t["grid"], lw=0)
    top.plot(cross.index, cross["lfs_rate"], color=t["series"][0], lw=1.8)
    top.set_ylabel("%")
    top.text(pd.Timestamp("2023-10-01"), top.get_ylim()[1], " LFS suspended", va="top", fontsize=8,
             color=t["secondary"])
    _title(top, "UK unemployment rate (LFS), as first printed", "Three months ending the month shown.", t)
    bottom.axhline(0, color=t["axis"], lw=1)
    bottom.plot(cross.index, cross["claimants_change_12m_pct"], color=t["series"][0], lw=1.5,
                label="Claimant count, % on a year")
    bottom.plot(cross.index, cross["paye_change_12m_pct"], color=t["series"][1], lw=1.8,
                label="PAYE payrolled employees, % on a year")
    bottom.set_ylabel("% on a year")
    bottom.set_ylim(-15, 30)
    bottom.legend(loc="upper left", fontsize=9, labelcolor=t["secondary"])
    _title(bottom, "What the other two measures said, as first printed",
           "Claimants should move with unemployment and payrolls against it. Clipped at -15%/+30% (2020).", t)
    for ax in (top, bottom):
        ax.xaxis.set_major_locator(mdates.YearLocator(2))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
        ax.tick_params(axis="both", length=0)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def write_figures(cross, out_dir, ccy):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for theme in THEMES:
        p = out_dir / f"nowcast_{ccy}_{theme}.png"
        figure(cross, p, theme)
        written.append(p)
    return written


def write(ccy, frame, panel, spec, as_of, reports):
    """The report and its figures under `reports`. Returns lines to print."""
    headline, tables, cross = checks(frame, panel, spec, as_of)
    (reports / f"nowcast_{ccy}.md").write_text(markdown(ccy, headline, tables, spec.get("tags", {})),
                                               encoding="utf-8")
    drawn = write_figures(cross, reports / "figures", ccy)
    first = next(iter(tables))
    return [f"{headline['business_days']} days, {headline['first']:%Y-%m-%d} .. {headline['last']:%Y-%m-%d}",
            f"\n{first}\n{tables[first].round(2).to_string(index=False)}",
            f"\nwrote {reports / f'nowcast_{ccy}.md'} and {len(drawn)} figures"]
