"""The model path against the market path: coverage, the gap at named moments, the crude backtest.

Generated by `scripts/build_model.py`, never hand-edited.
"""

import pandas as pd
from policypath.backtest import engine, policy
from policypath.report.coverage import table

# Days the gap should be able to explain. Each is read on the first session on or after it.
MOMENTS = [
    ("2011-08-09", "\"Exceptionally low\" through mid-2013: calendar guidance"),
    ("2013-06-24", "Taper tantrum"),
    ("2015-06-01", "Liftoff delayed"),
    ("2015-12-15", "Eve of liftoff"),
    ("2018-12-20", "Day after the last hike of the cycle"),
    ("2019-07-30", "Eve of the first insurance cut"),
    ("2020-06-01", "Both at the floor"),
    ("2021-11-01", "Late 2021: inflation up, the Fed waits"),
    ("2022-03-01", "Eve of liftoff, 2022"),
    ("2022-06-13", "Before the first 75bp hike"),
    ("2023-06-13", "The pause"),
    ("2023-12-14", "Pivot debate: the day after the December dots"),
    ("2024-04-15", "Cuts priced out"),
    ("2024-09-17", "Eve of the first cut"),
]


def snapshot(day, paths, summaries, sessions, signal):
    """Everything the chart and the page say about one session."""
    s = sessions.set_index("session").loc[day]
    rule = summaries.set_index("session").loc[day]
    sig = signal[signal["session"] == day].set_index("k")[["gap_bp", "z", "window_mean_bp", "window_sd_bp"]]
    m = paths[paths["session"] == day].set_index("k").join(sig).reset_index()
    return {"session": day, "rate_now": s["rate_now"], "last_fixing": s["last_fixing"],
            "model_now": rule["r0"] + rule["spread_bp"] / 100.0, "rule": rule, "meetings": m}


def checks(sessions, summaries, paths, signal, meetings, spec, moments=MOMENTS):
    """Every section as a named DataFrame, a dict of headline numbers, and the backtest result."""
    k = spec["backtest"]["horizon"]
    ok = sessions[sessions["error"].isna()]
    gap = signal.pivot(index="session", columns="k", values="gap_bp")
    z = signal.pivot(index="session", columns="k", values="z")
    rule = summaries.set_index("session")

    at = [gap.index[gap.index >= pd.Timestamp(d)][0] for d, _ in moments]
    named = pd.DataFrame({
        "session": at, "moment": [label for _, label in moments],
        "gap_k1": gap.loc[at, 1].to_numpy(), f"gap_k{k}": gap.loc[at, k].to_numpy(),
        "gap_k8": gap.loc[at, 8].to_numpy(), f"z_k{k}": z.loc[at, k].to_numpy(),
        "core_pce": rule.loc[at, "inflation"].to_numpy(), "u_gap": rule.loc[at, "u_gap"].to_numpy(),
        "rstar": rule.loc[at, "rstar"].to_numpy(), "notional": rule.loc[at, "notional"].to_numpy(),
    })

    by_k = {h: policy.run(signal, sessions, meetings, h, spec["backtest"]) for h in sorted(gap.columns)}
    stats = {h: engine.stats(r) for h, r in by_k.items()}
    result, summary = by_k[k], stats[k]
    sensitivity = pd.DataFrame([{"k": h, **{c: s[c] for c in ["total", "per_year", "vol", "sharpe",
                                                               "hit_rate", "max_drawdown"]}}
                                for h, s in stats.items()])
    live = result[result["position"].notna()]
    yearly = live.groupby(live.index.year).agg(pnl_bp=("pnl", "sum"), mean_abs_z=("position", lambda p: p.abs().mean()))
    yearly = yearly.reset_index(names="year")

    by_year = gap.groupby(gap.index.year).agg(["mean"])[[(1, "mean"), (k, "mean"), (8, "mean")]]
    by_year.columns = ["gap_k1_mean", f"gap_k{k}_mean", "gap_k8_mean"]
    by_year = by_year.join(rule.groupby(rule.index.year)["at_elb"].mean().rename("share_at_elb"))
    by_year = by_year.reset_index(names="year")

    headline = {
        "panel_sessions": len(ok), "model_sessions": len(rule),
        "first_model": rule.index.min(), "last": rule.index.max(),
        "before_macro": int((ok["session"] < rule.index.min()).sum()),
        "at_elb": int(rule["at_elb"].sum()), "before_first_sep": int(rule["sep_date"].isna().sum()),
        "first_z": z[k].first_valid_index(), "k": k, "backtest": summary,
    }
    tables = {
        "The gap at named moments, bp (negative: the market prices less tightening than the rule)": named,
        "The gap by year, bp, and the share of sessions the rule sat on the floor": by_year,
        f"Crude backtest at k = {k}, by year (no costs)": yearly,
        "Horizon sensitivity (k = 4 was chosen before any of these were run; not a menu)": sensitivity,
    }
    return headline, tables, result


def markdown(ccy, headline, tables, today):
    h, b, r = headline, headline["backtest"], today["rule"]
    m = today["meetings"]
    lines = [
        f"# Model path against market path: {ccy}",
        "",
        f"Generated by `scripts/build_model.py` for {h['first_model']:%Y-%m-%d} .. {h['last']:%Y-%m-%d}. "
        "Do not edit by hand. The rule, r* and the conditioning are explained in notes/decisions.md "
        "(2026-09-27); the inputs in [nowcast_USD.md](nowcast_USD.md).",
        "",
        f"- Sessions with a market path: {h['panel_sessions']}; with a model path: {h['model_sessions']} "
        f"(the first {h['before_macro']} precede the nowcast, which needs a vintaged u*: 2011-03-04)",
        f"- Sessions where the rule's notional rate is below the ELB, so the model sits on the floor: {h['at_elb']}",
        f"- Sessions before the first SEP dot (r* = Taylor's 2%): {h['before_first_sep']}",
        f"- First z at k = {h['k']}: {h['first_z']:%Y-%m-%d} (two-year trailing window, a year of history first)",
        f"- Crude backtest at k = {h['k']}, {b['first']:%Y-%m} .. {b['last']:%Y-%m}, **no costs**: "
        f"{b['total']:+.0f}bp x z, Sharpe {b['sharpe']:.2f}, max drawdown {b['max_drawdown']:.0f}bp",
        "",
        f"## Latest session: {today['session']:%Y-%m-%d}",
        "",
        f"Core PCE {r['inflation']:.2f}%, u - u* {r['u_gap']:+.2f}pp, r* {r['rstar']:.2f} "
        f"(SEP of {r['sep_date']:%Y-%m-%d}): the rule's notional rate is {r['notional']:.2f}%. "
        f"Midpoint in force {r['r0']:.3f}%, EFFR - midpoint {r['spread_bp']:+.1f}bp.",
        "",
        table(m[["k", "announcement_date", "effective_date", "market", "model", "gap_bp", "z",
                 "window_mean_bp", "window_sd_bp"]].rename(columns={"announcement_date": "announced",
                                                                  "effective_date": "effective"})),
        "",
    ]
    for title, df in tables.items():
        lines += [f"## {title}", "", table(df) if len(df) else "None.", ""]
    return "\n".join(lines)
