"""The macro nowcast panel: coverage, the bridge's real-time error, the gap, activity vs GDPNow.

Generated by `scripts/build_nowcast.py` into ``reports/``; never edit the output.
Everything here reads the panel through `as_of`, including the benchmarks: the
SEP longer-run rate and GDPNow are compared as they stood on each day.
"""

from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath.macro.inflation import bridge_backtest
from policypath.report.coverage import table
from policypath.report.figures import THEMES, _style, _title

WINDOWS = [36, 60, 120]   # the bridge windows reported once; never tuned
EXCLUDE_QUARTER = "2025-01-01"   # GDPNow's gold-import quarter


def _latest(panel, name, day):
    s = panel.series(name, day).dropna()
    return (s.index[-1], s.iloc[-1]) if len(s) else (pd.NaT, np.nan)


def benchmarks(frame, panel, spec):
    """The SEP longer-run rate, GDPNow and the CBO vintage in force, as they stood on each day."""
    rows = []
    for day in frame["as_of"]:
        _, sep = _latest(panel, spec["gap"]["longer_run"], day)
        quarter, now = _latest(panel, spec["activity"]["benchmark"], day)
        cbo = panel.as_of(day, spec["gap"]["natural_rate"])["published"].max()
        rows.append({"as_of": day, "u_longer_run": sep, "gdpnow_quarter": quarter, "gdpnow": now,
                     "cbo_vintage": cbo})
    return pd.DataFrame(rows)


def _rmse(e):
    return float(np.sqrt((e ** 2).mean()))


def bridge_tables(panel, as_of, spec, start):
    """The backtest at the configured window, and the window sensitivity."""
    bt = bridge_backtest(panel, as_of, spec["inflation"], start)
    methods = {"bridge": f"bridge ({spec['inflation']['bridge_window']}-month fit)",
               "proxy_1to1": "core CPI m/m 1:1", "last_carried": "last PCE m/m carried"}
    summary = pd.DataFrame([{"method": label,
                             "rmse_pp": _rmse(bt[c] - bt["first_print"]),
                             "rmse_ex_hole_pp": _rmse((bt[c] - bt["first_print"])[~bt["across_hole"]]),
                             "mae_pp": float((bt[c] - bt["first_print"]).abs().mean()),
                             "months": len(bt)} for c, label in methods.items()])
    windows = []
    for w in WINDOWS:
        b = bt if w == spec["inflation"]["bridge_window"] else bridge_backtest(panel, as_of, spec["inflation"],
                                                                                start, window=w)
        windows.append({"window_months": w, "rmse_pp": _rmse(b["bridge"] - b["first_print"]), "months": len(b)})
    return bt, summary, pd.DataFrame(windows)


def cbo_vintages(gap):
    """What each CBO natural-rate vintage did to u* on the first business day it was in force.

    Vintages are found from the newest ``published`` in force each day, not
    from release dates: some vintages only revise dates already published.
    """
    new = gap["cbo_vintage"] != gap["cbo_vintage"].shift()
    rows = []
    for i in gap.index[new][1:]:
        on, before = gap.loc[i], gap.loc[i - 1]
        rows.append({"vintage": on["cbo_vintage"], "first_day": on["as_of"], "gap_month": on["gap_month"],
                     "u_star_before": before["u_star"], "u_star_after": on["u_star"],
                     "change": on["u_star"] - before["u_star"], "same_month": on["gap_month"] == before["gap_month"]})
    return pd.DataFrame(rows)


def correlations(frame, bench, series):
    """Same-day correlation of each activity z with GDPNow, over the windows §6.4 asks for."""
    df = frame.merge(bench, on="as_of")
    cols = ["activity_z", *[f"{s}_z" for s in series]]
    end = df["as_of"].max()
    windows = {
        f"2021-01 .. {end:%Y-%m}": df["as_of"] >= "2021-01-01",
        f"2022-01 .. {end:%Y-%m}": df["as_of"] >= "2022-01-01",
        f"2022-01 .. {end:%Y-%m}, ex GDPNow {pd.Timestamp(EXCLUDE_QUARTER).to_period('Q')}":
            (df["as_of"] >= "2022-01-01") & (df["gdpnow_quarter"] != pd.Timestamp(EXCLUDE_QUARTER)),
    }
    rows = []
    for label, keep in windows.items():
        d = df[keep]
        rows.append({"window": label, "days": len(d),
                     **{c.removesuffix("_z") if c != "activity_z" else "composite": d[c].corr(d["gdpnow"])
                        for c in cols}})
    return pd.DataFrame(rows)


def checks(frame, panel, spec, as_of):
    """Every section as a named DataFrame, plus a dict of headline numbers."""
    start = frame["as_of"].min()
    bench = benchmarks(frame, panel, spec)
    bt, bridge_summary, windows = bridge_tables(panel, as_of, spec, spec["start"])
    series = spec["activity"]["series"]

    gap = frame.merge(bench, on="as_of")
    gap["u_minus_longer_run"] = gap["u"] - gap["u_longer_run"]
    quarterly = gap.groupby(gap["as_of"].dt.to_period("Q")).head(1)[
        ["as_of", "gap_month", "u", "u_star", "u_gap", "u_longer_run", "u_minus_longer_run"]]

    last = frame.iloc[-1]
    headline = {
        "fed_business_days": len(frame),
        "first": start, "last": frame["as_of"].max(),
        "n_bridged": frame["n_bridged"].value_counts().sort_index().to_dict(),
        "activity_n": frame["activity_n"].value_counts().sort_index().to_dict(),
        "bridge_rmse_pp": bridge_summary["rmse_pp"].iloc[0],
        "latest": last,
    }
    tables = {
        "Bridge backtest: real-time error against PCE's first print, pp m/m": bridge_summary,
        "Bridge window sensitivity (reported once, not tuned)": windows,
        "Bridged months across the October 2025 CPI hole, and the last 12": pd.concat(
            [bt[bt["across_hole"]], bt.tail(12)]).drop_duplicates("month").sort_values("month"),
        "The gap on the first business day of each quarter: CBO and the SEP longer-run median": quarterly,
        "CBO natural-rate vintages: u* for the gap's quarter the business day before and the first day in force":
            cbo_vintages(gap),
        "Activity z against GDPNow, same-day correlation": correlations(frame, bench, series),
    }
    return headline, tables, gap


def markdown(ccy, headline, tables):
    h, last = headline, headline["latest"]
    lines = [
        f"# Macro nowcast: {ccy}",
        "",
        f"Generated by `scripts/build_nowcast.py` for {h['first']:%Y-%m-%d} .. {h['last']:%Y-%m-%d}. "
        "Do not edit by hand. Publication lags and the revision calendar are in "
        f"[vintages_{ccy}.md](vintages_{ccy}.md).",
        "",
        f"- Fed business days: {h['fed_business_days']}, every one solved (a failure stops the build)",
        f"- Months of core PCE bridged from core CPI, days by count: {h['n_bridged']}",
        f"- Activity series in the composite, days by count: {h['activity_n']}",
        f"- Bridge RMSE: **{h['bridge_rmse_pp']:.3f}pp m/m**, real time, against first prints",
        f"- Latest ({last['as_of']:%Y-%m-%d}): core PCE 12m {last['infl_12m']:.2f}% to {last['infl_month']:%Y-%m} "
        f"({last['n_bridged']} bridged), u - u* {last['u_gap']:+.2f}pp ({last['gap_month']:%Y-%m}), "
        f"activity z {last['activity_z']:+.2f} for {last['activity_quarter'].to_period('Q')}",
        "",
        "The composite is a diagnostic; the rule's activity input is the unemployment gap. Since 2022 "
        "GDPNow has moved on net exports, inventories and (2025Q1) gold imports, which none of the four "
        "monthly series sees, so the post-2022 correlation is weak or negative. The weights are equal "
        "and fixed ex ante, not fitted to it.",
        "",
    ]
    for title, df in tables.items():
        if title.startswith("Bridge"):   # errors of a few hundredths: two decimals would hide them
            df = df.apply(lambda c: c.map("{:.3f}".format) if c.dtype == float else c)
        lines += [f"## {title}", ""]
        lines += [table(df) if len(df) else "None.", ""]
    return "\n".join(lines)


def figure(gap, path, theme="light"):
    """Core PCE 12m and the unemployment gap, both as read on each day."""
    t = _style(theme)
    fig, (top, bottom) = plt.subplots(2, 1, figsize=(11, 7), sharex=True, gridspec_kw={"hspace": 0.35})
    top.axhline(2, color=t["axis"], lw=1)
    top.plot(gap["as_of"], gap["infl_12m"], color=t["series"][0], lw=1.8, label="Core PCE, 12m (bridged)")
    top.set_ylabel("%")
    top.legend(loc="upper right", fontsize=9, labelcolor=t["secondary"])
    _title(top, "Core PCE inflation as it could be read each day",
           "12-month rate to the latest month core CPI has; months PCE has not printed yet bridged from CPI.", t)
    bottom.axhline(0, color=t["axis"], lw=1)
    for day in cbo_vintages(gap)["first_day"]:
        bottom.axvline(day, color=t["muted"], lw=0.8, ls=":")
    bottom.plot(gap["as_of"], gap["u_gap"], color=t["series"][0], lw=1.8, label="u - u*, CBO (the input)")
    bottom.plot(gap["as_of"], gap["u_minus_longer_run"], color=t["series"][1], lw=1.2,
                label="u - SEP longer-run median (sensitivity)")
    bottom.set_ylabel("pp")
    bottom.legend(loc="upper right", fontsize=9, labelcolor=t["secondary"])
    _title(bottom, "The unemployment gap, positive = slack", "Both natural rates from the vintage of the day. Dotted: a new CBO vintage.", t)
    for ax in (top, bottom):
        ax.xaxis.set_major_locator(mdates.YearLocator())
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
        ax.tick_params(axis="both", length=0)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def write_figures(gap, out_dir, ccy):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for theme in THEMES:
        p = out_dir / f"nowcast_{ccy}_{theme}.png"
        figure(gap, p, theme)
        written.append(p)
    return written
