"""reports/numbers.md: every number the note quotes, each with the report line that prints it.

Reads only what the build scripts have already written: reports/results/*.json
and the markdown reports beside it. It needs no data and no strategy chain, so
it runs in well under a second. Each value is formatted from the JSON (or
parsed from a report that has no JSON), then looked up in the report that
prints it. If the report does not print it, the build stops. A report
regenerated without its JSON, or the other way round, cannot pass silently.

A few numbers no build script computes: a one-off study, a hand check, a
statement about a test. They are listed as static, with the README or
DECISIONS line that records them. That line must still exist, or the build
stops too.
"""

from dataclasses import dataclass
import json
from pathlib import Path
import re
from policypath.report.costs import pct, sr
from policypath.report.portfolio import pc

HEADER = ("Generated by `scripts/build_numbers.py` from `reports/results/*.json` and the reports beside it. "
          "Do not edit by hand: rebuild after any build script runs.")


@dataclass
class Row:
    item: str
    value: str
    source: str
    sample: str = ""


class Reports:
    """The generated reports under repo `root`, read once each, with line lookups that stop the build on a miss."""

    def __init__(self, root):
        self.root = Path(root)
        self._text = {}

    def text(self, rel):
        if rel not in self._text:
            self._text[rel] = (self.root / rel).read_text(encoding="utf-8").splitlines()
        return self._text[rel]

    def json(self, name):
        return json.loads((self.root / "reports" / "results" / f"{name}.json").read_text(encoding="utf-8"))

    def _span(self, rel, section):
        lines = self.text(rel)
        if section is None:
            return 0, len(lines)
        start = next((i for i, l in enumerate(lines) if l.startswith("#") and l.lstrip("#").strip() == section), None)
        if start is None:
            raise ValueError(f"{rel}: no section '{section}'")
        end = next((i for i in range(start + 1, len(lines)) if re.match(r"#{1,%d} " % _depth(lines[start]), lines[i])),
                   len(lines))
        return start, end

    def line(self, rel, *needles, section=None):
        """The 1-based number of the first line in `rel` (within `section`, a heading's text) holding every needle."""
        lo, hi = self._span(rel, section)
        for i in range(lo, hi):
            if all(n in self.text(rel)[i] for n in needles):
                return i + 1
        where = f" under '{section}'" if section else ""
        raise ValueError(f"{rel}{where}: no line prints {' and '.join(repr(n) for n in needles)}")

    def grab(self, rel, pattern, section=None):
        """(the match, its 1-based line) for the first line in `rel` matching `pattern`."""
        lo, hi = self._span(rel, section)
        for i in range(lo, hi):
            m = re.search(pattern, self.text(rel)[i])
            if m:
                return m, i + 1
        raise ValueError(f"{rel}: no line matches {pattern!r}")

    def cite(self, rel, *needles, section=None):
        return link(rel, self.line(rel, *needles, section=section))


def _depth(heading):
    return len(heading) - len(heading.lstrip("#"))


def link(rel, n):
    """A markdown link to line `n` of repo-relative `rel`, written from reports/numbers.md."""
    name = Path(rel).name
    href = name if rel.startswith("reports/") else f"../{rel}"
    return f"[{name}:{n}]({href}:{n})"


def bp(x):
    return f"{x:+.0f}"


def thousands(x):
    return f"{x / 1000:.0f}k"


METRICS, ROBUST = "reports/metrics.md", "reports/robustness.md"


# ---- the sections -------------------------------------------------------------------

def sample(r):
    m = r.json("metrics")
    book = _perf(m)["book"]
    first = m["first_counted"]
    trades = {p["name"]: p["trades"] for p in m["performance"]}
    entries = {s: v["entries"] for s, v in m["filter"].items()}
    late = {s: entries[s] - trades[s] for s in entries if entries[s] != trades[s]}
    note = ("An entry is decided at a close and becomes a trade from the next session. "
            + ("Entries the rule made at a close whose trade has not started yet: "
               + ", ".join(f"{s} {k}" for s, k in late.items()) + "." if late else "Every entry is a trade."))
    return [
        Row("Book sample", f"{book['first']} to {book['last']}, {book['sessions']:,} sessions, {book['years']:.1f} years",
            r.cite(METRICS, f"counted from {first}"),
            f"The book runs from {m['days'][0]}; sessions count from {first}."),
        Row("Trades, book", f"{trades['book']}", r.cite(METRICS, "| book |", section="Performance"),
            "A run of one side, from the close that opens it. By sleeve: "
            + ", ".join(f"{s} {t}" for s, t in trades.items() if s != "book") + "."),
        Row("Entries, book (the carry filter's count)", f"{sum(entries.values())}",
            r.cite(METRICS, f"of the rule's {sum(entries.values())} entries"), note),
    ]


def definitions(r):
    usd_sep, n1 = r.grab("reports/model_USD.md", r"Sessions before the first SEP \(r\* = Taylor's 2%\): (\d+)")
    gbp_r, n2 = r.grab("reports/model_GBP.md", r"r\* is a constant ([-+]?\d+\.\d+)%")
    hind, n3 = r.grab("reports/nowcast_GBP.md", r"r\* is a constant \(([-+]?\d+\.\d+)%, (the [^)]+)\): a hindsight number")
    spec = r.json("metrics")["spec"]
    return [
        Row("USD r*", f"SEP longer-run median; Taylor's 2% before the first SEP ({usd_sep[1]} sessions)",
            link("reports/model_USD.md", n1), "From the SEP, not ALFRED. ALFRED supplies the macro vintages."),
        Row("GBP r*", f"Constant {gbp_r[1]}%, {hind[2]}", f"{link('reports/model_GBP.md', n2)}, "
            f"{link('reports/nowcast_GBP.md', n3)}", "A hindsight number. It moves the bp gap, not the z."),
        Row("Trading rule", f"{spec['rule']} (enter {spec['enter']:g}, exit {spec['exit']:g}), "
            f"{'flat' if spec['treatment'] == 'flat' else spec['treatment']} at the ELB",
            r.cite(METRICS, f"hysteresis ({spec['enter']:g}, {spec['exit']:g})"),
            "Inverse-vol, shrunk covariance, 5% vol target, no drawdown control."),
    ]


def construction(r):
    cov, cu = "reports/coverage_USD.md", "reports/coverage_GBP.md"
    us, n_us = r.grab(cov, r"Sessions in the panel: (\d+) \(solved \d+, failed (\d+)\)")
    us_cov, n_uc = r.grab(cov, r"\*\*Coverage: ([\d.]+%)\*\*")
    miss, n_m = r.grab(cov, r"^## Fed business days missing from the panel \((\d+)\)")
    span_us, n_su = r.grab(cov, r"for (\d{4}-\d\d-\d\d) \.\. (\d{4}-\d\d-\d\d)")
    gb, n_gb = r.grab(cu, r"Sessions in the panel: (\d+) \(solved \d+, failed (\d+)\)")
    span_gb, n_sg = r.grab(cu, r"for (\d{4}-\d\d-\d\d) \.\. (\d{4}-\d\d-\d\d)")
    sofr = "reports/sofr_check_USD.md"
    s1, n_s1 = r.grab(sofr, r"Sessions: (\d+) \((\S+) \.\. (\S+)\)")
    s2, n_s2 = r.grab(sofr, r"mean ([-+][\d.]+bp), mean absolute ([\d.]+bp), within 3bp on (\d+%)")
    mpr = "reports/mpr_check_GBP.md"
    m1, n_m1 = r.grab(mpr, r"Reports compared: (\d+), (\d+) quarters")
    m2, n_m2 = r.grab(mpr, r"mean difference ([-+]?[\d.]+bp), mean absolute ([\d.]+bp), worst ([\d.]+bp)")
    m3, n_m3 = r.grab(mpr, r"correlates ([-+]?[\d.]+) with the move priced inside the quarter")
    reports = [l.split("|")[1].strip() for l in r.text(mpr)[slice(*r._span(mpr, "By report"))]
               if l.startswith("| ") and not l.startswith("| report") and not l.startswith("| ---")]
    mu, n_mu = r.grab("reports/model_USD.md", r"with a model path: (\d+)")
    fu, n_fu = r.grab("reports/model_USD.md", r"the model sits on the floor: (\d+)")
    mg, n_mg = r.grab("reports/model_GBP.md", r"with a model path: (\d+)")
    fg, n_fg = r.grab("reports/model_GBP.md", r"the model sits on the floor: (\d+)")
    zu, n_zu = r.grab("reports/model_USD.md", r"First z at k = 4: (\S+) \((two-year trailing window[^)]*)\)")
    zg, n_zg = r.grab("reports/model_GBP.md", r"First z at k = 4: (\S+)")
    now = "reports/nowcast_USD.md"
    start, n_ns = r.grab(now, r"for (\d{4}-\d\d-\d\d) \.\.")
    rmse, n_r = r.grab(now, r"Bridge RMSE: \*\*([\d.]+pp m/m)\*\*")
    fit, n_f = r.grab(now, r"^\| bridge \((\d+)-month fit\) \| ([\d.]+) \| [\d.]+ \| ([\d.]+) \| (\d+) \|")
    nrou, n_v = r.grab("reports/vintages_USD.md", r"^\| NROU \|(?:[^|]*\|){5} (\d{4}-\d\d-\d\d) \|")
    return [
        Row("ZQ: sessions with a market path", f"{int(us[1]):,}, {us[2]} solver failures",
            link(cov, n_us), f"{span_us[1]} to {span_us[2]} ({link(cov, n_su)})"),
        Row("ZQ: coverage", f"{us_cov[1]} of Fed business days; {miss[1]} missing",
            f"{link(cov, n_uc)}, {link(cov, n_m)}", "Missing days are listed in the coverage report."),
        Row("ZQ: front-contract pinning (static)", "Error in the implied step: mean 5.8bp → 0.5bp, worst 34bp → 1.6bp",
            f"{r.cite('README.md', '5.8bp mean')}, {r.cite('notes/DECISIONS.md', '5.8bp mean')}",
            "A one-off study, measured against the actual decision on 46 announcement days since 2021."),
        Row("ZQ: SR1 cross-check", f"Implied minus later-realized SOFR - EFFR basis: mean {s2[1]}, "
            f"mean absolute {s2[2]}, within 3bp on {s2[3]}", f"{link(sofr, n_s1)}, {link(sofr, n_s2)}",
            f"{int(s1[1]):,} sessions, {s1[2]} to {s1[3]}"),
        Row("ZQ: FedWatch (static)", "No historical comparison: FedWatch publishes no history",
            r.cite("README.md", "FedWatch publishes no history"), "Captures go forward only."),
        Row("BoE OIS: sessions with a market path", f"{int(gb[1]):,}, {gb[2]} solver failures",
            link(cu, n_gb), f"{span_gb[1]} to {span_gb[2]} ({link(cu, n_sg)})"),
        Row("MPR conditioning-path check", f"Mean absolute difference {m2[2]}; mean signed {m2[1]}; worst {m2[3]}",
            f"{link(mpr, n_m1)}, {link(mpr, n_m2)}",
            f"{m1[1]} reports, {reports[0]} to {reports[-1]}, {m1[2]} quarters inside the eight-meeting path"),
        Row("MPR: why the differences have a sign", f"They correlate {m3[1]} with the move priced inside the quarter",
            link(mpr, n_m3), "The Bank averages a smooth spline; the path is a step."),
        Row("USD model path", f"{int(mu[1]):,} sessions, {int(fu[1]):,} on the floor",
            f"{link('reports/model_USD.md', n_mu)}, {link('reports/model_USD.md', n_fu)}", ""),
        Row("GBP model path", f"{int(mg[1]):,} sessions, {int(fg[1]):,} on the floor",
            f"{link('reports/model_GBP.md', n_mg)}, {link('reports/model_GBP.md', n_fg)}", ""),
        Row("Why the USD sample starts when it does", f"Nowcast from {start[1]}; CBO natural-rate (NROU) vintages "
            f"from {nrou[1]}", f"{link(now, n_ns)}, {link('reports/vintages_USD.md', n_v)}",
            "The first day every input has an ALFRED vintage."),
        Row("CPI-to-PCE bridge", f"RMSE {rmse[1]}, MAE {fit[3]}pp", f"{link(now, n_r)}, {link(now, n_f)}",
            f"Real time, against PCE's first print, {fit[4]} months, {fit[1]}-month fit window"),
        Row("No-lookahead test (static)", "The whole chain on inputs truncated at D; everything after D poisoned",
            r.cite("README.md", "tests/test_no_lookahead.py"), "Runs per currency."),
        Row("z", f"Gap at meeting 4 against its {zu[2]}", f"{link('reports/model_USD.md', n_zu)}",
            f"First z: USD {zu[1]}, GBP {zg[1]} ({link('reports/model_GBP.md', n_zg)})"),
    ]


def level(r):
    lg = r.json("metrics")["level_gap"]
    rows = []
    for ccy in ("USD", "GBP"):
        g = lg[ccy]
        years = {int(y): v for y, v in g["years"].items()}
        below = [y for y, v in years.items() if v < 0]
        lo, hi = min(years, key=years.get), max(years, key=years.get)
        above = [y for y in sorted(years) if years[y] > 0]
        tail = sorted(years)[-len(above):] == above if above else False
        extra = f" Above from {above[0]}: " + ", ".join(bp(years[y]) for y in above) + "." if above and tail else ""
        rows.append(Row(f"{ccy} below the rule at meeting {g['k'][1]}",
                        f"{len(below)} of {len(years)} years, {bp(years[lo])}bp ({lo}) to {bp(years[hi])}bp ({hi})",
                        r.cite(METRICS, f"| {lo} |", bp(years[lo]), section="The level the z removes"),
                        f"{min(years)} to {max(years)}, outside the ELB state, years with 60 or more sessions. "
                        f"r* {g['rstar']}.{extra}"))
        rows.append(Row(f"{ccy} by regime, meeting {g['k'][1]}",
                        ", ".join(f"{x['regime']} {bp(x['mean'][str(g['k'][1])])}bp ({x['sessions']:,})"
                                  for x in g["regimes"]),
                        r.cite(METRICS, f"| {ccy} | {g['regimes'][0]['regime']} |", section="The level the z removes"),
                        "Mean gap, market minus rule; sessions in brackets."))
    return rows


def ic_table(r):
    m = r.json("metrics")["ic"]
    out = []
    for s, v in m.items():
        rows = {x["h"]: x for x in v["rate"]["ex_elb"]}
        cells = [f"{rows[h]['ic']:+.3f} ({rows[h]['t']:+.1f})" for h in sorted(rows)]
        h21 = rows[21]
        line = r.line(METRICS, f"| {s} | rate | outside the ELB |", *cells, section="The IC")
        out.append([s, *cells, f"{h21['sessions']:,}", f"{h21['offsets_sessions']:,}",
                    f"{abs(h21['ic'] / h21['t']):.3f}",
                    f"{h21['offsets_mean']:+.3f} [{h21['offsets_min']:+.2f}, {h21['offsets_max']:+.2f}]",
                    link(METRICS, line)])
    return out


def _perf(m):
    return {p["name"]: p for p in m["performance"]}


def performance(r):
    m = r.json("metrics")
    out = []
    for p in m["performance"]:
        cells = [sr(p["gross_sr"], p["gross_se"]), sr(p["net_sr"], p["net_se"]), pc(p["net_year"]),
                 sr(p["ex_2022"]["net_sr"], p["ex_2022"]["net_se"]),
                 sr(p["ex_2022_23"]["net_sr"], p["ex_2022_23"]["net_se"])]
        out.append([p["name"], *cells, r.cite(METRICS, f"| {p['name']} |", *cells, section="Performance")])
    return out


def signal_notes(r):
    m = r.json("metrics")
    book, dd, lv = _perf(m)["book"], m["drawdown"], m["level"]
    gbp = next(x for x in m["regimes"]["sleeves"]["GBP outright"]["rows"] if x["regime"] == "hiking")
    gbp_cell = f"{gbp['net_sr']:+.2f} ({gbp['sessions']:,}; {gbp['trades']})"
    return [
        Row("Book: gross a year, vol", f"{pc(book['gross_year'])} of capital gross, {book['vol']:.1f}% vol",
            r.cite(METRICS, f"Of its gross {pc(book['gross_year'])} of capital a year")),
        Row("Worst drawdown", f"{dd['depth']:.1f}% of capital, {dd['peak'][:7]} to {dd['trough'][:7]} "
            f"({dd['years']:.1f} years); worst 21-session loss {dd['worst_month']:.1f}%",
            r.cite(METRICS, f"{dd['depth']:.1f}% of capital", f"{dd['worst_month']:.1f}%")),
        Row("Level share of risk", f"{pct(lv['variance_share'])} of the variance of daily gross P&L",
            r.cite(METRICS, f"{pct(lv['variance_share'])} of the variance"), "DECISIONS A4."),
        Row("GBP outright when hiking", f"Net SR {sr(gbp['net_sr'], gbp['net_se'])}, {gbp['sessions']:,} sessions, "
            f"{gbp['trades']} trades", r.cite(METRICS, "| GBP outright | GBP |", gbp_cell, section="By regime"),
            "Where the only positive sleeve earns."),
    ]


def costs(r):
    m = r.json("metrics")
    c = {x["name"]: x for x in m["costs"]}
    b = c["book"]
    comp = next(x for x in m["components"] if x["group"] == "book")
    roll, restrike = b["cost"]["roll"], b["cost"]["restrike"]
    saving = roll / 2
    shares = ", ".join(f"{n} {pct(x['maintenance'])}" for n, x in c.items() if n != "book")
    turns = b["turns"]
    return [
        Row("Reconciliation", f"{b['turns_year']:.1f} turns × {thousands(b['mean_dv01'])} mean gross DV01 × "
            f"{b['one_way_bp']:.2f}bp one way = {b['cost_year']:.2f}% of capital a year",
            r.cite(METRICS, "| book |", f"{b['cost_year']:.2f}%", section="Where the costs go"),
            f"DV01 over {b['legs']} legs, on sessions with a position; a round trip is 2 turns."),
        Row("Turns by cause, book", f"entries and exits {turns['signal']:.1f}, resizing {turns['resize']:.1f}, "
            f"rescaling {turns['rescale']:.1f}, rolls {turns['roll']:.1f}, re-strikes {turns['restrike']:.1f}",
            r.cite(METRICS, "| book |", f"{turns['roll']:.1f}", section="Where the costs go")),
        Row("Maintenance share", f"{pct(b['maintenance'])} of cost", r.cite(METRICS, f"{pct(b['maintenance'])} of it is"
            " maintenance"), f"Rolls plus re-strikes, weighted by each sleeve's cost. By sleeve: {shares}."),
        Row("Rolls, the part meeting N+4 forces", f"{roll:.2f}% of capital a year, {pct(roll / b['cost_year'])} of cost",
            "metrics.json costs[book].cost.roll", "The outrights move to the new instrument as each meeting passes."),
        Row("Re-strikes, the par legs", f"{restrike:.2f}% of capital a year, {pct(restrike / b['cost_year'])} of cost",
            "metrics.json costs[book].cost.restrike", "Quarterly, from marking a constant-maturity bond."),
        Row("USD outright's rolls", f"{c['USD outright']['cost']['roll']:.2f}% a year",
            r.cite(METRICS, f"the most USD outright's, {c['USD outright']['cost']['roll']:.2f}% a year")),
        Row("Calendar-spread sensitivity", f"Rolls at half price save {saving:.1f}% a year: net "
            f"{pc(comp['net'])} → {pc(comp['net'] + saving)}; gross stays {pc(comp['gross'])}",
            "metrics.json costs[book].cost.roll / 2",
            "Rolls are charged as two outright one-ways, the conservative end. Gross is before costs, so no cost "
            "treatment moves it."),
        Row("Hand check (static)", "USD outright 2018, contract by contract: 58,462 contracts, $1,276,426, the cost "
            "charged to the dollar", r.cite("notes/DECISIONS.md", "1,276,426"),
            "Done 2026-09-29, before the 2026-09-30 regeneration. It's not in any report."),
    ]


def breakeven(r):
    m = r.json("metrics")
    comp = next(x for x in m["components"] if x["group"] == "book")
    need = comp["cost"] - comp["carry_roll"]
    rows = [Row("Rate change earned against needed", f"{pc(comp['rate'])} a year against {pc(need)}: "
                f"{need / comp['rate']:.1f} times", r.cite(METRICS, f"{need / comp['rate']:.1f} times as much")),
            Row("Carry and roll against rate, book", f"carry and roll {pc(comp['carry_roll'])}, rate {pc(comp['rate'])}",
                r.cite(METRICS, f"carry and roll are {pc(comp['carry_roll'])}"))]
    cells = []
    for s in m["carry_sleeves"]["sleeves"]:
        clears = " (clears)" if s["rho"] >= s["rho_star"] else ""
        cells.append(f"{s['sleeve']} {s['rho']:+.3f} against {s['rho_star']:+.3f}{clears}")
    first = m["carry_sleeves"]["sleeves"][0]
    rows.append(Row("ρ held against ρ* needed, per sleeve", "; ".join(cells),
                    r.cite(METRICS, f"{first['sleeve']} {first['rho']:+.3f} against {first['rho_star']:+.3f}"),
                    "Clears when ρ ≥ ρ*."))
    return rows


def carry_filter(r):
    m, rob = r.json("metrics"), r.json("robustness")
    f = m["filter"]
    skipped, entries = sum(v["skipped"] for v in f.values()), sum(v["entries"] for v in f.values())
    row, base = rob["rows"]["carry_filter"], rob["rows"]["baseline"]
    off, on = base["net"]["book"]["sr"], row["net"]["book"]["sr"]
    change, se = row["change"]["book"], row["paired_se"]["book"]
    own = row["own"]["book"]
    common = rob["sample"]["book"]
    return [
        Row("Entries skipped", f"{skipped} of {entries} ({pct(skipped / entries)}): "
            + ", ".join(f"{s} {v['skipped']} of {v['entries']}" for s, v in f.items()),
            r.cite(METRICS, f"skip {skipped} of the rule's {entries} entries")),
        Row("Effect on the book, common sample", f"net {off:+.2f} → {on:+.2f} ({change:+.2f}, paired SE {se:.2f})",
            r.cite(ROBUST, "**carry filter**", f"on {on:+.2f} ({change:+.2f}, paired SE {se:.2f})"),
            f"The grid's common sample: {common['sessions']:,} sessions from {common['first']}."),
        Row("Effect on the book, its own sample", f"net {sr(own['sr'], own['se'])}",
            r.cite(ROBUST, "| carry filter: on |", sr(own["sr"], own["se"])), f"{own['sessions']:,} sessions"),
    ]


def robustness(r):
    rob = r.json("robustness")
    rows = rob["rows"]
    base = rows["baseline"]["net"]["book"]
    best = max((x for k, x in rows.items() if k != "baseline"), key=lambda x: x["net"]["book"]["sr"])
    move = max((x for k, x in rows.items() if k != "baseline"), key=lambda x: abs(x["net"]["book"]["sr"] - base["sr"]))
    hlw = rows["usd_rstar_hlw"]["own"]["book"]
    return [
        Row("Every row loses net", f"best row {best['choice']}: {best['label']}, {best['net']['book']['sr']:+.2f}; "
            f"largest move {move['choice']}: {move['label']}, {move['net']['book']['sr'] - base['sr']:+.3f} against "
            f"one SE {base['se']:.3f}", r.cite(ROBUST, "every row loses money net", f"one SE ({base['se']:.2f})"),
            f"{len(rows) - 1} rows, one choice at a time, common sample"),
        Row("HLW real-time r* (USD)", f"net {sr(hlw['sr'], hlw['se'])}",
            r.cite(ROBUST, "| r* (USD): HLW, real time |", sr(hlw["sr"], hlw["se"])), f"{hlw['sessions']:,} sessions"),
    ]


def runs(r):
    """Each report's generated line: which run its numbers come from."""
    out = []
    for p in sorted((r.root / "reports").glob("*.md")):
        rel = f"reports/{p.name}"
        if p.name == "numbers.md":
            continue
        m = next(((i + 1, l) for i, l in enumerate(r.text(rel)) if l.startswith("Generated by")), None)
        if m:
            spans = [re.search(r"\d{4}-\d\d-\d\d \.\. \d{4}-\d\d-\d\d", l) for l in r.text(rel)[:12]]
            out.append([link(rel, m[0]), next((s[0] for s in spans if s), "")])
    return out


# ---- the page ----------------------------------------------------------------------

def table(rows):
    lines = ["| Item | Value | Source | Sample / definition |", "|---|---|---|---|"]
    lines += [f"| {x.item} | {x.value} | {x.source} | {x.sample} |" for x in rows]
    return "\n".join(lines)


def grid(head, rows):
    return "\n".join([f"| {' | '.join(head)} |", "|" + "---|" * len(head)] + [f"| {' | '.join(x)} |" for x in rows])


def markdown(root):
    r = Reports(root)
    parts = [
        "# Numbers for the note", "", HEADER, "",
        "Every value below is formatted from the JSON or a generated report and found again in the report line it "
        "links to. Static rows are not computed by any build; they link to the line that records them.", "",
        "## Sample", "", table(sample(r)), "",
        "## Definitions", "", table(definitions(r)), "",
        "## Construction", "", table(construction(r)), "",
        "## The level", "", table(level(r)), "",
        "## The signal: IC of z against the next h sessions' rate change, outside the ELB", "",
        grid(["Sleeve", "IC(5) (t)", "IC(21) (t)", "IC(63) (t)", "Sessions (21)", "Non-overlapping windows (21)",
              "Implied SE (21)", "Non-overlapping IC(21) [range]", "Source"], ic_table(r)), "",
        "The t is Newey-West, Bartlett weights to lag h. A persistent z keeps the products autocorrelated past h, so "
        "the t overstates the precision. The implied SE is |IC / t|.", "",
        "## Performance: net Sharpe (SE), net of costs", "",
        grid(["", "Gross SR", "Net SR", "Net a year", "Ex-2022", "Ex-2022-23", "Source"], performance(r)), "",
        table(signal_notes(r)), "",
        "## Costs", "", table(costs(r)), "",
        "## Breakeven", "", table(breakeven(r)), "",
        "## Carry filter", "", table(carry_filter(r)), "",
        "## Robustness", "", table(robustness(r)), "",
        "## Runs: the span each report was generated for", "", grid(["Report", "Span"], runs(r)), "",
    ]
    return "\n".join(parts)


def write(root):
    """reports/numbers.md under repo `root`. Returns its path."""
    out = Path(root) / "reports" / "numbers.md"
    out.write_text(markdown(root), encoding="utf-8")
    return out
