"""The portfolio report: what the book earns net of costs, how fragile that is, and what carries it.

Generated by `scripts/build_portfolio.py`, never hand-edited: every number
comes from the books run here, and every sentence is a template filled from
them. The answer comes first: what the book earns net, how fragile that is
(the cost curve and its breakeven, week 8's closed form), and what carries it
(the sleeves and the years).

**What is run.** Week 8's sleeves, unchanged: their legs, unit P&L, rules
(``positions.rule`` at (``positions.enter``, ``positions.exit``)), ELB
treatment (``evaluation.elb.chosen``) and costs (`report/costs.py`'s
`inputs`, built once). The book (`strategy/portfolio.py`) sizes their sides
together; `simulate` hands each sleeve the positions decided at the book's
closes, runs it through `expression.run` and `costs.traded` (the week 7 and 8
seams, so marks, instruments and costs are theirs to the bit), and credits
its flows to the book calendar. A book is a `Choice`: the construction, the
sleeves (all, or the RV-only book of the curve and cross sleeves), shrinkage
on or off, the drawdown overlay on or off. The headline (`headline`) is the
configured construction (``portfolio.headline``, inverse-vol, proposed),
shrunk, every sleeve, no overlay: the book the robustness grid and the cost
curves use.

**The sample.** A book decides from the first close with
``portfolio.min_history`` complete sessions of unit P&L behind it and is
evaluated from the first session a position decided there is held. A book
session counts where any sleeve's treatment counts a session credited to it
(`positions.samples`, as week 8's sum), so under the flat treatment the
sessions every sleeve spends in the ELB state are left out. Sharpe, its SE,
the breakeven and the cost curve are week 8's (`report/costs.py` `stats`,
`curve`), on the book's own daily frame.

**Turnover by cause** (`CAUSES`): a close's trade on a sleeve is an entry or
exit where the sleeve's own side moved, a resize where another sleeve's did
(the active set changed, so every weight moved), a rescale where neither did
(the covariance, the vol target, the cap, the overlay, and for mean-variance
its z), and maintenance where week 8 says so (rolls, re-strikes).

**Comparing two books** (`difference`): they share most of their positions
(daily net P&L correlations 0.91 to 0.997 on the build of 2026-09-29), so a
difference between them is judged against the SE of the difference, paired on
the sessions both count, never a single book's SE, which is 3 to 15 times
larger. Mean-variance's difference from inverse-vol is split into its two
channels by `DIAGONAL`, mean-variance on the covariance's diagonal.

**The drawdown overlay's fixed point** (`run_book`): the state at a close
reads the equity before it, which depends only on the scale at earlier
closes, so the scale path is causal and has one fixed point. It is found by
rerunning the book on the state machine's scale until the scale stops moving
(two rounds on the headline).
"""

from dataclasses import dataclass, replace
import itertools
import json
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath.backtest import metrics
from policypath.backtest.engine import SESSIONS_PER_YEAR
from policypath.report import costs as sleeves
from policypath.report.coverage import table
from policypath.report.expression import _and, _plain
from policypath.report.figures import THEMES, _style
from policypath.strategy import costs, expression, portfolio, positions, risk

RV_KINDS = ("curve", "cross")
CAUSES = ("signal", "resize", "rescale", "roll", "restrike")     # entries and exits, resizing, rescaling, maintenance
FLOWS = ["gross", "cost", "traded", "assumed", "observed_cost", *CAUSES]
CAUSE_WORDS = {"signal": "entries and exits", "resize": "resizing", "rescale": "rescaling", "roll": "rolls",
               "restrike": "re-strikes"}
WORDS = {"inverse_vol": "inverse-vol", "erc": "ERC", "mean_variance": "mean-variance"}
NUMBERS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}
BLOCK = 21      # sessions in the non-overlapping sums a month-horizon realized vol is read from (`block_vol`)
# The reference palette's first five categorical slots, in order, each theme's own steps (validated for adjacent
# pairs on both surfaces; three light steps are under 3:1, so the report's tables are the relief).
CATEGORICAL = {"light": ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4"],
               "dark": ["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181"]}


# ---- what every book shares --------------------------------------------------------

@dataclass
class Setup:
    """Built once: the sleeves' week 8 inputs, the side each decides, and both on the book calendar.

    `side` is {name: the rule's side at each of the sleeve's closes} under the
    book's spec (rule, pair, ELB treatment, carry filter); `g` and `z` are the
    side and z as of each book close; `units` the unit P&L credited to each
    book session (`portfolio.unit_pnl`).
    """
    book: dict
    days: pd.DatetimeIndex
    inputs: dict
    side: dict
    g: pd.DataFrame
    z: pd.DataFrame
    units: pd.DataFrame
    spec: sleeves.Spec


def setup(world=None):
    """The `Setup` from `world` (the real one by default)."""
    world = expression.World() if world is None else world
    book = world.book
    built = expression.build(world)
    inp = {n: sleeves.inputs(s, world, book) for n, s in built.items()}
    return from_inputs(book, sleeves._book_days(world, book), inp)


def from_inputs(book, days, inp):
    """The `Setup` from the sleeves' week 8 `Inputs` ({name: Inputs}) on the book calendar `days`.

    A signal variant (week 9's robustness) replaces each sleeve's component
    (and, where the model moves it, its ELB state) in `inp` and calls this: the
    unit P&L, and so the covariance (`risk_of`), are the baseline's.
    """
    spec = sleeves.chosen(book)
    side = {n: positions.decide(i.sleeve.component["z"], spec.rule, spec.enter, spec.exit, i.state, spec.treatment,
                                i.allow if spec.carry_filter else None) for n, i in inp.items()}
    g = pd.DataFrame({n: portfolio.asof(s, days) for n, s in side.items()}).fillna(0.0)
    z = pd.DataFrame({n: portfolio.asof(i.sleeve.component["z"], days) for n, i in inp.items()})
    units = portfolio.unit_pnl({n: i.u.groupby("session")["total"].sum(min_count=1).reindex(i.sleeve.sessions)
                                for n, i in inp.items()}, days)
    return Setup(book, days, inp, side, g, z, units, spec)


@dataclass
class Risk:
    """One set of sleeves' covariance (`risk.ewma_cov` on their unit P&L), and where their book may first decide.

    `first` is the first book session with ``portfolio.min_history`` complete
    rows of the sleeves' unit P&L before it; `floored` is {shrink: (sd,
    matrices)}, `portfolio.floored`.
    """
    names: list
    cov: risk.Cov
    first: int
    floored: dict


def risk_of(st, names):
    """The `Risk` of sleeves `names` in `st`."""
    r = st.book["risk"]
    cov = risk.ewma_cov(st.units[names], r["ewma_lambda"], r["nonsynchronous_lag"])
    enough = np.flatnonzero(cov.observations >= st.book["portfolio"]["min_history"])
    if not len(enough):
        raise RuntimeError(f"{names}: fewer than portfolio.min_history sessions of unit P&L")
    return Risk(names, cov, int(enough[0]), {k: portfolio.floored(cov, k, r["sigma_floor"]) for k in (True, False)})


# ---- one book ----------------------------------------------------------------------

@dataclass(frozen=True)
class Choice:
    """One book: its construction, sleeves (None: all), shrinkage, the drawdown overlay, and whether the
    construction reads the covariance's correlations (False: its diagonal only, so mean-variance is |z|-weighted
    inverse-vol, the split of mean-variance's difference from inverse-vol into its two channels)."""
    construction: str
    sleeves: tuple | None = None
    shrink: bool = True
    overlay: bool = False
    correlations: bool = True

    def words(self):
        out = [WORDS[self.construction], "shrunk" if self.shrink else "unshrunk"]
        out += [] if self.correlations else ["no correlations"]
        return ", ".join(out + (["drawdown control"] if self.overlay else []))


@dataclass
class Book:
    """One book run: its `Targets`, the positions decided, the overlay's scale, and what it earned.

    `run` is a `report.costs.Run` on the book calendar (the columns `FLOWS`,
    ``kept`` and ``gross_dv01``, book currency), so week 8's `stats` and
    `curve` read it. `parts` is {sleeve: its flows on the book calendar};
    `net_dv01` the book DV01 on after each close, by currency; `credits` the
    sleeve sessions credited to each book session; `episodes` the sessions the
    overlay triggered on.
    """
    choice: Choice
    targets: portfolio.Targets
    decided: pd.DataFrame
    scale: pd.Series
    episodes: list
    run: sleeves.Run
    parts: dict
    net_dv01: pd.DataFrame
    credits: pd.DataFrame
    rounds: int


def limit(book):
    """The gross DV01 cap in book currency per bp (``risk.max_gross_dv01_per_capital`` x capital), or None."""
    x = book["risk"]["max_gross_dv01_per_capital"]
    return None if x is None else x * book["book"]["capital"]


def _legs(st, names):
    return [len(st.inputs[n].sleeve.legs) for n in names]


def target_of(st, rk, choice):
    """The construction's `portfolio.Targets` for `choice` on the sleeves of `rk`."""
    book = st.book
    sd, m = rk.floored[choice.shrink]
    if not choice.correlations:
        m = np.where(np.eye(m.shape[1], dtype=bool)[None], m, 0.0)
    target = book["book"]["vol_target"] * book["book"]["capital"]
    return portfolio.targets(choice.construction, st.g[rk.names], st.z[rk.names], sd, m, _legs(st, rk.names),
                             SESSIONS_PER_YEAR, target, limit(book), rk.first, book["portfolio"]["z_cap"])


def _sleeve(st, name, decided, start):
    """One sleeve's flows by its own session, the book's decisions executed on its calendar, and its levels.

    The position decided at a book close reaches the sleeve at its next own
    session and executes ``lag`` of its sessions later (`expression.run`); a
    close's trade is split by cause: its own side moved (``signal``), another
    sleeve's side moved (``resize``), neither (``rescale``: the covariance, the
    vol target, the cap or the overlay), and maintenance (`costs.traded`).
    """
    i = st.inputs[name]
    s, treatment = i.sleeve, st.spec.treatment
    days = s.sessions
    q = portfolio.asof(decided[name], days).fillna(0.0)
    side = portfolio.asof(st.g[name], days).fillna(0.0)
    others = pd.DataFrame({n: portfolio.asof(st.g[n], days) for n in decided.columns if n != name}, index=days)
    moved = (others.fillna(0.0).diff().fillna(0.0) != 0).any(axis=1).shift(s.lag, fill_value=False).to_numpy()
    legs, sessions = expression.run(s, q, i.u)
    trades = costs.traded(s, legs, side, i.costs)
    per_leg = costs.by_leg(trades)
    rates = costs.configured(i.costs)
    observed = [c.leg for c in i.costs if c.observed]
    rescale = trades["rescale"].sum(axis=1)
    kept, pnl, paid, _ = positions.samples(i.state, treatment, s.lag)
    daily = pd.DataFrame({
        "gross": sessions["pnl"], "cost": costs.charge(trades, rates), "traded": per_leg.sum(axis=1),
        "assumed": per_leg.drop(columns=observed).sum(axis=1),
        "observed_cost": sum((per_leg[leg] * rates[leg] for leg in observed), pd.Series(0.0, index=days)),
        "signal": trades["signal"].sum(axis=1), "resize": rescale.where(moved, 0.0),
        "rescale": rescale.where(~moved, 0.0), "roll": trades["roll"].sum(axis=1),
        "restrike": trades["restrike"].sum(axis=1)}, index=days)
    daily["gross"] = daily["gross"].where(pnl, 0.0)
    daily[FLOWS[1:]] = daily[FLOWS[1:]].where(paid, 0.0, axis=0)
    ccy = {label: leg.ccy for label, _, leg in s.legs}
    on = legs.pivot(index="session", columns="leg", values="q").reindex(days).fillna(0.0)
    held = (sessions["position"].fillna(0.0).abs() * len(s.legs)).where(pnl, 0.0)
    return daily, (kept & (days >= start)), on.T.groupby(ccy).sum().T, held


def simulate(st, rk, choice, tg, scale):
    """The book for `choice` with the targets `tg` scaled by `scale` at each close: a `Book` (no overlay rounds)."""
    book, days = st.book, st.days
    names = rk.names
    legs = _legs(st, names)
    decided = portfolio.band(tg.q.mul(scale, axis=0), book["risk"]["no_trade_band"], legs, limit(book))
    lag = max(st.inputs[n].sleeve.lag for n in names)
    start = days[min(rk.first + lag + 1, len(days) - 1)]
    parts, kept, dv01, held = {}, [], [], []
    for n in names:
        daily, k, on, h = _sleeve(st, n, decided, start)
        parts[n] = portfolio.to_book(daily, days)
        kept.append(portfolio.to_book(k.astype(int), days) > 0)
        dv01.append(pd.DataFrame({c: portfolio.asof(on[c], days) for c in on}).fillna(0.0))
        held.append(portfolio.asof(h, days).fillna(0.0))
    daily = sum(parts.values())
    daily["kept"] = pd.concat(kept, axis=1).any(axis=1) & (days >= start)
    daily["gross_dv01"] = sum(held)
    net = pd.concat(dv01, axis=1).T.groupby(level=0).sum().T
    credited = pd.DataFrame({n: portfolio.credits(st.inputs[n].sleeve.sessions, days) for n in names})
    run = sleeves.Run(choice.words(), None, daily, start, metrics.per_year(days[days >= start]))
    return Book(choice, tg, decided, scale, [], run, parts, net, credited, 1)


def run_book(st, rk, choice, tg=None):
    """One `Book`. With the overlay, the scale is the fixed point of the drawdown state machine on the book's equity.

    The state at a close reads the equity before it, and that equity only the
    scale at earlier closes, so the scale path is causal and its fixed point
    unique: start from 1 everywhere, rerun on the state machine's scale until it
    no longer moves (each round settles at least the first session it changed).
    """
    tg = target_of(st, rk, choice) if tg is None else tg
    ones = pd.Series(1.0, index=st.days)
    b = simulate(st, rk, choice, tg, ones)
    if not choice.overlay:
        return b
    dd = st.book["portfolio"]["drawdown"]
    cap = st.book["book"]["capital"]
    for rounds in range(1, portfolio.OVERLAY_ROUNDS + 1):
        scale, starts = portfolio.overlay(equity(b), cap, dd["trigger"], dd["release"], dd["scale"])
        if np.array_equal(scale.to_numpy(), b.scale.to_numpy()):
            return replace(b, episodes=starts, rounds=rounds)
        b = simulate(st, rk, choice, tg, scale)
    raise RuntimeError(f"the drawdown overlay did not settle in {portfolio.OVERLAY_ROUNDS} rounds")


def equity(b):
    """The book's net equity on the book calendar (book currency): cumulative gross less costs."""
    d = b.run.daily
    return (d["gross"] - d["cost"]).cumsum()


def never_released(b):
    """True when the overlay triggered and its scale stayed below 1 from the first trigger to the last session."""
    if not b.episodes:
        return False
    return bool((b.scale[b.scale.index >= b.episodes[0]] < 1).all())


# ---- the statistics ----------------------------------------------------------------

def kept(b):
    """The book's counted sessions: its daily frame there."""
    return b.run.daily[b.run.daily["kept"]]


def net(b):
    """Net P&L on the counted sessions, book currency."""
    d = kept(b)
    return d["gross"] - d["cost"]


def block_vol(x, periods, h=BLOCK):
    """Realized vol a year from the sums of `x` over consecutive non-overlapping `h`-session blocks (the last,
    incomplete one dropped): sd of the sums x sqrt(periods / h). NaN with fewer than two blocks."""
    k = len(x) // h
    if k < 2:
        return np.nan
    sums = np.asarray(x, dtype=float)[:k * h].reshape(k, h).sum(axis=1)
    return float(sums.std(ddof=1) * np.sqrt(periods / h))


def difference(a, b):
    """Book `a`'s net Sharpe less book `b`'s over the sessions both count, and the SE of that difference.

    Two books over the same sessions share most of their positions, so their
    difference is far less noisy than either Sharpe, and is judged against its
    own SE, not a single book's. Jobson and Korkie's SE with Memmel's (2003)
    correction, iid as `metrics.sharpe_se`: with s_a, s_b the per-session
    Sharpes, rho the correlation of the two daily net P&Ls and n the sessions,
    var = (2 (1 - rho) + (s_a^2 + s_b^2 - 2 s_a s_b rho^2) / 2) / n, annualised by
    the calendar's sessions a year. Where the two books have the same vol it is
    `strategy/robustness.paired_se` to first order (sd(x - x0)^2 / sd(x0)^2 =
    2 (1 - rho) there); unlike it, it is scale-free, so a book at half size (the
    drawdown control) is compared on its Sharpe, not its size.
    """
    ka, kb = a.run.daily["kept"], b.run.daily["kept"].reindex(a.run.daily.index, fill_value=False)
    both = ka & kb
    x = (a.run.daily["gross"] - a.run.daily["cost"])[both]
    y = (b.run.daily["gross"] - b.run.daily["cost"]).reindex(x.index)
    n, per = len(x), a.run.periods
    sx, sy = x.std(ddof=1), y.std(ddof=1)
    if n < 3 or not (sx > 0 and sy > 0):
        return {"diff": np.nan, "se": np.nan, "rho": np.nan, "sessions": n}
    s1, s2 = x.mean() / sx, y.mean() / sy
    rho = float(np.corrcoef(x, y)[0, 1])
    var = (2.0 * (1.0 - rho) + (s1 ** 2 + s2 ** 2 - 2.0 * s1 * s2 * rho ** 2) / 2.0) / n
    return {"diff": float((s1 - s2) * np.sqrt(per)), "se": float(np.sqrt(max(var, 0.0) * per)), "rho": rho,
            "sessions": n}


def window_words(lo, hi):
    """"2022" for a calendar year, "Dec 2021 to Aug 2023" otherwise."""
    if (lo.month, lo.day, hi.month, hi.day) == (1, 1, 12, 31) and lo.year == hi.year:
        return str(lo.year)
    return f"{lo:%b %Y} to {hi:%b %Y}"


def without(b, windows, capital):
    """Each window of `windows` (``evaluation.exclude``, {name: [first, last]}) that holds counted sessions, on the
    book's counted net P&L, the positions not re-run: the net inside and outside it (% of capital, the book and
    each sleeve), the Sharpe with its sessions left out, and the second half's (week 8's `stats` split) likewise."""
    k = b.run.daily["kept"]
    x = net(b)
    per = b.run.periods
    half = len(x) // 2
    out = []
    for name, (lo, hi) in windows.items():
        lo, hi = pd.Timestamp(lo), pd.Timestamp(hi)
        inside = (x.index >= lo) & (x.index <= hi)
        if not inside.any():
            continue
        rest, late = x[~inside], x.iloc[half:][~inside[half:]]
        (sr_, se), (sr2, se2) = sleeves._sharpe(rest, per), sleeves._sharpe(late, per)
        parts = {n: (p["gross"] - p["cost"])[k] for n, p in b.parts.items()}
        out.append({"name": name, "first": lo, "last": hi, "words": window_words(lo, hi),
                    "sessions": int(inside.sum()), "inside_pct": x[inside].sum() / capital * 100,
                    "outside_pct": x[~inside].sum() / capital * 100, "net_sr": sr_, "net_se": se,
                    "second_sr": sr2, "second_se": se2, "second_sessions": len(late),
                    "sleeves_inside_pct": {n: p[inside].sum() / capital * 100 for n, p in parts.items()}})
    return out


def summary(b, capital):
    """Everything the tables print for one book: week 8's `stats` and the book's own numbers, % of capital a year."""
    s = sleeves.stats(b.run)
    d = kept(b)
    x = net(b)
    per = b.run.periods
    active = d["gross_dv01"] > 0
    traded = d["traded"].sum()
    tg = b.targets
    on = tg.exante.reindex(d.index) > 0
    return s | {
        "return_pct": s["net_year"] / capital * 100, "gross_pct": s["gross_year"] / capital * 100,
        "cost_pct": s["cost_year"] / capital * 100,
        "vol_pct": float(x.std() * np.sqrt(per) / capital * 100),
        "active_vol_pct": float(x[active].std() * np.sqrt(per) / capital * 100),
        "active_vol_block_pct": block_vol(x[active], per) / capital * 100,
        "exante_pct": float(tg.exante.reindex(d.index)[on].mean() / capital * 100),
        "max_dd_pct": float(portfolio.drawdown(x.cumsum(), capital).max() * 100),
        "first_counted": d.index.min(),
        "shares": {c: d[c].sum() / traded if traded > 0 else np.nan for c in CAUSES},
        "capped": float(tg.capped.reindex(d.index)[on].mean()),
        "flipped": float(tg.flipped.reindex(d.index).to_numpy()[(tg.q.reindex(d.index) != 0).to_numpy()].mean()),
        "episodes": [f"{e:%Y-%m-%d}" for e in b.episodes], "halved": float((b.scale.reindex(d.index) < 1).mean()),
        "rounds": b.rounds,
    }


def by_year(b, capital):
    """Net P&L by year on the counted sessions, % of capital: the book and each sleeve."""
    d = b.run.daily["kept"]
    years = {n: (p["gross"] - p["cost"])[d].groupby(p.index[d].year).sum() / capital * 100 for n, p in b.parts.items()}
    out = pd.DataFrame(years)
    return out.assign(book=out.sum(axis=1))


def vol_by_year(b, capital):
    """By year: sessions counted and with a position, ex-ante and realized vol (% of capital, on those with a
    position; realized from daily P&L and from its `BLOCK`-session sums), the share of them the cap binds on, and
    net P&L."""
    d = kept(b)
    x = d["gross"] - d["cost"]
    active = d["gross_dv01"] > 0
    ex = b.targets.exante.reindex(d.index)
    rows = []
    for y, idx in d.groupby(d.index.year).groups.items():
        a = active[idx]
        on = a[a].index
        rows.append({"year": y, "sessions": len(idx), "with a position": int(a.sum()),
                     "sleeves sized (mean)": (b.targets.q.reindex(on) != 0).sum(axis=1).mean() if len(on) else 0.0,
                     "ex-ante": ex[on].mean() / capital * 100 if len(on) else np.nan,
                     "realized": x[on].std() * np.sqrt(b.run.periods) / capital * 100 if len(on) > 1 else np.nan,
                     "realized, block sums": block_vol(x[on], b.run.periods) / capital * 100,
                     "cap binds": b.targets.capped.reindex(on).mean() if len(on) else np.nan,
                     "net": x[idx].sum() / capital * 100})
    return pd.DataFrame(rows)


def dv01_by_year(b):
    """By year, the headline's mean net DV01 by currency and mean |net| summed over currencies against the mean
    gross, book currency per bp, over the counted sessions with a position."""
    d = kept(b)
    on = d.index[d["gross_dv01"] > 0]
    n = b.net_dv01.reindex(on)
    out = n.groupby(on.year).mean()
    out["|net|"] = n.abs().sum(axis=1).groupby(on.year).mean()
    out["gross"] = d.loc[on, "gross_dv01"].groupby(on.year).mean()
    return out


def cov_by_year(rk, first):
    """By year from the book's first decision: delta (mean, min, max), and the correlation matrix's condition
    number unshrunk and shrunk (median, max)."""
    c = rk.cov
    ok = np.arange(len(c.index)) >= first
    days = c.index[ok]
    cs, cu = risk.condition(c.shrunk[ok]), risk.condition(c.s[ok])
    frame = pd.DataFrame({"delta": c.delta[ok], "shrunk": cs, "unshrunk": cu}, index=days)
    g = frame.groupby(days.year)
    return pd.DataFrame({"delta mean": g["delta"].mean(), "delta min": g["delta"].min(),
                         "delta max": g["delta"].max(), "condition unshrunk (median)": g["unshrunk"].median(),
                         "condition unshrunk (max)": g["unshrunk"].max(), "condition shrunk (median)": g["shrunk"].median(),
                         "condition shrunk (max)": g["shrunk"].max()})


def mean_correlations(rk, first, which="s"):
    """The mean over sessions (from the book's first decision) of the correlation matrix of `which` (s0, s, shrunk)."""
    m = getattr(rk.cov, which)[first:]
    return pd.DataFrame(np.nanmean(risk.correlation(m), axis=0), index=rk.names, columns=rk.names)


def stale(b):
    """Per sleeve, from the book's start: book sessions credited nothing (stale) and credited two or more (catch-up)."""
    c = b.credits[b.credits.index >= b.run.start]
    return pd.DataFrame({"stale": (c == 0).sum(), "catch-up": (c > 1).sum()})


def lag_effect(rk, first):
    """The non-synchronous term in numbers, from the book's first decision.

    Each sleeve's lag-1 autocorrelation (the lag term's diagonal over S0's,
    mean and lowest) and what the term does to its inverse-vol size,
    sqrt(S0_ii / S_ii) = 1 / sqrt(1 + rho) (mean and highest); the sessions
    on which the unweighted form, s0 + s1 + s1', is not positive definite, has
    a variance at or below zero (in all and by sleeve), and is not positive
    definite with each sleeve dropped in turn.
    """
    c = rk.cov
    s0 = c.s0[first:]
    s1 = (c.s[first:] - s0)                       # the Bartlett-weighted lag term, (s1 + s1') / 2
    d0 = np.diagonal(s0, axis1=1, axis2=2)
    rho = np.diagonal(s1, axis1=1, axis2=2) / d0
    size = np.sqrt(d0 / np.diagonal(c.s[first:], axis1=1, axis2=2))
    full = s0 + 2.0 * s1
    ok = ~np.isnan(full).any(axis=(1, 2))
    full = full[ok]
    bad = int((np.linalg.eigvalsh(full)[:, 0] <= 0).sum())
    low = np.diagonal(full, axis1=1, axis2=2) <= 0
    drop = {}
    for i, n in enumerate(rk.names):
        keep = [j for j in range(len(rk.names)) if j != i]
        drop[n] = int((np.linalg.eigvalsh(full[:, keep][:, :, keep])[:, 0] <= 0).sum()) if keep else 0
    return {"rho": dict(zip(rk.names, np.nanmean(rho, axis=0))), "rho_min": dict(zip(rk.names, np.nanmin(rho, axis=0))),
            "size": dict(zip(rk.names, np.nanmean(size, axis=0))), "size_max": dict(zip(rk.names, np.nanmax(size, axis=0))),
            "sessions": int(ok.sum()), "not_pd": bad, "negative_variance": int(low.any(axis=1).sum()),
            "negative_by_sleeve": dict(zip(rk.names, low.sum(axis=0).astype(int).tolist())), "not_pd_without": drop,
            "bartlett_not_pd": int((np.linalg.eigvalsh(c.s[first:][ok])[:, 0] <= 0).sum())}


# ---- the build ---------------------------------------------------------------------

def headline(book):
    """The headline book: the configured construction (proposed), shrunk, every sleeve, no overlay."""
    return Choice(book["portfolio"]["headline"])


def order(book):
    """The constructions, the headline first."""
    h = book["portfolio"]["headline"]
    return [h, *[c for c in book["portfolio"]["constructions"] if c != h]]


@dataclass
class Build:
    """Everything the report says.

    `books` is {Choice: Book}: every construction shrunk and unshrunk, with and
    without the overlay (shrunk), mean-variance on the covariance's diagonal
    (no correlations), and the RV-only headline; `summaries` their `summary`;
    `uncapped` the `summary` of `free`, the headline with the gross DV01 cap
    off; `week8` the week 8 equal-risk sums' `stats` ({sizing: stats}); `rv`
    the RV sleeves.
    """
    setup: Setup
    risks: dict
    books: dict
    summaries: dict
    uncapped: dict
    week8: dict
    rv: tuple
    free: Book | None = None


DIAGONAL = Choice("mean_variance", correlations=False)      # |z|-weighted inverse-vol: mean-variance's |z| channel


def choices(book, rv):
    """Every book the report runs (`Build.books`)."""
    out = []
    for c in order(book):
        out += [Choice(c), Choice(c, shrink=False), Choice(c, overlay=True)]
    out += [DIAGONAL] if DIAGONAL.construction in book["portfolio"]["constructions"] else []
    h = book["portfolio"]["headline"]
    return out + [Choice(h, sleeves=rv), Choice(h, sleeves=rv, overlay=True)]


def build(world=None):
    """Every book the report reads, from `world`'s sleeves (week 8's inputs, built once)."""
    world = expression.World() if world is None else world
    st = setup(world)
    book, capital = st.book, st.book["book"]["capital"]
    names = list(st.inputs)
    rv = tuple(n for n in names if st.inputs[n].sleeve.kind in RV_KINDS)
    risks = {None: risk_of(st, names), rv: risk_of(st, list(rv))}
    made, books = {}, {}
    for ch in choices(book, rv):
        rk = risks[ch.sleeves]
        key = (ch.construction, ch.sleeves, ch.shrink, ch.correlations)
        if key not in made:
            made[key] = target_of(st, rk, ch)
        books[ch] = run_book(st, rk, ch, made[key])
    free = copy_book(book)
    free["risk"]["max_gross_dv01_per_capital"] = None
    loose = replace(st, book=free)
    free_book = run_book(loose, risks[None], headline(book))
    uncapped = summary(free_book, capital)
    week8 = {}
    for sz in positions.SIZING:
        runs = sleeves.run_all(st.inputs, sleeves.chosen(book, sz), book, st.days)
        week8[sz] = sleeves.stats(runs[sleeves.SUM])
    week8["vol_scaled"]["vol_pct"] = sleeves._realized(
        sleeves.run_all(st.inputs, sleeves.chosen(book), book, st.days)[sleeves.SUM], capital)
    b = Build(st, risks, books, {ch: summary(x, capital) for ch, x in books.items()}, uncapped, week8, rv, free_book)
    check(b)
    return b


def copy_book(book):
    """A deep copy of the book config, to vary one key."""
    return json.loads(json.dumps(book))


def check(b, tol=1e-8):
    """Raise if the build's own invariants fail.

    On every book: DV01 traded by cause adds up; nothing is on a session the
    treatment leaves out (flat and exclude); the cap holds on every close; the
    book's P&L is its sleeves'. ERC's risk contributions are equal on every
    session it sizes two or more sleeves, and ERC is inverse-vol where it sizes
    one. A breakeven is its curve's zero. The overlay's scale is its own state
    machine's on the book's equity. Every book on the headline's sleeves counts
    the headline's sessions, so the paired differences between them add up.
    """
    st = b.setup
    cap = limit(st.book)
    base = b.books[headline(st.book)].run.daily["kept"]
    for ch, x in b.books.items():
        d = x.run.daily
        where = ch.words() + ("" if ch.sleeves is None else ", RV only")
        if ch.sleeves is None and not d["kept"].equals(base):
            raise RuntimeError(f"{where}: counts other sessions than the headline, so paired differences do not add up")
        if not np.allclose(d[list(CAUSES)].sum(axis=1), d["traded"], atol=tol):
            raise RuntimeError(f"{where}: DV01 traded by cause does not add up")
        if st.spec.treatment != "hold":
            left = d.loc[~d["kept"] & (d.index >= x.run.start), FLOWS].abs().to_numpy().sum()
            if left > tol:
                raise RuntimeError(f"{where}: {left:g} of P&L or cost on sessions the treatment leaves out")
        if cap is not None:
            legs = np.asarray(_legs(st, list(x.decided.columns)), dtype=float)
            worst = float((x.decided.abs().to_numpy() @ legs).max())
            if worst > cap * (1 + 1e-9):
                raise RuntimeError(f"{where}: gross DV01 {worst:,.0f} over the cap {cap:,.0f}")
        parts = sum(p["gross"] for p in x.parts.values())
        if not np.allclose(parts, d["gross"], atol=tol):
            raise RuntimeError(f"{where}: the book's gross P&L is not its sleeves'")
        s = b.summaries[ch]
        if s["cstar_bp"] is not None and np.isfinite(s["cstar_bp"]) and abs(sleeves.curve(x.run, [s["cstar_bp"]])[0]) > 1e-6:
            raise RuntimeError(f"{where}: the net Sharpe at c* is not 0")
        if ch.overlay:
            dd = st.book["portfolio"]["drawdown"]
            again, _ = portfolio.overlay(equity(x), st.book["book"]["capital"], dd["trigger"], dd["release"], dd["scale"])
            if not np.array_equal(again.to_numpy(), x.scale.to_numpy()):
                raise RuntimeError(f"{where}: the overlay's scale is not its fixed point")
    e, i = b.books[Choice("erc")].targets, b.books[Choice("inverse_vol")].targets
    n = (st.g[e.q.columns] != 0).sum(axis=1)
    sh = e.share[n > 1]
    spread = sh.where(sh > 0).max(axis=1) - sh.where(sh > 0).min(axis=1)
    if spread.max() > 1e-8:
        raise RuntimeError(f"ERC risk contributions differ by {spread.max():.1e}")
    one = n == 1
    rel = ((e.q[one] - i.q[one]).abs().sum(axis=1) / i.q[one].abs().sum(axis=1)).max() if one.any() else 0.0
    if rel > 1e-8:
        raise RuntimeError(f"ERC with one sleeve is not inverse-vol (relative difference {rel:.1e})")


# ---- the words ---------------------------------------------------------------------

sr, cstar, pct = sleeves.sr, sleeves.cstar, sleeves.pct


def pc(x, digits=2):
    """"+1.23%": a signed percent of capital."""
    return "n/a" if pd.isna(x) else f"{x:+.{digits}f}%"


def _verdict(s):
    if not s["net_sr"] > 0:
        return "loses money"
    return "earns, but within two SEs of zero" if s["net_sr"] < 2 * s["net_se"] else "earns"


def gap(d):
    """"-0.15 (paired SE 0.12)": a Sharpe difference and its paired SE (`difference`)."""
    return f"{d['diff']:+.2f} (paired SE {d['se']:.2f})"


def _apart(d, k=1.0):
    """True when a `difference` is at least `k` of its paired SEs."""
    return bool(abs(d["diff"]) >= k * d["se"])


def _constructions_words(b):
    """The constructions bullet: each against the others on the paired SE, and mean-variance's two channels."""
    book = b.setup.book
    h = headline(book)
    hs = b.summaries[h]
    cons = [Choice(c) for c in order(book)]
    others = cons[1:]
    pairs = [(y, x, difference(b.books[y], b.books[x])) for x, y in itertools.combinations(cons, 2)]
    apart = [(x, y) for x, y, d in pairs if _apart(d)]
    far = [(x, y) for x, y, d in pairs if _apart(d, 2.0)]
    title = ("The construction does not change the answer" if not apart else
             "The construction moves the net Sharpe, by less than two paired SEs" if not far else
             "The construction moves the answer")
    both = lambda xy: f"{WORDS[xy[0].construction]} with {WORDS[xy[1].construction]}"
    count = lambda x: "one pair is" if len(x) == 1 else f"{NUMBERS.get(len(x), len(x))} pairs are"
    rhos = [d["rho"] for *_, d in pairs]
    verdict = ("Every pair is within a paired SE of each other." if not apart else
               f"{count(apart).capitalize()} more than a paired SE apart ({_and(both(p) for p in apart)})"
               + ((", not two." if len(apart) == 1 else ", neither by two." if len(apart) == 2 else ", none by two.")
                  if not far else f"; {count(far)} more than two ({_and(both(p) for p in far)})."))
    out = (f"- **{title}.** "
           + _and(f"{WORDS[o.construction]} nets {sr(b.summaries[o]['net_sr'], b.summaries[o]['net_se'])} "
                  f"({sr(b.summaries[o]['gross_sr'])} gross, {b.summaries[o]['turns_year']:.1f} turns a year)"
                  for o in others)
           + f", against the headline's {sr(hs['net_sr'])} ({hs['turns_year']:.1f} turns). The books share most of "
           f"their positions (their daily net P&Ls correlate {min(rhos):.2f} to {max(rhos):.2f}), so a difference is "
           "judged against the SE of the difference on the same sessions, not a single Sharpe's: "
           + _and(f"{WORDS[x.construction]} against {WORDS[y.construction]} {gap(d)}" for x, y, d in pairs)
           + f". {verdict}")
    mv, iv = Choice("mean_variance"), Choice("inverse_vol")
    if DIAGONAL in b.books and mv in b.books and iv in b.books:
        ds, ms, vs = b.summaries[DIAGONAL], b.summaries[mv], b.summaries[iv]
        total, z, corr = (difference(b.books[x], b.books[y]) for x, y in ((mv, iv), (DIAGONAL, iv), (mv, DIAGONAL)))
        out += (f" Mean-variance differs from inverse-vol by its |z| weights and by its correlations. On the diagonal of "
                f"the same Sigma (|z|-weighted inverse-vol) it nets {sr(ds['net_sr'], ds['net_se'])} "
                f"({sr(ds['gross_sr'])} gross, {ds['turns_year']:.1f} turns): of mean-variance's {total['diff']:+.2f} "
                f"against inverse-vol, {gap(z)} is the |z| weights' and {gap(corr)} the correlations'; of its "
                f"{ms['turns_year'] - vs['turns_year']:.1f} extra turns a year, {ds['turns_year'] - vs['turns_year']:.1f} "
                f"are the |z| weights' and {ms['turns_year'] - ds['turns_year']:.1f} the correlations'.")
    return (out + f" Mean-variance puts {pct(b.summaries[mv]['flipped'])} of its active sleeve-sessions on the other "
            "side from their own signal, where the correlations say hedge.") if mv in b.summaries else out


def _carries_words(b):
    """What carries it: the sleeves and the years, and the `evaluation.exclude` window the book earns in, if any."""
    book, capital = b.setup.book, b.setup.book["book"]["capital"]
    hb = b.books[headline(book)]
    years = by_year(hb, capital)
    total = years["book"].sum()
    best = years["book"].idxmax()
    parts = years.drop(columns="book").sum()
    winners = parts[parts > 0]
    ws = without(hb, book["evaluation"]["exclude"], capital)
    win = max(ws, key=lambda w: w["inside_pct"]) if ws else None
    one = win is not None and win["inside_pct"] > 0 >= win["outside_pct"]
    if one:
        title = f"What carries it: {win['words']}"
        where = (f"; the book {pc(total, 1)}, {pc(win['inside_pct'], 1)} of it from {win['words']} and "
                 f"{pc(win['outside_pct'], 1)} outside it")
        sleeve = lambda n, v: (f"{n} {pc(v, 1)} ({pc(win['sleeves_inside_pct'][n], 1)} inside)" if n in winners.index
                               else f"{n} {pc(v, 1)}")
        head = f"Net over the sample, % of capital (for a sleeve that earns, how much of it is from {win['words']}): "
    else:
        title = (f"What carries it: {_and(winners.index) if len(winners) else 'no sleeve'}"
                 f"{', and ' + str(best) if years['book'].max() > 0 else ''}")
        where = f"; the book {pc(total, 1)}"
        sleeve = lambda n, v: f"{n} {pc(v, 1)}"
        head = "Net over the sample, % of capital: "
    return (f"- **{title}.** {head}" + _and(sleeve(n, v) for n, v in parts.sort_values(ascending=False).items())
            + f"{where}. Its best year, {best}, made {pc(years['book'].max(), 1)}; the other {len(years) - 1} years "
            f"{pc(total - years['book'].max(), 1)}. {_losing_years(years['book'])}" + _cost_words(b))


def _halves_words(b):
    """The halves bullet: the two halves against the SE of their difference, and each exclude window left out."""
    book, capital = b.setup.book, b.setup.book["book"]["capital"]
    h = headline(book)
    hs = b.summaries[h]
    halves = hs["halves"]
    d = halves["second_sr"] - halves["first_sr"]
    se = float(np.hypot(halves["first_se"], halves["second_se"]))
    apart = abs(d) > se
    out = (f"- **The two halves {'disagree' if apart else 'agree within an SE'}.** To {halves['split']:%b %Y} the "
           f"headline nets {sr(halves['first_sr'], halves['first_se'])}, after it "
           f"{sr(halves['second_sr'], halves['second_se'])}: a difference of {d:+.2f}, against an SE of {se:.2f} for "
           "two independent halves.")
    n = hs["sessions"]
    ws = [w for w in without(b.books[h], book["evaluation"]["exclude"], capital) if w["second_sessions"] < n - n // 2]
    if not ws:
        return out
    out += (" With each `evaluation.exclude` window's P&L left out (the positions not re-run): "
            + "; ".join(f"without {w['words']} the headline nets {sr(w['net_sr'], w['net_se'])} and its second half "
                        f"{sr(w['second_sr'], w['second_se'])}" for w in ws) + ".")
    w = min(ws, key=lambda w: w["second_sr"])
    if abs(halves["second_sr"]) < halves["second_se"] and w["second_sr"] < -w["second_se"]:
        out += (f" The second half is near zero only with {w['words']} in it: without it, it loses more than an SE "
                f"over {w['second_sessions']:,} sessions.")
    return out


def _vol_words(b):
    """Realized against ex-ante vol: daily and from `BLOCK`-session sums, what the gap is consistent with, and the
    years the cap holds ex-ante under the target."""
    book, capital = b.setup.book, b.setup.book["book"]["capital"]
    h = headline(book)
    hs = b.summaries[h]
    vy = vol_by_year(b.books[h], capital)
    over = vy[vy["realized"] > vy["ex-ante"]]
    above = hs["active_vol_pct"] > hs["exante_pct"]
    blk = hs["active_vol_block_pct"]
    lam = book["risk"]["ewma_lambda"]
    out = (f"- **Realized vol runs {'above' if above else 'below'} ex-ante.** {hs['active_vol_pct']:.1f}% realized on "
           f"the sessions with a position against {hs['exante_pct']:.1f}% ex-ante, higher in {len(over)} of {len(vy)} "
           f"years; from non-overlapping {BLOCK}-session sums it is {blk:.1f}%"
           + (", so the daily figure understates the miss." if above and blk > hs["active_vol_pct"] else "."))
    if above:
        out += (f" The gap is consistent with the EWMA lagging a rise in vol (its weights' mean age is "
                f"{1 / (1 - lam):.0f} sessions), with the noise of a {b.risks[None].cov.n_eff[-1]:.0f}-session "
                "effective sample, which alone pushes realized above ex-ante, and with fat tails; the report does not "
                "separate them.")
    return out + f" Ex-ante is under the {book['book']['vol_target']:.0%} target where the cap binds: {_cap_years(vy)}."


def answer(b):
    """The report's opening: a one-line verdict and the bullets, each worded by what the numbers say."""
    st = b.setup
    book = st.book
    h = headline(book)
    hs, hb = b.summaries[h], b.books[h]
    lines = [
        f"- **Net of costs, the headline book {_verdict(hs)}.** {head_words(b)}: a gross Sharpe of "
        f"{sr(hs['gross_sr'], hs['gross_se'])} and a net one of {sr(hs['net_sr'], hs['net_se'])} (SE in brackets), "
        f"{pc(hs['return_pct'])} of capital a year net ({pc(hs['gross_pct'])} gross, {hs['cost_pct']:.2f}% in costs) at "
        f"{hs['vol_pct']:.1f}% realized vol, against a {book['book']['vol_target']:.0%} ex-ante target. Its worst "
        f"drawdown is {hs['max_dd_pct']:.1f}% of capital. {hs['active']:,} of the {hs['sessions']:,} sessions counted "
        f"(from {hs['first_counted']:%b %Y}) have a position.",
        _constructions_words(b),
        f"- **{'No cost makes it work' if hs['cstar_bp'] is None else 'Its breakeven cost is ' + cstar(hs['cstar_bp'])}.** "
        + (f"Its gross P&L is at or below zero, so there is no breakeven round trip: at zero cost it nets its gross "
           f"{sr(float(sleeves.curve(hb.run, [0.0])[0]))}. " if hs["cstar_bp"] is None else
           f"c* = 2 x gross P&L / DV01 traded, against a configured mix of {hs['mix_bp']:.2f}bp a round trip. ")
        + f"It trades {hs['turns_year']:.1f} turns a year; costs take {hs['cost_pct']:.2f}% of capital a year.",
        _carries_words(b),
        _concentration_words(b),
        _shrink_words(b),
        _overlay_words(b),
    ]
    rv = Choice(h.construction, sleeves=b.rv)
    rs = b.summaries[rv]
    lines.append(
        f"- **The RV-only book ({_and(b.rv)}) {_verdict(rs)}.** {sr(rs['gross_sr'], rs['gross_se'])} gross and "
        f"{sr(rs['net_sr'], rs['net_se'])} net, {gap(difference(b.books[rv], hb))} against the headline's net, "
        f"{pc(rs['return_pct'])} a year, worst drawdown {rs['max_dd_pct']:.1f}%: "
        f"{'the relative-value sleeves lose before costs' if rs['gross_sr'] <= 0 else 'the relative-value sleeves earn before costs'}"
        f", so taking the outrights out does not leave an edge behind them. "
        f"The headline's outrights carry {pct(_outright_share(b))} of its ex-ante variance on average.")
    w8, un = b.week8["vol_scaled"], b.uncapped
    lines.append(
        f"- **Against week 8's sum of sleeves.** The equal-risk sum (each sleeve alone at the book's risk, "
        f"{w8['vol_pct']:.1f}% realized vol) netted {sr(w8['net_sr'], w8['net_se'])}; the book, one covariance and "
        f"one {book['book']['vol_target']:.0%} target, nets {sr(hs['net_sr'], hs['net_se'])}. The gross DV01 cap binds "
        f"on {pct(hs['capped'])} of the sessions with a position; without it the headline nets "
        f"{sr(un['net_sr'], un['net_se'])}, {gap(difference(b.free, hb))} against the capped book, with a worst "
        f"drawdown of {un['max_dd_pct']:.1f}%.")
    lines += [_halves_words(b), _vol_words(b)]
    return [_head(b), "", *lines]


def _losing_years(years):
    """'Every year but 2022 and 2023 lost money. ' where most years lost; empty otherwise."""
    good = years.index[years > 0]
    if len(good) > len(years) / 2:
        return ""
    return "Every year lost money. " if not len(good) else f"Every year but {_and(str(y) for y in good)} lost money. "


def _cost_words(b):
    """Costs over the sample, and the sleeve that pays most of them."""
    capital = b.setup.book["book"]["capital"]
    hb = b.books[headline(b.setup.book)]
    k = hb.run.daily["kept"]
    paid = pd.Series({n: p["cost"][k].sum() for n, p in hb.parts.items()})
    top = paid.idxmax()
    return (f"Costs come to {paid.sum() / capital * 100:.1f}% of capital over the sample, {paid[top] / paid.sum():.0%} "
            f"of them {top}'s ({paid[top] / capital * 100:.1f}%).")


def _concentration_words(b):
    """The vol target is the whole book's: where few sleeves have a side, they carry all of it."""
    book = b.setup.book
    capital = book["book"]["capital"]
    hb = b.books[headline(book)]
    vy = vol_by_year(hb, capital)
    vy = vy[vy["with a position"] > 0]
    few = vy.loc[vy["sleeves sized (mean)"].idxmin()]
    y = int(few["year"])
    years = by_year(hb, capital).drop(columns="book")
    top = years.loc[y].abs().idxmax()
    cap = f", the cap binding on {few['cap binds']:.0%} of its sessions" if few["cap binds"] > 0.25 else ""
    return (f"- **The vol target is the whole book's, so the few sleeves with a side carry all of it.** In {y} the "
            f"book sized {few['sleeves sized (mean)']:.1f} sleeves on average, at {few['ex-ante']:.1f}% ex-ante{cap}, "
            f"and netted {pc(few['net'])}, {pc(years.loc[y, top])} of it {top}'s. The sleeves sized average "
            f"{vy['sleeves sized (mean)'].min():.1f} to {vy['sleeves sized (mean)'].max():.1f} a year: the book "
            "diversifies only as far as the sleeves with a side on the day allow.")


def head_words(b):
    """The headline book in words: construction, covariance, target, cap, rules."""
    book = b.setup.book
    cap = book["risk"]["max_gross_dv01_per_capital"]
    return (f"{WORDS[book['portfolio']['headline']].capitalize()} (the headline, proposed), shrunk covariance, "
            f"{book['book']['vol_target']:.0%} ex-ante vol on {book['book']['currency']} "
            f"{book['book']['capital'] / 1e6:,.0f}m, gross DV01 capped at "
            f"{'no cap' if cap is None else f'{cap * 100:g}% of capital per bp'}, {b.setup.spec.words(sizing=False)}")


def _outright_share(b):
    st = b.setup
    tg = b.books[headline(st.book)].targets
    on = tg.exante > 0
    outs = [n for n in tg.share.columns if st.inputs[n].sleeve.kind == "outright"]
    return float(tg.share.loc[on, outs].sum(axis=1).mean())


def _cap_years(vy):
    top = vy.sort_values("cap binds", ascending=False).head(3)
    top = top[top["cap binds"] > 0.25]
    if top.empty:
        return "it rarely does"
    return _and(f"{int(r.year)} ({r['ex-ante']:.1f}% ex-ante, the cap binding on {r['cap binds']:.0%})"
                for _, r in top.iterrows())


def _shrink_words(b):
    """The shrinkage bullet: how far delta goes, and what it moves (worded by the numbers, not before them)."""
    book = b.setup.book
    rk = b.risks[None]
    first = rk.first
    delta = rk.cov.delta[first:]
    moves = {c: difference(b.books[Choice(c)], b.books[Choice(c, shrink=False)]) for c in order(book)}
    big = [c for c in moves if _apart(moves[c])]
    most = max(moves, key=lambda c: abs(moves[c]["diff"]))
    cy = cov_by_year(rk, first)
    cs, cu = risk.condition(rk.cov.shrunk[first:]), risk.condition(rk.cov.s[first:])
    mv, mvu = b.summaries[Choice("mean_variance")], b.summaries[Choice("mean_variance", shrink=False)]
    title = ("Shrinkage moves no construction by as much as a paired SE; it matters most for " + WORDS[most]
             if not big else f"Shrinkage moves {WORDS[most]} by more than a paired SE, and no other construction"
             if big == [most] else f"Shrinkage moves {_and(WORDS[c] for c in big)} by more than a paired SE; it "
             f"matters most for {WORDS[most]}")
    return (
        f"- **{title}.** The intensity delta averages {np.nanmean(delta):.2f} (from "
        f"{np.nanmin(delta):.2f} to {np.nanmax(delta):.2f}; yearly means {cy['delta mean'].min():.2f} to "
        f"{cy['delta mean'].max():.2f}): the EWMA's effective sample is {rk.cov.n_eff[-1]:.0f} sessions, so a small "
        f"matrix is still a noisy one. It takes the correlation matrix's condition number from a median of "
        f"{np.nanmedian(cu):.1f} (max {np.nanmax(cu):.0f}) to {np.nanmedian(cs):.1f} (max {np.nanmax(cs):.0f}). "
        "Net Sharpe shrunk against unshrunk, and the difference: "
        + _and(f"{WORDS[c]} {sr(b.summaries[Choice(c)]['net_sr'])} against "
               f"{sr(b.summaries[Choice(c, shrink=False)]['net_sr'])}, {gap(moves[c])}" for c in order(book))
        + f". Mean-variance's sign flips fall from {pct(mvu['flipped'])} to {pct(mv['flipped'])} of its active "
        f"sleeve-sessions, its turns a year from {mvu['turns_year']:.1f} to {mv['turns_year']:.1f}. Inverse-vol's weights do "
        "not read the correlations; only its vol-target scale does.")


def _overlay_words(b):
    """The drawdown overlay's bullet: with and without, its cost in return, and 'anecdotal' at two episodes or fewer."""
    book = b.setup.book
    dd = book["portfolio"]["drawdown"]
    h = headline(book)
    with_ = b.books[Choice(h.construction, overlay=True)]
    off, on = b.summaries[h], b.summaries[with_.choice]
    n = len(on["episodes"])
    cost = off["return_pct"] - on["return_pct"]
    head = (f"The drawdown control fired {'once' if n == 1 else f'{n} times'}"
            + (": anecdotal, not evidence" if n <= 2 else ""))
    return (
        f"- **{head}.** Half size when the book is {dd['trigger']:.0%} of capital below its peak, full again under "
        f"{dd['release']:.0%}. It triggered on {_and(on['episodes']) if n else 'no session'}"
        + (f" and never released: the book never came back within {dd['release']:.0%} of its peak, so it ran at half "
           f"size on {pct(on['halved'])} of the sessions counted" if never_released(with_) else "")
        + f". Headline with it and without: {pc(on['return_pct'])} against {pc(off['return_pct'])} a year, net Sharpe "
        f"{sr(on['net_sr'], on['net_se'])} against {sr(off['net_sr'], off['net_se'])}, "
        f"{gap(difference(with_, b.books[h]))}, worst drawdown "
        f"{on['max_dd_pct']:.1f}% against {off['max_dd_pct']:.1f}%. Its cost in return is "
        + (f"{cost:.2f}% of capital a year" if cost >= 0 else
           f"negative: it added {-cost:.2f}% a year, by halving a book that kept losing")
        + ". It is reported, not used: no robustness cell or cost curve has it.")


def _head(b):
    """The one-line verdict, from what the numbers say."""
    st = b.setup
    capital = st.book["book"]["capital"]
    h = headline(st.book)
    hs = b.summaries[h]
    years = by_year(b.books[h], capital)["book"]
    good = years[years > 0]
    rs = b.summaries[Choice(h.construction, sleeves=b.rv)]
    if hs["net_sr"] > 0:
        first = "the book earns net of costs" + (", within two SEs of zero" if hs["net_sr"] < 2 * hs["net_se"] else "")
    else:
        first = "the book loses money, net of costs" + (" and before them" if hs["gross_sr"] <= 0 else "")
    rest = []
    if all(not b.summaries[Choice(c)]["net_sr"] > 0 for c in order(st.book)):
        rest.append("every construction loses money net")
    if len(good) and years.sum() <= 0:
        rest.append(f"its {len(good)} good year{'s' if len(good) > 1 else ''} ({_and(str(y) for y in good.index)}) "
                    f"{'do' if len(good) > 1 else 'does'} not make up the other {len(years) - len(good)}")
    if not rs["gross_sr"] > 0:
        rest.append("the relative-value sleeves lose before costs on their own")
    words = _and(rest) if rest else ""
    return f"**In one line: {first}.**" + (f" {words[:1].upper()}{words[1:]}." if words else "")


# ---- the tables --------------------------------------------------------------------

def _name(ch):
    return WORDS[ch.construction] + ("" if ch.correlations else ", no correlations") + (", RV only" if ch.sleeves else "")


def _listed(b):
    """The books the side-by-side tables print: every construction shrunk, mean-variance without its correlations,
    and the RV-only headline."""
    h = headline(b.setup.book)
    return [Choice(c) for c in order(b.setup.book)] + ([DIAGONAL] if DIAGONAL in b.books else []) + \
        [Choice(h.construction, sleeves=b.rv)]


def _books_table(b):
    h = headline(b.setup.book)
    rows = []
    for ch in _listed(b):
        s = b.summaries[ch]
        rows.append({"book": _name(ch) + (" (headline)" if ch == h else ""),
                     "gross": sr(s["gross_sr"], s["gross_se"]), "net": sr(s["net_sr"], s["net_se"]),
                     "net against the headline": "" if ch == h else gap(difference(b.books[ch], b.books[h])),
                     "net a year": pc(s["return_pct"]), "gross a year": pc(s["gross_pct"]),
                     "costs a year": f"{s['cost_pct']:.2f}%", "realized vol": f"{s['vol_pct']:.1f}%",
                     "worst drawdown": f"{s['max_dd_pct']:.1f}%", "turns a year": f"{s['turns_year']:.1f}",
                     "in market": pct(s["time_in_market"]), "cap binds": pct(s["capped"]), "c*": cstar(s["cstar_bp"])})
    return pd.DataFrame(rows)


def _shrink_table(b):
    rows = []
    for c in order(b.setup.book):
        on, off = b.summaries[Choice(c)], b.summaries[Choice(c, shrink=False)]
        rows.append({"construction": WORDS[c], "shrunk: net": sr(on["net_sr"], on["net_se"]),
                     "unshrunk: net": sr(off["net_sr"], off["net_se"]),
                     "difference": f"{on['net_sr'] - off['net_sr']:+.2f}",
                     "paired SE": f"{difference(b.books[Choice(c)], b.books[Choice(c, shrink=False)])['se']:.2f}",
                     "shrunk: turns a year": f"{on['turns_year']:.1f}", "unshrunk: turns a year": f"{off['turns_year']:.1f}",
                     "shrunk: sign flips": pct(on["flipped"]), "unshrunk: sign flips": pct(off["flipped"]),
                     "shrunk: worst drawdown": f"{on['max_dd_pct']:.1f}%", "unshrunk: worst drawdown": f"{off['max_dd_pct']:.1f}%"})
    return pd.DataFrame(rows)


def _overlay_table(b):
    h = headline(b.setup.book)
    rows = []
    for ch in [Choice(c) for c in order(b.setup.book)] + [Choice(h.construction, sleeves=b.rv)]:
        off, on = b.summaries[ch], b.summaries[replace(ch, overlay=True)]
        rows.append({"book": _name(ch), "without: net a year": pc(off["return_pct"]),
                     "without: net Sharpe": sr(off["net_sr"], off["net_se"]),
                     "without: worst drawdown": f"{off['max_dd_pct']:.1f}%", "with: net a year": pc(on["return_pct"]),
                     "with: net Sharpe": sr(on["net_sr"], on["net_se"]), "with: worst drawdown": f"{on['max_dd_pct']:.1f}%",
                     "net Sharpe, with less without": gap(difference(b.books[replace(ch, overlay=True)], b.books[ch])),
                     "cost in return": pc(off["return_pct"] - on["return_pct"]),
                     "episodes": len(on["episodes"]), "triggered": ", ".join(on["episodes"]) or "none",
                     "sessions at half size": pct(on["halved"])})
    return pd.DataFrame(rows)


def _curve_table(b):
    grid = b.setup.book["costs"]["sensitivity_bp"]
    h = headline(b.setup.book)
    rows = []
    for ch in [Choice(c) for c in order(b.setup.book)] + [Choice(h.construction, sleeves=b.rv)]:
        x, s = b.books[ch], b.summaries[ch]
        for mode in ("uniform", "assumed"):
            if mode == "assumed" and ch != h:
                continue
            vals = sleeves.curve(x.run, grid, mode)
            key = "cstar_bp" if mode == "uniform" else "cstar_assumed_bp"
            rows.append({"book": _name(ch) + (" (headline)" if ch == h else "") +
                         (", only the assumed legs varied" if mode == "assumed" else ""),
                         **{f"{c:g}bp": sr(v) for c, v in zip(grid, vals)},
                         "configured": sr(s["net_sr"], s["net_se"]), "c*": cstar(s[key])})
    return pd.DataFrame(rows)


def _turnover_table(b):
    rows = []
    for ch in _listed(b):
        s = b.summaries[ch]
        rows.append({"book": _name(ch), "turns a year": f"{s['turns_year']:.1f}",
                     **{CAUSE_WORDS[c]: pct(s["shares"][c]) for c in CAUSES},
                     "maintenance": pct(s["shares"]["roll"] + s["shares"]["restrike"]),
                     "mean gross DV01": f"{s['mean_gross_dv01'] / 1e3:,.0f}k", "costs a year": f"{s['cost_pct']:.2f}%"})
    return pd.DataFrame(rows)


def _cov_table(b):
    rk = b.risks[None]
    cy = cov_by_year(rk, rk.first)
    return cy.round(2).map(lambda x: f"{x:.2f}").reset_index(names="year")


def _correlation_table(b):
    rk = b.risks[None]
    s0, s = mean_correlations(rk, rk.first, "s0"), mean_correlations(rk, rk.first, "s")
    rows = []
    for i in rk.names:
        rows.append({"sleeve": i, **{j: ("1" if i == j else f"{s0.loc[i, j]:+.2f} / {s.loc[i, j]:+.2f}")
                                     for j in rk.names}})
    return pd.DataFrame(rows)


def _vol_table(b):
    vy = vol_by_year(b.books[headline(b.setup.book)], b.setup.book["book"]["capital"])
    return vy.assign(**{"ex-ante": vy["ex-ante"].map(lambda x: f"{x:.1f}%"),
                        "sleeves sized (mean)": vy["sleeves sized (mean)"].map(lambda x: f"{x:.1f}"),
                        "realized": vy["realized"].map(_vol),
                        "realized, block sums": vy["realized, block sums"].map(_vol),
                        "cap binds": vy["cap binds"].map(pct), "net": vy["net"].map(pc),
                        "year": vy["year"].astype(str)}).rename(
        columns={"realized": "realized, daily", "realized, block sums": f"realized, {BLOCK}-session sums"})


def _vol(x):
    return "n/a" if pd.isna(x) else f"{x:.1f}%"


def _dv01_table(b):
    d = dv01_by_year(b.books[headline(b.setup.book)])
    home = b.setup.book["book"]["currency"]
    signed = [c for c in d.columns if c not in ("|net|", "gross")]
    d = (d / 1e3).round(0)
    d[signed] = d[signed].map(lambda x: f"{x:+,.0f}k")
    d[["|net|", "gross"]] = d[["|net|", "gross"]].map(lambda x: f"{x:,.0f}k")
    return d.rename(
        columns=lambda c: f"net {c}" if c not in ("|net|", "gross") else c).reset_index(names="year").assign(
        year=lambda f: f["year"].astype(str)).rename(columns={"|net|": f"absolute net ({home} per bp)",
                                                             "gross": f"gross ({home} per bp)"})


def _years_table(b):
    capital = b.setup.book["book"]["capital"]
    hb = b.books[headline(b.setup.book)]
    y = by_year(hb, capital)
    body = y.map(pc).reset_index(names="year").assign(year=lambda f: f["year"].astype(str))
    total = {"year": "all", **{n: pc(y[n].sum()) for n in y}}
    tg = hb.targets
    share = {"year": "share of ex-ante variance", **{n: pct(tg.share.loc[tg.exante > 0, n].mean()) for n in tg.share},
             "book": "100%"}
    gross = {"year": "gross, all", **{n: pc(p["gross"][hb.run.daily["kept"]].sum() / capital * 100)
                                      for n, p in hb.parts.items()},
             "book": pc(kept(hb)["gross"].sum() / capital * 100)}
    cost = {"year": "costs, all", **{n: f"{p['cost'][hb.run.daily['kept']].sum() / capital * 100:.2f}%"
                                     for n, p in hb.parts.items()},
            "book": f"{kept(hb)['cost'].sum() / capital * 100:.2f}%"}
    return pd.concat([body, pd.DataFrame([total, gross, cost, share])], ignore_index=True)


def _stale_table(b):
    hb = b.books[headline(b.setup.book)]
    s = stale(hb)
    return s.reset_index(names="sleeve")


def _closes(st, name):
    """The closes a sleeve is marked at: one per currency its legs are in."""
    return len({leg.ccy for _, _, leg in st.inputs[name].sleeve.legs})


def _lag_table(b):
    rk = b.risks[None]
    e = lag_effect(rk, rk.first)
    n = rk.names
    return pd.DataFrame({"sleeve": n, "closes marked at": [str(_closes(b.setup, x)) for x in n],
                         "mean lag-1 autocorrelation": [f"{e['rho'][x]:+.2f}" for x in n],
                         "lowest": [f"{e['rho_min'][x]:+.2f}" for x in n],
                         "inverse-vol size on S over S0: mean": [f"{e['size'][x]:.2f}" for x in n],
                         "highest": [f"{e['size_max'][x]:.2f}" for x in n],
                         "unweighted: variance <= 0 (sessions)": [f"{e['negative_by_sleeve'][x]:,}" for x in n],
                         "unweighted: not positive definite without it": [f"{e['not_pd_without'][x]:,}" for x in n]}), e


def _lag_words(b, e):
    """What the unweighted lag term's failures come from, in the numbers of `lag_effect` `e`."""
    rk = b.risks[None]
    neg = [n for n in rk.names if e["negative_by_sleeve"][n] > 0]
    top = min(rk.names, key=lambda n: e["not_pd_without"][n])
    one = [n for n in neg if _closes(b.setup, n) == 1]
    return (f"The largest contributor is {top}: without it the unweighted form fails on {e['not_pd_without'][top]:,} "
            "sessions. " + (f"Every variance below zero is {_and(neg)}'s" if neg else "No variance falls below zero")
            + (f", marked at one close, so its negative lag-1 autocorrelation is its own P&L's, not the closes' timing"
               if neg and one == neg else "")
            + ". The lag term's diagonal is each sleeve's own lag-1 autocovariance, so S's diagonal is a one-lag "
            "long-run variance for every sleeve, not a timing correction only.")


# ---- the report --------------------------------------------------------------------

def markdown(b):
    """reports/portfolio.md."""
    st = b.setup
    book = st.book
    r, p = book["risk"], book["portfolio"]
    capital, home = book["book"]["capital"], book["book"]["currency"]
    h = headline(book)
    hb = b.books[h]
    rk = b.risks[None]
    lag_rows, lag = _lag_table(b)
    cap = r["max_gross_dv01_per_capital"]
    dd = p["drawdown"]
    lines = [
        "# The book: the sleeves sized together, what they earn net, and what carries it",
        "",
        f"Generated by `scripts/build_portfolio.py` from `data/panel/` and the cache, book sessions "
        f"{st.days[0]:%Y-%m-%d} .. {st.days[-1]:%Y-%m-%d} ({home}). Do not edit by hand. The book is "
        "`strategy/portfolio.py`, its covariance `strategy/risk.py`; the sleeves, their rules and their costs are "
        "week 8's (`reports/costs.md`). Every choice is a row in notes/DECISIONS.md, section P (portfolio).",
        "",
        "## The answer",
        "",
        *answer(b),
        "",
        "![The book](figures/book_equity_light.png)",
        "",
        "## How the book is built",
        "",
        f"**Calendar.** The book runs on {home}'s sessions. A sleeve's P&L on its own sessions is credited to the next "
        "book session on or after it, so a sterling session on a US holiday is summed into the next US session and a "
        "US session on a UK holiday gets nothing from the sterling sleeves (the stale sessions are counted below). "
        "Positions are decided only at book closes; a sleeve reaches a decision at its next own session and executes "
        "it a session later, as week 8's sleeves do.",
        "",
        f"**Covariance.** Of the sleeves' unit P&L (+1 book DV01 on the first leg), strictly before each close: EWMA "
        f"weights lambda^age, lambda = {r['ewma_lambda']:g} (effective sample {rk.cov.n_eff[-1]:.0f} sessions), zero "
        f"mean, complete rows only. The non-synchronous term: London closes before New York, so a {home} move after "
        "the London close reaches the sterling sleeves a day later. S = S0 + (S1 + S1')/2, S1 the EWMA of x_t x_(t-1)': "
        f"the Newey-West estimator at one lag. The unweighted S0 + S1 + S1' is not positive definite on "
        f"{lag['not_pd']:,} of the {lag['sessions']:,} sessions from the book's first decision (a variance below zero on "
        f"{lag['negative_variance']}); the Bartlett-weighted S is on {lag['sessions'] - lag['bartlett_not_pd']:,} of them. "
        f"{_lag_words(b, lag)} Shrunk toward its diagonal: "
        "Sigma = (1 - delta) S + delta diag(S), delta = sum over i != j of pi_ij / n_eff, over sum over i != j of "
        "S_ij^2, clipped to [0, 1], pi_ij = sum w (x_i x_j - S0_ij)^2, n_eff = 1 / sum w^2: a Ledoit-Wolf-type "
        "intensity with Schafer and Strimmer's target D (the diagonal, unequal variances). The sd each "
        f"sleeve is sized on is the diagonal's, floored at {r['sigma_floor']:g} x its trailing two-year median as week "
        "8's, and the covariance is rescaled to the floored sds with its correlations kept.",
        "",
        f"**Constructions**, on the sleeves with a side (g, the hysteresis side under the ELB treatment): "
        "inverse-vol (the headline, proposed) w = g / sd; ERC, the signs fixed by g and every sleeve's share of the "
        "ex-ante variance equal (cyclical coordinate descent to 1e-10; one sleeve is inverse-vol); mean-variance "
        f"w = Sigma^-1 mu, mu = g x min(|z|, {p['z_cap']:g}) x sd (the z as expected return, so with no correlation it "
        "is inverse-vol weighted by |z|). Mean-variance on the diagonal of the same Sigma (no correlations) is run "
        "beside it, to split its difference from inverse-vol into its |z| weights and its correlations.",
        "",
        f"**Size.** Scaled to {book['book']['vol_target']:.0%} of capital a year ex ante, sqrt(w' Sigma w x 252); the "
        f"gross DV01, every leg's |q|, capped at {cap * 100:g}% of capital per bp ({home} {cap * capital / 1e3:,.0f}k per "
        f"bp); a sleeve re-sized only on a new side or when its target moves more than {r['no_trade_band']:.0%} from "
        "the position held, unless keeping it would break the cap. Costs on every leg's change, week 8's. The book "
        f"decides from the first close with {p['min_history']} complete sessions of unit P&L behind it "
        f"({st.days[rk.first]:%Y-%m-%d}); flat at the ELB it has nothing counted before {hb.run.daily.index[hb.run.daily['kept']][0]:%b %Y}.",
        "",
        f"**Drawdown control** (reported, not used): half size ({dd['scale']:g}) from the close after the drawdown "
        f"(peak less equity, over capital) exceeds {dd['trigger']:.0%}, full again when it is back under "
        f"{dd['release']:.0%}; decided at the close and executed a session later, like everything else.",
        "",
        "Sharpe is mean over sd of daily net P&L on the counted sessions, annualised by the book calendar's observed "
        "sessions a year, with its SE, sqrt((1 + SR^2/2)/years), in brackets: the least the uncertainty can be. Two "
        "books over the same sessions share most of their positions, so a difference between them is judged against "
        "the SE of the difference, paired on the sessions both count (Jobson and Korkie's, with Memmel's correction: "
        "sqrt((2 (1 - rho) + (s_a^2 + s_b^2 - 2 s_a s_b rho^2) / 2) / n), s the per-session Sharpes, rho the "
        "correlation of the two daily net P&Ls, annualised), not against either Sharpe's own SE.",
        "",
        "## The books side by side",
        "",
        "All shrunk, without the drawdown control, at the configured costs. Turns: DV01 traded a year over the mean "
        "gross DV01 held (a round trip is 2). In market: counted sessions with a position. c*: the uniform round trip "
        "per leg at which the net Sharpe is zero, 2 x gross P&L / DV01 traded; none where the gross is at or below 0. "
        "Net against the headline: the book's net Sharpe less the headline's, with its paired SE.",
        "",
        table(_books_table(b)),
        "",
        "## Cost sensitivity",
        "",
        "Net Sharpe with every leg at a uniform round trip c (a future's fee inside c), and for the headline also "
        "with only the assumed legs varied (the tick-based legs at their tick): week 8's curves, on the book.",
        "",
        table(_curve_table(b)),
        "",
        "## The covariance: shrinkage and conditioning",
        "",
        "Delta by year from the book's first decision, and the condition number (largest over smallest eigenvalue) "
        "of the correlation matrix, unshrunk and shrunk: the correlation's, because the covariance's own mixes "
        "sleeves whose vols differ by a factor of ten.",
        "",
        table(_cov_table(b)),
        "",
        "### Shrinkage on and off",
        "",
        "Sign flips: the share of active sleeve-sessions a construction puts on the other side from the sleeve's own "
        "signal (mean-variance only can).",
        "",
        table(_shrink_table(b)),
        "",
        "### The non-synchronous term",
        "",
        "Mean correlation over the sessions from the book's first decision, S0 / S: the same-day moment, then with "
        "the lag term. Then, by sleeve: the closes its legs are marked at (two only where its legs are in two "
        "currencies); its lag-1 autocorrelation rho (the lag term's diagonal over S0's), mean and lowest; what the lag "
        "term does to its inverse-vol size, sqrt(S0_ii / S_ii) = 1 / sqrt(1 + rho), mean and highest; and, for the "
        "unweighted S0 + S1 + S1', the sessions its variance is at or below zero and the sessions the form is not "
        f"positive definite with the sleeve dropped ({lag['not_pd']:,} with every sleeve).",
        "",
        table(_correlation_table(b)),
        "",
        table(lag_rows),
        "",
        "## The drawdown control",
        "",
        table(_overlay_table(b)),
        "",
        "## Turnover",
        "",
        "Share of DV01 traded by cause. Entries and exits: the sleeve's own side changed. Resizing: another sleeve's "
        "side changed, so every weight moved. Rescaling: neither (the covariance, the vol target, the cap, and for "
        "mean-variance its z, which moves mu every session). Rolls "
        "and re-strikes: maintenance, week 8's.",
        "",
        table(_turnover_table(b)),
        "",
        f"## Realized and ex-ante vol by year ({_name(h)})",
        "",
        f"Sleeves sized: those with a side, the ones the book's {book['book']['vol_target']:.0%} is spread over. "
        "Ex-ante and realized vol over the sessions with a position, realized from the daily P&L and from its sums "
        f"over non-overlapping {BLOCK}-session blocks (a year holds about {SESSIONS_PER_YEAR // BLOCK}, so it is noisy by year); the "
        "cap's share of them; net P&L, % of capital.",
        "",
        table(_vol_table(b)),
        "",
        f"## Net DV01 by currency ({_name(h)})",
        "",
        f"Mean book DV01 on after the close, {home} per bp, by year over the counted sessions with a position: net "
        "per currency (receive positive), the sum of their absolute values, and the gross (every leg's |q|). A "
        "relative-value book has |net| well under gross.",
        "",
        table(_dv01_table(b)),
        "",
        f"## What carries it: net P&L by sleeve and year ({_name(h)}, % of capital)",
        "",
        table(_years_table(b)),
        "",
        "## The book calendar",
        "",
        f"Book sessions from the book's start with no session of the sleeve credited (stale: a UK holiday on a "
        f"{home} session), and with two or more (catch-up: a sterling session on a US holiday, summed into the next).",
        "",
        table(_stale_table(b)),
        "",
        "## Checks (the build stops if one fails)",
        "",
        "- ERC's risk contributions are equal on every session it sizes two or more sleeves, to 1e-8; on the "
        f"{int(((st.g != 0).sum(axis=1) == 1).sum()):,} sessions with one active sleeve ERC is inverse-vol.",
        "- The covariance each construction reads is positive definite on every session it sizes.",
        "- The gross DV01 cap holds on every close; DV01 traded by cause adds up; the book's P&L is its sleeves'.",
        "- Nothing is earned or charged on a session the ELB treatment leaves out.",
        "- Every book on the headline's sleeves counts the headline's sessions, so the paired differences between them "
        "add up (mean-variance's two channels sum to its difference from inverse-vol).",
        "- The drawdown control's scale is the fixed point of its state machine on the book's own equity "
        f"({b.summaries[Choice(h.construction, overlay=True)]['rounds']} rounds for the headline).",
        "",
    ]
    return "\n".join(lines)


# ---- the figure --------------------------------------------------------------------

def figure(b, path, theme="light"):
    """Left: the book's net equity by construction (and RV only). Right: the headline's net P&L by sleeve."""
    t = _style(theme)
    colors = CATEGORICAL[theme]
    st = b.setup
    capital = st.book["book"]["capital"]
    h = headline(st.book)
    fig, (left, right) = plt.subplots(1, 2, figsize=(12, 4.6), gridspec_kw={"wspace": 0.28})
    books = [Choice(c) for c in order(st.book)] + [Choice(h.construction, sleeves=b.rv)]
    for ch, color in zip(books, colors):
        x = net(b.books[ch]).cumsum() / capital * 100
        name = _name(ch) + (" (headline)" if ch == h else "")
        left.plot(x.index, x, color=color, lw=2.4 if ch == h else 1.6, ls=(0, (4, 2)) if ch.sleeves else "-",
                  label=f"{name} {x.iloc[-1]:+.1f}%")
    left.axhline(0, color=t["axis"], lw=1)
    left.set_ylabel("cumulative net P&L, % of capital", fontsize=8)
    left.legend(fontsize=8, labelcolor=t["secondary"], loc="lower left")
    left.set_title("Net equity by construction", loc="left", fontsize=10, fontweight="bold", color=t["ink"])
    hb = b.books[h]
    k = hb.run.daily["kept"]
    for (n, part), color in zip(hb.parts.items(), colors):
        x = (part["gross"] - part["cost"])[k].cumsum() / capital * 100
        right.plot(x.index, x, color=color, lw=1.8, label=f"{n} {x.iloc[-1]:+.1f}%")
    right.axhline(0, color=t["axis"], lw=1)
    right.legend(fontsize=8, labelcolor=t["secondary"], loc="lower left", ncols=2)
    right.set_title(f"What carries it: the headline's net P&L by sleeve, % of capital", loc="left", fontsize=10,
                    fontweight="bold", color=t["ink"])
    for ax in (left, right):
        ax.tick_params(labelsize=8, length=0)
        ax.xaxis.set_major_locator(mdates.YearLocator(2))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
        ax.margins(x=0.02)
    s = b.summaries[h]
    fig.text(0.125, 1.04, f"The book's net Sharpe is {sr(s['net_sr'])} ({pc(s['return_pct'])} of capital a year) "
             f"at {s['exante_pct']:.1f}% mean ex-ante vol ({st.book['book']['vol_target']:.0%} target); its worst "
             f"drawdown is {s['max_dd_pct']:.0f}% of capital",
             fontsize=12, fontweight="bold", color=t["ink"], va="bottom")
    fig.text(0.125, 1.0, f"Net of costs, counted sessions only (flat stretches: the ELB state), "
             f"{st.spec.words(sizing=False)}, shrunk covariance, no drawdown control.", fontsize=9,
             color=t["secondary"], va="bottom")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---- the outputs -------------------------------------------------------------------

def _key(ch):
    return "_".join([ch.construction, *(["rv"] if ch.sleeves else []), "shrunk" if ch.shrink else "unshrunk",
                     *([] if ch.correlations else ["diagonal"]), *(["drawdown"] if ch.overlay else [])])


def comparisons(b):
    """Every book-against-book difference the report quotes: {"a - b": `difference`}."""
    book = b.setup.book
    h = headline(book)
    cons = [Choice(c) for c in order(book)]
    rv = Choice(h.construction, sleeves=b.rv)
    pairs = [*itertools.combinations(cons, 2), *((Choice(c), Choice(c, shrink=False)) for c in order(book)),
             *((replace(ch, overlay=True), ch) for ch in [*cons, rv]), (rv, h),
             (Choice("mean_variance"), DIAGONAL), (DIAGONAL, Choice("inverse_vol"))]
    out = {f"{_key(x)} - {_key(y)}": difference(b.books[x], b.books[y]) for x, y in pairs
           if x in b.books and y in b.books}
    if b.free is not None:
        out[f"uncapped - {_key(h)}"] = difference(b.free, b.books[h])
    return out


def results(b):
    """reports/results/portfolio.json: the numbers the note quotes, to six significant figures."""
    st = b.setup
    book, capital = st.book, st.book["book"]["capital"]
    h = headline(book)
    hb = b.books[h]
    rk = b.risks[None]
    grid = book["costs"]["sensitivity_bp"]
    _, lag = _lag_table(b)
    return _plain({
        "spec": {"headline": _key(h), "construction": h.construction, "vol_target": book["book"]["vol_target"],
                 "capital": capital, "max_gross_dv01_per_capital": book["risk"]["max_gross_dv01_per_capital"],
                 "rule": st.spec.rule, "enter": st.spec.enter, "exit": st.spec.exit, "treatment": st.spec.treatment,
                 "first_decision": st.days[rk.first], "rv_sleeves": list(b.rv)},
        "books": {_key(ch): {k: v for k, v in s.items() if k != "halves"} | {"halves": s["halves"]}
                  for ch, s in b.summaries.items()},
        "uncapped_headline": b.uncapped,
        "paired": comparisons(b),
        "without_windows": without(hb, book["evaluation"]["exclude"], capital),
        "week8_sum": b.week8,
        "curves": {_key(ch): {"round_trip_bp": grid, "net_sr": list(sleeves.curve(x.run, grid)),
                              "assumed_only_net_sr": list(sleeves.curve(x.run, grid, "assumed"))}
                   for ch, x in b.books.items() if not ch.overlay and ch.shrink},
        "covariance": {"n_eff": rk.cov.n_eff[-1], "delta_mean": float(np.nanmean(rk.cov.delta[rk.first:])),
                       "by_year": cov_by_year(rk, rk.first).to_dict("index"), "lag": lag,
                       "mean_correlation_s0": mean_correlations(rk, rk.first, "s0").to_dict(),
                       "mean_correlation_s": mean_correlations(rk, rk.first, "s").to_dict()},
        "by_year_pct_capital": by_year(hb, capital).to_dict("index"),
        "vol_by_year": vol_by_year(hb, capital).set_index("year").to_dict("index"),
        "net_dv01_by_year": dv01_by_year(hb).to_dict("index"),
        "share_of_exante_variance": hb.targets.share[hb.targets.exante > 0].mean().to_dict(),
        "outright_share_of_exante_variance": _outright_share(b),
        "stale": stale(hb).to_dict("index"),
    })


def write(b, root):
    """Every output of the build under repo `root`. Returns the paths."""
    root = Path(root)
    out = {"report": root / "reports" / "portfolio.md", "json": root / "reports" / "results" / "portfolio.json"}
    for p in out.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    out["report"].write_text(markdown(b), encoding="utf-8")
    out["json"].write_text(json.dumps(results(b), indent=1) + "\n", encoding="utf-8")
    figures = root / "reports" / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        p = figures / f"book_equity_{theme}.png"
        figure(b, p, theme)
        out[f"figure_{theme}"] = p
    return out
