"""The robustness report: the headline book with one choice at a time moved off the chosen specification.

Generated by `scripts/build_robustness.py`, never hand-edited: every number
comes from the rows run here, and every sentence is a template filled from
them. Numbers are from the build of 2026-09-29 (reports/robustness.md).

**What is run.** Every row of ``robustness.choices`` (`strategy/robustness.py`,
13 rows over 8 choices) is the headline book (`report/portfolio.py`
`headline`: the configured construction, shrunk, every sleeve, no drawdown
control, at the chosen ELB treatment and the configured costs) on the row's
signal, and each sleeve alone as `report/costs.py` runs it (`simulate`:
vol-scaled, the book's rule). A row's sleeves are the baseline's legs with the
row's components, ELB state and carry gate (`report/costs.py` `inputs(like=)`),
so the unit P&L, sigma, the covariance (the baseline's `Risk`, reused) and the
costs are the baseline's; `build` stops if a row's unit P&L is not.

**The cells.** Primary: the book's net Sharpe over the common sample, the
book sessions on which every row has an eligible signal (`robustness.eligible`;
a book session counts where any sleeve's does, as the book counts its
sessions): 2,866 from 2014-05-05 (the constant dollar r* keeps the dollar
model in the ELB state to May 2014, the chosen one to Jan 2014), where SE(SR)
is 0.32 at the chosen specification's -0.62. The sleeves are run alone, not read off their part of
the book: the book's vol target is shared, so a sleeve's part moves with every
other sleeve's side, and a row that changes one currency would move the other
currency's sleeves; alone, those cells are the chosen ones exactly. Each is over
its own common sample (the sterling sleeves' from Aug 2016, where every row's
sterling model leaves the ELB state; the -2.6 r* row, in it on more sessions
after that, takes the GBP outright's from 2,294 to 2,208). Secondary: gross Sharpe; each row on
its own sample; IC(21) of each sleeve's z on the rate component of its unit P&L
(a signal-level number, free of sizing, costs and the book), over the sessions
every row has a z outside its ELB state, where the model has no view; and, for
the estimated rows, the same cells from the first estimate on (2017-01-03 for
the book, the later of the two currencies').

**The paired SE** (`robustness.paired_se`), beside every move: two cells over
the same sessions share most of their positions, so the noise in their
difference is far below the SE of either Sharpe (0.03 for the NSS row, 0.22
for the 365-day window, against 0.32). It is iid, and for a difference that is
no bound: its Newey-West version (Bartlett weights to 21 sessions) is lower on
10 of the 13 rows and puts two in another band (the carry filter at 2.30
paired SEs against 1.90 iid). The reading sorts the choices by the iid one,
says where the other differs, and how many moves beyond one paired SE noise
alone would give (4.1 of 13; 4 are). Each sleeve's largest move carries its
own paired SE: the book's insensitivity to r* (GBP) and the coefficients hides
the GBP outright's (1.3 and 1.6 paired SEs).

**The note on r*** gives its shares over the sessions every row counts for the
currency's outright (2,208 for sterling), with every session's beside them:
the whole sample counts the years both models sit flat in the ELB state, where
no side can differ (the -2.6 row changes the GBP outright's side on 16.8% of
the counted sessions, 10.6% of all). The z is the chosen one's only on the 185
(-2.6) and 1,043 (-0.6) counted sessions with no floored goal in the trailing
730 days. The HLW row says how much of the common sample has a current
vintage: 66% (Taylor's 2% before March 2016 and the 2020Q2 vintage, held to
May 2023, are the rest).

**The IC's t** is Newey-West to 21 lags (spec section 6), which covers the
forward windows' overlap and not the z's persistence (the rank products'
autocorrelation at lag 21 is 0.33 for the USD outright, 0.12 for the GBP
outright), so the non-overlapping check (`metrics.ic_offsets`) is beside it;
its mean has the IC's sign in all 70 row-sleeve cells.

**The headline** is read from reports/results/portfolio.json, not from the
grid's own run: the build stops unless the chosen specification on its own
sample is it.
"""

from dataclasses import dataclass
import json
import math
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from policypath import regimes
from policypath.report import costs as sleeves
from policypath.report import portfolio as books
from policypath.report.coverage import table
from policypath.report.expression import _and, _plain
from policypath.report.figures import THEMES, _style
from policypath.strategy import expression, portfolio, robustness

BASE = robustness.BASELINE.key          # rows are told apart by key, so a copied or unpickled grid reads the same


@dataclass
class Grid:
    """Every row run: `rows` in order, and by row key the book's `Setup` and headline `Book`, the sleeves'
    stand-alone `Run`s, and the sessions each row has an eligible signal on (``book`` on the book calendar, each sleeve on its
    own). `common` is their intersection over the rows; `ic_common` the sessions every row has a z outside its ELB
    state on (the IC's). `moves` is {key: {ccy: `robustness.moves`, on the currency's outright's common sample}},
    `sides` {key: {sleeve: (share of sessions whose side changes, the same over its common sample)}}, `onto`
    {key: {ccy: (sessions added, dropped)}}, `models` {key: {ccy: model panel}}, `elb` {key: {ccy: ELB-state
    sessions}} and `first` {key: {ccy: first estimate}}."""
    book: dict
    rows: list
    setups: dict
    books: dict
    runs: dict
    eligible: dict
    common: dict
    ic_common: dict
    moves: dict
    sides: dict
    onto: dict
    models: dict
    elb: dict
    first: dict
    risk: books.Risk


def _book_eligible(st, b):
    """The book sessions with an eligible signal: those a sleeve's eligible session is credited to, from the book's
    start (as the book counts its sessions)."""
    days, start = st.days, b.run.start
    out = np.zeros(len(days), dtype=bool)
    for i in st.inputs.values():
        s = i.sleeve
        e = robustness.eligible(s.component["z"], i.state, st.spec.treatment, s.lag) & (s.sessions >= start)
        out |= portfolio.to_book(e.astype(int), days).to_numpy() > 0
    return pd.Series(out & (days >= start), index=days)


def _sleeve_eligible(i, treatment):
    s = i.sleeve
    return robustness.eligible(s.component["z"], i.state, treatment, s.lag) & (s.sessions >= i.start)


def _row_inputs(world, row, base, legs, signal):
    """A row's book config, currency blocks, view, and each sleeve's stand-alone `Inputs` on the baseline's legs."""
    book = robustness.book_of(row, world.book)
    cfgs = {c: robustness.block(c, world.cfg(c), over) for c, over in row.currencies.items()}
    placed = {c: robustness.onto(s, world.panel(c, "signal")) for c, (_, s) in signal.items()}
    panels = {c: {"model": signal[c][0], "signal": placed[c][0]} for c in signal}
    view = robustness.View(world, legs, book=book, cfgs=cfgs, panels=panels)
    specs = {s["name"]: s for s in book["sleeves"]}
    inp = {}
    for n, i in base.items():
        if not robustness.touches(row, i.sleeve):
            inp[n] = i
            continue
        sleeve = expression.sleeve(specs[n], view)
        if sleeve.component["z"].first_valid_index() is None:
            raise RuntimeError(f"row {row.key}: the {n} sleeve has no z on any session")
        inp[n] = sleeves.inputs(sleeve, view, book, like=i)
    return book, view, inp, {c: p[1:] for c, p in placed.items()}


def build(world=None, signals=None, store=None, log=None):
    """Every row of the grid, run: a `Grid`.

    `signals` is `robustness.signals`' result ({key: {ccy: (model, signal)}});
    by default it is built from `world` (the real one by default) through
    `store` (`robustness.Store`).
    """
    world = expression.World() if world is None else world
    book = world.book
    grid = robustness.rows(book)
    if signals is None:
        signals = robustness.signals(world, grid, store, log=log)
    legs = {}
    view0 = robustness.View(world, legs, build=True)
    base = {n: sleeves.inputs(s, view0, book) for n, s in expression.build(view0).items()}
    days = sleeves._book_days(world, book)
    st0 = books.from_inputs(book, days, base)
    rk = books.risk_of(st0, list(base))
    k = {c: world.cfg(c)["backtest"]["horizon"] for c in robustness.book_currencies(book)}
    out = {name: {} for name in ("setups", "books", "runs", "eligible", "moves", "sides", "onto", "models", "elb",
                                 "first")}
    views = {}
    for row in grid:
        if row.key == BASE:
            b_book, view, inp, placed = book, view0, base, {}
        else:
            b_book, view, inp, placed = _row_inputs(world, row, base, legs, signals[row.key])
        st = st0 if row.key == BASE else books.from_inputs(b_book, days, inp)
        if not st.units.equals(st0.units) or any(inp[n].u is not base[n].u for n in base):
            raise RuntimeError(f"row {row.key}: the unit P&L is not the baseline's")
        b = books.run_book(st, rk, books.headline(b_book))
        runs = {n: sleeves.simulate(i, sleeves.chosen(b_book), b_book) for n, i in inp.items()}
        out["setups"][row.key], out["books"][row.key], out["runs"][row.key] = st, b, runs
        out["eligible"][row.key] = {"book": _book_eligible(st, b),
                                    **{n: _sleeve_eligible(i, st.spec.treatment) for n, i in inp.items()}}
        models = out["models"][row.key] = {c: view.panel(c, "model") for c in k}
        out["elb"][row.key] = {c: int(regimes.elb_state(m).sum()) for c, m in models.items()}
        out["first"][row.key] = {c: robustness.first_estimate(m) for c, m in models.items()}
        out["onto"][row.key] = placed
        views[row.key] = view
    names = ["book", *base]
    common = {n: robustness.common(out["eligible"][r.key][n] for r in grid) for n in names}
    ic_common = {n: robustness.common(_ic_sample(out["setups"][r.key].inputs[n]) for r in grid) for n in base}
    for row in grid:
        view, models = views[row.key], out["models"][row.key]
        traded = {c: common[n] if (n := _outright_in(base, c)) else None for c in row.currencies}
        out["moves"][row.key] = {c: robustness.moves(world.panel(c, "signal"), view.panel(c, "signal"), k[c],
                                                     world.panel(c, "model"), models[c], traded[c],
                                                     view.cfg(c)["signal"]["window"]) for c in row.currencies}
        out["sides"][row.key] = {n: _side_changes(st0, out["setups"][row.key], n, common[n]) for n in base}
    g = Grid(book, grid, out["setups"], out["books"], out["runs"], out["eligible"], common, ic_common, out["moves"],
             out["sides"], out["onto"], out["models"], out["elb"], out["first"], rk)
    check(g)
    return g


def _ic_sample(i):
    """A sleeve's sessions with a z, outside the ELB state: where the signal says something."""
    return i.sleeve.component["z"].notna() & ~i.state.reindex(i.sleeve.sessions, fill_value=False)


def _side_changes(st0, st, name, on):
    """The share of a sleeve's sessions with a z in both on which the row decides another side than the baseline:
    (over every such session, over those in `on`, the sleeve's common sample). Every session counts years in
    which both are flat in the ELB state and cannot differ; the common sample is where the sleeve trades."""
    z0, z1 = st0.inputs[name].sleeve.component["z"], st.inputs[name].sleeve.component["z"]
    both = z0.notna() & z1.notna()
    differ = st0.side[name] != st.side[name]
    traded = both & on.reindex(both.index, fill_value=False)
    return tuple(float(differ[m].mean()) if m.any() else np.nan for m in (both, traded))


def check(g):
    """Raise if the grid's invariants fail: every row's eligible sessions are ones its book and runs count; no row
    adds or drops a session; the common samples are not empty."""
    for row in g.rows:
        b, e = g.books[row.key], g.eligible[row.key]
        if (e["book"] & ~b.run.daily["kept"]).any():
            raise RuntimeError(f"row {row.key}: an eligible book session the book does not count")
        for n, r in g.runs[row.key].items():
            if (e[n] & ~r.daily["kept"]).any():
                raise RuntimeError(f"row {row.key}: an eligible {n} session the sleeve does not count")
        moved = {c: p for c, p in g.onto[row.key].items() if any(p)}
        if moved:
            raise RuntimeError(f"row {row.key}: sessions added or dropped against the baseline: {moved}")
    empty = [n for n, m in g.common.items() if not m.any()]
    if empty:
        raise RuntimeError(f"no session every row counts for {empty}")


# ---- the numbers -------------------------------------------------------------------

def periods(g):
    """Sessions a year: the book's, and each sleeve's (the baseline run's), used for every row's cell."""
    base = robustness.BASELINE.key
    return {"book": g.books[base].run.periods, **{n: r.periods for n, r in g.runs[base].items()}}


def _pnl(g, key, name, net=True):
    d = g.books[key].run.daily if name == "book" else g.runs[key][name].daily
    return d["gross"] - d["cost"] if net else d["gross"]


def cells(g, mask=None, own=False, net=True):
    """{row key: {book and sleeve: (Sharpe, SE, sessions)}} over the common samples (or each row's own with `own`),
    each intersected with `mask` ({name: bool series}) if given."""
    per = periods(g)
    out = {}
    for row in g.rows:
        out[row.key] = {}
        for n in ["book", *g.runs[row.key]]:
            m = g.eligible[row.key][n] if own else g.common[n]
            if mask is not None:
                m = m & mask[n].reindex(m.index, fill_value=False)
            out[row.key][n] = robustness.cell(_pnl(g, row.key, n, net), m, per[n])
    return out


def _rate(i):
    """A sleeve's rate component of unit P&L by session (bp): what its IC is on."""
    return i.u.groupby("session")["rate"].sum(min_count=1).reindex(i.sleeve.sessions)


def ics(g, how=robustness.ic):
    """{row key: {sleeve: (IC, t, sessions)}}: IC(``robustness.ic_horizon``) on the rate component, over the IC's
    common sample; with `how` another function of the same arguments (`robustness.ic_offsets`, `ic_persistence`)."""
    h = g.book["robustness"]["ic_horizon"]
    return {row.key: {n: how(i.sleeve.component["z"], _rate(i), h, i.sleeve.lag, g.ic_common[n])
                      for n, i in g.setups[row.key].inputs.items()} for row in g.rows}


def estimated(g):
    """The rows with estimated coefficients, the first estimate each window starts at, and their cells from it.

    Returns (keys, {name: window start}, cells): the baseline and those rows
    over the common samples from the latest first estimate among the rows
    and the currencies a book or sleeve trades.
    """
    keys = [r.key for r in g.rows if any(v is not None for v in g.first[r.key].values())]
    if not keys:
        return [], {}, {}
    base = g.setups[robustness.BASELINE.key]
    ccys = {"book": robustness.book_currencies(g.book), **{n: list(i.sleeve.ccys) for n, i in base.inputs.items()}}
    start = {n: max(g.first[k][c] for k in keys for c in cs if g.first[k][c] is not None) for n, cs in ccys.items()}
    mask = {n: pd.Series(g.common[n].index >= start[n], index=g.common[n].index) for n in start}
    return keys, start, cells(g, mask)


def summary(g, published=None):
    """Every number the report prints: the cells (net and gross; common and own samples), the paired SEs (iid and
    Newey-West), the ICs and their non-overlapping check, the estimated rows' window, and each common sample's size.

    `published` is the headline book as reports/results/portfolio.json has it (`published_headline`). Given, the
    chosen specification on its own sample must be it, net Sharpe to the JSON's six figures and sessions, or this
    raises: the report then says so from the file, not from its own run.
    """
    per = periods(g)
    names = ["book", *g.runs[BASE]]
    paired, hac = ({r.key: {n: robustness.paired_se(_pnl(g, r.key, n), _pnl(g, BASE, n), g.common[n], per[n], lags)
                            for n in names} for r in g.rows} for lags in (None, robustness.PAIRED_LAGS))
    keys, start, est = estimated(g)
    samples = {}
    for n in names:
        on = g.common[n][g.common[n]].index
        samples[n] = {"sessions": len(on), "first": on.min(), "last": on.max(), "years": len(on) / per[n]}
    own = cells(g, own=True)
    if published is not None:
        got = (float(f"{own[BASE]['book'][0]:.6g}"), own[BASE]["book"][2])
        if got != (published["net_sr"], published["sessions"]):
            raise RuntimeError(f"the chosen specification nets {got[0]} over {got[1]:,} sessions on its own sample; "
                               f"reports/results/portfolio.json's headline {published['net_sr']} over "
                               f"{published['sessions']:,}: rebuild it (scripts/build_portfolio.py)")
    return {"periods": per, "net": cells(g), "gross": cells(g, net=False), "own": own,
            "own_gross": cells(g, own=True, net=False), "paired": paired, "paired_hac": hac, "ic": ics(g),
            "ic_offsets": ics(g, robustness.ic_offsets), "ic_persistence": ics(g, robustness.ic_persistence)[BASE],
            "estimated": {"keys": keys, "start": start, "cells": est}, "sample": samples, "published": published}


def published_headline(root, book):
    """The headline book's numbers in reports/results/portfolio.json under repo `root` (`summary`'s check)."""
    books_json = json.loads((Path(root) / "reports" / "results" / "portfolio.json").read_text(encoding="utf-8"))["books"]
    return books_json[books._key(books.headline(book))]


def choices(g):
    """The grid's choices in config order: (name, chosen value, [its `Row`s])."""
    by = {r.key: r for r in g.rows}
    return [(c["name"], c["chosen"], [by[r["key"]] for r in c["rows"]]) for c in g.book["robustness"]["choices"]]


def _outright_in(inputs, ccy):
    """The outright sleeve of one currency among `inputs` ({name: `Inputs`}), or None."""
    for n, i in inputs.items():
        if i.sleeve.kind == "outright" and i.sleeve.ccys == (ccy,):
            return n
    return None


def _outright(g, ccy):
    return _outright_in(g.setups[BASE].inputs, ccy)


def _net(s, key, name="book"):
    return s["net"][key][name][0]


def _delta(s, key, name="book"):
    return _net(s, key, name) - _net(s, BASE, name)


def _moved(s, key, name="book", se="paired"):
    """|delta| over its paired SE (``paired``: iid; ``paired_hac``: Newey-West); 0 where the row leaves the cell."""
    x, d = s[se][key][name], abs(_delta(s, key, name))
    return d / x if x > 0 else 0.0 if d == 0 else np.inf


def _band(moved):
    return "over two" if moved > 2 else "under one" if moved < 1 else "one to two"


def _sign(values):
    pos, n = sum(v > 0 for v in values), len(values)
    return "positive in every row" if pos == n else "negative in every row" if pos == 0 else f"positive in {pos} of {n}"


# ---- the words ---------------------------------------------------------------------

sr, pct = sleeves.sr, sleeves.pct


def head_words(g):
    """The book every cell is: the headline, in words."""
    b = g.book
    spec = g.setups[BASE].spec
    return (f"{books.WORDS[b['portfolio']['headline']]} (the headline), shrunk covariance, "
            f"{b['book']['vol_target']:.0%} ex-ante vol, the gross DV01 cap, {spec.words(sizing=False)}, at the "
            "configured costs, no drawdown control")


def _head(g, s):
    alt = {r.key: _net(s, r.key) for r in g.rows if r.key != BASE}
    words = {r.key: r.words() for r in g.rows}
    lo, hi = min(alt, key=alt.get), max(alt, key=alt.get)
    n, base = len(alt), s["net"][BASE]["book"]
    earn = sum(v > 0 for v in alt.values())
    if earn == 0 and base[0] <= 0:
        first = "no single choice turns the book's loss into a gain"
    elif earn == n and base[0] > 0:
        first = "every row earns: the result does not hinge on one choice"
    else:
        first = f"the sign turns on the choice: {earn} of the {n} rows earn net, the chosen specification " + (
            "among them" if base[0] > 0 else "not")
    above = sum(v > base[0] for v in alt.values())
    return (f"**In one line: {first}.** Net of costs, over the {s['sample']['book']['sessions']:,} book sessions every "
            f"row counts, the {n} rows net from {sr(alt[lo])} ({words[lo]}) to {sr(alt[hi])} ({words[hi]}), around "
            f"the chosen specification's {sr(*base[:2])}. {above} of the {n} net more than the chosen specification: "
            "it was fixed in config before the grid ran, so it is the reference here, not a cell picked from it.")


def _design_words(g, s):
    names = [c[0] for c in choices(g)]
    n = len(g.rows) - 1
    sm = s["sample"]["book"]
    return (f"- **One choice at a time.** Each of the {n} rows moves one of {len(names)} choices ({_and(names)}) "
            "off its chosen value and leaves every other where the book has it, so interactions between choices are "
            "not run. A row changes the signal only: its sleeves are built on the baseline's legs, so the marks, the "
            "instruments, carry, roll, costs, the unit P&L and the covariance are the baseline's, checked on every "
            f"row. Every cell is the headline book: {head_words(g)}. The primary cell is its net Sharpe over the "
            f"common sample, the {sm['sessions']:,} book sessions from {sm['first']:%b %Y} to {sm['last']:%b %Y} on "
            "which every row has an eligible signal (counted by the ELB treatment, with a z behind the position), so "
            "the rows differ only in what the signal did on the same days.")


def _move_words(g, s):
    alt = [r for r in g.rows if r.key != BASE]
    se = s["net"][BASE]["book"][1]
    top = sorted(alt, key=lambda r: -abs(_delta(s, r.key)))
    big = [r for r in alt if abs(_delta(s, r.key)) >= se]
    two = [r for r in alt if _moved(s, r.key) > 2]
    one = [r for r in alt if _moved(s, r.key) < 1]
    head = (f"No row moves the book by as much as one SE of its Sharpe ({se:.2f})" if not big else
            f"{len(big)} of the {len(alt)} rows move the book by one SE of its Sharpe ({se:.2f}) or more")
    return (f"- **{head}.** The largest moves: "
            + _and(f"{r.words()} {_delta(s, r.key):+.2f} (paired SE {s['paired'][r.key]['book']:.2f})" for r in top[:3])
            + ". Rows share the sessions and most of the positions, so the noise in a difference is the paired SE, "
            "sd(x_row - x_chosen) / sd(x_chosen) / sqrt(years), well under the SE of either Sharpe. Against it, "
            + (f"{len(two)} rows move the book by more than two ({_and(r.words() for r in two)})" if two else
               "no row moves the book by more than two")
            + (f" and {len(one)} by less than one ({_and(r.words() for r in one)})." if one else
               ", and every row moves it by at least one.") + " " + _hac_words(g, s))


def _hac_lower(g, s):
    """How many rows' Newey-West paired SE of the book's move is below the iid one."""
    return sum(s["paired_hac"][r.key]["book"] < s["paired"][r.key]["book"] for r in g.rows if r.key != BASE)


def _hac_words(g, s):
    """The iid paired SE against its Newey-West version: where it is lower, and the rows it moves to another band."""
    alt = [r for r in g.rows if r.key != BASE]
    lower = _hac_lower(g, s)
    other = [r for r in alt if _band(_moved(s, r.key)) != _band(_moved(s, r.key, se="paired_hac"))]
    return (f"The paired SE is iid; its Newey-West version (Bartlett weights to {robustness.PAIRED_LAGS} sessions) "
            f"is lower on {lower} of the {len(alt)} rows"
            + (", and the bands' edges are not sharp: under it the book moves by " + _and(
                f"{_moved(s, r.key, se='paired_hac'):.2f} paired SEs at {r.words()} ({_moved(s, r.key):.2f} iid: "
                f"{_band(_moved(s, r.key, se='paired_hac'))}, not {_band(_moved(s, r.key))})" for r in other) + "."
               if other else " and puts every row in the same band."))


def _chance(n, k, p):
    """P(at least `k` of `n` independent draws land where each does with probability `p`)."""
    return sum(math.comb(n, j) * p ** j * (1 - p) ** (n - j) for j in range(k, n + 1))


def _choice_verdicts(g, s):
    """(choices moving the book by more than two paired SEs, by less than one, in between): their names."""
    out = ([], [], [])
    for name, _, rows in choices(g):
        worst = max(_moved(s, r.key) for r in rows)
        out[0 if worst > 2 else 1 if worst < 1 else 2].append(name)
    return out


def _reading(g, s):
    """What the result is and is not sensitive to, in a paragraph (V13)."""
    alt = [r for r in g.rows if r.key != BASE]
    se = s["net"][BASE]["book"][1]
    vals = [_net(s, r.key) for r in g.rows]
    two, one, mid = _choice_verdicts(g, s)
    big = [r for r in alt if _moved(s, r.key) >= 1]
    up = [r for r in big if _delta(s, r.key) > 0]
    best = max(alt, key=lambda r: _net(s, r.key))
    first = ("The book's loss does not hinge on one choice: every row loses money net" if max(vals) <= 0 else
             "The book's gain does not hinge on one choice: every row earns net" if min(vals) > 0 else
             f"The book's sign hinges on the choice: {sum(v > 0 for v in vals)} of the {len(vals)} specifications earn")
    moved = [r for r in alt if abs(_delta(s, r.key)) >= se]
    parts = [first + (f", and no row moves its net Sharpe by as much as one SE ({se:.2f})." if not moved else
                      f", and {len(moved)} rows move its net Sharpe by one SE ({se:.2f}) or more.")]
    if two or mid:
        parts.append(f"Against the paired SE, {_and(two + mid)} move it by more than one paired SE"
                     + (f" ({_and(two)} by more than two)" if two else "") + ", "
                     + ("every such move upward: the chosen specification sits low among its neighbours, and "
                        f"{'no neighbour earns' if max(vals) <= 0 else 'a neighbour earns'} (the best, "
                        f"{best.words()}, nets {sr(_net(s, best.key))})." if len(up) == len(big) else
                        f"{len(up)} of those {len(big)} moves upward."))
    if big:
        p1, p2 = math.erfc(1 / math.sqrt(2)), math.erfc(2 / math.sqrt(2))
        k2 = sum(_moved(s, r.key) > 2 for r in alt)
        parts.append(f"Noise alone would put about {len(alt) * p1:.1f} of {len(alt)} independent moves beyond one "
                     f"paired SE and {len(alt) * p2:.1f} beyond two; {len(big)} and {k2} are, so the count "
                     + ("is about what chance gives, and the band alone is not evidence that the result is sensitive "
                        "to those choices." if _chance(len(alt), len(big), p1) > 0.05 else
                        "is more than chance gives."))
    if one:
        parts.append(f"Under {_and(one)} it moves by less than one paired SE.")
    signed = [n for n in g.runs[BASE] if len({_net(s, r.key, n) > 0 for r in g.rows}) == 1]
    for n in signed:
        v = [_net(s, r.key, n) for r in g.rows]
        top = max(alt, key=lambda r: abs(_delta(s, r.key, n)))
        parts.append(f"The {n} {'earns' if _net(s, BASE, n) > 0 else 'loses'} in every row ({min(v):+.2f} to "
                     f"{max(v):+.2f}); what moves it most is {top.words()} ({_delta(s, top.key, n):+.2f}, "
                     f"{_moved(s, top.key, n):.1f} paired SEs).")
    earning = [n for n in signed if _net(s, BASE, n) > 0]
    for n in earning:
        hidden = [(name, max(rows, key=lambda r: _moved(s, r.key, n))) for name, _, rows in choices(g) if name in one]
        hidden = [(name, r) for name, r in hidden if _moved(s, r.key, n) > 1]
        if hidden:
            parts.append(f"The book's insensitivity to {_and(name for name, _ in hidden)} hides the {n}'s"
                         + (", the one sleeve that earns in every row" if len(earning) == 1 else "") + ": it moves by "
                         + _and(f"{_moved(s, r.key, n):.1f} paired SEs under {name} ({r.label}, "
                                f"{_delta(s, r.key, n):+.2f})" for name, r in hidden) + ".")
    return "- **What the result is and is not sensitive to.** " + " ".join(parts)


def _sleeve_words(g, s):
    parts = []
    for n in g.runs[BASE]:
        vals = {r.key: _net(s, r.key, n) for r in g.rows}
        lo, hi = min(vals.values()), max(vals.values())
        top = max((r for r in g.rows if r.key != BASE), key=lambda r: abs(_delta(s, r.key, n)))
        parts.append(f"{n} {lo:+.2f} to {hi:+.2f} ({_sign(vals.values())}; chosen {vals[BASE]:+.2f}, moved most by "
                     f"{top.words()}, {_delta(s, top.key, n):+.2f}, {_moved(s, top.key, n):.1f} paired SEs)")
    return ("- **Each sleeve alone** (the vol-scaled sleeve of reports/costs.md, net, over its own common sample): " + "; ".join(parts)
            + ". A row that changes one currency's block leaves the sleeves that do not trade it exactly at their "
            "chosen cells.")


def _slope_words(g, s):
    """For a row that changes the book's signal block: how much of the level each curve sleeve's z then carries."""
    rows = [r for r in g.rows if "signal" in r.book]
    parts, level_like = [], True
    for r in rows:
        for n, i in g.setups[BASE].inputs.items():
            level = _outright(g, i.sleeve.ccys[0]) if i.sleeve.kind == "curve" else None
            if level is None:
                continue
            z = g.setups[BASE].inputs[level].sleeve.component["z"]
            corr = [g.setups[k].inputs[n].sleeve.component["z"].corr(z) for k in (BASE, r.key)]
            level_like &= corr[1] > 0.8 > 0.5 > abs(corr[0])
            parts.append(f"the {n}'s z correlates {corr[1]:.2f} with the {level}'s under {r.label} and {corr[0]:.2f} "
                         f"chosen, and nets {_net(s, r.key, n):+.2f} against {_net(s, BASE, n):+.2f}")
    if not parts:
        return None
    return (f"- **What the slope row trades.** {_cap('; '.join(parts))}" + (
        ": the raw slope re-trades most of the level on the curve (why the traded slope is orthogonalised), so the "
        "row tests the level's timing on the curve more than it tests the slope." if level_like else "."))


def _gross_words(g, s):
    vals = {r.key: s["gross"][r.key]["book"][0] for r in g.rows}
    earn = [r for r in g.rows if vals[r.key] > 0]
    lo, hi = min(vals.values()), max(vals.values())
    return (f"- **Before costs the book earns in {len(earn)} of the {len(g.rows)} specifications"
            + (f" ({_and(r.words() for r in earn)}), at most {sr(hi)}" if earn else "")
            + f".** Its gross Sharpe runs from {sr(lo)} to {sr(hi)} (chosen {sr(vals[BASE])}): "
            + ("no row's gross covers its costs." if max(_net(s, r.key) for r in g.rows) <= 0 else
               "some rows' gross covers their costs."))


def _rstar_rows(g):
    """(row, ccy) for every row that moves a currency's r*, split into constant offsets of the chosen r* and not."""
    rows = [(r, c) for r in g.rows for c, o in r.currencies.items() if "rstar" in o.get("rule", {})]
    constant = [(r, c) for r, c in rows if g.moves[r.key][c]["rstar_offset_sd"] < 1e-9]
    return constant, [x for x in rows if x not in constant]


def _rstar_words(g, s):
    """The note on r*, checked: what a constant r* does to the quoted gap, to the z and to the trade."""
    constant, moving = _rstar_rows(g)
    if not constant and not moving:
        return None
    lines = []
    for ccy in dict.fromkeys(c for _, c in constant):
        rows = [r for r, c in constant if c == ccy]
        m = {r.key: g.moves[r.key][ccy] for r in rows}
        first = m[rows[0].key]
        out = _outright(g, ccy)
        almost = all(m[r.key]["corr_z"] >= 0.95 and (g.sides[r.key][out][1] if out else 0) <= 0.05 for r in rows)
        worst = min(rows, key=lambda r: m[r.key]["corr_z"])
        lines.append(
            f"- **The note on r\\*, in {ccy}: a constant r\\* moves the quoted gap, and the z absorbs "
            f"{'almost all of it' if almost else 'less of it than is usually assumed'}.** "
            f"{_cap(_and(r.label for r in rows))} "
            f"{'are constant offsets' if len(rows) > 1 else 'is a constant offset'} of "
            f"the chosen {choices_chosen(g, rows[0])}. Each pp of r* moves the gap at the backtest horizon by "
            f"{abs(first['bp_per_pp']):.1f}bp the other way where the rule's goal is off the floor in both, and that "
            f"is the number the brief quotes: on {first['latest']:%Y-%m-%d} it is {first['latest_base_bp']:+.1f}bp at "
            f"the chosen value, "
            + _and(f"{m[r.key]['latest_row_bp']:+.1f} at {r.label}" for r in rows)
            + ". Where the goal is floored in both the gap does not move. "
            + (_floored_words(g, rows, ccy, out) if out else
               f"It is floored on {first['floored_base']:.0%} of {ccy}'s sessions at the chosen value ("
               + _and(f"{m[r.key]['floored_row']:.0%} at {r.label}" for r in rows) + ")")
            + ", so the shift is not constant (its sd is "
            + _and(f"{m[r.key]['sd_change_bp']:.1f}bp" for r in rows)
            + ") and a trailing z cannot remove all of it: corr(z, the chosen z) is "
            + _and(f"{m[r.key]['corr_z']:.2f}" for r in rows)
            + (_traded_rstar_words(g, rows, ccy, out) if out else
               ", and the z changes sign on " + _and(pct1(m[r.key]['sign_changes']) for r in rows) + " of sessions. ")
            + ("That is the usual claim that it 'absorbs a constant r* offset almost entirely'." if almost else
               f"The usual claim that 'the z-score absorbs a constant r* offset almost entirely' holds away from the floor and "
               f"not near it: it fails most at {worst.label} (corr {m[worst.key]['corr_z']:.2f}), where the goal is "
               + (f"floored on {pct1(m[worst.key]['floored_row_traded'])} of the counted sessions against "
                  f"{pct1(first['floored_base_traded'])}." if out else
                  f"floored on {m[worst.key]['floored_row']:.0%} of sessions against {first['floored_base']:.0%}."))
            + (_trade_words(g, s, rows, out) if out else ""))
    for ccy in dict.fromkeys(c for _, c in moving):
        rows = [r for r, c in moving if c == ccy]
        m = {r.key: g.moves[r.key][ccy] for r in rows}
        out = _outright(g, ccy)
        lines.append(
            f"- **In {ccy}, the r\\* rows are not constant offsets of the chosen {choices_chosen(g, rows[0])}** "
            "(the offset's sd over the sample: " + _and(f"{m[r.key]['rstar_offset_sd']:.2f}pp at {r.label}" for r in rows)
            + "), so the z has a moving offset to absorb: corr(z) " + _and(f"{m[r.key]['corr_z']:.2f}" for r in rows)
            + ", sign changes " + _and(pct1(m[r.key]['sign_changes']) for r in rows)
            + f", the latest gap {m[rows[0].key]['latest_base_bp']:+.1f}bp becomes "
            + _and(f"{m[r.key]['latest_row_bp']:+.1f}" for r in rows) + "."
            + _vintage_words(g, rows, ccy)
            + (f" The {out} nets " + _and(f"{_net(s, r.key, out):+.2f}" for r in rows)
               + f" against {_net(s, BASE, out):+.2f} chosen; the book " + _and(f"{_net(s, r.key):+.2f}" for r in rows)
               + "." if out else "")
            + _constant_mean_words(g, rows, ccy))
    return lines


def _floored_words(g, rows, ccy, out):
    """The goal's floored share over the sessions every row counts for the outright, where it trades, with the share
    over every session beside it: every session counts the years both models spend flat in the ELB state."""
    m = {r.key: g.moves[r.key][ccy] for r in rows}
    first = m[rows[0].key]
    return (f"Over the {first['traded_sessions']:,} sessions every row counts for the {out} it is floored on "
            f"{pct1(first['floored_base_traded'])} at the chosen value ("
            + _and(f"{pct1(m[r.key]['floored_row_traded'])} at {r.label}" for r in rows)
            + f"; over every session, the years both models spend flat in the ELB state included, "
            + _and([f"{first['floored_base']:.0%}", *(f"{m[r.key]['floored_row']:.0%}" for r in rows)]) + ")")


def _traded_rstar_words(g, rows, ccy, out):
    """What the constant r* rows do to the z and the outright's side over the sessions every row counts for it (every
    session's share beside it), and on how many of those the z is left exactly as it is."""
    m = {r.key: g.moves[r.key][ccy] for r in rows}
    first = m[rows[0].key]
    n = first["traded_sessions"]
    return (", and on those sessions the z changes sign on "
            + _and(pct1(m[r.key]["sign_changes_traded"]) for r in rows) + " ("
            + _and(pct1(m[r.key]["sign_changes"]) for r in rows) + f" of every session) and the {out}'s side on "
            + _and(pct1(g.sides[r.key][out][1]) for r in rows) + " ("
            + _and(pct1(g.sides[r.key][out][0]) for r in rows) + "). The z is the chosen one's only where neither "
            f"model's goal has been floored over the trailing {first['floor_free_window']} (the largest change in z "
            f"there is {max(m[r.key]['floor_free_max_dz'] for r in rows):.0e}): on "
            + _and(f"{m[r.key]['floor_free']:,}" for r in rows) + f" of the {n:,}. ")


def _vintage_words(g, rows, ccy):
    """For a row whose r* is a vintaged series: the share of the currency's outright's common sample on the stand-in
    before the first vintage, or on a vintage that stood for more than a year (a gap in the source)."""
    out = _outright(g, ccy)
    if out is None:
        return ""
    on = g.common[out]
    days = on[on].index
    parts = []
    for r in rows:
        spec = r.currencies[ccy]["rule"]["rstar"]
        if "source" not in spec:
            continue
        m = g.models[r.key][ccy].set_index("session")
        spans = m.index.to_series().groupby(m["sep_date"]).agg(["min", "max"])
        long = spans[spans["max"] - spans["min"] > pd.Timedelta(days=365)]
        vintage = m["sep_date"].reindex(days)
        stand, stale = vintage.isna(), vintage.isin(long.index)
        words = []
        if stand.any():
            words.append(f"{spec.get('before_first_label', 'its stand-in')} before the first vintage on "
                         f"{stand.sum():,} ({stand.mean():.1%}, to {days[stand][-1]:%Y-%m-%d})")
        for d, (a, b) in long.iterrows():
            n = vintage.eq(d)
            if n.any():
                words.append(f"the vintage dated {d:%Y-%m-%d} ({m.loc[a, 'rstar']:.2f}%), which stood from "
                             f"{a:%Y-%m-%d} to {b:%Y-%m-%d}, on {n.sum():,} ({n.mean():.1%})")
        if words:
            parts.append(f"{r.label} uses " + _and(words) + f": a current vintage on {1 - (stand | stale).mean():.0%}")
    return (f" Of the {len(days):,} sessions every row counts for the {out}, " + "; ".join(parts) + "."
            if parts else "")


def _trade_words(g, s, rows, out):
    """What a constant r* does to the trade: the outright alone and the book, each move in paired SEs."""
    book = max(_moved(s, r.key) for r in rows)
    sleeve = max(_moved(s, r.key, out) for r in rows)
    verdict = ("nearly free for the book" if book < 1 else "not free for the book") + (
        " and for the sleeve" if sleeve < 1 else ", less so for the sleeve" if sleeve <= 2 else ", not for the sleeve")
    return (f" For trading it is {verdict}: the {out} nets " + _and(f"{_net(s, r.key, out):+.2f} at {r.label}" for r in rows)
            + f" against {_net(s, BASE, out):+.2f} chosen (" + _and(f"{_moved(s, r.key, out):.1f}" for r in rows)
            + " paired SEs), the book " + _and(f"{_net(s, r.key):+.2f}" for r in rows) + f" against {_net(s, BASE):+.2f} ("
            + _and(f"{_moved(s, r.key):.1f}" for r in rows) + " paired SEs).")


def _cap(text):
    """`text` with its first letter capitalised and the rest as it is (a currency code stays upper case)."""
    return text[:1].upper() + text[1:]


def pct1(x):
    return "n/a" if pd.isna(x) else f"{x:.1%}"


def choices_chosen(g, row):
    """The chosen value of the choice `row` moves."""
    return next(chosen for name, chosen, _ in choices(g) if name == row.choice)


def _constant_mean_words(g, rows, ccy):
    """For a constant row against a published chosen r*: the constant beside that r*'s sample mean."""
    base = g.models[BASE][ccy]
    constants = [r for r in rows if "constant" in r.currencies[ccy]["rule"]["rstar"]]
    if not constants or "sep_date" not in base or base["sep_date"].isna().all():
        return ""
    published = base["sep_date"].notna()
    return (" " + _cap(_and(r.label for r in constants)) + " rounds the chosen r*'s mean over the sessions "
            f"with a published value, {base.loc[published, 'rstar'].mean():.2f} ({base['rstar'].mean():.2f} with the "
            "stand-in before the first): a hindsight number.")


def _ic_words(g, s):
    h = g.book["robustness"]["ic_horizon"]
    parts, stable = [], 0
    for n in g.runs[BASE]:
        v = {r.key: s["ic"][r.key][n] for r in g.rows}
        ic, t = [x[0] for x in v.values()], [x[1] for x in v.values()]
        stable += all(x > 0 for x in ic) or all(x < 0 for x in ic)
        parts.append(f"{n} {min(ic):+.2f} to {max(ic):+.2f} (t {min(t):+.1f} to {max(t):+.1f}; chosen "
                     f"{v[BASE][0]:+.2f}, {_sign(ic)})")
    same = [r for r in g.rows if r.key != BASE and not r.currencies and "signal" not in r.book]
    off, names = s["ic_offsets"], list(g.runs[BASE])
    agree = sum(np.sign(off[r.key][n][0]) == np.sign(s["ic"][r.key][n][0]) for r in g.rows for n in names)
    return (f"- **The signal before sizing and costs: IC({h}).** The rank correlation of each sleeve's z with the rate "
            f"component of its unit P&L over the {h} sessions after the execution lag, over the sessions on which every "
            "row has a z outside its ELB state: " + "; ".join(parts) + f". The IC keeps its sign in every row for "
            f"{stable} of the {len(names)} sleeves. Its t uses Newey-West with Bartlett weights to {h} lags, which "
            "allows for the overlap of the forward windows and not for the z's own persistence: the rank products' "
            f"autocorrelation {h} sessions apart is "
            + _and(f"{round(s['ic_persistence'][n], 2) + 0.0:.2f} ({n})" for n in names)
            + " for the chosen specification, and where it is positive the t overstates the precision. The "
            f"non-overlapping check, the IC on one session in "
            f"{h} (at least {min(off[BASE][n][3] for n in names):,} each) from each of the {h} start offsets, gives "
            "the chosen specification "
            + _and(f"{n} {off[BASE][n][0]:+.2f} ({off[BASE][n][1]:+.2f} to {off[BASE][n][2]:+.2f})" for n in names)
            + f"; its mean has the IC's sign in {agree} of the {len(g.rows) * len(names)} row-sleeve cells."
            + (f" The {_and(r.choice for r in same)} row{'' if len(same) == 1 else 's'} "
               f"change{'s' if len(same) == 1 else ''} the rule, not the z, so "
               f"{'its IC is' if len(same) == 1 else 'their ICs are'} the chosen one's." if same else ""))


def _estimated_words(g, s):
    e = s["estimated"]
    if not e["keys"]:
        return None
    rows = [r for r in g.rows if r.key in e["keys"]]
    firsts = {c: min(g.first[k][c] for k in e["keys"] if g.first[k][c] is not None)
              for c in robustness.book_currencies(g.book)}
    c = e["cells"]
    sleeve = max(g.runs[BASE], key=lambda n: max(abs(c[k][n][0] - c[BASE][n][0]) for k in e["keys"]))
    return (f"- **The estimated rule from its first estimate.** Its coefficients first rest on data on "
            + _and(f"{d:%Y-%m-%d} ({ccy})" for ccy, d in firsts.items())
            + f"; before that they are the prior, the imposed values. From {e['start']['book']:%Y-%m-%d} (the later) "
            f"the chosen specification nets {sr(*c[BASE]['book'][:2])} over the common sample, and "
            + _and(f"{r.label} {sr(c[r.key]['book'][0])}" for r in rows)
            + f". The sleeve the estimate moves most there is {sleeve}: {c[BASE][sleeve][0]:+.2f} chosen, "
            + _and(f"{c[r.key][sleeve][0]:+.2f} {r.label}" for r in rows) + ".")


def _own_words(g, s):
    base = s["own"][BASE]["book"]
    far = [r for r in g.rows if abs(s["own"][r.key]["book"][2] - base[2]) > 0.02 * base[2]]
    p = s["published"]
    text = (f"- **Each row on its own sample.** The chosen specification counts {base[2]:,} sessions and nets "
            f"{sr(*base[:2])} there"
            + (f": reports/portfolio.md's headline, whose reports/results/portfolio.json has {p['net_sr']:.6g} over "
               f"{p['sessions']:,} (checked: the build stops if they differ)" if p else "")
            + ". The ELB state is the model's, so a row can count other sessions: ")
    if not far:
        return text + "no row's count differs from it by more than 2%."
    return text + "; ".join(
        f"{r.words()} counts {s['own'][r.key]['book'][2]:,} and nets {sr(s['own'][r.key]['book'][0])} there "
        f"({sr(_net(s, r.key))} on the common sample), its ELB-state sessions "
        + _and(f"{g.elb[r.key][c]:,} against {g.elb[BASE][c]:,} ({c})" for c in g.elb[BASE] if g.elb[r.key][c] != g.elb[BASE][c])
        for r in far) + "."


def range_lines(g, s):
    """One generated line per choice: the chosen value's cell, each alternative's with its move and paired SE, the
    range against one SE, and the sleeve the choice moves most."""
    base, se = _net(s, BASE), s["net"][BASE]["book"][1]
    out = []
    for name, chosen, rows in choices(g):
        vals = [base, *(_net(s, r.key) for r in rows)]
        spread = max(vals) - min(vals)
        move = max(((r, n) for r in rows for n in g.runs[BASE]), key=lambda x: abs(_delta(s, x[0].key, x[1])))
        out.append(f"- **{name}**: {chosen}* {sr(base)}; "
                   + "; ".join(f"{r.label} {sr(_net(s, r.key))} ({_delta(s, r.key):+.2f}, paired SE "
                               f"{s['paired'][r.key]['book']:.2f})" for r in rows)
                   + f". Range {spread:.2f}, {'under' if spread < se else 'over'} one SE ({se:.2f}). The sleeve it "
                   f"moves most: {move[1]}, {_delta(s, move[0].key, move[1]):+.2f} at {move[0].label}.")
    return out


def answer(g, s):
    """The report's opening: the verdict and the bullets, each worded by what the numbers say."""
    lines = [_design_words(g, s), _move_words(g, s), _reading(g, s), _sleeve_words(g, s), _slope_words(g, s),
             _gross_words(g, s),
             *(_rstar_words(g, s) or []), _ic_words(g, s), _estimated_words(g, s), _own_words(g, s)]
    return [_head(g, s), "", *[x for x in lines if x]]


# ---- the tables --------------------------------------------------------------------

def _cell(c, se=True):
    return sr(c[0], c[1] if se else None)


def _grid_table(g, s, part="net"):
    names = list(g.runs[BASE])
    rows = []
    for name, chosen, alts in choices(g):
        for i, (label, key) in enumerate([(f"{chosen}*", BASE), *((r.label, r.key) for r in alts)]):
            c = s[part][key]
            row = {"choice": name if i == 0 else "", "value": label, "book": _cell(c["book"], key == BASE)}
            if part == "net":
                row |= {"change": "" if key == BASE else f"{_delta(s, key):+.2f}",
                        "paired SE": "" if key == BASE else f"{s['paired'][key]['book']:.2f}",
                        "Newey-West": "" if key == BASE else f"{s['paired_hac'][key]['book']:.2f}"}
            rows.append(row | {n: _cell(c[n], False) for n in names})
    return pd.DataFrame(rows)


def _sample_line(g, s):
    sm = s["sample"]
    base = s["net"][BASE]
    return (f"Common sample: {sm['book']['sessions']:,} book sessions, {sm['book']['first']:%Y-%m-%d} to "
            f"{sm['book']['last']:%Y-%m-%d} ({sm['book']['years']:.1f} years); **SE(SR) there is "
            f"{base['book'][1]:.2f}** at the chosen specification's {sr(base['book'][0])}. Each sleeve over its own "
            "common sample: " + _and(f"{n} {sm[n]['sessions']:,} sessions from {sm[n]['first']:%b %Y} (SE "
                                     f"{base[n][1]:.2f})" for n in g.runs[BASE]) + ". * the chosen value.")


def _own_table(g, s):
    ccys = list(g.elb[BASE])
    rows = []
    for r in g.rows:
        o, og = s["own"][r.key]["book"], s["own_gross"][r.key]["book"]
        on = g.eligible[r.key]["book"]
        rows.append({"row": r.words(), "sessions counted": f"{o[2]:,}", "from": f"{on[on].index.min():%Y-%m-%d}",
                     "net": _cell(o), "gross": _cell(og),
                     **{f"ELB-state sessions ({c})": f"{g.elb[r.key][c]:,}" for c in ccys}})
    return pd.DataFrame(rows)


def _ic_table(g, s):
    return pd.DataFrame([{"row": r.words(), **{n: f"{v[0]:+.2f} ({v[1]:+.1f})" for n, v in s["ic"][r.key].items()}}
                         for r in g.rows])


def _ic_line(g, s):
    n = s["ic"][BASE]
    return ("Sessions: " + _and(f"{k} {v[2]:,}" for k, v in n.items()) + ".")


def _persistent(s):
    """The sleeves whose rank products stay positively autocorrelated past the IC's horizon, in words."""
    names = [n for n, x in s["ic_persistence"].items() if x > 0]
    return _and(names) if names else "no sleeve"


def _ic_offsets_table(g, s):
    return pd.DataFrame([{"row": r.words(), **{n: f"{v[0]:+.2f} ({v[1]:+.2f} to {v[2]:+.2f})"
                                                for n, v in s["ic_offsets"][r.key].items()}} for r in g.rows])


def _estimated_table(g, s):
    e = s["estimated"]
    names = ["book", *g.runs[BASE]]
    rows = [{"row": r.words(), **{n: _cell(e["cells"][r.key][n], n == "book") for n in names}}
            for r in g.rows if r.key == BASE or r.key in e["keys"]]
    return pd.DataFrame(rows)


def _moves_table(g):
    rows = []
    for r in g.rows:
        for ccy, m in g.moves[r.key].items():
            rows.append({"row": r.words(), "currency": ccy,
                         "gap change, mean (sd)": f"{m['mean_change_bp']:+.1f} ({m['sd_change_bp']:.1f})",
                         "latest gap": f"{m['latest_row_bp']:+.1f} ({m['latest_change_bp']:+.1f})",
                         "corr(z)": f"{m['corr_z']:.3f}", "z changes sign": pct1(m["sign_changes"]),
                         "r* offset, mean (sd)": f"{m['rstar_offset_mean']:+.2f} ({m['rstar_offset_sd']:.2f})",
                         "goal floored: chosen, row, differ": f"{m['floored_base']:.0%}, {m['floored_row']:.0%}, "
                                                              f"{m['floored_differ']:.1%}",
                         "counted: z changes sign; floored, chosen and row; floor-free":
                             f"{pct1(m.get('sign_changes_traded'))}; {pct1(m.get('floored_base_traded'))}, "
                             f"{pct1(m.get('floored_row_traded'))}; {m.get('floor_free', 0):,} of "
                             f"{m.get('traded_sessions', 0):,}",
                         "ELB-state sessions": f"{g.elb[BASE][ccy]:,} to {g.elb[r.key][ccy]:,}"})
    return pd.DataFrame(rows)


def _sides_table(g):
    return pd.DataFrame([{"row": r.words(), **{n: f"{pct1(v[0])} ({pct1(v[1])})" for n, v in g.sides[r.key].items()}}
                         for r in g.rows if r.key != BASE])


# ---- the report --------------------------------------------------------------------

def markdown(g, s):
    """reports/robustness.md."""
    days = g.setups[BASE].days
    e = s["estimated"]
    h = g.book["robustness"]["ic_horizon"]
    lines = [
        "# Robustness: the headline book with one choice at a time moved off the chosen specification",
        "",
        f"Generated by `scripts/build_robustness.py` from `data/panel/` and the cache, book sessions "
        f"{days[0]:%Y-%m-%d} .. {days[-1]:%Y-%m-%d}. Do not edit by hand. The rows are `config/strategy.yml: "
        "robustness`; the grid is `strategy/robustness.py`, the book `strategy/portfolio.py` (reports/portfolio.md), "
        "the sleeves as in reports/costs.md. Every choice is a row in notes/DECISIONS.md, section V.",
        "",
        "## The answer",
        "",
        *answer(g, s),
        "",
        "![The grid](figures/robustness_light.png)",
        "",
        "## One line per choice",
        "",
        "The headline book's net Sharpe over the common sample: the chosen value (*), each alternative with its move "
        "from it and the paired SE of that move, the range against one SE of a Sharpe, and the sleeve the choice "
        "moves most. The chosen specification is the reference, not the best cell.",
        "",
        *range_lines(g, s),
        "",
        "## How the grid is run",
        "",
        "**A row** is one alternative value of one choice, every other choice at its chosen value. It overrides the "
        "currency blocks' `rule`, `signal` or `market.curve.method`, or the book's `signal` or "
        "`positions.carry_filter`, and nothing else (the config refuses a wider override). Its signal is rebuilt from "
        "`data/panel/`'s sessions, meetings and macro through the chain's own entry points, rerunning only the stages "
        "the override reaches: the market path from the cache for a curve fit, the model path for anything in the "
        "rule, the gap and its z always. With no override the same path rebuilds `data/panel/`'s model and signal "
        "bit for bit (checked before the first rebuild in each currency). Rebuilt rows are kept in "
        "`data/panel/robustness/` under a fingerprint of everything they read.",
        "",
        "**The invariant.** A row's sleeves are built on the baseline's legs: the marks (the Bank's own curve under "
        "NSS too), the instrument selected, carry, roll and costs are the baseline's, and so are the unit P&L, the "
        "sigma the sleeves are sized on and the book's covariance. What moves is the component, its z, the ELB state "
        "(the model's: it moves with r*, the coefficients and the conditioning) and the carry gate.",
        "",
        f"**The cells.** The book is the headline: {head_words(g)}. The sleeves are each alone, the vol-scaled "
        "sleeve at the book's rule. A session has an eligible signal where the ELB treatment counts it and a z stands "
        "behind the position held into it or the one put on at its close; the common sample is the sessions on which "
        "every row has one (for the book: any sleeve with one, as the book counts its sessions). Sharpe and its SE "
        "are those of reports/costs.md: mean over sd of daily net P&L, annualised by the calendar's sessions a year, SE "
        "sqrt((1 + SR^2/2)/years), iid, for a Sharpe the least the uncertainty can be. The paired SE of a row's move "
        "is sd(x_row - x_chosen) / sd(x_chosen) / sqrt(years): two cells over the same sessions share most of their "
        "positions, so their difference is less noisy than either. It is iid too, and for a difference that is not a "
        f"bound either way: its Newey-West version (Bartlett weights to {robustness.PAIRED_LAGS} sessions) is beside "
        f"it in the grid, lower on {_hac_lower(g, s)} of the {len(g.rows) - 1} rows.",
        "",
        "## The grid: net Sharpe over the common sample (primary)",
        "",
        _sample_line(g, s),
        "",
        table(_grid_table(g, s)),
        "",
        "## Gross Sharpe over the common sample",
        "",
        table(_grid_table(g, s, "gross")),
        "",
        "## Each row on its own sample",
        "",
        "The book over the sessions the row itself has an eligible signal on, net and gross (SE), from the first; and "
        "the ELB-state sessions of each currency's model under the row.",
        "",
        table(_own_table(g, s)),
        "",
        f"## IC({h}) on the rate component",
        "",
        f"The rank IC of each sleeve's z with the next {h} sessions of the rate component of its unit P&L, after the "
        f"execution lag (Newey-West t, Bartlett to {h} lags, in brackets), over the sessions on which every row has a "
        "z outside its ELB state: a signal-level number, free of sizing, costs and the book. The t allows for the "
        f"overlap of the forward windows, not for the z's persistence past {h} sessions: where that leaves the rank "
        f"products autocorrelated ({_persistent(s)}), the t overstates the precision. " + _ic_line(g, s),
        "",
        table(_ic_table(g, s)),
        "",
        f"The non-overlapping check: the IC on one session in {h}, whose forward windows do not overlap, from each of "
        f"the {h} start offsets; the mean and, in brackets, the lowest and highest.",
        "",
        table(_ic_offsets_table(g, s)),
        "",
    ]
    if e["keys"]:
        lines += [
            "## The estimated rule from its first estimate",
            "",
            "Net Sharpe over the common sample from the first estimate on: "
            + _and(f"{n} from {d:%Y-%m-%d}" for n, d in e["start"].items())
            + " (the latest first estimate among the currencies each trades). The book's SE in brackets.",
            "",
            table(_estimated_table(g, s)),
            "",
        ]
    lines += [
        "## What each row does to the level signal",
        "",
        "Per row and currency it changes, the gap at the backtest horizon against the chosen one: the change in bp "
        "(mean and sd over sessions), the latest gap and its change (the number the brief quotes), corr(z, the chosen "
        "z) and the share of sessions whose z changes sign (over sessions with a z in both), r*'s offset from the "
        "chosen r* (pp), the share of sessions with the rule's goal on the floor (chosen, row, and in exactly one); "
        "over the sessions every row counts for the currency's outright, the z's sign changes, the goal floored, and "
        "the sessions on which neither model's goal has been floored over the trailing z window (floor-free, where a "
        "constant r* leaves the z as it is); and the ELB-state sessions.",
        "",
        table(_moves_table(g)),
        "",
        "### The traded side",
        "",
        "Share of each sleeve's sessions with a z in both on which the row's rule (hysteresis under the ELB "
        "treatment) holds another side than the chosen specification's; in brackets, over the sleeve's common sample, "
        "the sessions every row counts. Every session with a z includes years both sit flat in the ELB state.",
        "",
        table(_sides_table(g)),
        "",
        "## Checks (the build stops if one fails)",
        "",
        "- With no override, the rebuild reproduces `data/panel/`'s model and signal bit for bit in every currency a "
        "row rebuilds.",
        f"- Every row's unit P&L is the baseline's, the same objects and the same bits, on all {len(days):,} book "
        "sessions; its covariance is the baseline's; its legs are the baseline's (a row that asks for another leg "
        "stops the build).",
        "- No row adds or drops a session against the baseline's signal.",
        "- Every eligible session is one the row's book and sleeves count.",
        *(["- The chosen specification on its own sample is reports/results/portfolio.json's headline: its net Sharpe "
           "to the file's six figures, and its sessions."] if s["published"] else []),
        "",
    ]
    return "\n".join(lines)


# ---- the figure --------------------------------------------------------------------

def figure(g, s, path, theme="light"):
    """Every row's net Sharpe over the common sample around the chosen specification's, with its paired SE."""
    t = _style(theme)
    color = t["series"][0]
    base, se = s["net"][BASE]["book"][:2]
    labels, values, errors, y, heads = [], [], [], [], []
    at = 0.0
    for name, _, rows in choices(g):
        heads.append((at, name))
        for r in rows:
            at += 1.0
            labels.append(r.label)
            values.append(_net(s, r.key))
            errors.append(s["paired"][r.key]["book"])
            y.append(at)
        at += 1.4
    fig, ax = plt.subplots(figsize=(8.2, 0.24 * at + 1.4))
    ax.axvspan(base - se, base + se, color=t["grid"], lw=0, zorder=0)
    ax.axvline(0.0, color=t["axis"], lw=1, zorder=1)
    ax.axvline(base, color=t["ink"], lw=1.4, zorder=2)
    ax.errorbar(values, y, xerr=errors, fmt="none", ecolor=color, elinewidth=1.4, capsize=0, zorder=3)
    ax.plot(values, y, "o", ms=7, color=color, mec=t["surface"], mew=1.5, zorder=4)
    ax.set_yticks(y, labels, fontsize=8)
    for h, name in heads:
        ax.text(-0.02, h + 0.1, name, transform=ax.get_yaxis_transform(), ha="right", va="center", fontsize=8.5,
                fontweight="bold", color=t["ink"])
    ax.set_ylim(at - 0.6, -0.8)
    lo, hi = min([*values, base - se, 0.0]), max([*values, base + se, 0.0])
    ax.set_xlim(lo - 0.1, hi + 0.1)
    ax.grid(axis="y", visible=False)
    ax.grid(axis="x", visible=True, color=t["grid"], lw=0.8)
    ax.tick_params(axis="both", length=0, labelsize=8)
    ax.set_xlabel("net Sharpe of the headline book over the common sample", fontsize=8)
    sm = s["sample"]["book"]
    top = ("No single choice turns the book's loss into a gain" if max(values + [base]) <= 0 else
           "Every row earns" if min(values + [base]) > 0 else "The book's sign turns on the choice")
    ax.set_title(f"{top}: {len(values)} rows, net {min(values):+.2f} to {max(values):+.2f}", loc="left", x=-0.42,
                 fontsize=12, fontweight="bold", color=t["ink"], pad=28)
    ax.text(-0.42, 1.0, f"One choice at a time, over the {sm['sessions']:,} book sessions every row counts "
            f"({sm['first']:%b %Y} to {sm['last']:%b %Y}).\nLine: the chosen specification ({base:+.2f}); band: its "
            f"SE ({se:.2f}); whiskers: each row's paired SE against it.", transform=ax.transAxes, fontsize=8.5,
            color=t["secondary"], va="bottom")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---- the outputs -------------------------------------------------------------------

def _cells_json(c):
    return {n: {"sr": v[0], "se": v[1], "sessions": v[2]} for n, v in c.items()}


def results(g, s):
    """reports/results/robustness.json: the numbers the note quotes, to six significant figures."""
    e = s["estimated"]
    rows = {}
    for r in g.rows:
        k = r.key
        rows[k] = {"choice": r.choice, "label": r.label, "net": _cells_json(s["net"][k]),
                   "gross": _cells_json(s["gross"][k]), "own": _cells_json(s["own"][k]),
                   "own_gross": _cells_json(s["own_gross"][k]), "paired_se": s["paired"][k],
                   "change": {n: s["net"][k][n][0] - s["net"][BASE][n][0] for n in s["net"][k]},
                   "paired_se_newey_west": s["paired_hac"][k],
                   "ic": {n: {"ic": v[0], "t": v[1], "sessions": v[2]} for n, v in s["ic"][k].items()},
                   "ic_offsets": {n: {"mean": v[0], "low": v[1], "high": v[2], "fewest_sessions": v[3]}
                                  for n, v in s["ic_offsets"][k].items()},
                   "moves": g.moves[k],
                   "side_changes": {n: {"all": v[0], "counted": v[1]} for n, v in g.sides[k].items()},
                   "elb_sessions": g.elb[k],
                   "first_estimate": g.first[k]}
        if e["keys"] and (k == BASE or k in e["keys"]):
            rows[k]["from_first_estimate"] = _cells_json(e["cells"][k])
    two, one, mid = _choice_verdicts(g, s)
    return _plain({
        "spec": {"headline": g.book["portfolio"]["headline"], "treatment": g.setups[BASE].spec.treatment,
                 "ic_horizon": g.book["robustness"]["ic_horizon"], "paired_se_lags": robustness.PAIRED_LAGS,
                 "design": "one at a time"},
        "ic_persistence": s["ic_persistence"],
        "sample": s["sample"],
        "choices": [{"name": n, "chosen": c, "rows": [r.key for r in rs]} for n, c, rs in choices(g)],
        "sensitive": {"over_two_paired_se": two, "one_to_two": mid, "under_one_paired_se": one},
        "from_first_estimate": e["start"],
        "rows": rows,
    })


def write(g, root, s=None):
    """Every output of the build under repo `root`. Returns the paths."""
    s = summary(g) if s is None else s
    root = Path(root)
    out = {"report": root / "reports" / "robustness.md", "json": root / "reports" / "results" / "robustness.json"}
    for p in out.values():
        p.parent.mkdir(parents=True, exist_ok=True)
    out["report"].write_text(markdown(g, s), encoding="utf-8")
    out["json"].write_text(json.dumps(results(g, s), indent=1) + "\n", encoding="utf-8")
    figures = root / "reports" / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    for theme in THEMES:
        p = figures / f"robustness_{theme}.png"
        figure(g, s, p, theme)
        out[f"figure_{theme}"] = p
    return out
