"""The tear sheet: one page that can be attached to an email. Week 10.

Generated by `scripts/build_tearsheet.py`, never hand-edited: every number on
the page comes from `report/attribution.py`'s build (week 9's headline book,
run in memory from `data/panel/` and the cache), and every sentence is a
template filled from it or from the config. Edit the wording here and rerun.
The page is one US-letter matplotlib figure saved as PDF, laid out by the
one-pager's column (`report/onepager.py`: content that does not fit on one page
raises instead of spilling), and dated by the book's last session.

What is on it, in order: the framework in three sentences; the headline chart
(the book's net equity by component, its gross beside it, 2022 shaded); the
cost sensitivity curve and the net Sharpe by regime; the current signal; the
performance summary (the book and each sleeve's contribution, with and
without 2022 and 2022-23); and what carries it, in four generated sentences.
"""

from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from policypath import config
from policypath.report import attribution, charts
from policypath.report import portfolio as books
from policypath.report.brief import _table
from policypath.report.expression import _and
from policypath.report.figures import _style
from policypath.report.onepager import ORDINAL, PAGE, _Column, _day

sr, pc, pct = books.sr, books.pc, books.pct
NUMBERS = {**books.NUMBERS, 1: "one", 7: "seven", 8: "eight", 9: "nine", 10: "ten", 12: "twelve"}


def framework(b):
    """The framework in three sentences, from the config: the paths, the signal and sleeves, the book."""
    st = b.portfolio.setup
    book = st.book
    ccys = list(dict.fromkeys(c for i in st.inputs.values() for c in i.sleeve.ccys))
    cfgs = {c: config.currency(c) for c in ccys}
    first = cfgs[ccys[0]]
    n, k = first["path"]["n_meetings"], first["backtest"]["horizon"]
    years = pd.Timedelta(first["signal"]["window"]).days / 365
    markets = _and(f"{c} from {cfgs[c]['report']['labels']['market']}" for c in ccys)
    kinds = {i.sleeve.kind: [] for i in st.inputs.values()}
    for name, i in st.inputs.items():
        kinds[i.sleeve.kind].append((name, i.sleeve.ccys))
    words = {"outright": lambda x: f"the {ORDINAL[k]}-meeting rate in {_and(c[0] for _, c in x)}",
             "curve": lambda x: f"2s10s in {_and(c[0] for _, c in x)} on the part of the slope gap the level does not "
                                "explain",
             "cross": lambda x: f"the {_and(name for name, _ in x)} differential"}
    p = book["positions"]
    return (f"Every session, the market's path for each policy rate over the next {NUMBERS.get(n, n)} meetings "
            f"({markets}) is set against the path a balanced-approach rule would take on the macro data public that "
            f"day, held flat. The gap between the two, z-scored against its own trailing "
            f"{NUMBERS.get(round(years), round(years))} years, is traded in {NUMBERS.get(len(st.inputs), len(st.inputs))} "
            "sleeves: " + _and(words[kd](x) for kd, x in kinds.items()) + ". "
            f"Each sleeve takes a side at |z| {p['enter']:g} and drops it at z {p['exit']:g}, flat when the policy "
            "rate and the rule are both at the lower bound; the book sizes the sides inverse to their vol under one "
            f"{book['book']['vol_target']:.0%} vol target, net of costs.")


def carries(b):
    """What carries it, in four sentences: level or relative value, carry or rate, the ELB, 2022."""
    n = b.numbers
    lv, comp = n["level"], {r["group"]: r for r in n["components"]}
    c, e = n["carry"], n["elb"]
    p = n["performance"][0]
    chosen = n["treatment"]
    others = [t for t in e if t != chosen]
    level = (f"{'The level dominates' if lv['dominates'] else 'Relative value dominates'}: the front-end exposure is "
             f"{pct(lv['variance_share'])} of the book's gross P&L variance"
             + (", so this is closer to a duration timer than to relative value" if lv["dominates"] else "")
             + f"; in P&L it made {pc(lv['level'])} a year gross and the rest {pc(lv['rest'])}.")
    carry = (f"Carry and roll cost {pc(comp['book']['carry_roll'])} a year and the rate change earned "
             f"{pc(comp['book']['rate'])}; the book is {c['words']} (daily correlation {c['corr']:+.2f} with a "
             "benchmark trading the sign of carry and roll).")
    elb = (f"At the lower bound the book is flat (proposed): {sr(e[chosen]['net_sr'], e[chosen]['net_se'])}; "
           + "; ".join(f"{attribution.sleeves.TREATMENT_WORDS[t]}, {sr(e[t]['net_sr'], e[t]['net_se'])}" for t in others)
           + ".")
    ex = (f"Without 2022 it nets {sr(p['ex_2022']['net_sr'], p['ex_2022']['net_se'])}, and without Dec 2021 to Aug "
          f"2023 {sr(p['ex_2022_23']['net_sr'], p['ex_2022_23']['net_se'])}: the one cycle that pays carries it.")
    return [level, carry, elb, ex]


def signal_rows(b):
    """The current signal table's rows (`attribution.current`)."""
    side = {1.0: "receive", -1.0: "pay", 0.0: "flat"}
    return [[r["sleeve"], f"{r['session']:%d %b}", f"{r['z']:+.1f}", side[r["side"]], f"{r['dv01'] / 1e3:+,.0f}k",
             r["instrument"], f"{r['edge_bp']:+.0f}", f"{r['cr_h_bp']:+.0f}", f"{r['expected_bp']:+.0f}"]
            for r in b.numbers["current"]]


def performance_rows(b):
    """The performance summary's rows: the book, then each sleeve's contribution."""
    out = []
    for r in b.numbers["performance"]:
        out.append([r["name"], sr(r["gross_sr"]), sr(r["net_sr"], r["net_se"]), pc(r["net_year"]),
                    f"{r['vol']:.1f}%", f"{r['max_dd']:.0f}%", pct(r["hit_daily"]), pct(r["hit_trade"]),
                    f"{r['turns_year']:.0f}", sr(r["ex_2022"]["net_sr"]), sr(r["ex_2022_23"]["net_sr"])])
    return out


def _small(ax, t):
    ax.title.set_fontsize(9)
    for text in ax.texts:
        text.set_fontsize(7)
    ax.tick_params(labelsize=7)
    ax.xaxis.label.set_fontsize(7)
    ax.yaxis.label.set_fontsize(7)
    if ax.get_legend():
        for text in ax.get_legend().get_texts():
            text.set_fontsize(6.5)


def write(b, out_dir, preview=None, generated=None):
    """reports/tearsheet_<last book session>.pdf. Returns the path."""
    t = _style("light")
    n = b.numbers
    st = b.portfolio.setup
    book = st.book
    colors = books.CATEGORICAL["light"]
    day = n["days"][1]
    h = book["carry"]["horizon_days"]
    generated = pd.Timestamp(generated) if generated is not None else pd.Timestamp.today().normalize()
    fig = plt.figure(figsize=PAGE)
    col = _Column(fig, t)
    p = n["performance"][0]
    col.text("Policy paths against the rules: tear sheet", size=15, weight="bold", gap=0.03)
    col.text(f"As of {_day(day)}  ·  book in {book['book']['currency']}, counted from {n['first_counted']:%b %Y}  ·  "
             f"generated {generated:%Y-%m-%d} by scripts/build_tearsheet.py, nothing typed by hand", size=8,
             color=t["secondary"], gap=0.07)
    col.text(framework(b), size=8, gap=0.02)

    (ax,) = col.axes(1.85)
    charts.equity_by_component(ax, attribution.equity_curves(b), t, colors, windows=attribution._windows(b),
                               title=False, ncols=5)
    _small(ax, t)
    ax.set_title(f"The book nets {sr(p['net_sr'], p['net_se'])}, {pc(p['net_year'])} of capital a year "
                 f"({sr(p['gross_sr'])} gross); worst drawdown {p['max_dd']:.0f}%", loc="left", fontsize=10,
                 fontweight="bold", color=t["ink"], pad=14)
    ax.text(0, 1.02, "Cumulative P&L net of costs by component, % of capital. Sharpe SEs in brackets.",
            transform=ax.transAxes, fontsize=7.5, color=t["secondary"], va="bottom")
    col.y += 0.1 / PAGE[1]
    for line in carries(b):
        col.text("·  " + line, size=7.5, gap=0.015)

    height, gap = 1.35, 0.55
    top = col.y - 0.3 / PAGE[1]
    width = (col.width - gap / PAGE[0]) / 2
    left = fig.add_axes([col.left + 0.05, top - height / PAGE[1], width - 0.06, height / PAGE[1]])
    right = fig.add_axes([col.left + width + gap / PAGE[0] + 0.02, top - height / PAGE[1], width - 0.03,
                          height / PAGE[1]])
    charts.cost_curve(left, n["cost_curve"], t, colors, title=False)
    left.set_title("Net Sharpe against the round trip assumed", loc="left", fontsize=9, fontweight="bold",
                   color=t["ink"], pad=5)
    book_rows, sleeve_rows = attribution.regime_bars_data(n)
    charts.regime_bars(right, book_rows, sleeve_rows, t, attribution.marks(st, colors), title=False)
    right.set_title(f"Net Sharpe by {n['regimes']['book_ccy']} regime: the book ±1 SE, and each sleeve", loc="left",
                    fontsize=9, fontweight="bold", color=t["ink"], pad=5)
    for ax in (left, right):
        _small(ax, t)
    col.y = top - (height + 0.72) / PAGE[1]
    col._check()

    col.text(f"The current signal, {_day(day)}", size=9.5, weight="bold", gap=0.02)
    _table(fig, col, ["", "as of", "z", "side", "DV01/bp", "instrument", "edge", f"CR {h}d", f"E {h}d"],
           signal_rows(b), [1.05, 0.5, 0.45, 0.65, 0.65, 1.95, 0.5, 0.55, 0.55], size=7, left=(0, 3, 5))
    col.y += 0.05 / PAGE[1]
    col.text(f"Edge: the de-meaned gap, bp (a proxy for the legs' move on curve and cross sleeves), for the side z "
             f"points to, as are CR (carry and roll over {h} days, curve frozen) and E (the edge's past closure, CR on "
             "the rest). DV01: the book's position, book currency.", size=6.5, color=t["secondary"], gap=0.06)

    col.text("Performance, net of costs (Sharpe with its SE)", size=9.5, weight="bold", gap=0.02)
    _table(fig, col, ["", "gross SR", "net SR", "a year", "vol", "worst dd", "hit day", "hit trade", "turns",
                      "ex-2022", "ex-22-23"],
           performance_rows(b), [1.05, 0.6, 0.85, 0.6, 0.5, 0.6, 0.6, 0.65, 0.5, 0.65, 0.65], size=7)
    col.y += 0.05 / PAGE[1]
    c = n["cost_curve"]
    col.text(f"Sleeves: their contribution inside the book, over its sessions. Breakeven round trip: "
             f"{attribution.sleeves.cstar(c['cstar_bp'])}; configured mix {c['mix_bp']:.2f}bp. Ex-2022 and ex-22-23 "
             "leave calendar 2022, and Dec 2021 to Aug 2023, out of the P&L, the positions not re-run. Tables: "
             "reports/metrics.md and reports/portfolio.md; choices: notes/DECISIONS.md.", size=6.5,
             color=t["secondary"], gap=0.0)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"tearsheet_{day:%Y-%m-%d}.pdf"
    fig.savefig(path)
    if preview is not None:
        fig.savefig(preview, dpi=110)
    plt.close(fig)
    return path
