"""The vintage catalogue: what each macro series covers in real time, and where it is thin.

Generated by `scripts/catalogue_vintages.py` into ``reports/``; never edit the output.
Reads only the cache and its manifest, so it runs with no network. The
decisions it prompts (what to do about each series) go in notes/macro.md.
"""

import numpy as np
import pandas as pd
from policypath import config
from policypath.macro.vintage import VintagePanel
from policypath.report.coverage import table
from policypath.sources import cache

STATS_FROM = "2015-01-01"   # lags and revisions: long enough to be typical, recent enough to be relevant
SINCE = "2021-01-01"        # the nowcast's window
BIG_REVISION = 6            # a vintage revising more past observations than this is in the calendar
PERIOD = {"M": ("MS", pd.offsets.MonthEnd(0)), "Q": ("QS", pd.offsets.QuarterEnd(0))}


def roles(spec):
    """What each pulled series is for, read off the macro block."""
    out = {s: "validation" for s in spec["validation"]}
    out |= {s: "activity" for s in spec["activity"]["series"]}
    out |= {d: "deflator" for d in spec["activity"].get("deflate", {}).values()}
    for block in ("inflation", "gap"):
        out |= {v: f"{block}: {k}" for k, v in spec[block].items() if v in spec["series"]}
    return out


def change(level, units):
    """Period-on-period change in the units a revision is worth reading in.

    Rates (units in %) and counts in thousands as differences; indexes and
    dollar levels as log changes in percent, so a rebasing is not a revision.
    """
    if "%" in units or units.startswith("Thous"):
        return level.diff()
    return np.log(level / level.shift()) * 100


def first_print_changes(panel, name, freq, units, as_of):
    """Each period's change as first printed, i.e. from the vintage it first appeared in."""
    released = panel.release_dates(as_of, name).set_index("date")["published"]
    released = released[released.index >= STATS_FROM]
    out = {}
    for day in released.unique():
        level = panel.series(name, day).asfreq(freq)
        for date in released.index[released == day]:
            out[date] = change(level, units).get(date)
    return pd.Series(out).sort_index()


def series_row(name, frame, meta, role, panel, as_of, projection):
    freq = meta["frequency_short"]
    row = {
        "series": name, "role": role, "title": meta["title"][:48], "freq": freq,
        "units": meta["units_short"], "sa": meta["seasonal_adjustment_short"],
        "first_vintage": pd.Timestamp(meta["first_vintage"]),
        "vintages": frame["realtime_start"].nunique(),
        "since_2021": frame.loc[frame["realtime_start"] >= SINCE, "realtime_start"].nunique(),
    }
    now = panel.series(name, as_of)
    holes = now.loc[now.first_valid_index():now.last_valid_index()]
    row["holes"] = ", ".join(f"{d:%Y-%m}" for d in holes.index[holes.isna()]) or "-"
    # A value blanked in a vintage that has since been superseded: an artifact, not a hole.
    blanked = frame[frame["value"].isna() & frame["realtime_end"].notna()]
    days = sorted(blanked["realtime_start"].unique())
    row["blanked_in"] = ("-" if not days else f"{days[0]:%Y-%m-%d}" if len(days) == 1
                         else f"{len(days)} vintages, {days[0]:%Y-%m-%d} .. {days[-1]:%Y-%m-%d}")

    row["lag_median"] = row["lag_max"] = row["revision"] = np.nan
    if freq in PERIOD and not projection:
        start, end = PERIOD[freq]
        rel = panel.release_dates(as_of, name).set_index("date")["published"]
        rel = rel[rel.index >= STATS_FROM]
        lag = (rel - (rel.index + end)).dt.days
        if len(lag) and lag.min() > 0:   # nowcasts (GDPNow) print inside their own period: no lag to report
            row["lag_median"], row["lag_max"] = float(lag.median()), float(lag.max())
        first = first_print_changes(panel, name, start, meta["units_short"], as_of)
        current = change(now.asfreq(start), meta["units_short"]).reindex(first.index)
        row["revision"] = float((current - first).abs().mean())
    return row


def revision_calendar(frames, since=SINCE, big=BIG_REVISION):
    """Vintages since `since` that revised more than `big` observations already published."""
    rows = []
    for name, f in frames.items():
        seen = f.groupby("date")["realtime_start"].min()
        revised = f[f["realtime_start"] > f["date"].map(seen)]   # not an observation's first appearance
        revised = revised[revised["realtime_start"] >= since]
        for day, g in revised.groupby("realtime_start"):
            if len(g) > big:
                rows.append({"series": name, "vintage": day, "revised": len(g),
                             "from": f"{g['date'].min():%Y-%m}", "to": f"{g['date'].max():%Y-%m}"})
    return pd.DataFrame(rows, columns=["series", "vintage", "revised", "from", "to"])


def catalogue(ccy, as_of):
    """The catalogue and the revision calendar, as named DataFrames."""
    spec = config.currency(ccy)["macro"]
    names = [*spec["series"], *spec["validation"]]
    frames = {s: cache.vintages(spec["source"], s, ccy) for s in names}
    panel = VintagePanel(pd.concat([f.assign(series=s) for s, f in frames.items()], ignore_index=True),
                         spec["projections"])
    role = roles(spec)
    rows = [series_row(s, frames[s], cache.metadata(spec["source"], s, ccy), role.get(s, "-"),
                       panel, as_of, s in spec["projections"]) for s in names]
    return {"Series": pd.DataFrame(rows), "Revision calendar": revision_calendar(frames)}


def markdown(ccy, tables, as_of):
    series = tables["Series"]
    lines = [
        f"# ALFRED vintage catalogue: {ccy}",
        "",
        f"Generated by `scripts/catalogue_vintages.py` from the cache as of {pd.Timestamp(as_of).date()}. "
        "Do not edit by hand.",
        "",
        f"- Series: {len(series)}; earliest possible `as_of` for all of them: "
        f"{series['first_vintage'].max():%Y-%m-%d}",
        f"- Lag: days from the end of the reference period to the first print, {STATS_FROM[:4]} on.",
        f"- Revision: mean absolute difference between first print and current value of the "
        f"period-on-period change ({STATS_FROM[:4]} on): pp for rates, thousands for counts, "
        "% for indexes and levels.",
        "- Holes: periods missing in the current vintage between the first and last value. "
        "Blanked in: superseded vintages that carried a missing value.",
        "",
        "## Series",
        "",
        table(series),
        "",
        f"## Revision calendar: vintages since {SINCE[:4]} revising more than {BIG_REVISION} past observations",
        "",
        table(tables["Revision calendar"]) if len(tables["Revision calendar"]) else "None.",
        "",
    ]
    return "\n".join(lines)